CREATE TABLE [LND].[LND_CA_DLDELADR] (
    [Cust#]               NVARCHAR (4000) NULL,
    [AdrCde]              NVARCHAR (4000) NULL,
    [Delivery Name]       NVARCHAR (4000) NULL,
    [Delivery Address 1]  NVARCHAR (4000) NULL,
    [Delivery Address 2]  NVARCHAR (4000) NULL,
    [Delivery Address 3]  NVARCHAR (4000) NULL,
    [Contact]             NVARCHAR (4000) NULL,
    [Phone]               NVARCHAR (4000) NULL,
    [Fax]                 NVARCHAR (4000) NULL,
    [Are]                 NVARCHAR (4000) NULL,
    [Dsp]                 NVARCHAR (4000) NULL,
    [Delivery Address 4]  NVARCHAR (4000) NULL,
    [Delivery Address 5]  NVARCHAR (4000) NULL,
    [Delivery Address 6]  NVARCHAR (4000) NULL,
    [Delivery Address 7]  NVARCHAR (4000) NULL,
    [Delivery Address 8]  NVARCHAR (4000) NULL,
    [Delivery Address 9]  NVARCHAR (4000) NULL,
    [Delivery Address 10] NVARCHAR (4000) NULL,
    [Delivery Address 11] NVARCHAR (4000) NULL,
    [Mobile]              NVARCHAR (4000) NULL,
    [Email]               NVARCHAR (4000) NULL,
    [Email Quote]         NVARCHAR (4000) NULL,
    [Ste]                 NVARCHAR (4000) NULL,
    [Pstcde]              NVARCHAR (4000) NULL,
    [Cry]                 NVARCHAR (4000) NULL,
    [District]            NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Start By]            NVARCHAR (4000) NULL,
    [Amend Date]          NVARCHAR (4000) NULL,
    [ATime]               NVARCHAR (4000) NULL,
    [Amend By]            NVARCHAR (4000) NULL,
    [Last So#]            NVARCHAR (4000) NULL,
    [LstSo Date]          NVARCHAR (4000) NULL,
    [Last Sq#]            NVARCHAR (4000) NULL,
    [LstSq Date]          NVARCHAR (4000) NULL,
    [Webshop ID]          NVARCHAR (4000) NULL,
    [B]                   NVARCHAR (4000) NULL,
    [Ora ID]              NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

