CREATE TABLE [LND].[LND_CA_SOCOLINE] (
    [So#]                 NVARCHAR (4000) NULL,
    [Co#]                 NVARCHAR (4000) NULL,
    [Sol#]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [Deliv Date]          NVARCHAR (4000) NULL,
    [Comment]             NVARCHAR (4000) NULL,
    [Order Qty]           NVARCHAR (4000) NULL,
    [LinePrice]           NVARCHAR (4000) NULL,
    [Disc %]              NVARCHAR (4000) NULL,
    [Order Value]         NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [X]                   NVARCHAR (4000) NULL,
    [Gst%]                NVARCHAR (4000) NULL,
    [Gst Value]           NVARCHAR (4000) NULL,
    [Disc Value]          NVARCHAR (4000) NULL,
    [Customer Reference]  NVARCHAR (4000) NULL,
    [Inmast Description]  NVARCHAR (4000) NULL,
    [InmTrdPrc]           NVARCHAR (4000) NULL,
    [InmRetPrc]           NVARCHAR (4000) NULL,
    [Uom]                 NVARCHAR (4000) NULL,
    [CancelQty]           NVARCHAR (4000) NULL,
    [Net Qty]             NVARCHAR (4000) NULL,
    [Net Value]           NVARCHAR (4000) NULL,
    [Net Gst]             NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

