CREATE TABLE [LND].[LND_CA_POLINE] (
    [Po#]                 NVARCHAR (4000) NULL,
    [Pol#]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [Order Qty]           NVARCHAR (4000) NULL,
    [Buy Price]           NVARCHAR (4000) NULL,
    [InvoiceCost]         NVARCHAR (4000) NULL,
    [Order Value]         NVARCHAR (4000) NULL,
    [ExpectDate]          NVARCHAR (4000) NULL,
    [Receipt Qty]         NVARCHAR (4000) NULL,
    [Receipt Val]         NVARCHAR (4000) NULL,
    [Invoice Qty]         NVARCHAR (4000) NULL,
    [Invoice Val]         NVARCHAR (4000) NULL,
    [Cancel Qty]          NVARCHAR (4000) NULL,
    [Sup#]                NVARCHAR (4000) NULL,
    [Job Ref]             NVARCHAR (4000) NULL,
    [L]                   NVARCHAR (4000) NULL,
    [Comment]             NVARCHAR (4000) NULL,
    [Factor]              NVARCHAR (4000) NULL,
    [Prc Fact]            NVARCHAR (4000) NULL,
    [GlAcct#]             NVARCHAR (4000) NULL,
    [Supplier Item Code]  NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Start By]            NVARCHAR (4000) NULL,
    [Amend Date]          NVARCHAR (4000) NULL,
    [ATime]               NVARCHAR (4000) NULL,
    [Amend By]            NVARCHAR (4000) NULL,
    [O Price M2]          NVARCHAR (4000) NULL,
    [InmLastCost]         NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

