CREATE TABLE [LND].[LND_CA_INTR] (
    [Request#]            NVARCHAR (4000) NULL,
    [Lfm]                 NVARCHAR (4000) NULL,
    [Lto]                 NVARCHAR (4000) NULL,
    [XfrBatch]            NVARCHAR (4000) NULL,
    [So#]                 NVARCHAR (4000) NULL,
    [Sol#]                NVARCHAR (4000) NULL,
    [Po#]                 NVARCHAR (4000) NULL,
    [Pol#]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [S]                   NVARCHAR (4000) NULL,
    [Request Qty]         NVARCHAR (4000) NULL,
    [Reject Qty]          NVARCHAR (4000) NULL,
    [Dispatch Qty]        NVARCHAR (4000) NULL,
    [RequestDat]          NVARCHAR (4000) NULL,
    [Req Time]            NVARCHAR (4000) NULL,
    [Rby]                 NVARCHAR (4000) NULL,
    [AcceptDate]          NVARCHAR (4000) NULL,
    [Fill Date]           NVARCHAR (4000) NULL,
    [FillTime]            NVARCHAR (4000) NULL,
    [Fby]                 NVARCHAR (4000) NULL,
    [Comment]             NVARCHAR (4000) NULL,
    [Notes]               NVARCHAR (4000) NULL,
    [To#]                 NVARCHAR (4000) NULL,
    [Tol#]                NVARCHAR (4000) NULL,
    [PublishDat]          NVARCHAR (4000) NULL,
    [ExpectDate]          NVARCHAR (4000) NULL,
    [Reason]              NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

