CREATE TABLE [LND].[LND_CA_INWORDS] (
    [Item Code]           NVARCHAR (4000) NULL,
    [Item Search Words]   NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

