CREATE TABLE [LND].[LND_CA_POMAST] (
    [Po#]                  NVARCHAR (4000) NULL,
    [Sup#]                 NVARCHAR (4000) NULL,
    [Order Date]           NVARCHAR (4000) NULL,
    [ExpectDate]           NVARCHAR (4000) NULL,
    [Recpt Date]           NVARCHAR (4000) NULL,
    [RequestDat]           NVARCHAR (4000) NULL,
    [S]                    NVARCHAR (4000) NULL,
    [Lst Invoice Ref]      NVARCHAR (4000) NULL,
    [Deliver to (legal)]   NVARCHAR (4000) NULL,
    [Delivery Street & No] NVARCHAR (4000) NULL,
    [Delivery District]    NVARCHAR (4000) NULL,
    [Delivery Region]      NVARCHAR (4000) NULL,
    [Site Name / Details]  NVARCHAR (4000) NULL,
    [Site Contact / Phone] NVARCHAR (4000) NULL,
    [Order Value]          NVARCHAR (4000) NULL,
    [Receipt Val]          NVARCHAR (4000) NULL,
    [Invoice Val]          NVARCHAR (4000) NULL,
    [Oby]                  NVARCHAR (4000) NULL,
    [Supplier Ref]         NVARCHAR (4000) NULL,
    [Adr#]                 NVARCHAR (4000) NULL,
    [Supplier Message]     NVARCHAR (4000) NULL,
    [Transmission Message] NVARCHAR (4000) NULL,
    [Delivery Method]      NVARCHAR (4000) NULL,
    [Flags]                NVARCHAR (4000) NULL,
    [Start Date]           NVARCHAR (4000) NULL,
    [STime]                NVARCHAR (4000) NULL,
    [Start By]             NVARCHAR (4000) NULL,
    [Amend Date]           NVARCHAR (4000) NULL,
    [ATime]                NVARCHAR (4000) NULL,
    [Amend By]             NVARCHAR (4000) NULL,
    [Internal Notes]       NVARCHAR (4000) NULL,
    [Loc]                  NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NOT NULL
);

