CREATE TABLE [LND].[LND_EBS_FND_FLEX_VALUES_TL_TBR] (
    [FLEX_VALUE_ID]      DECIMAL (15)   NULL,
    [LANGUAGE]           NVARCHAR (4)   NULL,
    [LAST_UPDATE_DATE]   DATETIME2 (0)  NULL,
    [LAST_UPDATED_BY]    DECIMAL (15)   NULL,
    [CREATION_DATE]      DATETIME2 (0)  NULL,
    [CREATED_BY]         DECIMAL (15)   NULL,
    [LAST_UPDATE_LOGIN]  DECIMAL (10)   NULL,
    [DESCRIPTION]        NVARCHAR (240) NULL,
    [SOURCE_LANG]        NVARCHAR (4)   NULL,
    [FLEX_VALUE_MEANING] NVARCHAR (150) NULL
);

