CREATE TABLE [LND].[LND_CA_CLMAST] (
    [Sup#]                NVARCHAR (4000) NULL,
    [Supplier Name]       NVARCHAR (4000) NULL,
    [Key]                 NVARCHAR (4000) NULL,
    [Address Line 1]      NVARCHAR (4000) NULL,
    [Address Line 2]      NVARCHAR (4000) NULL,
    [Address Line 3]      NVARCHAR (4000) NULL,
    [Phone]               NVARCHAR (4000) NULL,
    [Address Line 4]      NVARCHAR (4000) NULL,
    [Typ]                 NVARCHAR (4000) NULL,
    [Cat]                 NVARCHAR (4000) NULL,
    [OraId#]              NVARCHAR (4000) NULL,
    [Email]               NVARCHAR (4000) NULL,
    [Mobile]              NVARCHAR (4000) NULL,
    [T]                   NVARCHAR (4000) NULL,
    [R]                   NVARCHAR (4000) NULL,
    [P]                   NVARCHAR (4000) NULL,
    [C]                   NVARCHAR (4000) NULL,
    [A]                   NVARCHAR (4000) NULL,
    [B]                   NVARCHAR (4000) NULL,
    [Email Po]            NVARCHAR (4000) NULL,
    [Po Popup]            NVARCHAR (4000) NULL,
    [Rfc Popup]           NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [LstOrdDate]          NVARCHAR (4000) NULL,
    [LstDelDate]          NVARCHAR (4000) NULL,
    [LstRetDate]          NVARCHAR (4000) NULL,
    [Uninvoiced]          NVARCHAR (4000) NULL,
    [Uncredited]          NVARCHAR (4000) NULL,
    [Free Phone]          NVARCHAR (4000) NULL,
    [Email Rfc]           NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

