CREATE TABLE [LND].[LND_CA_SOLINE] (
    [So#]                 NVARCHAR (4000) NULL,
    [Sol#]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [Pr]                  NVARCHAR (4000) NULL,
    [Deliv Date]          NVARCHAR (4000) NULL,
    [S]                   NVARCHAR (4000) NULL,
    [Comment]             NVARCHAR (4000) NULL,
    [Order Qty]           NVARCHAR (4000) NULL,
    [Commit Qty]          NVARCHAR (4000) NULL,
    [Bord Qty]            NVARCHAR (4000) NULL,
    [Cancel Qty]          NVARCHAR (4000) NULL,
    [Inv Qty]             NVARCHAR (4000) NULL,
    [Po Qty]              NVARCHAR (4000) NULL,
    [LinePrice]           NVARCHAR (4000) NULL,
    [Disc %]              NVARCHAR (4000) NULL,
    [OV Gst Incl]         NVARCHAR (4000) NULL,
    [Po#]                 NVARCHAR (4000) NULL,
    [A]                   NVARCHAR (4000) NULL,
    [Quote Item Type]     NVARCHAR (4000) NULL,
    [Quote Item Ref]      NVARCHAR (4000) NULL,
    [Trade Prc]           NVARCHAR (4000) NULL,
    [Mx NetPrc]           NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [X]                   NVARCHAR (4000) NULL,
    [Gst%]                NVARCHAR (4000) NULL,
    [Gst Value]           NVARCHAR (4000) NULL,
    [Disc Value]          NVARCHAR (4000) NULL,
    [LSup]                NVARCHAR (4000) NULL,
    [Supplier Item Code]  NVARCHAR (4000) NULL,
    [Cust#]               NVARCHAR (4000) NULL,
    [Supply Qty]          NVARCHAR (4000) NULL,
    [Prev ComQty]         NVARCHAR (4000) NULL,
    [Prev SupQty]         NVARCHAR (4000) NULL,
    [Tr Qty]              NVARCHAR (4000) NULL,
    [Pol#]                NVARCHAR (4000) NULL,
    [Customer Reference]  NVARCHAR (4000) NULL,
    [Mx Price]            NVARCHAR (4000) NULL,
    [MxDis%]              NVARCHAR (4000) NULL,
    [Msp]                 NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Start By]            NVARCHAR (4000) NULL,
    [Unit Cost]           NVARCHAR (4000) NULL,
    [T]                   NVARCHAR (4000) NULL,
    [Mx Item/Incat]       NVARCHAR (4000) NULL,
    [MxCust]              NVARCHAR (4000) NULL,
    [Mx OV GstExc]        NVARCHAR (4000) NULL,
    [Mx Val Fm]           NVARCHAR (4000) NULL,
    [Mx Val To]           NVARCHAR (4000) NULL,
    [MxPrbk]              NVARCHAR (4000) NULL,
    [MPC]                 NVARCHAR (4000) NULL,
    [Request#]            NVARCHAR (4000) NULL,
    [P]                   NVARCHAR (4000) NULL,
    [Offerid]             NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

