CREATE TABLE [LND].[LND_EBS_FND_FLEX_VALUES_TL] (
    [FLEX_VALUE_ID]       NVARCHAR (4000) NULL,
    [LANGUAGE]            NVARCHAR (4000) NULL,
    [LAST_UPDATE_DATE]    NVARCHAR (4000) NULL,
    [LAST_UPDATED_BY]     NVARCHAR (4000) NULL,
    [CREATION_DATE]       NVARCHAR (4000) NULL,
    [CREATED_BY]          NVARCHAR (4000) NULL,
    [LAST_UPDATE_LOGIN]   NVARCHAR (4000) NULL,
    [DESCRIPTION]         NVARCHAR (4000) NULL,
    [SOURCE_LANG]         NVARCHAR (4000) NULL,
    [FLEX_VALUE_MEANING]  NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

