CREATE TABLE [LND].[LND_CA_DLAREA] (
    [CusTyp]                    NVARCHAR (4000) NULL,
    [Customer Type Description] NVARCHAR (4000) NULL,
    [Sales 1]                   NVARCHAR (4000) NULL,
    [Sales 2]                   NVARCHAR (4000) NULL,
    [Sales 3]                   NVARCHAR (4000) NULL,
    [Sales 4]                   NVARCHAR (4000) NULL,
    [Sales 5]                   NVARCHAR (4000) NULL,
    [Sales 6]                   NVARCHAR (4000) NULL,
    [Sales 7]                   NVARCHAR (4000) NULL,
    [Sales 8]                   NVARCHAR (4000) NULL,
    [Sales 9]                   NVARCHAR (4000) NULL,
    [Sales 10]                  NVARCHAR (4000) NULL,
    [Sales 11]                  NVARCHAR (4000) NULL,
    [Sales 12]                  NVARCHAR (4000) NULL,
    [Sales 13]                  NVARCHAR (4000) NULL,
    [Sales 14]                  NVARCHAR (4000) NULL,
    [Sales 15]                  NVARCHAR (4000) NULL,
    [Sales 16]                  NVARCHAR (4000) NULL,
    [Sales 17]                  NVARCHAR (4000) NULL,
    [Sales 18]                  NVARCHAR (4000) NULL,
    [Sales 19]                  NVARCHAR (4000) NULL,
    [Sales 20]                  NVARCHAR (4000) NULL,
    [Sales 21]                  NVARCHAR (4000) NULL,
    [Sales 22]                  NVARCHAR (4000) NULL,
    [Sales 23]                  NVARCHAR (4000) NULL,
    [Sales 24]                  NVARCHAR (4000) NULL,
    [Cogs 1]                    NVARCHAR (4000) NULL,
    [Cogs 2]                    NVARCHAR (4000) NULL,
    [Cogs 3]                    NVARCHAR (4000) NULL,
    [Cogs 4]                    NVARCHAR (4000) NULL,
    [Cogs 5]                    NVARCHAR (4000) NULL,
    [Cogs 6]                    NVARCHAR (4000) NULL,
    [Cogs 7]                    NVARCHAR (4000) NULL,
    [Cogs 8]                    NVARCHAR (4000) NULL,
    [Cogs 9]                    NVARCHAR (4000) NULL,
    [Cogs 10]                   NVARCHAR (4000) NULL,
    [Cogs 11]                   NVARCHAR (4000) NULL,
    [Cogs 12]                   NVARCHAR (4000) NULL,
    [Cogs 13]                   NVARCHAR (4000) NULL,
    [Cogs 14]                   NVARCHAR (4000) NULL,
    [Cogs 15]                   NVARCHAR (4000) NULL,
    [Cogs 16]                   NVARCHAR (4000) NULL,
    [Cogs 17]                   NVARCHAR (4000) NULL,
    [Cogs 18]                   NVARCHAR (4000) NULL,
    [Cogs 19]                   NVARCHAR (4000) NULL,
    [Cogs 20]                   NVARCHAR (4000) NULL,
    [Cogs 21]                   NVARCHAR (4000) NULL,
    [Cogs 22]                   NVARCHAR (4000) NULL,
    [Cogs 23]                   NVARCHAR (4000) NULL,
    [Cogs 24]                   NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]       DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]             VARCHAR (8000)  NOT NULL
);

