CREATE TABLE [LND].[LND_EBS_RD_BI_INV_VALUES_RPT] (
    [DC]                      NVARCHAR (4000) NULL,
    [SUBINV_NAME]             NVARCHAR (4000) NULL,
    [LOCATOR_CODE]            NVARCHAR (4000) NULL,
    [ITEM_CODE]               NVARCHAR (4000) NULL,
    [CATEGORY_CODE]           NVARCHAR (4000) NULL,
    [STOCK_QTY]               NVARCHAR (4000) NULL,
    [INTRANSIT_QTY]           NVARCHAR (4000) NULL,
    [RECEIVING_QTY]           NVARCHAR (4000) NULL,
    [STOCK_VALUE]             NVARCHAR (4000) NULL,
    [INTRANSIT_VALUE]         NVARCHAR (4000) NULL,
    [RECEIVING_VALUE]         NVARCHAR (4000) NULL,
    [ITEM_COST]               NVARCHAR (4000) NULL,
    [AS_OF_DATE]              NVARCHAR (4000) NULL,
    [CREATION_DATE]           NVARCHAR (4000) NULL,
    [TOTAL_QTY]               NVARCHAR (4000) NULL,
    [UNRECEIVED_PO_QTY]       NVARCHAR (4000) NULL,
    [BO_QTY]                  NVARCHAR (4000) NULL,
    [META_EFFECTIVE_DATETIME] DATETIME2 (7)   NULL,
    [META_FILE_NAME]          NVARCHAR (MAX)  NULL,
    [META_RECORD_SOURCE]      NVARCHAR (MAX)  NULL
);

