CREATE TABLE [LND].[LND_CA_DLREASON] (
    [RC]                  NVARCHAR (4000) NULL,
    [Credit Note Reason]  NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

