CREATE TABLE [LND].[LND_CA_SOMAST] (
    [So#]                     NVARCHAR (4000) NULL,
    [Cust#]                   NVARCHAR (4000) NULL,
    [Order Date]              NVARCHAR (4000) NULL,
    [Customer Reference]      NVARCHAR (4000) NULL,
    [Deliv Date]              NVARCHAR (4000) NULL,
    [H]                       NVARCHAR (4000) NULL,
    [Spn]                     NVARCHAR (4000) NULL,
    [AdrCde]                  NVARCHAR (4000) NULL,
    [Delivery Name]           NVARCHAR (4000) NULL,
    [Delivery Address Line 1] NVARCHAR (4000) NULL,
    [Delivery Address Line 2] NVARCHAR (4000) NULL,
    [Delivery Address Line 3] NVARCHAR (4000) NULL,
    [Message]                 NVARCHAR (4000) NULL,
    [P]                       NVARCHAR (4000) NULL,
    [OV Gst Incl]             NVARCHAR (4000) NULL,
    [Last Inv#]               NVARCHAR (4000) NULL,
    [LstInvDate]              NVARCHAR (4000) NULL,
    [Inv Value]               NVARCHAR (4000) NULL,
    [T]                       NVARCHAR (4000) NULL,
    [S]                       NVARCHAR (4000) NULL,
    [Pr]                      NVARCHAR (4000) NULL,
    [I]                       NVARCHAR (4000) NULL,
    [F]                       NVARCHAR (4000) NULL,
    [Req Ref]                 NVARCHAR (4000) NULL,
    [ProjPB]                  NVARCHAR (4000) NULL,
    [Freight Co]              NVARCHAR (4000) NULL,
    [Order Source]            NVARCHAR (4000) NULL,
    [Quote Salutation]        NVARCHAR (4000) NULL,
    [PckC]                    NVARCHAR (4000) NULL,
    [TxCert]                  NVARCHAR (4000) NULL,
    [Loc]                     NVARCHAR (4000) NULL,
    [Delivery Address Line 4] NVARCHAR (4000) NULL,
    [Contact]                 NVARCHAR (4000) NULL,
    [Contact Phone]           NVARCHAR (4000) NULL,
    [Contact Fax]             NVARCHAR (4000) NULL,
    [Start Date]              NVARCHAR (4000) NULL,
    [Delivery Instructions]   NVARCHAR (4000) NULL,
    [Eby]                     NVARCHAR (4000) NULL,
    [Start By]                NVARCHAR (4000) NULL,
    [Contact Mobile]          NVARCHAR (4000) NULL,
    [Contact Email]           NVARCHAR (4000) NULL,
    [Gst Value]               NVARCHAR (4000) NULL,
    [STime]                   NVARCHAR (4000) NULL,
    [Inby]                    NVARCHAR (4000) NULL,
    [Aby]                     NVARCHAR (4000) NULL,
    [Edit Date]               NVARCHAR (4000) NULL,
    [ESTime]                  NVARCHAR (4000) NULL,
    [EFTime]                  NVARCHAR (4000) NULL,
    [Ste]                     NVARCHAR (4000) NULL,
    [Pstcde]                  NVARCHAR (4000) NULL,
    [Delivery District]       NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]     DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]           VARCHAR (8000)  NOT NULL
);

