CREATE TABLE [LND].[LND_EBS_RD_BI_ITEM_PREF_VENDORS] (
    [DC]                      NVARCHAR (4000) NULL,
    [ITEM_ID]                 NVARCHAR (4000) NULL,
    [ITEM_CODE]               NVARCHAR (4000) NULL,
    [VENDOR_NUMBER]           NVARCHAR (4000) NULL,
    [LAST_UPDATE_DATE]        NVARCHAR (4000) NULL,
    [META_EFFECTIVE_DATETIME] DATETIME2 (7)   NULL,
    [META_FILE_NAME]          NVARCHAR (MAX)  NULL,
    [META_RECORD_SOURCE]      NVARCHAR (MAX)  NULL
);

