CREATE TABLE [LND].[LND_CA_INTRAN] (
    [Recnum]              NVARCHAR (4000) NULL,
    [Type]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [Lto]                 NVARCHAR (4000) NULL,
    [Prtnr#]              NVARCHAR (4000) NULL,
    [Trans Date]          NVARCHAR (4000) NULL,
    [Lin#]                NVARCHAR (4000) NULL,
    [Trans Qty]           NVARCHAR (4000) NULL,
    [SV Gst Incl]         NVARCHAR (4000) NULL,
    [Gst Value]           NVARCHAR (4000) NULL,
    [Cogs Value]          NVARCHAR (4000) NULL,
    [C2O Date]            NVARCHAR (4000) NULL,
    [Batch#]              NVARCHAR (4000) NULL,
    [DPF]                 NVARCHAR (4000) NULL,
    [Last Cost]           NVARCHAR (4000) NULL,
    [VReb %]              NVARCHAR (4000) NULL,
    [Invoice#]            NVARCHAR (4000) NULL,
    [Count Qty]           NVARCHAR (4000) NULL,
    [Frozen Qoh]          NVARCHAR (4000) NULL,
    [Delivery Docket]     NVARCHAR (4000) NULL,
    [Po#]                 NVARCHAR (4000) NULL,
    [Spn]                 NVARCHAR (4000) NULL,
    [S]                   NVARCHAR (4000) NULL,
    [GlAcct#]             NVARCHAR (4000) NULL,
    [C2O Cogs Val]        NVARCHAR (4000) NULL,
    [Ven Reb Qty]         NVARCHAR (4000) NULL,
    [VR]                  NVARCHAR (4000) NULL,
    [Vend Price]          NVARCHAR (4000) NULL,
    [Vendor Ref]          NVARCHAR (4000) NULL,
    [Comment]             NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Sby]                 NVARCHAR (4000) NULL,
    [Amend Date]          NVARCHAR (4000) NULL,
    [ATime]               NVARCHAR (4000) NULL,
    [Aby]                 NVARCHAR (4000) NULL,
    [G]                   NVARCHAR (4000) NULL,
    [Gst %]               NVARCHAR (4000) NULL,
    [Inm Vac]             NVARCHAR (4000) NULL,
    [Inm Qoh]             NVARCHAR (4000) NULL,
    [Inl Vac]             NVARCHAR (4000) NULL,
    [Inl Qoh]             NVARCHAR (4000) NULL,
    [Qty Eop]             NVARCHAR (4000) NULL,
    [Cogs Eop]            NVARCHAR (4000) NULL,
    [TypPE]               NVARCHAR (4000) NULL,
    [Rfc#]                NVARCHAR (4000) NULL,
    [UPFM]                NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

