CREATE TABLE [LND].[LND_CA_SQMQUOTE] (
    [Sq#]                     NVARCHAR (4000) NULL,
    [Cust#]                   NVARCHAR (4000) NULL,
    [Quote Date]              NVARCHAR (4000) NULL,
    [Customer Reference]      NVARCHAR (4000) NULL,
    [Deliv Date]              NVARCHAR (4000) NULL,
    [H]                       NVARCHAR (4000) NULL,
    [Spn]                     NVARCHAR (4000) NULL,
    [DelCod]                  NVARCHAR (4000) NULL,
    [Delivery Name]           NVARCHAR (4000) NULL,
    [Delivery Address Line 1] NVARCHAR (4000) NULL,
    [Delivery Address Line 2] NVARCHAR (4000) NULL,
    [Delivery Address Line 3] NVARCHAR (4000) NULL,
    [Contact]                 NVARCHAR (4000) NULL,
    [Phone]                   NVARCHAR (4000) NULL,
    [Fax]                     NVARCHAR (4000) NULL,
    [QV Gst Incl]             NVARCHAR (4000) NULL,
    [Valid Date]              NVARCHAR (4000) NULL,
    [Cogs Value]              NVARCHAR (4000) NULL,
    [T]                       NVARCHAR (4000) NULL,
    [S]                       NVARCHAR (4000) NULL,
    [Pr]                      NVARCHAR (4000) NULL,
    [I]                       NVARCHAR (4000) NULL,
    [F]                       NVARCHAR (4000) NULL,
    [ProjPB]                  NVARCHAR (4000) NULL,
    [Webshop / Copy2So#-Sq#]  NVARCHAR (4000) NULL,
    [Quote Salutation]        NVARCHAR (4000) NULL,
    [PC]                      NVARCHAR (4000) NULL,
    [TxCert]                  NVARCHAR (4000) NULL,
    [Loc]                     NVARCHAR (4000) NULL,
    [Gst Value]               NVARCHAR (4000) NULL,
    [Email]                   NVARCHAR (4000) NULL,
    [Contact Mobile]          NVARCHAR (4000) NULL,
    [Start Date]              NVARCHAR (4000) NULL,
    [STime]                   NVARCHAR (4000) NULL,
    [Start By]                NVARCHAR (4000) NULL,
    [P]                       NVARCHAR (4000) NULL,
    [CopyFmSq#]               NVARCHAR (4000) NULL,
    [Pstcde]                  NVARCHAR (4000) NULL,
    [Delivery Mode]           NVARCHAR (4000) NULL,
    [Order Placed By]         NVARCHAR (4000) NULL,
    [Rfq#]                    NVARCHAR (4000) NULL,
    [QteNeedDat]              NVARCHAR (4000) NULL,
    [Quote Description]       NVARCHAR (4000) NULL,
    [W]                       NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]     DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]           VARCHAR (8000)  NOT NULL
);

