CREATE TABLE [LND].[LND_CA_SOCOMAST] (
    [So#]                  NVARCHAR (4000) NULL,
    [Co#]                  NVARCHAR (4000) NULL,
    [Start Date]           NVARCHAR (4000) NULL,
    [STime]                NVARCHAR (4000) NULL,
    [Cust#]                NVARCHAR (4000) NULL,
    [Order Date]           NVARCHAR (4000) NULL,
    [Customer Reference]   NVARCHAR (4000) NULL,
    [Deliv Date]           NVARCHAR (4000) NULL,
    [H]                    NVARCHAR (4000) NULL,
    [Spn]                  NVARCHAR (4000) NULL,
    [CusLnk]               NVARCHAR (4000) NULL,
    [DelCod]               NVARCHAR (4000) NULL,
    [DelLnk]               NVARCHAR (4000) NULL,
    [MesLnk]               NVARCHAR (4000) NULL,
    [InsLnk]               NVARCHAR (4000) NULL,
    [P]                    NVARCHAR (4000) NULL,
    [Order Value]          NVARCHAR (4000) NULL,
    [T]                    NVARCHAR (4000) NULL,
    [Pr]                   NVARCHAR (4000) NULL,
    [I]                    NVARCHAR (4000) NULL,
    [F]                    NVARCHAR (4000) NULL,
    [Disc Value]           NVARCHAR (4000) NULL,
    [Loc]                  NVARCHAR (4000) NULL,
    [Gst Value]            NVARCHAR (4000) NULL,
    [Short Message]        NVARCHAR (4000) NULL,
    [Short Delivery Instr] NVARCHAR (4000) NULL,
    [Req Ref]              NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NOT NULL
);

