CREATE TABLE [LND].[LND_EBS_OE_TRANSACTION_TYPES_TL] (
    [TRANSACTION_TYPE_ID]    NVARCHAR (4000) NULL,
    [LANGUAGE]               NVARCHAR (4000) NULL,
    [SOURCE_LANG]            NVARCHAR (4000) NULL,
    [NAME]                   NVARCHAR (4000) NULL,
    [DESCRIPTION]            NVARCHAR (4000) NULL,
    [CREATION_DATE]          NVARCHAR (4000) NULL,
    [CREATED_BY]             NVARCHAR (4000) NULL,
    [LAST_UPDATE_DATE]       NVARCHAR (4000) NULL,
    [LAST_UPDATED_BY]        NVARCHAR (4000) NULL,
    [LAST_UPDATE_LOGIN]      NVARCHAR (4000) NULL,
    [PROGRAM_APPLICATION_ID] NVARCHAR (4000) NULL,
    [PROGRAM_ID]             NVARCHAR (4000) NULL,
    [REQUEST_ID]             NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]    DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]          VARCHAR (8000)  NOT NULL
);

