CREATE TABLE [LND].[LND_CA_INCAT] (
    [Incat]                    NVARCHAR (4000) NULL,
    [Category Description]     NVARCHAR (4000) NULL,
    [L]                        NVARCHAR (4000) NULL,
    [Gl Sales]                 NVARCHAR (4000) NULL,
    [Gl Purch]                 NVARCHAR (4000) NULL,
    [Gl Cogs]                  NVARCHAR (4000) NULL,
    [Gl Stock]                 NVARCHAR (4000) NULL,
    [Sales 1]                  NVARCHAR (4000) NULL,
    [Sales 2]                  NVARCHAR (4000) NULL,
    [Sales 3]                  NVARCHAR (4000) NULL,
    [Sales 4]                  NVARCHAR (4000) NULL,
    [Sales 5]                  NVARCHAR (4000) NULL,
    [Sales 6]                  NVARCHAR (4000) NULL,
    [Sales 7]                  NVARCHAR (4000) NULL,
    [Sales 8]                  NVARCHAR (4000) NULL,
    [Sales 9]                  NVARCHAR (4000) NULL,
    [Sales 10]                 NVARCHAR (4000) NULL,
    [Sales 11]                 NVARCHAR (4000) NULL,
    [Sales 12]                 NVARCHAR (4000) NULL,
    [Sales 13]                 NVARCHAR (4000) NULL,
    [Sales 14]                 NVARCHAR (4000) NULL,
    [Sales 15]                 NVARCHAR (4000) NULL,
    [Sales 16]                 NVARCHAR (4000) NULL,
    [Sales 17]                 NVARCHAR (4000) NULL,
    [Sales 18]                 NVARCHAR (4000) NULL,
    [Sales 19]                 NVARCHAR (4000) NULL,
    [Sales 20]                 NVARCHAR (4000) NULL,
    [Sales 21]                 NVARCHAR (4000) NULL,
    [Sales 22]                 NVARCHAR (4000) NULL,
    [Sales 23]                 NVARCHAR (4000) NULL,
    [Sales 24]                 NVARCHAR (4000) NULL,
    [Purch 1]                  NVARCHAR (4000) NULL,
    [Purch 2]                  NVARCHAR (4000) NULL,
    [Purch 3]                  NVARCHAR (4000) NULL,
    [Purch 4]                  NVARCHAR (4000) NULL,
    [Purch 5]                  NVARCHAR (4000) NULL,
    [Purch 6]                  NVARCHAR (4000) NULL,
    [Purch 7]                  NVARCHAR (4000) NULL,
    [Purch 8]                  NVARCHAR (4000) NULL,
    [Purch 9]                  NVARCHAR (4000) NULL,
    [Purch 10]                 NVARCHAR (4000) NULL,
    [Purch 11]                 NVARCHAR (4000) NULL,
    [Purch 12]                 NVARCHAR (4000) NULL,
    [Purch 13]                 NVARCHAR (4000) NULL,
    [Purch 14]                 NVARCHAR (4000) NULL,
    [Purch 15]                 NVARCHAR (4000) NULL,
    [Purch 16]                 NVARCHAR (4000) NULL,
    [Purch 17]                 NVARCHAR (4000) NULL,
    [Purch 18]                 NVARCHAR (4000) NULL,
    [Purch 19]                 NVARCHAR (4000) NULL,
    [Purch 20]                 NVARCHAR (4000) NULL,
    [Purch 21]                 NVARCHAR (4000) NULL,
    [Purch 22]                 NVARCHAR (4000) NULL,
    [Purch 23]                 NVARCHAR (4000) NULL,
    [Purch 24]                 NVARCHAR (4000) NULL,
    [Cogs 1]                   NVARCHAR (4000) NULL,
    [Cogs 2]                   NVARCHAR (4000) NULL,
    [Cogs 3]                   NVARCHAR (4000) NULL,
    [Cogs 4]                   NVARCHAR (4000) NULL,
    [Cogs 5]                   NVARCHAR (4000) NULL,
    [Cogs 6]                   NVARCHAR (4000) NULL,
    [Cogs 7]                   NVARCHAR (4000) NULL,
    [Cogs 8]                   NVARCHAR (4000) NULL,
    [Cogs 9]                   NVARCHAR (4000) NULL,
    [Cogs 10]                  NVARCHAR (4000) NULL,
    [Cogs 11]                  NVARCHAR (4000) NULL,
    [Cogs 12]                  NVARCHAR (4000) NULL,
    [Cogs 13]                  NVARCHAR (4000) NULL,
    [Cogs 14]                  NVARCHAR (4000) NULL,
    [Cogs 15]                  NVARCHAR (4000) NULL,
    [Cogs 16]                  NVARCHAR (4000) NULL,
    [Cogs 17]                  NVARCHAR (4000) NULL,
    [Cogs 18]                  NVARCHAR (4000) NULL,
    [Cogs 19]                  NVARCHAR (4000) NULL,
    [Cogs 20]                  NVARCHAR (4000) NULL,
    [Cogs 21]                  NVARCHAR (4000) NULL,
    [Cogs 22]                  NVARCHAR (4000) NULL,
    [Cogs 23]                  NVARCHAR (4000) NULL,
    [Cogs 24]                  NVARCHAR (4000) NULL,
    [Type]                     NVARCHAR (4000) NULL,
    [Minor]                    NVARCHAR (4000) NULL,
    [Mj]                       NVARCHAR (4000) NULL,
    [A]                        NVARCHAR (4000) NULL,
    [MaxDis]                   NVARCHAR (4000) NULL,
    [Gl Stk Adj]               NVARCHAR (4000) NULL,
    [HG]                       NVARCHAR (4000) NULL,
    [CatReb]                   NVARCHAR (4000) NULL,
    [MinDis]                   NVARCHAR (4000) NULL,
    [Category Sub Description] NVARCHAR (4000) NULL,
    [Gl Grni]                  NVARCHAR (4000) NULL,
    [Gl Gsni]                  NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]      DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]            VARCHAR (8000)  NOT NULL
);

