CREATE TABLE [LND].[LND_EBS_OE_ORDER_SOURCES] (
    [ORDER_SOURCE_ID]       NVARCHAR (4000) NULL,
    [CREATION_DATE]         NVARCHAR (4000) NULL,
    [CREATED_BY]            NVARCHAR (4000) NULL,
    [LAST_UPDATE_DATE]      NVARCHAR (4000) NULL,
    [LAST_UPDATED_BY]       NVARCHAR (4000) NULL,
    [LAST_UPDATE_LOGIN]     NVARCHAR (4000) NULL,
    [NAME]                  NVARCHAR (4000) NULL,
    [DESCRIPTION]           NVARCHAR (4000) NULL,
    [ENABLED_FLAG]          NVARCHAR (4000) NULL,
    [CREATE_CUSTOMERS_FLAG] NVARCHAR (4000) NULL,
    [USE_IDS_FLAG]          NVARCHAR (4000) NULL,
    [AIA_ENABLED_FLAG]      NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]   DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]         VARCHAR (8000)  NOT NULL
);

