CREATE TABLE [LND].[LND_CA_INLOC] (
    [Loc]                  NVARCHAR (4000) NULL,
    [Location Name]        NVARCHAR (4000) NULL,
    [P]                    NVARCHAR (4000) NULL,
    [Address Line 1]       NVARCHAR (4000) NULL,
    [Address Line 2]       NVARCHAR (4000) NULL,
    [Address Line 3]       NVARCHAR (4000) NULL,
    [Phone]                NVARCHAR (4000) NULL,
    [Fax]                  NVARCHAR (4000) NULL,
    [Banner Location Name] NVARCHAR (4000) NULL,
    [O]                    NVARCHAR (4000) NULL,
    [DB]                   NVARCHAR (4000) NULL,
    [CurrDep0]             NVARCHAR (4000) NULL,
    [Last Inv#]            NVARCHAR (4000) NULL,
    [Last Rcp#]            NVARCHAR (4000) NULL,
    [Last So#]             NVARCHAR (4000) NULL,
    [Last Sq#]             NVARCHAR (4000) NULL,
    [Last Po#]             NVARCHAR (4000) NULL,
    [LastXfr#]             NVARCHAR (4000) NULL,
    [LastBch#]             NVARCHAR (4000) NULL,
    [LstInBch]             NVARCHAR (4000) NULL,
    [Delivery Name]        NVARCHAR (4000) NULL,
    [Delivery Address 1]   NVARCHAR (4000) NULL,
    [Delivery Address 2]   NVARCHAR (4000) NULL,
    [Delivery Address 3]   NVARCHAR (4000) NULL,
    [Del Phone]            NVARCHAR (4000) NULL,
    [Deliv Fax]            NVARCHAR (4000) NULL,
    [B]                    NVARCHAR (4000) NULL,
    [X]                    NVARCHAR (4000) NULL,
    [Iar]                  NVARCHAR (4000) NULL,
    [Email]                NVARCHAR (4000) NULL,
    [Rg]                   NVARCHAR (4000) NULL,
    [A]                    NVARCHAR (4000) NULL,
    [Msp]                  NVARCHAR (4000) NULL,
    [Pstcde]               NVARCHAR (4000) NULL,
    [Last Stake]           NVARCHAR (4000) NULL,
    [Curr Stake]           NVARCHAR (4000) NULL,
    [S]                    NVARCHAR (4000) NULL,
    [W]                    NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NOT NULL
);

