CREATE TABLE [LND].[LND_CA_OEINVLIN] (
    [Invoice#]            NVARCHAR (4000) NULL,
    [Inl#]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [Memo#]               NVARCHAR (4000) NULL,
    [Sale Qty]            NVARCHAR (4000) NULL,
    [Disc %]              NVARCHAR (4000) NULL,
    [Disc Value]          NVARCHAR (4000) NULL,
    [LinePrice]           NVARCHAR (4000) NULL,
    [SV Gst Incl]         NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [Lto]                 NVARCHAR (4000) NULL,
    [Cogs Value]          NVARCHAR (4000) NULL,
    [Gst Value]           NVARCHAR (4000) NULL,
    [Gst %]               NVARCHAR (4000) NULL,
    [P]                   NVARCHAR (4000) NULL,
    [Reas]                NVARCHAR (4000) NULL,
    [Backord Qty]         NVARCHAR (4000) NULL,
    [Order Qty]           NVARCHAR (4000) NULL,
    [CusTyp]              NVARCHAR (4000) NULL,
    [Spn]                 NVARCHAR (4000) NULL,
    [OeIncat]             NVARCHAR (4000) NULL,
    [Trans Date]          NVARCHAR (4000) NULL,
    [Pd]                  NVARCHAR (4000) NULL,
    [Cust#]               NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Start By]            NVARCHAR (4000) NULL,
    [Amend Date]          NVARCHAR (4000) NULL,
    [ATime]               NVARCHAR (4000) NULL,
    [Amend By]            NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

