CREATE TABLE [LND].[LND_EBS_MTL_ABC_ASSIGNMENTS] (
    [INVENTORY_ITEM_ID]       NVARCHAR (4000) NULL,
    [ASSIGNMENT_GROUP_ID]     NVARCHAR (4000) NULL,
    [ABC_CLASS_ID]            NVARCHAR (4000) NULL,
    [LAST_UPDATE_DATE]        NVARCHAR (4000) NULL,
    [LAST_UPDATED_BY]         NVARCHAR (4000) NULL,
    [CREATION_DATE]           NVARCHAR (4000) NULL,
    [CREATED_BY]              NVARCHAR (4000) NULL,
    [REQUEST_ID]              NVARCHAR (4000) NULL,
    [PROGRAM_APPLICATION_ID]  NVARCHAR (4000) NULL,
    [PROGRAM_ID]              NVARCHAR (4000) NULL,
    [PROGRAM_UPDATE_DATE]     NVARCHAR (4000) NULL,
    [META_EFFECTIVE_DATETIME] DATETIME2 (7)   NULL,
    [META_FILE_NAME]          NVARCHAR (MAX)  NULL,
    [META_RECORD_SOURCE]      NVARCHAR (MAX)  NULL
);

