CREATE TABLE [LND].[LND_CA_SQLQUOTE] (
    [Sq#]                 NVARCHAR (4000) NULL,
    [Sql#]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [Pr]                  NVARCHAR (4000) NULL,
    [Deliv Date]          NVARCHAR (4000) NULL,
    [Comment]             NVARCHAR (4000) NULL,
    [Quote Qty]           NVARCHAR (4000) NULL,
    [LinePrice]           NVARCHAR (4000) NULL,
    [Disc %]              NVARCHAR (4000) NULL,
    [QV Gst Incl]         NVARCHAR (4000) NULL,
    [Quote Item Type]     NVARCHAR (4000) NULL,
    [Quote Item Ref]      NVARCHAR (4000) NULL,
    [Unit Cost]           NVARCHAR (4000) NULL,
    [Cost Value]          NVARCHAR (4000) NULL,
    [X]                   NVARCHAR (4000) NULL,
    [TxCert]              NVARCHAR (4000) NULL,
    [Gst Value]           NVARCHAR (4000) NULL,
    [Disc Value]          NVARCHAR (4000) NULL,
    [Gst%]                NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [LSup]                NVARCHAR (4000) NULL,
    [Supplier Item Code]  NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Start By]            NVARCHAR (4000) NULL,
    [Mx NetPrc]           NVARCHAR (4000) NULL,
    [Mx Price]            NVARCHAR (4000) NULL,
    [MxDis%]              NVARCHAR (4000) NULL,
    [T]                   NVARCHAR (4000) NULL,
    [Mx Item/Incat]       NVARCHAR (4000) NULL,
    [MxCust]              NVARCHAR (4000) NULL,
    [Mx QVGstExc]         NVARCHAR (4000) NULL,
    [Mx Val Fm]           NVARCHAR (4000) NULL,
    [Mx Val To]           NVARCHAR (4000) NULL,
    [MxPrbk]              NVARCHAR (4000) NULL,
    [MPC]                 NVARCHAR (4000) NULL,
    [Trade Prc]           NVARCHAR (4000) NULL,
    [Msp]                 NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

