CREATE TABLE [LND].[LND_CA_INRFCLIN] (
    [Rfc#]                NVARCHAR (4000) NULL,
    [Rfcl]                NVARCHAR (4000) NULL,
    [Item Code]           NVARCHAR (4000) NULL,
    [Buy Price]           NVARCHAR (4000) NULL,
    [Return Qty]          NVARCHAR (4000) NULL,
    [Cogs Value]          NVARCHAR (4000) NULL,
    [Comment]             NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Start By]            NVARCHAR (4000) NULL,
    [Amend Date]          NVARCHAR (4000) NULL,
    [ATime]               NVARCHAR (4000) NULL,
    [Amend By]            NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [Sup#]                NVARCHAR (4000) NULL,
    [Spn]                 NVARCHAR (4000) NULL,
    [Po Delivery Ref]     NVARCHAR (4000) NULL,
    [Po#]                 NVARCHAR (4000) NULL,
    [Pol#]                NVARCHAR (4000) NULL,
    [Po BuyPrice]         NVARCHAR (4000) NULL,
    [Po Invoice Ref]      NVARCHAR (4000) NULL,
    [Credit Qty]          NVARCHAR (4000) NULL,
    [Credit Cogs]         NVARCHAR (4000) NULL,
    [Glacct#]             NVARCHAR (4000) NULL,
    [LMatMeth]            NVARCHAR (4000) NULL,
    [Matched Reference]   NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

