CREATE TABLE [LND].[LND_CA_DLMAST] (
    [Cust#]                   NVARCHAR (4000) NULL,
    [Key]                     NVARCHAR (4000) NULL,
    [Customer Name]           NVARCHAR (4000) NULL,
    [Address Line 1]          NVARCHAR (4000) NULL,
    [Address Line 2]          NVARCHAR (4000) NULL,
    [Address Line 3]          NVARCHAR (4000) NULL,
    [Contact]                 NVARCHAR (4000) NULL,
    [Phone]                   NVARCHAR (4000) NULL,
    [Fax]                     NVARCHAR (4000) NULL,
    [Bal Future]              NVARCHAR (4000) NULL,
    [BalCurrent]              NVARCHAR (4000) NULL,
    [Bal 30Days]              NVARCHAR (4000) NULL,
    [Bal 60Days]              NVARCHAR (4000) NULL,
    [Bal 90Days]              NVARCHAR (4000) NULL,
    [LastRcpVal]              NVARCHAR (4000) NULL,
    [LstRcpDate]              NVARCHAR (4000) NULL,
    [Bnk]                     NVARCHAR (4000) NULL,
    [Bank Branch]             NVARCHAR (4000) NULL,
    [Cred Limit]              NVARCHAR (4000) NULL,
    [S]                       NVARCHAR (4000) NULL,
    [W]                       NVARCHAR (4000) NULL,
    [Profile]                 NVARCHAR (4000) NULL,
    [Start Date]              NVARCHAR (4000) NULL,
    [Comment]                 NVARCHAR (4000) NULL,
    [Prc]                     NVARCHAR (4000) NULL,
    [CusTyp]                  NVARCHAR (4000) NULL,
    [Crl]                     NVARCHAR (4000) NULL,
    [Open Bal]                NVARCHAR (4000) NULL,
    [Crmt]                    NVARCHAR (4000) NULL,
    [InsLim]                  NVARCHAR (4000) NULL,
    [TxCert]                  NVARCHAR (4000) NULL,
    [X]                       NVARCHAR (4000) NULL,
    [On Order]                NVARCHAR (4000) NULL,
    [Sales 1]                 NVARCHAR (4000) NULL,
    [Sales 2]                 NVARCHAR (4000) NULL,
    [Sales 3]                 NVARCHAR (4000) NULL,
    [Sales 4]                 NVARCHAR (4000) NULL,
    [Sales 5]                 NVARCHAR (4000) NULL,
    [Sales 6]                 NVARCHAR (4000) NULL,
    [Sales 7]                 NVARCHAR (4000) NULL,
    [Sales 8]                 NVARCHAR (4000) NULL,
    [Sales 9]                 NVARCHAR (4000) NULL,
    [Sales 10]                NVARCHAR (4000) NULL,
    [Sales 11]                NVARCHAR (4000) NULL,
    [Sales 12]                NVARCHAR (4000) NULL,
    [Sales 13]                NVARCHAR (4000) NULL,
    [Sales 14]                NVARCHAR (4000) NULL,
    [Sales 15]                NVARCHAR (4000) NULL,
    [Sales 16]                NVARCHAR (4000) NULL,
    [Sales 17]                NVARCHAR (4000) NULL,
    [Sales 18]                NVARCHAR (4000) NULL,
    [Sales 19]                NVARCHAR (4000) NULL,
    [Sales 20]                NVARCHAR (4000) NULL,
    [Sales 21]                NVARCHAR (4000) NULL,
    [Sales 22]                NVARCHAR (4000) NULL,
    [Sales 23]                NVARCHAR (4000) NULL,
    [Sales 24]                NVARCHAR (4000) NULL,
    [Cogs 1]                  NVARCHAR (4000) NULL,
    [Cogs 2]                  NVARCHAR (4000) NULL,
    [Cogs 3]                  NVARCHAR (4000) NULL,
    [Cogs 4]                  NVARCHAR (4000) NULL,
    [Cogs 5]                  NVARCHAR (4000) NULL,
    [Cogs 6]                  NVARCHAR (4000) NULL,
    [Cogs 7]                  NVARCHAR (4000) NULL,
    [Cogs 8]                  NVARCHAR (4000) NULL,
    [Cogs 9]                  NVARCHAR (4000) NULL,
    [Cogs 10]                 NVARCHAR (4000) NULL,
    [Cogs 11]                 NVARCHAR (4000) NULL,
    [Cogs 12]                 NVARCHAR (4000) NULL,
    [Cogs 13]                 NVARCHAR (4000) NULL,
    [Cogs 14]                 NVARCHAR (4000) NULL,
    [Cogs 15]                 NVARCHAR (4000) NULL,
    [Cogs 16]                 NVARCHAR (4000) NULL,
    [Cogs 17]                 NVARCHAR (4000) NULL,
    [Cogs 18]                 NVARCHAR (4000) NULL,
    [Cogs 19]                 NVARCHAR (4000) NULL,
    [Cogs 20]                 NVARCHAR (4000) NULL,
    [Cogs 21]                 NVARCHAR (4000) NULL,
    [Cogs 22]                 NVARCHAR (4000) NULL,
    [Cogs 23]                 NVARCHAR (4000) NULL,
    [Cogs 24]                 NVARCHAR (4000) NULL,
    [Last Sale]               NVARCHAR (4000) NULL,
    [Spare Bal]               NVARCHAR (4000) NULL,
    [DeliveryMeth]            NVARCHAR (4000) NULL,
    [C]                       NVARCHAR (4000) NULL,
    [Last Aged]               NVARCHAR (4000) NULL,
    [Stmt#]                   NVARCHAR (4000) NULL,
    [Mobile]                  NVARCHAR (4000) NULL,
    [Pstcde]                  NVARCHAR (4000) NULL,
    [Acn]                     NVARCHAR (4000) NULL,
    [PrvYrSals5]              NVARCHAR (4000) NULL,
    [PrvYrSals4]              NVARCHAR (4000) NULL,
    [PrvYrSals3]              NVARCHAR (4000) NULL,
    [PrvYrSals2]              NVARCHAR (4000) NULL,
    [PrvYrCogs5]              NVARCHAR (4000) NULL,
    [PrvYrCogs4]              NVARCHAR (4000) NULL,
    [PrvYrCogs3]              NVARCHAR (4000) NULL,
    [PrvYrCogs2]              NVARCHAR (4000) NULL,
    [Comment2]                NVARCHAR (4000) NULL,
    [Email Contact]           NVARCHAR (4000) NULL,
    [R]                       NVARCHAR (4000) NULL,
    [P]                       NVARCHAR (4000) NULL,
    [H]                       NVARCHAR (4000) NULL,
    [M]                       NVARCHAR (4000) NULL,
    [N]                       NVARCHAR (4000) NULL,
    [G]                       NVARCHAR (4000) NULL,
    [O]                       NVARCHAR (4000) NULL,
    [F]                       NVARCHAR (4000) NULL,
    [D]                       NVARCHAR (4000) NULL,
    [A]                       NVARCHAR (4000) NULL,
    [Invoice Popup Message]   NVARCHAR (4000) NULL,
    [Debt Bal]                NVARCHAR (4000) NULL,
    [Parm1]                   NVARCHAR (4000) NULL,
    [I]                       NVARCHAR (4000) NULL,
    [Email Invoice]           NVARCHAR (4000) NULL,
    [T]                       NVARCHAR (4000) NULL,
    [Email Order Confimation] NVARCHAR (4000) NULL,
    [Email Quote]             NVARCHAR (4000) NULL,
    [DefDAd]                  NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME]     DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]           VARCHAR (8000)  NOT NULL
);

