CREATE TABLE [LND].[LND_CA_INRFCHDR] (
    [Rfc#]                NVARCHAR (4000) NULL,
    [Sup#]                NVARCHAR (4000) NULL,
    [Batch#]              NVARCHAR (4000) NULL,
    [Rts Reference]       NVARCHAR (4000) NULL,
    [Original Inv]        NVARCHAR (4000) NULL,
    [Gra]                 NVARCHAR (4000) NULL,
    [Gra IssDat]          NVARCHAR (4000) NULL,
    [Reason]              NVARCHAR (4000) NULL,
    [Spn]                 NVARCHAR (4000) NULL,
    [ReturnDate]          NVARCHAR (4000) NULL,
    [M]                   NVARCHAR (4000) NULL,
    [Match Date]          NVARCHAR (4000) NULL,
    [AdrT]                NVARCHAR (4000) NULL,
    [Loc]                 NVARCHAR (4000) NULL,
    [Start Date]          NVARCHAR (4000) NULL,
    [STime]               NVARCHAR (4000) NULL,
    [Start By]            NVARCHAR (4000) NULL,
    [Rfc Value]           NVARCHAR (4000) NULL,
    [Amend Date]          NVARCHAR (4000) NULL,
    [ATime]               NVARCHAR (4000) NULL,
    [Amend By]            NVARCHAR (4000) NULL,
    [Ship Date]           NVARCHAR (4000) NULL,
    [Con Note]            NVARCHAR (4000) NULL,
    [Carrier]             NVARCHAR (4000) NULL,
    [O]                   NVARCHAR (4000) NULL,
    [Notes]               NVARCHAR (4000) NULL,
    [Transmission]        NVARCHAR (4000) NULL,
    [MatchMeth]           NVARCHAR (4000) NULL,
    [OMD_INSERT_DATETIME] DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]       VARCHAR (8000)  NOT NULL
);

