CREATE TABLE [DW].[Dim_Product] (
    [Dim_Product_Key]         INT             IDENTITY (1, 1) NOT NULL,
    [ItemCode]                NVARCHAR (30)   NULL,
    [Dim_ProductCategory_Key] INT             NULL,
    [Indent]                  VARCHAR (1)     NOT NULL,
    [ProductDescription]      NVARCHAR (200)  NULL,
    [ProductGroup]            NVARCHAR (30)   NULL,
    [Uom]                     NVARCHAR (20)   NULL,
    [ValueAtCost]             DECIMAL (36, 4) NULL,
    [StockQuantity]           DECIMAL (36, 4) NULL,
    [NationalBuyPrice]        DECIMAL (36, 4) NULL,
    [CommitQuantity]          DECIMAL (36, 4) NULL,
    [OrderQuantity]           DECIMAL (36, 4) NULL,
    [RetailPrice]             DECIMAL (36, 4) NULL,
    [SupplierCode]            INT             NULL,
    [SupplierItemCode]        NVARCHAR (50)   NULL,
    [LastSale]                DATETIME2 (7)   NULL,
    [Comment]                 NVARCHAR (200)  NULL,
    [CurrentStake]            DATETIME2 (7)   NULL,
    [StartDate]               DATETIME2 (7)   NULL,
    [LastPurchase]            DATETIME2 (7)   NULL,
    [OracleID]                FLOAT (53)      NULL,
    [BarcodeGTIN]             NVARCHAR (30)   NULL,
    [DCFilled]                NVARCHAR (20)   NULL,
    [AutoReplenished]         NVARCHAR (20)   NULL,
    [Dim_SourceSystem]        VARCHAR (20)    NOT NULL,
    [Dim_Type1HashDiff]       CHAR (32)       NULL,
    [Dim_Type2HashDiff]       CHAR (32)       NULL,
    [Dim_EffectiveFrom]       DATETIME2 (7)   NOT NULL,
    [Dim_EffectiveTo]         DATETIME2 (7)   NOT NULL,
    [Dim_InsertDateTime]      DATETIME2 (7)   CONSTRAINT [DF__Dim_Produ__Dim_I__2D9297B4] DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    [Dim_UpdateDateTime]      DATETIME2 (7)   CONSTRAINT [DF__Dim_Produ__Dim_U__2E86BBED] DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    CONSTRAINT [PK_Dim_Product] PRIMARY KEY CLUSTERED ([Dim_Product_Key] ASC)
);

