CREATE TABLE [DW].[Dim_Customer] (
    [Dim_Customer_Key]        INT             IDENTITY (1, 1) NOT NULL,
    [CustomerNumber]          INT             NOT NULL,
    [CustomerSortKey]         NVARCHAR (200)  NULL,
    [CustomerName]            NVARCHAR (200)  NOT NULL,
    [AddressLine1]            NVARCHAR (100)  NULL,
    [AddressLine2]            NVARCHAR (100)  NULL,
    [AddressLine3]            NVARCHAR (100)  NULL,
    [Contact]                 NVARCHAR (100)  NULL,
    [Phone]                   NVARCHAR (50)   NULL,
    [Mobile]                  NVARCHAR (50)   NULL,
    [PostCode]                NVARCHAR (10)   NULL,
    [ContactEmail]            NVARCHAR (200)  NULL,
    [InvoiceEmail]            NVARCHAR (200)  NULL,
    [CurrentBalance]          DECIMAL (36, 4) NULL,
    [LastSale]                DATETIME2 (7)   NULL,
    [CreditLimit]             DECIMAL (36, 4) NULL,
    [StartDate]               DATETIME2 (7)   NULL,
    [Dim_CustomerBranch_Key]  VARCHAR (32)    NOT NULL,
    [CustomerTypeDescription] NVARCHAR (100)  NULL,
    [CustomerSector]          NVARCHAR (20)   NULL,
    [CustomerSalesType]       NVARCHAR (20)   NULL,
    [SalespersonName]         NVARCHAR (50)   NULL,
    [CrmTerritory]            NVARCHAR (100)  NULL,
    [CRMTNumber]              INT             NULL,
    [Dim_SourceSystem]        VARCHAR (20)    NOT NULL,
    [Dim_Type1HashDiff]       CHAR (32)       NULL,
    [Dim_Type2HashDiff]       CHAR (32)       NULL,
    [Dim_EffectiveFrom]       DATETIME2 (7)   NOT NULL,
    [Dim_EffectiveTo]         DATETIME2 (7)   NOT NULL,
    [Dim_InsertDateTime]      DATETIME2 (7)   DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    [Dim_UpdateDateTime]      DATETIME2 (7)   DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    CONSTRAINT [PK_Dim_Customer] PRIMARY KEY CLUSTERED ([Dim_Customer_Key] ASC)
);

