CREATE TABLE [DW].[Dim_Location] (
    [Dim_Location_Key]    INT             IDENTITY (1, 1) NOT NULL,
    [LocationCode]        NVARCHAR (6)    NULL,
    [LocationName]        NVARCHAR (100)  NULL,
    [RegionCode]          NVARCHAR (4)    NULL,
    [Region]              VARCHAR (40)    NOT NULL,
    [AddressLine1]        NVARCHAR (100)  NULL,
    [AddressLine2]        NVARCHAR (100)  NULL,
    [AddressLine3]        NVARCHAR (100)  NULL,
    [Phone]               NVARCHAR (50)   NULL,
    [Fax]                 NVARCHAR (50)   NULL,
    [BannerLocationName]  NVARCHAR (160)  NULL,
    [DeliveryName]        NVARCHAR (160)  NULL,
    [DeliveryAddress1]    NVARCHAR (100)  NULL,
    [DeliveryAddress2]    NVARCHAR (100)  NULL,
    [DeliveryAddress3]    NVARCHAR (100)  NULL,
    [DeliveryPhone]       NVARCHAR (50)   NULL,
    [DeliveryFax]         NVARCHAR (50)   NULL,
    [Email]               NVARCHAR (200)  NULL,
    [PostCode]            NVARCHAR (10)   NULL,
    [LastStockTake]       DATETIME2 (7)   NULL,
    [CurrentStockTake]    DATETIME2 (7)   NULL,
    [StockTakeInProgress] CHAR (1)        NULL,
    [OperationsManager]   NVARCHAR (30)   NULL,
    [Latitude]            DECIMAL (12, 9) NULL,
    [Longitude]           DECIMAL (12, 9) NULL,
    [Dim_SourceSystem]    VARCHAR (20)    NOT NULL,
    [Dim_Type1HashDiff]   CHAR (32)       NULL,
    [Dim_Type2HashDiff]   CHAR (32)       NULL,
    [Dim_EffectiveFrom]   DATETIME2 (7)   NOT NULL,
    [Dim_EffectiveTo]     DATETIME2 (7)   NOT NULL,
    [Dim_InsertDateTime]  DATETIME2 (7)   CONSTRAINT [DF__Dim_Locat__Dim_I__2BAA4F42] DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    [Dim_UpdateDateTime]  DATETIME2 (7)   CONSTRAINT [DF__Dim_Locat__Dim_U__2C9E737B] DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    CONSTRAINT [PK_Dim_Location] PRIMARY KEY CLUSTERED ([Dim_Location_Key] ASC)
);

