CREATE TABLE [DW].[Fact_Sales] (
    [InvoiceNumber]                    FLOAT (53)      NOT NULL,
    [LineNumber]                       DECIMAL (10, 3) NOT NULL,
    [Dim_SalesTransaction_Key]         INT             NOT NULL,
    [Dim_Location_Key]                 INT             NOT NULL,
    [Dim_Customer_Key]                 INT             NOT NULL,
    [Dim_Product_Key]                  INT             NOT NULL,
    [Dim_ProductCategory_Key]          INT             NOT NULL,
    [Dim_TransactionSource_Key]        INT             NOT NULL,
    [Dim_Date_Key]                     INT             NOT NULL,
    [TransactionDate]                  DATETIME2 (7)   NULL,
    [Dim_RequestedDate_Key]            INT             NOT NULL,
    [RequestedDate]                    DATETIME2 (7)   NULL,
    [Dim_DeliveryDate_Key]             INT             NOT NULL,
    [DeliveryDate]                     DATETIME2 (7)   NULL,
    [SalesOrder]                       FLOAT (53)      NULL,
    [OrderSource]                      NVARCHAR (60)   NULL,
    [SalesQuantity]                    FLOAT (53)      NULL,
    [SalesValueExGST]                  FLOAT (53)      NULL,
    [N3Rebate]                         DECIMAL (38, 4) NULL,
    [IndividualRebate]                 DECIMAL (38, 4) NULL,
    [CustomerRebate]                   DECIMAL (38, 4) NULL,
    [NetSalesValue]                    FLOAT (53)      NULL,
    [COGS]                             FLOAT (53)      NULL,
    [LoyaltyRebate]                    DECIMAL (38, 4) NULL,
    [RawMargin]                        FLOAT (53)      NULL,
    [CommercialMargin]                 FLOAT (53)      NULL,
    [SupplierRebate]                   FLOAT (53)      NULL,
    [SalesCommercialMarginWithRebates] FLOAT (53)      NULL,
    [Fact_SourceSystem]                VARCHAR (16)    NOT NULL,
    [Fact_InsertDateTime]              DATETIME2 (7)   DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    [Fact_UpdateDateTime]              DATETIME2 (7)   DEFAULT (CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'AUS Eastern Standard Time'))) NULL,
    CONSTRAINT [PK_Fact_Sales] PRIMARY KEY CLUSTERED ([InvoiceNumber] ASC, [LineNumber] ASC)
);

