CREATE TABLE [DW].[Fact_InventoryTransfer] (
    [Dim_Transfer_Key]        INT             NOT NULL,
    [Dim_Location_Key]        INT             NULL,
    [Dim_LocationFrom_Key]    INT             NULL,
    [Dim_Customer_Key]        INT             NOT NULL,
    [Dim_Product_Key]         INT             NOT NULL,
    [Dim_ProductCategory_Key] INT             NOT NULL,
    [Dim_RequestDate_Key]     INT             NOT NULL,
    [RequestDate]             DATE            NULL,
    [AcceptDate]              DATE            NULL,
    [FillDate]                DATE            NULL,
    [PublishDate]             DATE            NULL,
    [ExpectDate]              DATE            NULL,
    [ItemCode]                NVARCHAR (100)  NULL,
    [RequestByLocation]       DECIMAL (36)    NULL,
    [RequestFromLocation]     DECIMAL (36)    NULL,
    [RequestQty]              DECIMAL (36)    NULL,
    [DispatchQty]             DECIMAL (36)    NULL,
    [RejectQty]               DECIMAL (36)    NULL,
    [OutstandingQty]          DECIMAL (38)    NULL,
    [RejectReason]            NVARCHAR (1000) NULL,
    [SalesOrder#]             DECIMAL (36)    NULL,
    [SalesOrderLine#]         DECIMAL (36)    NULL,
    [PurchaseOrder#]          DECIMAL (36)    NULL,
    [PurchaseOrderLine#]      DECIMAL (36)    NULL,
    [PubRef#]                 DECIMAL (36)    NULL,
    [PubRefLine#]             DECIMAL (36)    NULL,
    [Dim_Type1HashDiff]       CHAR (32)       NULL,
    [Dim_SourceSystem]        VARCHAR (16)    NOT NULL,
    [Fact_InsertDateTime]     DATETIME2 (7)   NULL,
    [Fact_UpdateDateTime]     DATETIME2 (7)   NULL
);

