CREATE TABLE [DW].[Fact_SalesOrderHistory] (
    [SnapshotDateKey]           INT             NOT NULL,
    [OrderNumber]               FLOAT (53)      NOT NULL,
    [LineNumber]                DECIMAL (10, 3) NOT NULL,
    [Dim_Location_Key]          INT             NOT NULL,
    [Dim_Customer_Key]          INT             NOT NULL,
    [Dim_Product_Key]           INT             NOT NULL,
    [Dim_ProductCategory_Key]   INT             NOT NULL,
    [Dim_TransactionSource_Key] INT             NOT NULL,
    [Dim_OrderDate_Key]         INT             NOT NULL,
    [OrderDate]                 DATETIME2 (7)   NULL,
    [DaysOpen]                  INT             NULL,
    [Dim_DeliveryDate_Key]      INT             NOT NULL,
    [DeliveryDate]              DATETIME2 (7)   NULL,
    [Priority]                  NVARCHAR (100)  NULL,
    [UserID]                    NVARCHAR (6)    NULL,
    [Hold]                      NVARCHAR (6)    NULL,
    [Project]                   NVARCHAR (2)    NULL,
    [OrderedQty]                FLOAT (53)      NULL,
    [CancelledQt]               FLOAT (53)      NULL,
    [BackorderedQty]            FLOAT (53)      NULL,
    [ShippedQty]                FLOAT (53)      NULL,
    [LinePrice]                 FLOAT (53)      NULL,
    [OnOrderQty]                FLOAT (53)      NULL,
    [SalesValueExGST]           FLOAT (53)      NULL,
    [GstValue]                  FLOAT (53)      NULL,
    [COGS]                      FLOAT (53)      NULL,
    [DiscountRate]              DECIMAL (36, 4) NULL,
    [DiscountValue]             DECIMAL (36, 4) NULL,
    [OnOrderValueExclGST]       FLOAT (53)      NULL,
    [SourceSystem]              VARCHAR (20)    NOT NULL,
    CONSTRAINT [PK_Fact_SalesOrderHistory] PRIMARY KEY CLUSTERED ([SnapshotDateKey] ASC, [OrderNumber] ASC, [LineNumber] ASC)
);

