

CREATE VIEW "HSTG"."VW_HSTG_EBS_PO_HEADERS_ALL"
AS


    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        14/10/2022 2:10:52 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    SELECT TOP 10 * FROM  "HSTG"."VW_HSTG_EBS_PO_HEADERS_ALL"();
    
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-10-14    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    SELECT
        "PO_HEADER_ID"
        ,"AGENT_ID"
        ,"TYPE_LOOKUP_CODE"
        ,"LAST_UPDATE_DATE"
        ,"LAST_UPDATED_BY"
        ,"SEGMENT1"
        ,"SUMMARY_FLAG"
        ,"ENABLED_FLAG"
        ,"SEGMENT2"
        ,"SEGMENT3"
        ,"SEGMENT4"
        ,"SEGMENT5"
        ,"START_DATE_ACTIVE"
        ,"END_DATE_ACTIVE"
        ,"LAST_UPDATE_LOGIN"
        ,"CREATION_DATE"
        ,"CREATED_BY"
        ,"VENDOR_ID"
        ,"VENDOR_SITE_ID"
        ,"VENDOR_CONTACT_ID"
        ,"SHIP_TO_LOCATION_ID"
        ,"BILL_TO_LOCATION_ID"
        ,"TERMS_ID"
        ,"SHIP_VIA_LOOKUP_CODE"
        ,"FOB_LOOKUP_CODE"
        ,"FREIGHT_TERMS_LOOKUP_CODE"
        ,"STATUS_LOOKUP_CODE"
        ,"CURRENCY_CODE"
        ,"RATE_TYPE"
        ,"RATE_DATE"
        ,"RATE"
        ,"FROM_HEADER_ID"
        ,"FROM_TYPE_LOOKUP_CODE"
        ,"START_DATE"
        ,"END_DATE"
        ,"BLANKET_TOTAL_AMOUNT"
        ,"AUTHORIZATION_STATUS"
        ,"REVISION_NUM"
        ,"REVISED_DATE"
        ,"APPROVED_FLAG"
        ,"APPROVED_DATE"
        ,"AMOUNT_LIMIT"
        ,"MIN_RELEASE_AMOUNT"
        ,"NOTE_TO_AUTHORIZER"
        ,"NOTE_TO_VENDOR"
        ,"NOTE_TO_RECEIVER"
        ,"PRINT_COUNT"
        ,"PRINTED_DATE"
        ,"VENDOR_ORDER_NUM"
        ,"CONFIRMING_ORDER_FLAG"
        ,"COMMENTS"
        ,"REPLY_DATE"
        ,"REPLY_METHOD_LOOKUP_CODE"
        ,"RFQ_CLOSE_DATE"
        ,"QUOTE_TYPE_LOOKUP_CODE"
        ,"QUOTATION_CLASS_CODE"
        ,"QUOTE_WARNING_DELAY_UNIT"
        ,"QUOTE_WARNING_DELAY"
        ,"QUOTE_VENDOR_QUOTE_NUMBER"
        ,"ACCEPTANCE_REQUIRED_FLAG"
        ,"ACCEPTANCE_DUE_DATE"
        ,"CLOSED_DATE"
        ,"USER_HOLD_FLAG"
        ,"APPROVAL_REQUIRED_FLAG"
        ,"CANCEL_FLAG"
        ,"FIRM_STATUS_LOOKUP_CODE"
        ,"FIRM_DATE"
        ,"FROZEN_FLAG"
        ,"SUPPLY_AGREEMENT_FLAG"
        ,"EDI_PROCESSED_FLAG"
        ,"EDI_PROCESSED_STATUS"
        ,"ATTRIBUTE_CATEGORY"
        ,"ATTRIBUTE1"
        ,"ATTRIBUTE2"
        ,"ATTRIBUTE3"
        ,"ATTRIBUTE4"
        ,"ATTRIBUTE5"
        ,"ATTRIBUTE6"
        ,"ATTRIBUTE7"
        ,"ATTRIBUTE8"
        ,"ATTRIBUTE9"
        ,"ATTRIBUTE10"
        ,"ATTRIBUTE11"
        ,"ATTRIBUTE12"
        ,"ATTRIBUTE13"
        ,"ATTRIBUTE14"
        ,"ATTRIBUTE15"
        ,"CLOSED_CODE"
        ,"USSGL_TRANSACTION_CODE"
        ,"GOVERNMENT_CONTEXT"
        ,"REQUEST_ID"
        ,"PROGRAM_APPLICATION_ID"
        ,"PROGRAM_ID"
        ,"PROGRAM_UPDATE_DATE"
        ,"ORG_ID"
        ,"GLOBAL_ATTRIBUTE_CATEGORY"
        ,"GLOBAL_ATTRIBUTE1"
        ,"GLOBAL_ATTRIBUTE2"
        ,"GLOBAL_ATTRIBUTE3"
        ,"GLOBAL_ATTRIBUTE4"
        ,"GLOBAL_ATTRIBUTE5"
        ,"GLOBAL_ATTRIBUTE6"
        ,"GLOBAL_ATTRIBUTE7"
        ,"GLOBAL_ATTRIBUTE8"
        ,"GLOBAL_ATTRIBUTE9"
        ,"GLOBAL_ATTRIBUTE10"
        ,"GLOBAL_ATTRIBUTE11"
        ,"GLOBAL_ATTRIBUTE12"
        ,"GLOBAL_ATTRIBUTE13"
        ,"GLOBAL_ATTRIBUTE14"
        ,"GLOBAL_ATTRIBUTE15"
        ,"GLOBAL_ATTRIBUTE16"
        ,"GLOBAL_ATTRIBUTE17"
        ,"GLOBAL_ATTRIBUTE18"
        ,"GLOBAL_ATTRIBUTE19"
        ,"GLOBAL_ATTRIBUTE20"
        ,"INTERFACE_SOURCE_CODE"
        ,"REFERENCE_NUM"
        ,"WF_ITEM_TYPE"
        ,"WF_ITEM_KEY"
        ,"MRC_RATE_TYPE"
        ,"MRC_RATE_DATE"
        ,"MRC_RATE"
        ,"PCARD_ID"
        ,"PRICE_UPDATE_TOLERANCE"
        ,"PAY_ON_CODE"
        ,"XML_FLAG"
        ,"XML_SEND_DATE"
        ,"XML_CHANGE_SEND_DATE"
        ,"GLOBAL_AGREEMENT_FLAG"
        ,"CONSIGNED_CONSUMPTION_FLAG"
        ,"CBC_ACCOUNTING_DATE"
        ,"CONSUME_REQ_DEMAND_FLAG"
        ,"CHANGE_REQUESTED_BY"
        ,"SHIPPING_CONTROL"
        ,"CONTERMS_EXIST_FLAG"
        ,"CONTERMS_ARTICLES_UPD_DATE"
        ,"CONTERMS_DELIV_UPD_DATE"
        ,"ENCUMBRANCE_REQUIRED_FLAG"
        ,"PENDING_SIGNATURE_FLAG"
        ,"CHANGE_SUMMARY"
        ,"DOCUMENT_CREATION_METHOD"
        ,"SUBMIT_DATE"
        ,"SUPPLIER_NOTIF_METHOD"
        ,"FAX"
        ,"EMAIL_ADDRESS"
        ,"RETRO_PRICE_COMM_UPDATES_FLAG"
        ,"RETRO_PRICE_APPLY_UPDATES_FLAG"
        ,"UPDATE_SOURCING_RULES_FLAG"
        ,"AUTO_SOURCING_FLAG"
        ,"CREATED_LANGUAGE"
        ,"CPA_REFERENCE"
        ,"LOCK_OWNER_ROLE"
        ,"LOCK_OWNER_USER_ID"
        ,"SUPPLIER_AUTH_ENABLED_FLAG"
        ,"CAT_ADMIN_AUTH_ENABLED_FLAG"
        ,"STYLE_ID"
        ,"TAX_ATTRIBUTE_UPDATE_CODE"
        ,"LAST_UPDATED_PROGRAM"
        ,"ENABLE_ALL_SITES"
        ,"PAY_WHEN_PAID"
        ,"COMM_REV_NUM"
        ,"CLM_DOCUMENT_NUMBER"
        ,"OTM_STATUS_CODE"
        ,"OTM_RECOVERY_FLAG"
        ,"AME_APPROVAL_ID"
        ,"AME_TRANSACTION_TYPE"
	,"META_RECORD_KEY"
    ,"META_EFFECTIVE_DATETIME"
    ,"META_EXPIRY_DATETIME"
    ,"META_CDC_OPERATION"
    ,"META_FILE_NAME"
    ,"META_CURRENT_RECORD_INDICATOR"
    ,"META_DELETE_INDICATOR"
    ,"META_RECORD_CHECKSUM"
    ,"META_RECORD_SOURCE"
    ,"META_ROW_ID"
    FROM "HSTG"."HSTG_EBS_PO_HEADERS_ALL" H
    WHERE "META_CURRENT_RECORD_INDICATOR"= 'Y'
