CREATE TABLE [REF].[CategoryRebateHistory] (
    [Incat]                         NVARCHAR (40)    NOT NULL,
    [L]                             FLOAT (53)       NULL,
    [A]                             NVARCHAR (50)    NULL,
    [NS]                            NVARCHAR (1)     NULL,
    [Typ]                           NVARCHAR (50)    NULL,
    [Item_Category_Description]     NVARCHAR (50)    NULL,
    [Item_Category_Sub_Description] NVARCHAR (100)   NULL,
    [Jan_20]                        DECIMAL (18, 10) NOT NULL,
    [Feb_20]                        DECIMAL (18, 10) NOT NULL,
    [Mar_20]                        DECIMAL (18, 10) NOT NULL,
    [Apr_20]                        DECIMAL (18, 10) NOT NULL,
    [May_20]                        DECIMAL (18, 10) NOT NULL,
    [Jun_20]                        DECIMAL (18, 10) NOT NULL,
    [Jul_20]                        DECIMAL (18, 10) NOT NULL,
    [Aug_20]                        DECIMAL (18, 10) NOT NULL,
    [Sep_20]                        DECIMAL (18, 10) NOT NULL,
    [Oct_20]                        DECIMAL (18, 10) NOT NULL,
    [Nov_20]                        DECIMAL (18, 10) NOT NULL,
    [Dec_20]                        DECIMAL (18, 10) NOT NULL,
    [Jan_21]                        DECIMAL (18, 10) NOT NULL,
    [Feb_21]                        DECIMAL (18, 10) NOT NULL,
    [Mar_21]                        DECIMAL (18, 10) NOT NULL,
    [Apr_21]                        DECIMAL (18, 10) NOT NULL,
    [May_21]                        DECIMAL (18, 10) NOT NULL,
    [Jun_21]                        DECIMAL (18, 10) NOT NULL,
    [Jul_21]                        DECIMAL (18, 10) NOT NULL,
    [Aug_21]                        DECIMAL (18, 10) NOT NULL,
    [Sep_21]                        DECIMAL (18, 10) NOT NULL,
    [Oct_21]                        DECIMAL (18, 10) NOT NULL,
    [Nov_21]                        DECIMAL (18, 10) NOT NULL,
    [Dec_21]                        DECIMAL (18, 10) NOT NULL,
    [Jan_22]                        DECIMAL (18, 10) NOT NULL,
    [Feb_22]                        DECIMAL (18, 10) NOT NULL,
    [Mar_22]                        DECIMAL (18, 10) NOT NULL,
    [_6_04_2022]                    VARCHAR (50)     NULL
);

