CREATE TABLE [RPT].[RPT_DailySalesSOLines] (
    [OrderNumber]               NVARCHAR (20)   NULL,
    [LineNumber]                INT             NULL,
    [Dim_Location_Key]          VARCHAR (32)    NOT NULL,
    [Dim_Customer_Key]          VARCHAR (32)    NOT NULL,
    [Dim_Product_Key]           VARCHAR (32)    NOT NULL,
    [Dim_DeliveryDate_Key]      INT             NULL,
    [Dim_OrderDate_Key]         INT             NULL,
    [Dim_TransactionSource_Key] INT             NOT NULL,
    [DeliveryDate]              DATETIME2 (7)   NULL,
    [OrderDate]                 DATETIME2 (7)   NULL,
    [Priority]                  NVARCHAR (2)    NULL,
    [UserID]                    NVARCHAR (6)    NULL,
    [Hold]                      NVARCHAR (6)    NULL,
    [Project]                   NVARCHAR (2)    NULL,
    [OrderedQty]                DECIMAL (36, 4) NULL,
    [CancelledQty]              DECIMAL (36, 4) NULL,
    [CommittedQty]              DECIMAL (36, 4) NULL,
    [BackorderedQty]            DECIMAL (36, 4) NULL,
    [SupplyQty]                 DECIMAL (36, 4) NULL,
    [InvoicedQty]               DECIMAL (36, 4) NULL,
    [OnOrderQty]                DECIMAL (36, 4) NULL,
    [LinePrice]                 DECIMAL (36, 4) NULL,
    [ValueInclGST]              DECIMAL (36, 4) NULL,
    [Gst Value]                 DECIMAL (36, 4) NULL,
    [DiscountRate]              DECIMAL (36, 4) NULL,
    [DiscountValue]             DECIMAL (36, 4) NULL,
    [ValueExclGST]              DECIMAL (38, 6) NULL,
    [SODeliveryPeriod]          VARCHAR (15)    NULL
);

