CREATE TABLE [RPT].[RPT_DimDate] (
    [Cal_Date_key]             INT           NULL,
    [Caldate]                  DATE          NULL,
    [ReportDate]               DATE          NULL,
    [TotalBusinessDaysInMonth] INT           NULL,
    [BusinessDayNo]            INT           NULL,
    [CalDayNo]                 INT           NULL,
    [CalDayNameshort]          NVARCHAR (3)  NULL,
    [CalDayNamelong]           NVARCHAR (30) NULL,
    [CalDayOfWeekNo]           INT           NULL,
    [CalDayOfYearNo]           INT           NULL,
    [CalWeekOfYearNo]          INT           NULL,
    [CalYearWeekNo]            INT           NULL,
    [CalMonthNo]               INT           NULL,
    [CalMonthNameshort]        NVARCHAR (3)  NULL,
    [CalMonthNamelong]         NVARCHAR (30) NULL,
    [CalYearMonthNo]           INT           NULL,
    [CalMonthYearName]         NVARCHAR (6)  NULL,
    [CalQuarterNo]             INT           NULL,
    [CalQuarterName]           VARCHAR (2)   NULL,
    [CalYearNo]                INT           NULL,
    [CalfirstDayOfMonth]       DATE          NULL,
    [CallastDayOfMonth]        DATE          NULL,
    [FinMonthNo]               INT           NULL,
    [FinQuarterNo]             INT           NULL,
    [FinQuarterName]           VARCHAR (2)   NULL,
    [FinYearMonthNo]           INT           NULL,
    [FinYearWeekNo]            INT           NULL,
    [FinYear]                  INT           NULL,
    [FinFirstDayOfMonth]       DATE          NULL,
    [FinLastDayOfMonth]        DATE          NULL,
    [IsBusinessDay]            VARCHAR (1)   NULL,
    [IsHoliday]                VARCHAR (1)   NOT NULL,
    [HolidayName]              VARCHAR (250) NULL
);

