

CREATE Procedure [HSTG].[LOAD_HSTG_EBS_PO_LINE_LOCATIONS_ALL]
AS 
BEGIN


    SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        4/05/2022 11:59:11 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "HSTG"."LOAD_HSTG_EBS_PO_LINE_LOCATIONS_ALL";
    
    Source                                   Destination                             
    -------------------------------------    -------------------------------------- 
    STG"."STG_EBS_PO_LINE_LOCATIONS_ALL"    "HSTG"."HSTG_EBS_PO_LINE_LOCATIONS_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-04    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  CALL CHECK RECORD COUNT FROM STAGING TABLE*/
        DECLARE @ROW_COUNT BIGINT = 0;
        SELECT @ROW_COUNT = COUNT_BIG(*)  FROM  "STG"."STG_EBS_PO_LINE_LOCATIONS_ALL"
        IF (@ROW_COUNT > 0)
        BEGIN
        /* Step 2:  IMPORT FROM STAGING TO HISTORY */
                INSERT INTO "HSTG"."HSTG_EBS_PO_LINE_LOCATIONS_ALL"
                (
                    "LINE_LOCATION_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"PO_HEADER_ID"
                    ,"PO_LINE_ID"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"QUANTITY"
                    ,"QUANTITY_RECEIVED"
                    ,"QUANTITY_ACCEPTED"
                    ,"QUANTITY_REJECTED"
                    ,"QUANTITY_BILLED"
                    ,"QUANTITY_CANCELLED"
                    ,"UNIT_MEAS_LOOKUP_CODE"
                    ,"PO_RELEASE_ID"
                    ,"SHIP_TO_LOCATION_ID"
                    ,"SHIP_VIA_LOOKUP_CODE"
                    ,"NEED_BY_DATE"
                    ,"PROMISED_DATE"
                    ,"LAST_ACCEPT_DATE"
                    ,"PRICE_OVERRIDE"
                    ,"ENCUMBERED_FLAG"
                    ,"ENCUMBERED_DATE"
                    ,"UNENCUMBERED_QUANTITY"
                    ,"FOB_LOOKUP_CODE"
                    ,"FREIGHT_TERMS_LOOKUP_CODE"
                    ,"TAXABLE_FLAG"
                    ,"TAX_NAME"
                    ,"ESTIMATED_TAX_AMOUNT"
                    ,"FROM_HEADER_ID"
                    ,"FROM_LINE_ID"
                    ,"FROM_LINE_LOCATION_ID"
                    ,"START_DATE"
                    ,"END_DATE"
                    ,"LEAD_TIME"
                    ,"LEAD_TIME_UNIT"
                    ,"PRICE_DISCOUNT"
                    ,"TERMS_ID"
                    ,"APPROVED_FLAG"
                    ,"APPROVED_DATE"
                    ,"CLOSED_FLAG"
                    ,"CANCEL_FLAG"
                    ,"CANCELLED_BY"
                    ,"CANCEL_DATE"
                    ,"CANCEL_REASON"
                    ,"FIRM_STATUS_LOOKUP_CODE"
                    ,"FIRM_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"UNIT_OF_MEASURE_CLASS"
                    ,"ENCUMBER_NOW"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"INSPECTION_REQUIRED_FLAG"
                    ,"RECEIPT_REQUIRED_FLAG"
                    ,"QTY_RCV_TOLERANCE"
                    ,"QTY_RCV_EXCEPTION_CODE"
                    ,"ENFORCE_SHIP_TO_LOCATION_CODE"
                    ,"ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                    ,"DAYS_EARLY_RECEIPT_ALLOWED"
                    ,"DAYS_LATE_RECEIPT_ALLOWED"
                    ,"RECEIPT_DAYS_EXCEPTION_CODE"
                    ,"INVOICE_CLOSE_TOLERANCE"
                    ,"RECEIVE_CLOSE_TOLERANCE"
                    ,"SHIP_TO_ORGANIZATION_ID"
                    ,"SHIPMENT_NUM"
                    ,"SOURCE_SHIPMENT_ID"
                    ,"SHIPMENT_TYPE"
                    ,"CLOSED_CODE"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"GOVERNMENT_CONTEXT"
                    ,"RECEIVING_ROUTING_ID"
                    ,"ACCRUE_ON_RECEIPT_FLAG"
                    ,"CLOSED_REASON"
                    ,"CLOSED_DATE"
                    ,"CLOSED_BY"
                    ,"ORG_ID"
                    ,"QUANTITY_SHIPPED"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"COUNTRY_OF_ORIGIN_CODE"
                    ,"TAX_USER_OVERRIDE_FLAG"
                    ,"MATCH_OPTION"
                    ,"TAX_CODE_ID"
                    ,"CALCULATE_TAX_FLAG"
                    ,"CHANGE_PROMISED_DATE_REASON"
                    ,"NOTE_TO_RECEIVER"
                    ,"SECONDARY_QUANTITY"
                    ,"SECONDARY_UNIT_OF_MEASURE"
                    ,"PREFERRED_GRADE"
                    ,"SECONDARY_QUANTITY_RECEIVED"
                    ,"SECONDARY_QUANTITY_ACCEPTED"
                    ,"SECONDARY_QUANTITY_REJECTED"
                    ,"SECONDARY_QUANTITY_CANCELLED"
                    ,"VMI_FLAG"
                    ,"CONSIGNED_FLAG"
                    ,"RETROACTIVE_DATE"
                    ,"SUPPLIER_ORDER_LINE_NUMBER"
                    ,"AMOUNT"
                    ,"AMOUNT_RECEIVED"
                    ,"AMOUNT_BILLED"
                    ,"AMOUNT_CANCELLED"
                    ,"AMOUNT_REJECTED"
                    ,"AMOUNT_ACCEPTED"
                    ,"DROP_SHIP_FLAG"
                    ,"SALES_ORDER_UPDATE_DATE"
                    ,"TRANSACTION_FLOW_HEADER_ID"
                    ,"FINAL_MATCH_FLAG"
                    ,"MANUAL_PRICE_CHANGE_FLAG"
                    ,"SHIPMENT_CLOSED_DATE"
                    ,"CLOSED_FOR_RECEIVING_DATE"
                    ,"CLOSED_FOR_INVOICE_DATE"
                    ,"SECONDARY_QUANTITY_SHIPPED"
                    ,"VALUE_BASIS"
                    ,"MATCHING_BASIS"
                    ,"PAYMENT_TYPE"
                    ,"DESCRIPTION"
                    ,"WORK_APPROVER_ID"
                    ,"BID_PAYMENT_ID"
                    ,"QUANTITY_FINANCED"
                    ,"AMOUNT_FINANCED"
                    ,"QUANTITY_RECOUPED"
                    ,"AMOUNT_RECOUPED"
                    ,"RETAINAGE_WITHHELD_AMOUNT"
                    ,"RETAINAGE_RELEASED_AMOUNT"
                    ,"AMOUNT_SHIPPED"
                    ,"OUTSOURCED_ASSEMBLY"
                    ,"TAX_ATTRIBUTE_UPDATE_CODE"
                    ,"ORIGINAL_SHIPMENT_ID"
                    ,"LCM_FLAG"
                    ,"UDA_TEMPLATE_ID"
                    ,"DRAFT_ID"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "LINE_LOCATION_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"PO_HEADER_ID"
                    ,"PO_LINE_ID"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"QUANTITY"
                    ,"QUANTITY_RECEIVED"
                    ,"QUANTITY_ACCEPTED"
                    ,"QUANTITY_REJECTED"
                    ,"QUANTITY_BILLED"
                    ,"QUANTITY_CANCELLED"
                    ,"UNIT_MEAS_LOOKUP_CODE"
                    ,"PO_RELEASE_ID"
                    ,"SHIP_TO_LOCATION_ID"
                    ,"SHIP_VIA_LOOKUP_CODE"
                    ,"NEED_BY_DATE"
                    ,"PROMISED_DATE"
                    ,"LAST_ACCEPT_DATE"
                    ,"PRICE_OVERRIDE"
                    ,"ENCUMBERED_FLAG"
                    ,"ENCUMBERED_DATE"
                    ,"UNENCUMBERED_QUANTITY"
                    ,"FOB_LOOKUP_CODE"
                    ,"FREIGHT_TERMS_LOOKUP_CODE"
                    ,"TAXABLE_FLAG"
                    ,"TAX_NAME"
                    ,"ESTIMATED_TAX_AMOUNT"
                    ,"FROM_HEADER_ID"
                    ,"FROM_LINE_ID"
                    ,"FROM_LINE_LOCATION_ID"
                    ,"START_DATE"
                    ,"END_DATE"
                    ,"LEAD_TIME"
                    ,"LEAD_TIME_UNIT"
                    ,"PRICE_DISCOUNT"
                    ,"TERMS_ID"
                    ,"APPROVED_FLAG"
                    ,"APPROVED_DATE"
                    ,"CLOSED_FLAG"
                    ,"CANCEL_FLAG"
                    ,"CANCELLED_BY"
                    ,"CANCEL_DATE"
                    ,"CANCEL_REASON"
                    ,"FIRM_STATUS_LOOKUP_CODE"
                    ,"FIRM_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"UNIT_OF_MEASURE_CLASS"
                    ,"ENCUMBER_NOW"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"INSPECTION_REQUIRED_FLAG"
                    ,"RECEIPT_REQUIRED_FLAG"
                    ,"QTY_RCV_TOLERANCE"
                    ,"QTY_RCV_EXCEPTION_CODE"
                    ,"ENFORCE_SHIP_TO_LOCATION_CODE"
                    ,"ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                    ,"DAYS_EARLY_RECEIPT_ALLOWED"
                    ,"DAYS_LATE_RECEIPT_ALLOWED"
                    ,"RECEIPT_DAYS_EXCEPTION_CODE"
                    ,"INVOICE_CLOSE_TOLERANCE"
                    ,"RECEIVE_CLOSE_TOLERANCE"
                    ,"SHIP_TO_ORGANIZATION_ID"
                    ,"SHIPMENT_NUM"
                    ,"SOURCE_SHIPMENT_ID"
                    ,"SHIPMENT_TYPE"
                    ,"CLOSED_CODE"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"GOVERNMENT_CONTEXT"
                    ,"RECEIVING_ROUTING_ID"
                    ,"ACCRUE_ON_RECEIPT_FLAG"
                    ,"CLOSED_REASON"
                    ,"CLOSED_DATE"
                    ,"CLOSED_BY"
                    ,"ORG_ID"
                    ,"QUANTITY_SHIPPED"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"COUNTRY_OF_ORIGIN_CODE"
                    ,"TAX_USER_OVERRIDE_FLAG"
                    ,"MATCH_OPTION"
                    ,"TAX_CODE_ID"
                    ,"CALCULATE_TAX_FLAG"
                    ,"CHANGE_PROMISED_DATE_REASON"
                    ,"NOTE_TO_RECEIVER"
                    ,"SECONDARY_QUANTITY"
                    ,"SECONDARY_UNIT_OF_MEASURE"
                    ,"PREFERRED_GRADE"
                    ,"SECONDARY_QUANTITY_RECEIVED"
                    ,"SECONDARY_QUANTITY_ACCEPTED"
                    ,"SECONDARY_QUANTITY_REJECTED"
                    ,"SECONDARY_QUANTITY_CANCELLED"
                    ,"VMI_FLAG"
                    ,"CONSIGNED_FLAG"
                    ,"RETROACTIVE_DATE"
                    ,"SUPPLIER_ORDER_LINE_NUMBER"
                    ,"AMOUNT"
                    ,"AMOUNT_RECEIVED"
                    ,"AMOUNT_BILLED"
                    ,"AMOUNT_CANCELLED"
                    ,"AMOUNT_REJECTED"
                    ,"AMOUNT_ACCEPTED"
                    ,"DROP_SHIP_FLAG"
                    ,"SALES_ORDER_UPDATE_DATE"
                    ,"TRANSACTION_FLOW_HEADER_ID"
                    ,"FINAL_MATCH_FLAG"
                    ,"MANUAL_PRICE_CHANGE_FLAG"
                    ,"SHIPMENT_CLOSED_DATE"
                    ,"CLOSED_FOR_RECEIVING_DATE"
                    ,"CLOSED_FOR_INVOICE_DATE"
                    ,"SECONDARY_QUANTITY_SHIPPED"
                    ,"VALUE_BASIS"
                    ,"MATCHING_BASIS"
                    ,"PAYMENT_TYPE"
                    ,"DESCRIPTION"
                    ,"WORK_APPROVER_ID"
                    ,"BID_PAYMENT_ID"
                    ,"QUANTITY_FINANCED"
                    ,"AMOUNT_FINANCED"
                    ,"QUANTITY_RECOUPED"
                    ,"AMOUNT_RECOUPED"
                    ,"RETAINAGE_WITHHELD_AMOUNT"
                    ,"RETAINAGE_RELEASED_AMOUNT"
                    ,"AMOUNT_SHIPPED"
                    ,"OUTSOURCED_ASSEMBLY"
                    ,"TAX_ATTRIBUTE_UPDATE_CODE"
                    ,"ORIGINAL_SHIPMENT_ID"
                    ,"LCM_FLAG"
                    ,"UDA_TEMPLATE_ID"
                    ,"DRAFT_ID"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'N' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "STG"."STG_EBS_PO_LINE_LOCATIONS_ALL" S
                WHERE NOT EXISTS(SELECT 1 FROM "HSTG"."HSTG_EBS_PO_LINE_LOCATIONS_ALL" H WHERE H.OMD_CURRENT_RECORD_INDICATOR = 'Y' AND OMD_IS_RECORD_DELETED = 'N' AND H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)



            /* Step 3:  IMPORT DELETED RECORDS FROM HISTORY TO HISTORY */

                /* THERE WAS NO BK FOR THIS TABLE. WE CANNOT IDENTIFY THE DELETED RECORDS.*/

            /* Step 4:  UPDATE OMD_CURRENT_RECORD_INDICATOR FLAG*/
				UPDATE  H 				SET OMD_CURRENT_RECORD_INDICATOR='N'				FROM "HSTG"."HSTG_EBS_PO_LINE_LOCATIONS_ALL" H					Join "STG"."STG_EBS_PO_LINE_LOCATIONS_ALL" S						On H.LINE_LOCATION_ID= S.LINE_LOCATION_ID				WHERE "OMD_IS_RECORD_DELETED" = 'N'						AND H.OMD_HASH_FULL_RECORD <> S.OMD_HASH_FULL_RECORD
            
            
            END
        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
