

CREATE Procedure [HSTG].[LOAD_HSTG_EBS_RA_CUSTOMER_TRX_ALL]
AS 
BEGIN


    SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        8/03/2022 5:53:40 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "HSTG"."LOAD_HSTG_EBS_RA_CUSTOMER_TRX_ALL";
    
    Source                                 Destination                           
    -----------------------------------    ------------------------------------ 
    STG"."STG_EBS_RA_CUSTOMER_TRX_ALL"    "HSTG"."HSTG_EBS_RA_CUSTOMER_TRX_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-08    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  CALL CHECK RECORD COUNT FROM STAGING TABLE*/
        DECLARE @ROW_COUNT BIGINT = 0;
        SELECT @ROW_COUNT = COUNT_BIG(*)  FROM  "STG"."STG_EBS_RA_CUSTOMER_TRX_ALL"
        IF (@ROW_COUNT > 0)
        BEGIN
        /* Step 2:  IMPORT FROM STAGING TO HISTORY */
                INSERT INTO "HSTG"."HSTG_EBS_RA_CUSTOMER_TRX_ALL"
                (
                    "CUSTOMER_TRX_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"TRX_NUMBER"
                    ,"CUST_TRX_TYPE_ID"
                    ,"TRX_DATE"
                    ,"SET_OF_BOOKS_ID"
                    ,"BILL_TO_CONTACT_ID"
                    ,"BATCH_ID"
                    ,"BATCH_SOURCE_ID"
                    ,"REASON_CODE"
                    ,"SOLD_TO_CUSTOMER_ID"
                    ,"SOLD_TO_CONTACT_ID"
                    ,"SOLD_TO_SITE_USE_ID"
                    ,"BILL_TO_CUSTOMER_ID"
                    ,"BILL_TO_SITE_USE_ID"
                    ,"SHIP_TO_CUSTOMER_ID"
                    ,"SHIP_TO_CONTACT_ID"
                    ,"SHIP_TO_SITE_USE_ID"
                    ,"SHIPMENT_ID"
                    ,"REMIT_TO_ADDRESS_ID"
                    ,"TERM_ID"
                    ,"TERM_DUE_DATE"
                    ,"PREVIOUS_CUSTOMER_TRX_ID"
                    ,"PRIMARY_SALESREP_ID"
                    ,"PRINTING_ORIGINAL_DATE"
                    ,"PRINTING_LAST_PRINTED"
                    ,"PRINTING_OPTION"
                    ,"PRINTING_COUNT"
                    ,"PRINTING_PENDING"
                    ,"PURCHASE_ORDER"
                    ,"PURCHASE_ORDER_REVISION"
                    ,"PURCHASE_ORDER_DATE"
                    ,"CUSTOMER_REFERENCE"
                    ,"CUSTOMER_REFERENCE_DATE"
                    ,"COMMENTS"
                    ,"INTERNAL_NOTES"
                    ,"EXCHANGE_RATE_TYPE"
                    ,"EXCHANGE_DATE"
                    ,"EXCHANGE_RATE"
                    ,"TERRITORY_ID"
                    ,"INVOICE_CURRENCY_CODE"
                    ,"INITIAL_CUSTOMER_TRX_ID"
                    ,"AGREEMENT_ID"
                    ,"END_DATE_COMMITMENT"
                    ,"START_DATE_COMMITMENT"
                    ,"LAST_PRINTED_SEQUENCE_NUM"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ORIG_SYSTEM_BATCH_NAME"
                    ,"POST_REQUEST_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"FINANCE_CHARGES"
                    ,"COMPLETE_FLAG"
                    ,"POSTING_CONTROL_ID"
                    ,"BILL_TO_ADDRESS_ID"
                    ,"RA_POST_LOOP_NUMBER"
                    ,"SHIP_TO_ADDRESS_ID"
                    ,"CREDIT_METHOD_FOR_RULES"
                    ,"CREDIT_METHOD_FOR_INSTALLMENTS"
                    ,"RECEIPT_METHOD_ID"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"RELATED_CUSTOMER_TRX_ID"
                    ,"INVOICING_RULE_ID"
                    ,"SHIP_VIA"
                    ,"SHIP_DATE_ACTUAL"
                    ,"WAYBILL_NUMBER"
                    ,"FOB_POINT"
                    ,"CUSTOMER_BANK_ACCOUNT_ID"
                    ,"INTERFACE_HEADER_ATTRIBUTE1"
                    ,"INTERFACE_HEADER_ATTRIBUTE2"
                    ,"INTERFACE_HEADER_ATTRIBUTE3"
                    ,"INTERFACE_HEADER_ATTRIBUTE4"
                    ,"INTERFACE_HEADER_ATTRIBUTE5"
                    ,"INTERFACE_HEADER_ATTRIBUTE6"
                    ,"INTERFACE_HEADER_ATTRIBUTE7"
                    ,"INTERFACE_HEADER_ATTRIBUTE8"
                    ,"INTERFACE_HEADER_CONTEXT"
                    ,"DEFAULT_USSGL_TRX_CODE_CONTEXT"
                    ,"INTERFACE_HEADER_ATTRIBUTE10"
                    ,"INTERFACE_HEADER_ATTRIBUTE11"
                    ,"INTERFACE_HEADER_ATTRIBUTE12"
                    ,"INTERFACE_HEADER_ATTRIBUTE13"
                    ,"INTERFACE_HEADER_ATTRIBUTE14"
                    ,"INTERFACE_HEADER_ATTRIBUTE15"
                    ,"INTERFACE_HEADER_ATTRIBUTE9"
                    ,"DEFAULT_USSGL_TRANSACTION_CODE"
                    ,"RECURRED_FROM_TRX_NUMBER"
                    ,"STATUS_TRX"
                    ,"DOC_SEQUENCE_ID"
                    ,"DOC_SEQUENCE_VALUE"
                    ,"PAYING_CUSTOMER_ID"
                    ,"PAYING_SITE_USE_ID"
                    ,"RELATED_BATCH_SOURCE_ID"
                    ,"DEFAULT_TAX_EXEMPT_FLAG"
                    ,"CREATED_FROM"
                    ,"ORG_ID"
                    ,"WH_UPDATE_DATE"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"GLOBAL_ATTRIBUTE21"
                    ,"GLOBAL_ATTRIBUTE22"
                    ,"GLOBAL_ATTRIBUTE23"
                    ,"GLOBAL_ATTRIBUTE24"
                    ,"GLOBAL_ATTRIBUTE25"
                    ,"GLOBAL_ATTRIBUTE26"
                    ,"GLOBAL_ATTRIBUTE27"
                    ,"GLOBAL_ATTRIBUTE28"
                    ,"GLOBAL_ATTRIBUTE29"
                    ,"GLOBAL_ATTRIBUTE30"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"EDI_PROCESSED_FLAG"
                    ,"EDI_PROCESSED_STATUS"
                    ,"MRC_EXCHANGE_RATE_TYPE"
                    ,"MRC_EXCHANGE_DATE"
                    ,"MRC_EXCHANGE_RATE"
                    ,"PAYMENT_SERVER_ORDER_NUM"
                    ,"APPROVAL_CODE"
                    ,"ADDRESS_VERIFICATION_CODE"
                    ,"OLD_TRX_NUMBER"
                    ,"BR_AMOUNT"
                    ,"BR_UNPAID_FLAG"
                    ,"BR_ON_HOLD_FLAG"
                    ,"DRAWEE_ID"
                    ,"DRAWEE_CONTACT_ID"
                    ,"DRAWEE_SITE_USE_ID"
                    ,"REMITTANCE_BANK_ACCOUNT_ID"
                    ,"OVERRIDE_REMIT_ACCOUNT_FLAG"
                    ,"DRAWEE_BANK_ACCOUNT_ID"
                    ,"SPECIAL_INSTRUCTIONS"
                    ,"REMITTANCE_BATCH_ID"
                    ,"PREPAYMENT_FLAG"
                    ,"CT_REFERENCE"
                    ,"CONTRACT_ID"
                    ,"BILL_TEMPLATE_ID"
                    ,"REVERSED_CASH_RECEIPT_ID"
                    ,"CC_ERROR_CODE"
                    ,"CC_ERROR_TEXT"
                    ,"CC_ERROR_FLAG"
                    ,"UPGRADE_METHOD"
                    ,"LEGAL_ENTITY_ID"
                    ,"REMIT_BANK_ACCT_USE_ID"
                    ,"PAYMENT_TRXN_EXTENSION_ID"
                    ,"AX_ACCOUNTED_FLAG"
                    ,"APPLICATION_ID"
                    ,"PAYMENT_ATTRIBUTES"
                    ,"BILLING_DATE"
                    ,"INTEREST_HEADER_ID"
                    ,"LATE_CHARGES_ASSESSED"
                    ,"TRAILER_NUMBER"
                    ,"REV_REC_APPLICATION"
                    ,"DOCUMENT_TYPE_ID"
                    ,"DOCUMENT_CREATION_DATE"
                    ,"SRC_INVOICING_RULE_ID"
                    ,"BILLING_EXT_REQUEST"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "CUSTOMER_TRX_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"TRX_NUMBER"
                    ,"CUST_TRX_TYPE_ID"
                    ,"TRX_DATE"
                    ,"SET_OF_BOOKS_ID"
                    ,"BILL_TO_CONTACT_ID"
                    ,"BATCH_ID"
                    ,"BATCH_SOURCE_ID"
                    ,"REASON_CODE"
                    ,"SOLD_TO_CUSTOMER_ID"
                    ,"SOLD_TO_CONTACT_ID"
                    ,"SOLD_TO_SITE_USE_ID"
                    ,"BILL_TO_CUSTOMER_ID"
                    ,"BILL_TO_SITE_USE_ID"
                    ,"SHIP_TO_CUSTOMER_ID"
                    ,"SHIP_TO_CONTACT_ID"
                    ,"SHIP_TO_SITE_USE_ID"
                    ,"SHIPMENT_ID"
                    ,"REMIT_TO_ADDRESS_ID"
                    ,"TERM_ID"
                    ,"TERM_DUE_DATE"
                    ,"PREVIOUS_CUSTOMER_TRX_ID"
                    ,"PRIMARY_SALESREP_ID"
                    ,"PRINTING_ORIGINAL_DATE"
                    ,"PRINTING_LAST_PRINTED"
                    ,"PRINTING_OPTION"
                    ,"PRINTING_COUNT"
                    ,"PRINTING_PENDING"
                    ,"PURCHASE_ORDER"
                    ,"PURCHASE_ORDER_REVISION"
                    ,"PURCHASE_ORDER_DATE"
                    ,"CUSTOMER_REFERENCE"
                    ,"CUSTOMER_REFERENCE_DATE"
                    ,"COMMENTS"
                    ,"INTERNAL_NOTES"
                    ,"EXCHANGE_RATE_TYPE"
                    ,"EXCHANGE_DATE"
                    ,"EXCHANGE_RATE"
                    ,"TERRITORY_ID"
                    ,"INVOICE_CURRENCY_CODE"
                    ,"INITIAL_CUSTOMER_TRX_ID"
                    ,"AGREEMENT_ID"
                    ,"END_DATE_COMMITMENT"
                    ,"START_DATE_COMMITMENT"
                    ,"LAST_PRINTED_SEQUENCE_NUM"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ORIG_SYSTEM_BATCH_NAME"
                    ,"POST_REQUEST_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"FINANCE_CHARGES"
                    ,"COMPLETE_FLAG"
                    ,"POSTING_CONTROL_ID"
                    ,"BILL_TO_ADDRESS_ID"
                    ,"RA_POST_LOOP_NUMBER"
                    ,"SHIP_TO_ADDRESS_ID"
                    ,"CREDIT_METHOD_FOR_RULES"
                    ,"CREDIT_METHOD_FOR_INSTALLMENTS"
                    ,"RECEIPT_METHOD_ID"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"RELATED_CUSTOMER_TRX_ID"
                    ,"INVOICING_RULE_ID"
                    ,"SHIP_VIA"
                    ,"SHIP_DATE_ACTUAL"
                    ,"WAYBILL_NUMBER"
                    ,"FOB_POINT"
                    ,"CUSTOMER_BANK_ACCOUNT_ID"
                    ,"INTERFACE_HEADER_ATTRIBUTE1"
                    ,"INTERFACE_HEADER_ATTRIBUTE2"
                    ,"INTERFACE_HEADER_ATTRIBUTE3"
                    ,"INTERFACE_HEADER_ATTRIBUTE4"
                    ,"INTERFACE_HEADER_ATTRIBUTE5"
                    ,"INTERFACE_HEADER_ATTRIBUTE6"
                    ,"INTERFACE_HEADER_ATTRIBUTE7"
                    ,"INTERFACE_HEADER_ATTRIBUTE8"
                    ,"INTERFACE_HEADER_CONTEXT"
                    ,"DEFAULT_USSGL_TRX_CODE_CONTEXT"
                    ,"INTERFACE_HEADER_ATTRIBUTE10"
                    ,"INTERFACE_HEADER_ATTRIBUTE11"
                    ,"INTERFACE_HEADER_ATTRIBUTE12"
                    ,"INTERFACE_HEADER_ATTRIBUTE13"
                    ,"INTERFACE_HEADER_ATTRIBUTE14"
                    ,"INTERFACE_HEADER_ATTRIBUTE15"
                    ,"INTERFACE_HEADER_ATTRIBUTE9"
                    ,"DEFAULT_USSGL_TRANSACTION_CODE"
                    ,"RECURRED_FROM_TRX_NUMBER"
                    ,"STATUS_TRX"
                    ,"DOC_SEQUENCE_ID"
                    ,"DOC_SEQUENCE_VALUE"
                    ,"PAYING_CUSTOMER_ID"
                    ,"PAYING_SITE_USE_ID"
                    ,"RELATED_BATCH_SOURCE_ID"
                    ,"DEFAULT_TAX_EXEMPT_FLAG"
                    ,"CREATED_FROM"
                    ,"ORG_ID"
                    ,"WH_UPDATE_DATE"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"GLOBAL_ATTRIBUTE21"
                    ,"GLOBAL_ATTRIBUTE22"
                    ,"GLOBAL_ATTRIBUTE23"
                    ,"GLOBAL_ATTRIBUTE24"
                    ,"GLOBAL_ATTRIBUTE25"
                    ,"GLOBAL_ATTRIBUTE26"
                    ,"GLOBAL_ATTRIBUTE27"
                    ,"GLOBAL_ATTRIBUTE28"
                    ,"GLOBAL_ATTRIBUTE29"
                    ,"GLOBAL_ATTRIBUTE30"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"EDI_PROCESSED_FLAG"
                    ,"EDI_PROCESSED_STATUS"
                    ,"MRC_EXCHANGE_RATE_TYPE"
                    ,"MRC_EXCHANGE_DATE"
                    ,"MRC_EXCHANGE_RATE"
                    ,"PAYMENT_SERVER_ORDER_NUM"
                    ,"APPROVAL_CODE"
                    ,"ADDRESS_VERIFICATION_CODE"
                    ,"OLD_TRX_NUMBER"
                    ,"BR_AMOUNT"
                    ,"BR_UNPAID_FLAG"
                    ,"BR_ON_HOLD_FLAG"
                    ,"DRAWEE_ID"
                    ,"DRAWEE_CONTACT_ID"
                    ,"DRAWEE_SITE_USE_ID"
                    ,"REMITTANCE_BANK_ACCOUNT_ID"
                    ,"OVERRIDE_REMIT_ACCOUNT_FLAG"
                    ,"DRAWEE_BANK_ACCOUNT_ID"
                    ,"SPECIAL_INSTRUCTIONS"
                    ,"REMITTANCE_BATCH_ID"
                    ,"PREPAYMENT_FLAG"
                    ,"CT_REFERENCE"
                    ,"CONTRACT_ID"
                    ,"BILL_TEMPLATE_ID"
                    ,"REVERSED_CASH_RECEIPT_ID"
                    ,"CC_ERROR_CODE"
                    ,"CC_ERROR_TEXT"
                    ,"CC_ERROR_FLAG"
                    ,"UPGRADE_METHOD"
                    ,"LEGAL_ENTITY_ID"
                    ,"REMIT_BANK_ACCT_USE_ID"
                    ,"PAYMENT_TRXN_EXTENSION_ID"
                    ,"AX_ACCOUNTED_FLAG"
                    ,"APPLICATION_ID"
                    ,"PAYMENT_ATTRIBUTES"
                    ,"BILLING_DATE"
                    ,"INTEREST_HEADER_ID"
                    ,"LATE_CHARGES_ASSESSED"
                    ,"TRAILER_NUMBER"
                    ,"REV_REC_APPLICATION"
                    ,"DOCUMENT_TYPE_ID"
                    ,"DOCUMENT_CREATION_DATE"
                    ,"SRC_INVOICING_RULE_ID"
                    ,"BILLING_EXT_REQUEST"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'N' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "STG"."STG_EBS_RA_CUSTOMER_TRX_ALL" S
                WHERE NOT EXISTS(SELECT 1 FROM "HSTG"."HSTG_EBS_RA_CUSTOMER_TRX_ALL" H WHERE H.OMD_CURRENT_RECORD_INDICATOR = 'Y' AND OMD_IS_RECORD_DELETED = 'N' AND H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)



            /* Step 3:  IMPORT DELETED RECORDS FROM HISTORY TO HISTORY */

                /* THERE WAS NO BK FOR THIS TABLE. WE CANNOT IDENTIFY THE DELETED RECORDS.*/

            /* Step 4:  UPDATE OMD_CURRENT_RECORD_INDICATOR FLAG*/
				UPDATE  H 				SET OMD_CURRENT_RECORD_INDICATOR='N'				FROM "HSTG"."HSTG_EBS_RA_CUSTOMER_TRX_ALL" H					Join "STG"."STG_EBS_RA_CUSTOMER_TRX_ALL" S						On H.CUSTOMER_TRX_ID= S.CUSTOMER_TRX_ID				WHERE "OMD_IS_RECORD_DELETED" = 'N'						AND H.OMD_HASH_FULL_RECORD <> S.OMD_HASH_FULL_RECORD
            
            
            END
        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
