

CREATE Procedure [HSTG].[LOAD_HSTG_EBS_PO_LINES_ALL]
AS 
BEGIN


    SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        4/05/2022 11:59:10 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "HSTG"."LOAD_HSTG_EBS_PO_LINES_ALL";
    
    Source                          Destination                    
    ----------------------------    ----------------------------- 
    STG"."STG_EBS_PO_LINES_ALL"    "HSTG"."HSTG_EBS_PO_LINES_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-04    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  CALL CHECK RECORD COUNT FROM STAGING TABLE*/
        DECLARE @ROW_COUNT BIGINT = 0;
        SELECT @ROW_COUNT = COUNT_BIG(*)  FROM  "STG"."STG_EBS_PO_LINES_ALL"
        IF (@ROW_COUNT > 0)
        BEGIN
        /* Step 2:  IMPORT FROM STAGING TO HISTORY */
                INSERT INTO "HSTG"."HSTG_EBS_PO_LINES_ALL"
                (
                    "PO_LINE_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"PO_HEADER_ID"
                    ,"LINE_TYPE_ID"
                    ,"LINE_NUM"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"ITEM_ID"
                    ,"ITEM_REVISION"
                    ,"CATEGORY_ID"
                    ,"ITEM_DESCRIPTION"
                    ,"UNIT_MEAS_LOOKUP_CODE"
                    ,"QUANTITY_COMMITTED"
                    ,"COMMITTED_AMOUNT"
                    ,"ALLOW_PRICE_OVERRIDE_FLAG"
                    ,"NOT_TO_EXCEED_PRICE"
                    ,"LIST_PRICE_PER_UNIT"
                    ,"UNIT_PRICE"
                    ,"QUANTITY"
                    ,"UN_NUMBER_ID"
                    ,"HAZARD_CLASS_ID"
                    ,"NOTE_TO_VENDOR"
                    ,"FROM_HEADER_ID"
                    ,"FROM_LINE_ID"
                    ,"MIN_ORDER_QUANTITY"
                    ,"MAX_ORDER_QUANTITY"
                    ,"QTY_RCV_TOLERANCE"
                    ,"OVER_TOLERANCE_ERROR_FLAG"
                    ,"MARKET_PRICE"
                    ,"UNORDERED_FLAG"
                    ,"CLOSED_FLAG"
                    ,"USER_HOLD_FLAG"
                    ,"CANCEL_FLAG"
                    ,"CANCELLED_BY"
                    ,"CANCEL_DATE"
                    ,"CANCEL_REASON"
                    ,"FIRM_STATUS_LOOKUP_CODE"
                    ,"FIRM_DATE"
                    ,"VENDOR_PRODUCT_NUM"
                    ,"CONTRACT_NUM"
                    ,"TAXABLE_FLAG"
                    ,"TAX_NAME"
                    ,"TYPE_1099"
                    ,"CAPITAL_EXPENSE_FLAG"
                    ,"NEGOTIATED_BY_PREPARER_FLAG"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"REFERENCE_NUM"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"MIN_RELEASE_AMOUNT"
                    ,"PRICE_TYPE_LOOKUP_CODE"
                    ,"CLOSED_CODE"
                    ,"PRICE_BREAK_LOOKUP_CODE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"GOVERNMENT_CONTEXT"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"CLOSED_DATE"
                    ,"CLOSED_REASON"
                    ,"CLOSED_BY"
                    ,"TRANSACTION_REASON_CODE"
                    ,"ORG_ID"
                    ,"QC_GRADE"
                    ,"BASE_UOM"
                    ,"BASE_QTY"
                    ,"SECONDARY_UOM"
                    ,"SECONDARY_QTY"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"LINE_REFERENCE_NUM"
                    ,"PROJECT_ID"
                    ,"TASK_ID"
                    ,"EXPIRATION_DATE"
                    ,"TAX_CODE_ID"
                    ,"OKE_CONTRACT_HEADER_ID"
                    ,"OKE_CONTRACT_VERSION_ID"
                    ,"SECONDARY_QUANTITY"
                    ,"SECONDARY_UNIT_OF_MEASURE"
                    ,"PREFERRED_GRADE"
                    ,"AUCTION_HEADER_ID"
                    ,"AUCTION_DISPLAY_NUMBER"
                    ,"AUCTION_LINE_NUMBER"
                    ,"BID_NUMBER"
                    ,"BID_LINE_NUMBER"
                    ,"RETROACTIVE_DATE"
                    ,"FROM_LINE_LOCATION_ID"
                    ,"SUPPLIER_REF_NUMBER"
                    ,"CONTRACT_ID"
                    ,"START_DATE"
                    ,"AMOUNT"
                    ,"JOB_ID"
                    ,"CONTRACTOR_FIRST_NAME"
                    ,"CONTRACTOR_LAST_NAME"
                    ,"ORDER_TYPE_LOOKUP_CODE"
                    ,"PURCHASE_BASIS"
                    ,"MATCHING_BASIS"
                    ,"SVC_AMOUNT_NOTIF_SENT"
                    ,"SVC_COMPLETION_NOTIF_SENT"
                    ,"BASE_UNIT_PRICE"
                    ,"MANUAL_PRICE_CHANGE_FLAG"
                    ,"RETAINAGE_RATE"
                    ,"MAX_RETAINAGE_AMOUNT"
                    ,"PROGRESS_PAYMENT_RATE"
                    ,"RECOUPMENT_RATE"
                    ,"CATALOG_NAME"
                    ,"SUPPLIER_PART_AUXID"
                    ,"IP_CATEGORY_ID"
                    ,"TAX_ATTRIBUTE_UPDATE_CODE"
                    ,"LAST_UPDATED_PROGRAM"
                    ,"GROUP_LINE_ID"
                    ,"LINE_NUM_DISPLAY"
                    ,"CLM_INFO_FLAG"
                    ,"CLM_OPTION_INDICATOR"
                    ,"CLM_BASE_LINE_NUM"
                    ,"CLM_OPTION_NUM"
                    ,"CLM_OPTION_FROM_DATE"
                    ,"CLM_OPTION_TO_DATE"
                    ,"CLM_FUNDED_FLAG"
                    ,"CONTRACT_TYPE"
                    ,"COST_CONSTRAINT"
                    ,"CLM_IDC_TYPE"
                    ,"UDA_TEMPLATE_ID"
                    ,"USER_DOCUMENT_STATUS"
                    ,"DRAFT_ID"
                    ,"CLM_EXERCISED_FLAG"
                    ,"CLM_EXERCISED_DATE"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "PO_LINE_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"PO_HEADER_ID"
                    ,"LINE_TYPE_ID"
                    ,"LINE_NUM"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"ITEM_ID"
                    ,"ITEM_REVISION"
                    ,"CATEGORY_ID"
                    ,"ITEM_DESCRIPTION"
                    ,"UNIT_MEAS_LOOKUP_CODE"
                    ,"QUANTITY_COMMITTED"
                    ,"COMMITTED_AMOUNT"
                    ,"ALLOW_PRICE_OVERRIDE_FLAG"
                    ,"NOT_TO_EXCEED_PRICE"
                    ,"LIST_PRICE_PER_UNIT"
                    ,"UNIT_PRICE"
                    ,"QUANTITY"
                    ,"UN_NUMBER_ID"
                    ,"HAZARD_CLASS_ID"
                    ,"NOTE_TO_VENDOR"
                    ,"FROM_HEADER_ID"
                    ,"FROM_LINE_ID"
                    ,"MIN_ORDER_QUANTITY"
                    ,"MAX_ORDER_QUANTITY"
                    ,"QTY_RCV_TOLERANCE"
                    ,"OVER_TOLERANCE_ERROR_FLAG"
                    ,"MARKET_PRICE"
                    ,"UNORDERED_FLAG"
                    ,"CLOSED_FLAG"
                    ,"USER_HOLD_FLAG"
                    ,"CANCEL_FLAG"
                    ,"CANCELLED_BY"
                    ,"CANCEL_DATE"
                    ,"CANCEL_REASON"
                    ,"FIRM_STATUS_LOOKUP_CODE"
                    ,"FIRM_DATE"
                    ,"VENDOR_PRODUCT_NUM"
                    ,"CONTRACT_NUM"
                    ,"TAXABLE_FLAG"
                    ,"TAX_NAME"
                    ,"TYPE_1099"
                    ,"CAPITAL_EXPENSE_FLAG"
                    ,"NEGOTIATED_BY_PREPARER_FLAG"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"REFERENCE_NUM"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"MIN_RELEASE_AMOUNT"
                    ,"PRICE_TYPE_LOOKUP_CODE"
                    ,"CLOSED_CODE"
                    ,"PRICE_BREAK_LOOKUP_CODE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"GOVERNMENT_CONTEXT"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"CLOSED_DATE"
                    ,"CLOSED_REASON"
                    ,"CLOSED_BY"
                    ,"TRANSACTION_REASON_CODE"
                    ,"ORG_ID"
                    ,"QC_GRADE"
                    ,"BASE_UOM"
                    ,"BASE_QTY"
                    ,"SECONDARY_UOM"
                    ,"SECONDARY_QTY"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"LINE_REFERENCE_NUM"
                    ,"PROJECT_ID"
                    ,"TASK_ID"
                    ,"EXPIRATION_DATE"
                    ,"TAX_CODE_ID"
                    ,"OKE_CONTRACT_HEADER_ID"
                    ,"OKE_CONTRACT_VERSION_ID"
                    ,"SECONDARY_QUANTITY"
                    ,"SECONDARY_UNIT_OF_MEASURE"
                    ,"PREFERRED_GRADE"
                    ,"AUCTION_HEADER_ID"
                    ,"AUCTION_DISPLAY_NUMBER"
                    ,"AUCTION_LINE_NUMBER"
                    ,"BID_NUMBER"
                    ,"BID_LINE_NUMBER"
                    ,"RETROACTIVE_DATE"
                    ,"FROM_LINE_LOCATION_ID"
                    ,"SUPPLIER_REF_NUMBER"
                    ,"CONTRACT_ID"
                    ,"START_DATE"
                    ,"AMOUNT"
                    ,"JOB_ID"
                    ,"CONTRACTOR_FIRST_NAME"
                    ,"CONTRACTOR_LAST_NAME"
                    ,"ORDER_TYPE_LOOKUP_CODE"
                    ,"PURCHASE_BASIS"
                    ,"MATCHING_BASIS"
                    ,"SVC_AMOUNT_NOTIF_SENT"
                    ,"SVC_COMPLETION_NOTIF_SENT"
                    ,"BASE_UNIT_PRICE"
                    ,"MANUAL_PRICE_CHANGE_FLAG"
                    ,"RETAINAGE_RATE"
                    ,"MAX_RETAINAGE_AMOUNT"
                    ,"PROGRESS_PAYMENT_RATE"
                    ,"RECOUPMENT_RATE"
                    ,"CATALOG_NAME"
                    ,"SUPPLIER_PART_AUXID"
                    ,"IP_CATEGORY_ID"
                    ,"TAX_ATTRIBUTE_UPDATE_CODE"
                    ,"LAST_UPDATED_PROGRAM"
                    ,"GROUP_LINE_ID"
                    ,"LINE_NUM_DISPLAY"
                    ,"CLM_INFO_FLAG"
                    ,"CLM_OPTION_INDICATOR"
                    ,"CLM_BASE_LINE_NUM"
                    ,"CLM_OPTION_NUM"
                    ,"CLM_OPTION_FROM_DATE"
                    ,"CLM_OPTION_TO_DATE"
                    ,"CLM_FUNDED_FLAG"
                    ,"CONTRACT_TYPE"
                    ,"COST_CONSTRAINT"
                    ,"CLM_IDC_TYPE"
                    ,"UDA_TEMPLATE_ID"
                    ,"USER_DOCUMENT_STATUS"
                    ,"DRAFT_ID"
                    ,"CLM_EXERCISED_FLAG"
                    ,"CLM_EXERCISED_DATE"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'N' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "STG"."STG_EBS_PO_LINES_ALL" S
                WHERE NOT EXISTS(SELECT 1 FROM "HSTG"."HSTG_EBS_PO_LINES_ALL" H WHERE H.OMD_CURRENT_RECORD_INDICATOR = 'Y' AND OMD_IS_RECORD_DELETED = 'N' AND H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)



            /* Step 3:  IMPORT DELETED RECORDS FROM HISTORY TO HISTORY */

                /* THERE WAS NO BK FOR THIS TABLE. WE CANNOT IDENTIFY THE DELETED RECORDS.*/

            /* Step 4:  UPDATE OMD_CURRENT_RECORD_INDICATOR FLAG*/
				UPDATE  H 				SET OMD_CURRENT_RECORD_INDICATOR='N'				FROM "HSTG"."HSTG_EBS_PO_LINES_ALL" H					Join "STG"."STG_EBS_PO_LINES_ALL" S						On H.PO_LINE_ID= S.PO_LINE_ID				WHERE "OMD_IS_RECORD_DELETED" = 'N'						AND H.OMD_HASH_FULL_RECORD <> S.OMD_HASH_FULL_RECORD
            
            
            END
        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
