

CREATE Procedure [HSTG].[LOAD_HSTG_EBS_OE_ORDER_HEADERS_ALL]
AS 
BEGIN


    SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        8/03/2022 5:53:48 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "HSTG"."LOAD_HSTG_EBS_OE_ORDER_HEADERS_ALL";
    
    Source                                  Destination                            
    ------------------------------------    ------------------------------------- 
    STG"."STG_EBS_OE_ORDER_HEADERS_ALL"    "HSTG"."HSTG_EBS_OE_ORDER_HEADERS_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-08    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  CALL CHECK RECORD COUNT FROM STAGING TABLE*/
        DECLARE @ROW_COUNT BIGINT = 0;
        SELECT @ROW_COUNT = COUNT_BIG(*)  FROM  "STG"."STG_EBS_OE_ORDER_HEADERS_ALL"
        IF (@ROW_COUNT > 0)
        BEGIN
        /* Step 2:  IMPORT FROM STAGING TO HISTORY */
                INSERT INTO "HSTG"."HSTG_EBS_OE_ORDER_HEADERS_ALL"
                (
                    "HEADER_ID"
                    ,"ORG_ID"
                    ,"ORDER_TYPE_ID"
                    ,"ORDER_NUMBER"
                    ,"VERSION_NUMBER"
                    ,"EXPIRATION_DATE"
                    ,"ORDER_SOURCE_ID"
                    ,"SOURCE_DOCUMENT_TYPE_ID"
                    ,"ORIG_SYS_DOCUMENT_REF"
                    ,"SOURCE_DOCUMENT_ID"
                    ,"ORDERED_DATE"
                    ,"REQUEST_DATE"
                    ,"PRICING_DATE"
                    ,"SHIPMENT_PRIORITY_CODE"
                    ,"DEMAND_CLASS_CODE"
                    ,"PRICE_LIST_ID"
                    ,"TAX_EXEMPT_FLAG"
                    ,"TAX_EXEMPT_NUMBER"
                    ,"TAX_EXEMPT_REASON_CODE"
                    ,"CONVERSION_RATE"
                    ,"CONVERSION_TYPE_CODE"
                    ,"CONVERSION_RATE_DATE"
                    ,"PARTIAL_SHIPMENTS_ALLOWED"
                    ,"SHIP_TOLERANCE_ABOVE"
                    ,"SHIP_TOLERANCE_BELOW"
                    ,"TRANSACTIONAL_CURR_CODE"
                    ,"AGREEMENT_ID"
                    ,"TAX_POINT_CODE"
                    ,"CUST_PO_NUMBER"
                    ,"INVOICING_RULE_ID"
                    ,"ACCOUNTING_RULE_ID"
                    ,"PAYMENT_TERM_ID"
                    ,"SHIPPING_METHOD_CODE"
                    ,"FREIGHT_CARRIER_CODE"
                    ,"FOB_POINT_CODE"
                    ,"FREIGHT_TERMS_CODE"
                    ,"SOLD_FROM_ORG_ID"
                    ,"SOLD_TO_ORG_ID"
                    ,"SHIP_FROM_ORG_ID"
                    ,"SHIP_TO_ORG_ID"
                    ,"INVOICE_TO_ORG_ID"
                    ,"DELIVER_TO_ORG_ID"
                    ,"SOLD_TO_CONTACT_ID"
                    ,"SHIP_TO_CONTACT_ID"
                    ,"INVOICE_TO_CONTACT_ID"
                    ,"DELIVER_TO_CONTACT_ID"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATE_LOGIN"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"REQUEST_ID"
                    ,"CONTEXT"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"CANCELLED_FLAG"
                    ,"OPEN_FLAG"
                    ,"BOOKED_FLAG"
                    ,"SALESREP_ID"
                    ,"RETURN_REASON_CODE"
                    ,"ORDER_DATE_TYPE_CODE"
                    ,"EARLIEST_SCHEDULE_LIMIT"
                    ,"LATEST_SCHEDULE_LIMIT"
                    ,"PAYMENT_TYPE_CODE"
                    ,"PAYMENT_AMOUNT"
                    ,"CHECK_NUMBER"
                    ,"CREDIT_CARD_CODE"
                    ,"CREDIT_CARD_HOLDER_NAME"
                    ,"CREDIT_CARD_NUMBER"
                    ,"CREDIT_CARD_EXPIRATION_DATE"
                    ,"CREDIT_CARD_APPROVAL_CODE"
                    ,"SALES_CHANNEL_CODE"
                    ,"FIRST_ACK_CODE"
                    ,"FIRST_ACK_DATE"
                    ,"LAST_ACK_CODE"
                    ,"LAST_ACK_DATE"
                    ,"ORDER_CATEGORY_CODE"
                    ,"CHANGE_SEQUENCE"
                    ,"DROP_SHIP_FLAG"
                    ,"CUSTOMER_PAYMENT_TERM_ID"
                    ,"SHIPPING_INSTRUCTIONS"
                    ,"PACKING_INSTRUCTIONS"
                    ,"TP_CONTEXT"
                    ,"TP_ATTRIBUTE1"
                    ,"TP_ATTRIBUTE2"
                    ,"TP_ATTRIBUTE3"
                    ,"TP_ATTRIBUTE4"
                    ,"TP_ATTRIBUTE5"
                    ,"TP_ATTRIBUTE6"
                    ,"TP_ATTRIBUTE7"
                    ,"TP_ATTRIBUTE8"
                    ,"TP_ATTRIBUTE9"
                    ,"TP_ATTRIBUTE10"
                    ,"TP_ATTRIBUTE11"
                    ,"TP_ATTRIBUTE12"
                    ,"TP_ATTRIBUTE13"
                    ,"TP_ATTRIBUTE14"
                    ,"TP_ATTRIBUTE15"
                    ,"FLOW_STATUS_CODE"
                    ,"MARKETING_SOURCE_CODE_ID"
                    ,"CREDIT_CARD_APPROVAL_DATE"
                    ,"UPGRADED_FLAG"
                    ,"CUSTOMER_PREFERENCE_SET_CODE"
                    ,"BOOKED_DATE"
                    ,"LOCK_CONTROL"
                    ,"PRICE_REQUEST_CODE"
                    ,"BATCH_ID"
                    ,"XML_MESSAGE_ID"
                    ,"ACCOUNTING_RULE_DURATION"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"BLANKET_NUMBER"
                    ,"SALES_DOCUMENT_TYPE_CODE"
                    ,"SOLD_TO_PHONE_ID"
                    ,"FULFILLMENT_SET_NAME"
                    ,"LINE_SET_NAME"
                    ,"DEFAULT_FULFILLMENT_SET"
                    ,"TRANSACTION_PHASE_CODE"
                    ,"SALES_DOCUMENT_NAME"
                    ,"QUOTE_NUMBER"
                    ,"QUOTE_DATE"
                    ,"USER_STATUS_CODE"
                    ,"DRAFT_SUBMITTED_FLAG"
                    ,"SOURCE_DOCUMENT_VERSION_NUMBER"
                    ,"SOLD_TO_SITE_USE_ID"
                    ,"SUPPLIER_SIGNATURE"
                    ,"SUPPLIER_SIGNATURE_DATE"
                    ,"CUSTOMER_SIGNATURE"
                    ,"CUSTOMER_SIGNATURE_DATE"
                    ,"MINISITE_ID"
                    ,"END_CUSTOMER_ID"
                    ,"END_CUSTOMER_CONTACT_ID"
                    ,"END_CUSTOMER_SITE_USE_ID"
                    ,"IB_OWNER"
                    ,"IB_CURRENT_LOCATION"
                    ,"IB_INSTALLED_AT_LOCATION"
                    ,"ORDER_FIRMED_DATE"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "HEADER_ID"
                    ,"ORG_ID"
                    ,"ORDER_TYPE_ID"
                    ,"ORDER_NUMBER"
                    ,"VERSION_NUMBER"
                    ,"EXPIRATION_DATE"
                    ,"ORDER_SOURCE_ID"
                    ,"SOURCE_DOCUMENT_TYPE_ID"
                    ,"ORIG_SYS_DOCUMENT_REF"
                    ,"SOURCE_DOCUMENT_ID"
                    ,"ORDERED_DATE"
                    ,"REQUEST_DATE"
                    ,"PRICING_DATE"
                    ,"SHIPMENT_PRIORITY_CODE"
                    ,"DEMAND_CLASS_CODE"
                    ,"PRICE_LIST_ID"
                    ,"TAX_EXEMPT_FLAG"
                    ,"TAX_EXEMPT_NUMBER"
                    ,"TAX_EXEMPT_REASON_CODE"
                    ,"CONVERSION_RATE"
                    ,"CONVERSION_TYPE_CODE"
                    ,"CONVERSION_RATE_DATE"
                    ,"PARTIAL_SHIPMENTS_ALLOWED"
                    ,"SHIP_TOLERANCE_ABOVE"
                    ,"SHIP_TOLERANCE_BELOW"
                    ,"TRANSACTIONAL_CURR_CODE"
                    ,"AGREEMENT_ID"
                    ,"TAX_POINT_CODE"
                    ,"CUST_PO_NUMBER"
                    ,"INVOICING_RULE_ID"
                    ,"ACCOUNTING_RULE_ID"
                    ,"PAYMENT_TERM_ID"
                    ,"SHIPPING_METHOD_CODE"
                    ,"FREIGHT_CARRIER_CODE"
                    ,"FOB_POINT_CODE"
                    ,"FREIGHT_TERMS_CODE"
                    ,"SOLD_FROM_ORG_ID"
                    ,"SOLD_TO_ORG_ID"
                    ,"SHIP_FROM_ORG_ID"
                    ,"SHIP_TO_ORG_ID"
                    ,"INVOICE_TO_ORG_ID"
                    ,"DELIVER_TO_ORG_ID"
                    ,"SOLD_TO_CONTACT_ID"
                    ,"SHIP_TO_CONTACT_ID"
                    ,"INVOICE_TO_CONTACT_ID"
                    ,"DELIVER_TO_CONTACT_ID"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATE_LOGIN"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"REQUEST_ID"
                    ,"CONTEXT"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"CANCELLED_FLAG"
                    ,"OPEN_FLAG"
                    ,"BOOKED_FLAG"
                    ,"SALESREP_ID"
                    ,"RETURN_REASON_CODE"
                    ,"ORDER_DATE_TYPE_CODE"
                    ,"EARLIEST_SCHEDULE_LIMIT"
                    ,"LATEST_SCHEDULE_LIMIT"
                    ,"PAYMENT_TYPE_CODE"
                    ,"PAYMENT_AMOUNT"
                    ,"CHECK_NUMBER"
                    ,"CREDIT_CARD_CODE"
                    ,"CREDIT_CARD_HOLDER_NAME"
                    ,"CREDIT_CARD_NUMBER"
                    ,"CREDIT_CARD_EXPIRATION_DATE"
                    ,"CREDIT_CARD_APPROVAL_CODE"
                    ,"SALES_CHANNEL_CODE"
                    ,"FIRST_ACK_CODE"
                    ,"FIRST_ACK_DATE"
                    ,"LAST_ACK_CODE"
                    ,"LAST_ACK_DATE"
                    ,"ORDER_CATEGORY_CODE"
                    ,"CHANGE_SEQUENCE"
                    ,"DROP_SHIP_FLAG"
                    ,"CUSTOMER_PAYMENT_TERM_ID"
                    ,"SHIPPING_INSTRUCTIONS"
                    ,"PACKING_INSTRUCTIONS"
                    ,"TP_CONTEXT"
                    ,"TP_ATTRIBUTE1"
                    ,"TP_ATTRIBUTE2"
                    ,"TP_ATTRIBUTE3"
                    ,"TP_ATTRIBUTE4"
                    ,"TP_ATTRIBUTE5"
                    ,"TP_ATTRIBUTE6"
                    ,"TP_ATTRIBUTE7"
                    ,"TP_ATTRIBUTE8"
                    ,"TP_ATTRIBUTE9"
                    ,"TP_ATTRIBUTE10"
                    ,"TP_ATTRIBUTE11"
                    ,"TP_ATTRIBUTE12"
                    ,"TP_ATTRIBUTE13"
                    ,"TP_ATTRIBUTE14"
                    ,"TP_ATTRIBUTE15"
                    ,"FLOW_STATUS_CODE"
                    ,"MARKETING_SOURCE_CODE_ID"
                    ,"CREDIT_CARD_APPROVAL_DATE"
                    ,"UPGRADED_FLAG"
                    ,"CUSTOMER_PREFERENCE_SET_CODE"
                    ,"BOOKED_DATE"
                    ,"LOCK_CONTROL"
                    ,"PRICE_REQUEST_CODE"
                    ,"BATCH_ID"
                    ,"XML_MESSAGE_ID"
                    ,"ACCOUNTING_RULE_DURATION"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"BLANKET_NUMBER"
                    ,"SALES_DOCUMENT_TYPE_CODE"
                    ,"SOLD_TO_PHONE_ID"
                    ,"FULFILLMENT_SET_NAME"
                    ,"LINE_SET_NAME"
                    ,"DEFAULT_FULFILLMENT_SET"
                    ,"TRANSACTION_PHASE_CODE"
                    ,"SALES_DOCUMENT_NAME"
                    ,"QUOTE_NUMBER"
                    ,"QUOTE_DATE"
                    ,"USER_STATUS_CODE"
                    ,"DRAFT_SUBMITTED_FLAG"
                    ,"SOURCE_DOCUMENT_VERSION_NUMBER"
                    ,"SOLD_TO_SITE_USE_ID"
                    ,"SUPPLIER_SIGNATURE"
                    ,"SUPPLIER_SIGNATURE_DATE"
                    ,"CUSTOMER_SIGNATURE"
                    ,"CUSTOMER_SIGNATURE_DATE"
                    ,"MINISITE_ID"
                    ,"END_CUSTOMER_ID"
                    ,"END_CUSTOMER_CONTACT_ID"
                    ,"END_CUSTOMER_SITE_USE_ID"
                    ,"IB_OWNER"
                    ,"IB_CURRENT_LOCATION"
                    ,"IB_INSTALLED_AT_LOCATION"
                    ,"ORDER_FIRMED_DATE"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'N' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "STG"."STG_EBS_OE_ORDER_HEADERS_ALL" S
                WHERE NOT EXISTS(SELECT 1 FROM "HSTG"."HSTG_EBS_OE_ORDER_HEADERS_ALL" H WHERE H.OMD_CURRENT_RECORD_INDICATOR = 'Y' AND OMD_IS_RECORD_DELETED = 'N' AND H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)



            /* Step 3:  IMPORT DELETED RECORDS FROM HISTORY TO HISTORY */

                /* THERE WAS NO BK FOR THIS TABLE. WE CANNOT IDENTIFY THE DELETED RECORDS.*/

            /* Step 4:  UPDATE OMD_CURRENT_RECORD_INDICATOR FLAG*/
				UPDATE  H 				SET OMD_CURRENT_RECORD_INDICATOR='N'				FROM "HSTG"."HSTG_EBS_OE_ORDER_HEADERS_ALL" H					Join "STG"."STG_EBS_OE_ORDER_HEADERS_ALL" S						On H.HEADER_ID= S.HEADER_ID				WHERE "OMD_IS_RECORD_DELETED" = 'N'						AND H.OMD_HASH_FULL_RECORD <> S.OMD_HASH_FULL_RECORD
            
            
            END
        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
