

CREATE Procedure [HSTG].[LOAD_HSTG_EBS_MTL_MATERIAL_TRANSACTIONS]
AS 
BEGIN


    SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        8/03/2022 5:53:45 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "HSTG"."LOAD_HSTG_EBS_MTL_MATERIAL_TRANSACTIONS";
    
    Source                                       Destination                                 
    -----------------------------------------    ------------------------------------------ 
    STG"."STG_EBS_MTL_MATERIAL_TRANSACTIONS"    "HSTG"."HSTG_EBS_MTL_MATERIAL_TRANSACTIONS" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-08    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  CALL CHECK RECORD COUNT FROM STAGING TABLE*/
        DECLARE @ROW_COUNT BIGINT = 0;
        SELECT @ROW_COUNT = COUNT_BIG(*)  FROM  "STG"."STG_EBS_MTL_MATERIAL_TRANSACTIONS"
        IF (@ROW_COUNT > 0)
        BEGIN
        /* Step 2:  IMPORT FROM STAGING TO HISTORY */
                INSERT INTO "HSTG"."HSTG_EBS_MTL_MATERIAL_TRANSACTIONS"
                (
                    "TRANSACTION_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"INVENTORY_ITEM_ID"
                    ,"REVISION"
                    ,"ORGANIZATION_ID"
                    ,"SUBINVENTORY_CODE"
                    ,"LOCATOR_ID"
                    ,"TRANSACTION_TYPE_ID"
                    ,"TRANSACTION_ACTION_ID"
                    ,"TRANSACTION_SOURCE_TYPE_ID"
                    ,"TRANSACTION_SOURCE_ID"
                    ,"TRANSACTION_SOURCE_NAME"
                    ,"TRANSACTION_QUANTITY"
                    ,"TRANSACTION_UOM"
                    ,"PRIMARY_QUANTITY"
                    ,"TRANSACTION_DATE"
                    ,"VARIANCE_AMOUNT"
                    ,"ACCT_PERIOD_ID"
                    ,"TRANSACTION_REFERENCE"
                    ,"REASON_ID"
                    ,"DISTRIBUTION_ACCOUNT_ID"
                    ,"ENCUMBRANCE_ACCOUNT"
                    ,"ENCUMBRANCE_AMOUNT"
                    ,"COST_UPDATE_ID"
                    ,"COSTED_FLAG"
                    ,"TRANSACTION_GROUP_ID"
                    ,"INVOICED_FLAG"
                    ,"ACTUAL_COST"
                    ,"TRANSACTION_COST"
                    ,"PRIOR_COST"
                    ,"NEW_COST"
                    ,"CURRENCY_CODE"
                    ,"CURRENCY_CONVERSION_RATE"
                    ,"CURRENCY_CONVERSION_TYPE"
                    ,"CURRENCY_CONVERSION_DATE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"QUANTITY_ADJUSTED"
                    ,"EMPLOYEE_CODE"
                    ,"DEPARTMENT_ID"
                    ,"OPERATION_SEQ_NUM"
                    ,"MASTER_SCHEDULE_UPDATE_CODE"
                    ,"RECEIVING_DOCUMENT"
                    ,"PICKING_LINE_ID"
                    ,"TRX_SOURCE_LINE_ID"
                    ,"TRX_SOURCE_DELIVERY_ID"
                    ,"REPETITIVE_LINE_ID"
                    ,"PHYSICAL_ADJUSTMENT_ID"
                    ,"CYCLE_COUNT_ID"
                    ,"RMA_LINE_ID"
                    ,"TRANSFER_TRANSACTION_ID"
                    ,"TRANSACTION_SET_ID"
                    ,"RCV_TRANSACTION_ID"
                    ,"MOVE_TRANSACTION_ID"
                    ,"COMPLETION_TRANSACTION_ID"
                    ,"SHORTAGE_PROCESS_CODE"
                    ,"SOURCE_CODE"
                    ,"SOURCE_LINE_ID"
                    ,"VENDOR_LOT_NUMBER"
                    ,"TRANSFER_ORGANIZATION_ID"
                    ,"TRANSFER_SUBINVENTORY"
                    ,"TRANSFER_LOCATOR_ID"
                    ,"SHIPMENT_NUMBER"
                    ,"TRANSFER_COST"
                    ,"TRANSPORTATION_DIST_ACCOUNT"
                    ,"TRANSPORTATION_COST"
                    ,"TRANSFER_COST_DIST_ACCOUNT"
                    ,"WAYBILL_AIRBILL"
                    ,"FREIGHT_CODE"
                    ,"NUMBER_OF_CONTAINERS"
                    ,"VALUE_CHANGE"
                    ,"PERCENTAGE_CHANGE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"MOVEMENT_ID"
                    ,"TASK_ID"
                    ,"TO_TASK_ID"
                    ,"PROJECT_ID"
                    ,"TO_PROJECT_ID"
                    ,"SOURCE_PROJECT_ID"
                    ,"PA_EXPENDITURE_ORG_ID"
                    ,"SOURCE_TASK_ID"
                    ,"EXPENDITURE_TYPE"
                    ,"ERROR_CODE"
                    ,"ERROR_EXPLANATION"
                    ,"PRIOR_COSTED_QUANTITY"
                    ,"TRANSFER_PRIOR_COSTED_QUANTITY"
                    ,"FINAL_COMPLETION_FLAG"
                    ,"PM_COST_COLLECTED"
                    ,"PM_COST_COLLECTOR_GROUP_ID"
                    ,"SHIPMENT_COSTED"
                    ,"TRANSFER_PERCENTAGE"
                    ,"MATERIAL_ACCOUNT"
                    ,"MATERIAL_OVERHEAD_ACCOUNT"
                    ,"RESOURCE_ACCOUNT"
                    ,"OUTSIDE_PROCESSING_ACCOUNT"
                    ,"OVERHEAD_ACCOUNT"
                    ,"COST_GROUP_ID"
                    ,"TRANSFER_COST_GROUP_ID"
                    ,"FLOW_SCHEDULE"
                    ,"QA_COLLECTION_ID"
                    ,"OVERCOMPLETION_TRANSACTION_QTY"
                    ,"OVERCOMPLETION_PRIMARY_QTY"
                    ,"OVERCOMPLETION_TRANSACTION_ID"
                    ,"MVT_STAT_STATUS"
                    ,"COMMON_BOM_SEQ_ID"
                    ,"COMMON_ROUTING_SEQ_ID"
                    ,"ORG_COST_GROUP_ID"
                    ,"COST_TYPE_ID"
                    ,"PERIODIC_PRIMARY_QUANTITY"
                    ,"MOVE_ORDER_LINE_ID"
                    ,"TASK_GROUP_ID"
                    ,"PICK_SLIP_NUMBER"
                    ,"LPN_ID"
                    ,"TRANSFER_LPN_ID"
                    ,"PICK_STRATEGY_ID"
                    ,"PICK_RULE_ID"
                    ,"PUT_AWAY_STRATEGY_ID"
                    ,"PUT_AWAY_RULE_ID"
                    ,"CONTENT_LPN_ID"
                    ,"PICK_SLIP_DATE"
                    ,"COST_CATEGORY_ID"
                    ,"ORGANIZATION_TYPE"
                    ,"TRANSFER_ORGANIZATION_TYPE"
                    ,"OWNING_ORGANIZATION_ID"
                    ,"OWNING_TP_TYPE"
                    ,"XFR_OWNING_ORGANIZATION_ID"
                    ,"TRANSFER_OWNING_TP_TYPE"
                    ,"PLANNING_ORGANIZATION_ID"
                    ,"PLANNING_TP_TYPE"
                    ,"XFR_PLANNING_ORGANIZATION_ID"
                    ,"TRANSFER_PLANNING_TP_TYPE"
                    ,"SECONDARY_UOM_CODE"
                    ,"SECONDARY_TRANSACTION_QUANTITY"
                    ,"TRANSACTION_GROUP_SEQ"
                    ,"SHIP_TO_LOCATION_ID"
                    ,"RESERVATION_ID"
                    ,"TRANSACTION_MODE"
                    ,"TRANSACTION_BATCH_ID"
                    ,"TRANSACTION_BATCH_SEQ"
                    ,"INTRANSIT_ACCOUNT"
                    ,"FOB_POINT"
                    ,"PARENT_TRANSACTION_ID"
                    ,"LOGICAL_TRX_TYPE_CODE"
                    ,"TRX_FLOW_HEADER_ID"
                    ,"LOGICAL_TRANSACTIONS_CREATED"
                    ,"LOGICAL_TRANSACTION"
                    ,"INTERCOMPANY_COST"
                    ,"INTERCOMPANY_PRICING_OPTION"
                    ,"INTERCOMPANY_CURRENCY_CODE"
                    ,"ORIGINAL_TRANSACTION_TEMP_ID"
                    ,"TRANSFER_PRICE"
                    ,"EXPENSE_ACCOUNT_ID"
                    ,"COGS_RECOGNITION_PERCENT"
                    ,"SO_ISSUE_ACCOUNT_TYPE"
                    ,"OPM_COSTED_FLAG"
                    ,"MATERIAL_EXPENSE_ACCOUNT"
                    ,"TRANSACTION_EXTRACTED"
                    ,"XML_DOCUMENT_ID"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "TRANSACTION_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"INVENTORY_ITEM_ID"
                    ,"REVISION"
                    ,"ORGANIZATION_ID"
                    ,"SUBINVENTORY_CODE"
                    ,"LOCATOR_ID"
                    ,"TRANSACTION_TYPE_ID"
                    ,"TRANSACTION_ACTION_ID"
                    ,"TRANSACTION_SOURCE_TYPE_ID"
                    ,"TRANSACTION_SOURCE_ID"
                    ,"TRANSACTION_SOURCE_NAME"
                    ,"TRANSACTION_QUANTITY"
                    ,"TRANSACTION_UOM"
                    ,"PRIMARY_QUANTITY"
                    ,"TRANSACTION_DATE"
                    ,"VARIANCE_AMOUNT"
                    ,"ACCT_PERIOD_ID"
                    ,"TRANSACTION_REFERENCE"
                    ,"REASON_ID"
                    ,"DISTRIBUTION_ACCOUNT_ID"
                    ,"ENCUMBRANCE_ACCOUNT"
                    ,"ENCUMBRANCE_AMOUNT"
                    ,"COST_UPDATE_ID"
                    ,"COSTED_FLAG"
                    ,"TRANSACTION_GROUP_ID"
                    ,"INVOICED_FLAG"
                    ,"ACTUAL_COST"
                    ,"TRANSACTION_COST"
                    ,"PRIOR_COST"
                    ,"NEW_COST"
                    ,"CURRENCY_CODE"
                    ,"CURRENCY_CONVERSION_RATE"
                    ,"CURRENCY_CONVERSION_TYPE"
                    ,"CURRENCY_CONVERSION_DATE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"QUANTITY_ADJUSTED"
                    ,"EMPLOYEE_CODE"
                    ,"DEPARTMENT_ID"
                    ,"OPERATION_SEQ_NUM"
                    ,"MASTER_SCHEDULE_UPDATE_CODE"
                    ,"RECEIVING_DOCUMENT"
                    ,"PICKING_LINE_ID"
                    ,"TRX_SOURCE_LINE_ID"
                    ,"TRX_SOURCE_DELIVERY_ID"
                    ,"REPETITIVE_LINE_ID"
                    ,"PHYSICAL_ADJUSTMENT_ID"
                    ,"CYCLE_COUNT_ID"
                    ,"RMA_LINE_ID"
                    ,"TRANSFER_TRANSACTION_ID"
                    ,"TRANSACTION_SET_ID"
                    ,"RCV_TRANSACTION_ID"
                    ,"MOVE_TRANSACTION_ID"
                    ,"COMPLETION_TRANSACTION_ID"
                    ,"SHORTAGE_PROCESS_CODE"
                    ,"SOURCE_CODE"
                    ,"SOURCE_LINE_ID"
                    ,"VENDOR_LOT_NUMBER"
                    ,"TRANSFER_ORGANIZATION_ID"
                    ,"TRANSFER_SUBINVENTORY"
                    ,"TRANSFER_LOCATOR_ID"
                    ,"SHIPMENT_NUMBER"
                    ,"TRANSFER_COST"
                    ,"TRANSPORTATION_DIST_ACCOUNT"
                    ,"TRANSPORTATION_COST"
                    ,"TRANSFER_COST_DIST_ACCOUNT"
                    ,"WAYBILL_AIRBILL"
                    ,"FREIGHT_CODE"
                    ,"NUMBER_OF_CONTAINERS"
                    ,"VALUE_CHANGE"
                    ,"PERCENTAGE_CHANGE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"MOVEMENT_ID"
                    ,"TASK_ID"
                    ,"TO_TASK_ID"
                    ,"PROJECT_ID"
                    ,"TO_PROJECT_ID"
                    ,"SOURCE_PROJECT_ID"
                    ,"PA_EXPENDITURE_ORG_ID"
                    ,"SOURCE_TASK_ID"
                    ,"EXPENDITURE_TYPE"
                    ,"ERROR_CODE"
                    ,"ERROR_EXPLANATION"
                    ,"PRIOR_COSTED_QUANTITY"
                    ,"TRANSFER_PRIOR_COSTED_QUANTITY"
                    ,"FINAL_COMPLETION_FLAG"
                    ,"PM_COST_COLLECTED"
                    ,"PM_COST_COLLECTOR_GROUP_ID"
                    ,"SHIPMENT_COSTED"
                    ,"TRANSFER_PERCENTAGE"
                    ,"MATERIAL_ACCOUNT"
                    ,"MATERIAL_OVERHEAD_ACCOUNT"
                    ,"RESOURCE_ACCOUNT"
                    ,"OUTSIDE_PROCESSING_ACCOUNT"
                    ,"OVERHEAD_ACCOUNT"
                    ,"COST_GROUP_ID"
                    ,"TRANSFER_COST_GROUP_ID"
                    ,"FLOW_SCHEDULE"
                    ,"QA_COLLECTION_ID"
                    ,"OVERCOMPLETION_TRANSACTION_QTY"
                    ,"OVERCOMPLETION_PRIMARY_QTY"
                    ,"OVERCOMPLETION_TRANSACTION_ID"
                    ,"MVT_STAT_STATUS"
                    ,"COMMON_BOM_SEQ_ID"
                    ,"COMMON_ROUTING_SEQ_ID"
                    ,"ORG_COST_GROUP_ID"
                    ,"COST_TYPE_ID"
                    ,"PERIODIC_PRIMARY_QUANTITY"
                    ,"MOVE_ORDER_LINE_ID"
                    ,"TASK_GROUP_ID"
                    ,"PICK_SLIP_NUMBER"
                    ,"LPN_ID"
                    ,"TRANSFER_LPN_ID"
                    ,"PICK_STRATEGY_ID"
                    ,"PICK_RULE_ID"
                    ,"PUT_AWAY_STRATEGY_ID"
                    ,"PUT_AWAY_RULE_ID"
                    ,"CONTENT_LPN_ID"
                    ,"PICK_SLIP_DATE"
                    ,"COST_CATEGORY_ID"
                    ,"ORGANIZATION_TYPE"
                    ,"TRANSFER_ORGANIZATION_TYPE"
                    ,"OWNING_ORGANIZATION_ID"
                    ,"OWNING_TP_TYPE"
                    ,"XFR_OWNING_ORGANIZATION_ID"
                    ,"TRANSFER_OWNING_TP_TYPE"
                    ,"PLANNING_ORGANIZATION_ID"
                    ,"PLANNING_TP_TYPE"
                    ,"XFR_PLANNING_ORGANIZATION_ID"
                    ,"TRANSFER_PLANNING_TP_TYPE"
                    ,"SECONDARY_UOM_CODE"
                    ,"SECONDARY_TRANSACTION_QUANTITY"
                    ,"TRANSACTION_GROUP_SEQ"
                    ,"SHIP_TO_LOCATION_ID"
                    ,"RESERVATION_ID"
                    ,"TRANSACTION_MODE"
                    ,"TRANSACTION_BATCH_ID"
                    ,"TRANSACTION_BATCH_SEQ"
                    ,"INTRANSIT_ACCOUNT"
                    ,"FOB_POINT"
                    ,"PARENT_TRANSACTION_ID"
                    ,"LOGICAL_TRX_TYPE_CODE"
                    ,"TRX_FLOW_HEADER_ID"
                    ,"LOGICAL_TRANSACTIONS_CREATED"
                    ,"LOGICAL_TRANSACTION"
                    ,"INTERCOMPANY_COST"
                    ,"INTERCOMPANY_PRICING_OPTION"
                    ,"INTERCOMPANY_CURRENCY_CODE"
                    ,"ORIGINAL_TRANSACTION_TEMP_ID"
                    ,"TRANSFER_PRICE"
                    ,"EXPENSE_ACCOUNT_ID"
                    ,"COGS_RECOGNITION_PERCENT"
                    ,"SO_ISSUE_ACCOUNT_TYPE"
                    ,"OPM_COSTED_FLAG"
                    ,"MATERIAL_EXPENSE_ACCOUNT"
                    ,"TRANSACTION_EXTRACTED"
                    ,"XML_DOCUMENT_ID"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'N' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "STG"."STG_EBS_MTL_MATERIAL_TRANSACTIONS" S
                WHERE NOT EXISTS(SELECT 1 FROM "HSTG"."HSTG_EBS_MTL_MATERIAL_TRANSACTIONS" H WHERE H.OMD_CURRENT_RECORD_INDICATOR = 'Y' AND OMD_IS_RECORD_DELETED = 'N' AND H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)



            /* Step 3:  IMPORT DELETED RECORDS FROM HISTORY TO HISTORY */

                /* THERE WAS NO BK FOR THIS TABLE. WE CANNOT IDENTIFY THE DELETED RECORDS.*/

            /* Step 4:  UPDATE OMD_CURRENT_RECORD_INDICATOR FLAG*/
				UPDATE  H 				SET OMD_CURRENT_RECORD_INDICATOR='N'				FROM "HSTG"."HSTG_EBS_MTL_MATERIAL_TRANSACTIONS" H					Join "STG"."STG_EBS_MTL_MATERIAL_TRANSACTIONS" S						On H.TRANSACTION_ID= S.TRANSACTION_ID				WHERE "OMD_IS_RECORD_DELETED" = 'N'						AND H.OMD_HASH_FULL_RECORD <> S.OMD_HASH_FULL_RECORD
            
            
            END
        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
