CREATE Procedure [HSTG].[LOAD_HSTG_EBS_PER_ALL_PEOPLE_F]
AS 
BEGIN


    SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        5/05/2022 12:10:01 am
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "HSTG"."LOAD_HSTG_EBS_PER_ALL_PEOPLE_F";
    
    Source                              Destination                        
    --------------------------------    --------------------------------- 
    STG"."STG_EBS_PER_ALL_PEOPLE_F"    "HSTG"."HSTG_EBS_PER_ALL_PEOPLE_F" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-05    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  CALL CHECK RECORD COUNT FROM STAGING TABLE*/
        DECLARE @ROW_COUNT BIGINT = 0;
        SELECT @ROW_COUNT = COUNT_BIG(*)  FROM  "STG"."STG_EBS_PER_ALL_PEOPLE_F"
        IF (@ROW_COUNT > 0)
        BEGIN
        /* Step 2:  IMPORT FROM STAGING TO HISTORY */
                INSERT INTO "HSTG"."HSTG_EBS_PER_ALL_PEOPLE_F"
                (
                    "PERSON_ID"
                    ,"EFFECTIVE_START_DATE"
                    ,"EFFECTIVE_END_DATE"
                    ,"BUSINESS_GROUP_ID"
                    ,"PERSON_TYPE_ID"
                    ,"LAST_NAME"
                    ,"START_DATE"
                    ,"APPLICANT_NUMBER"
                    ,"BACKGROUND_CHECK_STATUS"
                    ,"BACKGROUND_DATE_CHECK"
                    ,"BLOOD_TYPE"
                    ,"COMMENT_ID"
                    ,"CORRESPONDENCE_LANGUAGE"
                    ,"CURRENT_APPLICANT_FLAG"
                    ,"CURRENT_EMP_OR_APL_FLAG"
                    ,"CURRENT_EMPLOYEE_FLAG"
                    ,"DATE_EMPLOYEE_DATA_VERIFIED"
                    ,"DATE_OF_BIRTH"
                    ,"EMAIL_ADDRESS"
                    ,"EMPLOYEE_NUMBER"
                    ,"EXPENSE_CHECK_SEND_TO_ADDRESS"
                    ,"FAST_PATH_EMPLOYEE"
                    ,"FIRST_NAME"
                    ,"FTE_CAPACITY"
                    ,"FULL_NAME"
                    ,"HOLD_APPLICANT_DATE_UNTIL"
                    ,"HONORS"
                    ,"INTERNAL_LOCATION"
                    ,"KNOWN_AS"
                    ,"LAST_MEDICAL_TEST_BY"
                    ,"LAST_MEDICAL_TEST_DATE"
                    ,"MAILSTOP"
                    ,"MARITAL_STATUS"
                    ,"MIDDLE_NAMES"
                    ,"NATIONALITY"
                    ,"NATIONAL_IDENTIFIER"
                    ,"OFFICE_NUMBER"
                    ,"ON_MILITARY_SERVICE"
                    ,"ORDER_NAME"
                    ,"PRE_NAME_ADJUNCT"
                    ,"PREVIOUS_LAST_NAME"
                    ,"PROJECTED_START_DATE"
                    ,"REHIRE_AUTHORIZOR"
                    ,"REHIRE_REASON"
                    ,"REHIRE_RECOMMENDATION"
                    ,"RESUME_EXISTS"
                    ,"RESUME_LAST_UPDATED"
                    ,"REGISTERED_DISABLED_FLAG"
                    ,"SECOND_PASSPORT_EXISTS"
                    ,"SEX"
                    ,"STUDENT_STATUS"
                    ,"SUFFIX"
                    ,"TITLE"
                    ,"VENDOR_ID"
                    ,"WORK_SCHEDULE"
                    ,"WORK_TELEPHONE"
                    ,"COORD_BEN_MED_PLN_NO"
                    ,"COORD_BEN_NO_CVG_FLAG"
                    ,"DPDNT_ADOPTION_DATE"
                    ,"DPDNT_VLNTRY_SVCE_FLAG"
                    ,"RECEIPT_OF_DEATH_CERT_DATE"
                    ,"USES_TOBACCO_FLAG"
                    ,"BENEFIT_GROUP_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"ATTRIBUTE21"
                    ,"ATTRIBUTE22"
                    ,"ATTRIBUTE23"
                    ,"ATTRIBUTE24"
                    ,"ATTRIBUTE25"
                    ,"ATTRIBUTE26"
                    ,"ATTRIBUTE27"
                    ,"ATTRIBUTE28"
                    ,"ATTRIBUTE29"
                    ,"ATTRIBUTE30"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATED_BY"
                    ,"CREATION_DATE"
                    ,"PER_INFORMATION_CATEGORY"
                    ,"PER_INFORMATION1"
                    ,"PER_INFORMATION2"
                    ,"PER_INFORMATION3"
                    ,"PER_INFORMATION4"
                    ,"PER_INFORMATION5"
                    ,"PER_INFORMATION6"
                    ,"PER_INFORMATION7"
                    ,"PER_INFORMATION8"
                    ,"PER_INFORMATION9"
                    ,"PER_INFORMATION10"
                    ,"PER_INFORMATION11"
                    ,"PER_INFORMATION12"
                    ,"PER_INFORMATION13"
                    ,"PER_INFORMATION14"
                    ,"PER_INFORMATION15"
                    ,"PER_INFORMATION16"
                    ,"PER_INFORMATION17"
                    ,"PER_INFORMATION18"
                    ,"PER_INFORMATION19"
                    ,"PER_INFORMATION20"
                    ,"PER_INFORMATION21"
                    ,"PER_INFORMATION22"
                    ,"PER_INFORMATION23"
                    ,"PER_INFORMATION24"
                    ,"PER_INFORMATION25"
                    ,"PER_INFORMATION26"
                    ,"PER_INFORMATION27"
                    ,"PER_INFORMATION28"
                    ,"PER_INFORMATION29"
                    ,"PER_INFORMATION30"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"DATE_OF_DEATH"
                    ,"ORIGINAL_DATE_OF_HIRE"
                    ,"TOWN_OF_BIRTH"
                    ,"REGION_OF_BIRTH"
                    ,"COUNTRY_OF_BIRTH"
                    ,"GLOBAL_PERSON_ID"
                    ,"COORD_BEN_MED_PL_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_IDENT"
                    ,"COORD_BEN_MED_EXT_ER"
                    ,"COORD_BEN_MED_CVG_STRT_DT"
                    ,"COORD_BEN_MED_CVG_END_DT"
                    ,"PARTY_ID"
                    ,"NPW_NUMBER"
                    ,"CURRENT_NPW_FLAG"
                    ,"GLOBAL_NAME"
                    ,"LOCAL_NAME"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "PERSON_ID"
                    ,"EFFECTIVE_START_DATE"
                    ,"EFFECTIVE_END_DATE"
                    ,"BUSINESS_GROUP_ID"
                    ,"PERSON_TYPE_ID"
                    ,"LAST_NAME"
                    ,"START_DATE"
                    ,"APPLICANT_NUMBER"
                    ,"BACKGROUND_CHECK_STATUS"
                    ,"BACKGROUND_DATE_CHECK"
                    ,"BLOOD_TYPE"
                    ,"COMMENT_ID"
                    ,"CORRESPONDENCE_LANGUAGE"
                    ,"CURRENT_APPLICANT_FLAG"
                    ,"CURRENT_EMP_OR_APL_FLAG"
                    ,"CURRENT_EMPLOYEE_FLAG"
                    ,"DATE_EMPLOYEE_DATA_VERIFIED"
                    ,"DATE_OF_BIRTH"
                    ,"EMAIL_ADDRESS"
                    ,"EMPLOYEE_NUMBER"
                    ,"EXPENSE_CHECK_SEND_TO_ADDRESS"
                    ,"FAST_PATH_EMPLOYEE"
                    ,"FIRST_NAME"
                    ,"FTE_CAPACITY"
                    ,"FULL_NAME"
                    ,"HOLD_APPLICANT_DATE_UNTIL"
                    ,"HONORS"
                    ,"INTERNAL_LOCATION"
                    ,"KNOWN_AS"
                    ,"LAST_MEDICAL_TEST_BY"
                    ,"LAST_MEDICAL_TEST_DATE"
                    ,"MAILSTOP"
                    ,"MARITAL_STATUS"
                    ,"MIDDLE_NAMES"
                    ,"NATIONALITY"
                    ,"NATIONAL_IDENTIFIER"
                    ,"OFFICE_NUMBER"
                    ,"ON_MILITARY_SERVICE"
                    ,"ORDER_NAME"
                    ,"PRE_NAME_ADJUNCT"
                    ,"PREVIOUS_LAST_NAME"
                    ,"PROJECTED_START_DATE"
                    ,"REHIRE_AUTHORIZOR"
                    ,"REHIRE_REASON"
                    ,"REHIRE_RECOMMENDATION"
                    ,"RESUME_EXISTS"
                    ,"RESUME_LAST_UPDATED"
                    ,"REGISTERED_DISABLED_FLAG"
                    ,"SECOND_PASSPORT_EXISTS"
                    ,"SEX"
                    ,"STUDENT_STATUS"
                    ,"SUFFIX"
                    ,"TITLE"
                    ,"VENDOR_ID"
                    ,"WORK_SCHEDULE"
                    ,"WORK_TELEPHONE"
                    ,"COORD_BEN_MED_PLN_NO"
                    ,"COORD_BEN_NO_CVG_FLAG"
                    ,"DPDNT_ADOPTION_DATE"
                    ,"DPDNT_VLNTRY_SVCE_FLAG"
                    ,"RECEIPT_OF_DEATH_CERT_DATE"
                    ,"USES_TOBACCO_FLAG"
                    ,"BENEFIT_GROUP_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"ATTRIBUTE21"
                    ,"ATTRIBUTE22"
                    ,"ATTRIBUTE23"
                    ,"ATTRIBUTE24"
                    ,"ATTRIBUTE25"
                    ,"ATTRIBUTE26"
                    ,"ATTRIBUTE27"
                    ,"ATTRIBUTE28"
                    ,"ATTRIBUTE29"
                    ,"ATTRIBUTE30"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATED_BY"
                    ,"CREATION_DATE"
                    ,"PER_INFORMATION_CATEGORY"
                    ,"PER_INFORMATION1"
                    ,"PER_INFORMATION2"
                    ,"PER_INFORMATION3"
                    ,"PER_INFORMATION4"
                    ,"PER_INFORMATION5"
                    ,"PER_INFORMATION6"
                    ,"PER_INFORMATION7"
                    ,"PER_INFORMATION8"
                    ,"PER_INFORMATION9"
                    ,"PER_INFORMATION10"
                    ,"PER_INFORMATION11"
                    ,"PER_INFORMATION12"
                    ,"PER_INFORMATION13"
                    ,"PER_INFORMATION14"
                    ,"PER_INFORMATION15"
                    ,"PER_INFORMATION16"
                    ,"PER_INFORMATION17"
                    ,"PER_INFORMATION18"
                    ,"PER_INFORMATION19"
                    ,"PER_INFORMATION20"
                    ,"PER_INFORMATION21"
                    ,"PER_INFORMATION22"
                    ,"PER_INFORMATION23"
                    ,"PER_INFORMATION24"
                    ,"PER_INFORMATION25"
                    ,"PER_INFORMATION26"
                    ,"PER_INFORMATION27"
                    ,"PER_INFORMATION28"
                    ,"PER_INFORMATION29"
                    ,"PER_INFORMATION30"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"DATE_OF_DEATH"
                    ,"ORIGINAL_DATE_OF_HIRE"
                    ,"TOWN_OF_BIRTH"
                    ,"REGION_OF_BIRTH"
                    ,"COUNTRY_OF_BIRTH"
                    ,"GLOBAL_PERSON_ID"
                    ,"COORD_BEN_MED_PL_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_IDENT"
                    ,"COORD_BEN_MED_EXT_ER"
                    ,"COORD_BEN_MED_CVG_STRT_DT"
                    ,"COORD_BEN_MED_CVG_END_DT"
                    ,"PARTY_ID"
                    ,"NPW_NUMBER"
                    ,"CURRENT_NPW_FLAG"
                    ,"GLOBAL_NAME"
                    ,"LOCAL_NAME"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'N' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "STG"."STG_EBS_PER_ALL_PEOPLE_F" S
                WHERE NOT EXISTS(SELECT 1 FROM "HSTG"."HSTG_EBS_PER_ALL_PEOPLE_F" H WHERE H.OMD_CURRENT_RECORD_INDICATOR = 'Y' AND OMD_IS_RECORD_DELETED = 'N' AND H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)



            /* Step 3:  IMPORT DELETED RECORDS FROM HISTORY TO HISTORY */
                INSERT INTO "HSTG"."HSTG_EBS_PER_ALL_PEOPLE_F"
                (
                    "PERSON_ID"
                    ,"EFFECTIVE_START_DATE"
                    ,"EFFECTIVE_END_DATE"
                    ,"BUSINESS_GROUP_ID"
                    ,"PERSON_TYPE_ID"
                    ,"LAST_NAME"
                    ,"START_DATE"
                    ,"APPLICANT_NUMBER"
                    ,"BACKGROUND_CHECK_STATUS"
                    ,"BACKGROUND_DATE_CHECK"
                    ,"BLOOD_TYPE"
                    ,"COMMENT_ID"
                    ,"CORRESPONDENCE_LANGUAGE"
                    ,"CURRENT_APPLICANT_FLAG"
                    ,"CURRENT_EMP_OR_APL_FLAG"
                    ,"CURRENT_EMPLOYEE_FLAG"
                    ,"DATE_EMPLOYEE_DATA_VERIFIED"
                    ,"DATE_OF_BIRTH"
                    ,"EMAIL_ADDRESS"
                    ,"EMPLOYEE_NUMBER"
                    ,"EXPENSE_CHECK_SEND_TO_ADDRESS"
                    ,"FAST_PATH_EMPLOYEE"
                    ,"FIRST_NAME"
                    ,"FTE_CAPACITY"
                    ,"FULL_NAME"
                    ,"HOLD_APPLICANT_DATE_UNTIL"
                    ,"HONORS"
                    ,"INTERNAL_LOCATION"
                    ,"KNOWN_AS"
                    ,"LAST_MEDICAL_TEST_BY"
                    ,"LAST_MEDICAL_TEST_DATE"
                    ,"MAILSTOP"
                    ,"MARITAL_STATUS"
                    ,"MIDDLE_NAMES"
                    ,"NATIONALITY"
                    ,"NATIONAL_IDENTIFIER"
                    ,"OFFICE_NUMBER"
                    ,"ON_MILITARY_SERVICE"
                    ,"ORDER_NAME"
                    ,"PRE_NAME_ADJUNCT"
                    ,"PREVIOUS_LAST_NAME"
                    ,"PROJECTED_START_DATE"
                    ,"REHIRE_AUTHORIZOR"
                    ,"REHIRE_REASON"
                    ,"REHIRE_RECOMMENDATION"
                    ,"RESUME_EXISTS"
                    ,"RESUME_LAST_UPDATED"
                    ,"REGISTERED_DISABLED_FLAG"
                    ,"SECOND_PASSPORT_EXISTS"
                    ,"SEX"
                    ,"STUDENT_STATUS"
                    ,"SUFFIX"
                    ,"TITLE"
                    ,"VENDOR_ID"
                    ,"WORK_SCHEDULE"
                    ,"WORK_TELEPHONE"
                    ,"COORD_BEN_MED_PLN_NO"
                    ,"COORD_BEN_NO_CVG_FLAG"
                    ,"DPDNT_ADOPTION_DATE"
                    ,"DPDNT_VLNTRY_SVCE_FLAG"
                    ,"RECEIPT_OF_DEATH_CERT_DATE"
                    ,"USES_TOBACCO_FLAG"
                    ,"BENEFIT_GROUP_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"ATTRIBUTE21"
                    ,"ATTRIBUTE22"
                    ,"ATTRIBUTE23"
                    ,"ATTRIBUTE24"
                    ,"ATTRIBUTE25"
                    ,"ATTRIBUTE26"
                    ,"ATTRIBUTE27"
                    ,"ATTRIBUTE28"
                    ,"ATTRIBUTE29"
                    ,"ATTRIBUTE30"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATED_BY"
                    ,"CREATION_DATE"
                    ,"PER_INFORMATION_CATEGORY"
                    ,"PER_INFORMATION1"
                    ,"PER_INFORMATION2"
                    ,"PER_INFORMATION3"
                    ,"PER_INFORMATION4"
                    ,"PER_INFORMATION5"
                    ,"PER_INFORMATION6"
                    ,"PER_INFORMATION7"
                    ,"PER_INFORMATION8"
                    ,"PER_INFORMATION9"
                    ,"PER_INFORMATION10"
                    ,"PER_INFORMATION11"
                    ,"PER_INFORMATION12"
                    ,"PER_INFORMATION13"
                    ,"PER_INFORMATION14"
                    ,"PER_INFORMATION15"
                    ,"PER_INFORMATION16"
                    ,"PER_INFORMATION17"
                    ,"PER_INFORMATION18"
                    ,"PER_INFORMATION19"
                    ,"PER_INFORMATION20"
                    ,"PER_INFORMATION21"
                    ,"PER_INFORMATION22"
                    ,"PER_INFORMATION23"
                    ,"PER_INFORMATION24"
                    ,"PER_INFORMATION25"
                    ,"PER_INFORMATION26"
                    ,"PER_INFORMATION27"
                    ,"PER_INFORMATION28"
                    ,"PER_INFORMATION29"
                    ,"PER_INFORMATION30"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"DATE_OF_DEATH"
                    ,"ORIGINAL_DATE_OF_HIRE"
                    ,"TOWN_OF_BIRTH"
                    ,"REGION_OF_BIRTH"
                    ,"COUNTRY_OF_BIRTH"
                    ,"GLOBAL_PERSON_ID"
                    ,"COORD_BEN_MED_PL_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_IDENT"
                    ,"COORD_BEN_MED_EXT_ER"
                    ,"COORD_BEN_MED_CVG_STRT_DT"
                    ,"COORD_BEN_MED_CVG_END_DT"
                    ,"PARTY_ID"
                    ,"NPW_NUMBER"
                    ,"CURRENT_NPW_FLAG"
                    ,"GLOBAL_NAME"
                    ,"LOCAL_NAME"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "PERSON_ID"
                    ,"EFFECTIVE_START_DATE"
                    ,"EFFECTIVE_END_DATE"
                    ,"BUSINESS_GROUP_ID"
                    ,"PERSON_TYPE_ID"
                    ,"LAST_NAME"
                    ,"START_DATE"
                    ,"APPLICANT_NUMBER"
                    ,"BACKGROUND_CHECK_STATUS"
                    ,"BACKGROUND_DATE_CHECK"
                    ,"BLOOD_TYPE"
                    ,"COMMENT_ID"
                    ,"CORRESPONDENCE_LANGUAGE"
                    ,"CURRENT_APPLICANT_FLAG"
                    ,"CURRENT_EMP_OR_APL_FLAG"
                    ,"CURRENT_EMPLOYEE_FLAG"
                    ,"DATE_EMPLOYEE_DATA_VERIFIED"
                    ,"DATE_OF_BIRTH"
                    ,"EMAIL_ADDRESS"
                    ,"EMPLOYEE_NUMBER"
                    ,"EXPENSE_CHECK_SEND_TO_ADDRESS"
                    ,"FAST_PATH_EMPLOYEE"
                    ,"FIRST_NAME"
                    ,"FTE_CAPACITY"
                    ,"FULL_NAME"
                    ,"HOLD_APPLICANT_DATE_UNTIL"
                    ,"HONORS"
                    ,"INTERNAL_LOCATION"
                    ,"KNOWN_AS"
                    ,"LAST_MEDICAL_TEST_BY"
                    ,"LAST_MEDICAL_TEST_DATE"
                    ,"MAILSTOP"
                    ,"MARITAL_STATUS"
                    ,"MIDDLE_NAMES"
                    ,"NATIONALITY"
                    ,"NATIONAL_IDENTIFIER"
                    ,"OFFICE_NUMBER"
                    ,"ON_MILITARY_SERVICE"
                    ,"ORDER_NAME"
                    ,"PRE_NAME_ADJUNCT"
                    ,"PREVIOUS_LAST_NAME"
                    ,"PROJECTED_START_DATE"
                    ,"REHIRE_AUTHORIZOR"
                    ,"REHIRE_REASON"
                    ,"REHIRE_RECOMMENDATION"
                    ,"RESUME_EXISTS"
                    ,"RESUME_LAST_UPDATED"
                    ,"REGISTERED_DISABLED_FLAG"
                    ,"SECOND_PASSPORT_EXISTS"
                    ,"SEX"
                    ,"STUDENT_STATUS"
                    ,"SUFFIX"
                    ,"TITLE"
                    ,"VENDOR_ID"
                    ,"WORK_SCHEDULE"
                    ,"WORK_TELEPHONE"
                    ,"COORD_BEN_MED_PLN_NO"
                    ,"COORD_BEN_NO_CVG_FLAG"
                    ,"DPDNT_ADOPTION_DATE"
                    ,"DPDNT_VLNTRY_SVCE_FLAG"
                    ,"RECEIPT_OF_DEATH_CERT_DATE"
                    ,"USES_TOBACCO_FLAG"
                    ,"BENEFIT_GROUP_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"ATTRIBUTE21"
                    ,"ATTRIBUTE22"
                    ,"ATTRIBUTE23"
                    ,"ATTRIBUTE24"
                    ,"ATTRIBUTE25"
                    ,"ATTRIBUTE26"
                    ,"ATTRIBUTE27"
                    ,"ATTRIBUTE28"
                    ,"ATTRIBUTE29"
                    ,"ATTRIBUTE30"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATED_BY"
                    ,"CREATION_DATE"
                    ,"PER_INFORMATION_CATEGORY"
                    ,"PER_INFORMATION1"
                    ,"PER_INFORMATION2"
                    ,"PER_INFORMATION3"
                    ,"PER_INFORMATION4"
                    ,"PER_INFORMATION5"
                    ,"PER_INFORMATION6"
                    ,"PER_INFORMATION7"
                    ,"PER_INFORMATION8"
                    ,"PER_INFORMATION9"
                    ,"PER_INFORMATION10"
                    ,"PER_INFORMATION11"
                    ,"PER_INFORMATION12"
                    ,"PER_INFORMATION13"
                    ,"PER_INFORMATION14"
                    ,"PER_INFORMATION15"
                    ,"PER_INFORMATION16"
                    ,"PER_INFORMATION17"
                    ,"PER_INFORMATION18"
                    ,"PER_INFORMATION19"
                    ,"PER_INFORMATION20"
                    ,"PER_INFORMATION21"
                    ,"PER_INFORMATION22"
                    ,"PER_INFORMATION23"
                    ,"PER_INFORMATION24"
                    ,"PER_INFORMATION25"
                    ,"PER_INFORMATION26"
                    ,"PER_INFORMATION27"
                    ,"PER_INFORMATION28"
                    ,"PER_INFORMATION29"
                    ,"PER_INFORMATION30"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"DATE_OF_DEATH"
                    ,"ORIGINAL_DATE_OF_HIRE"
                    ,"TOWN_OF_BIRTH"
                    ,"REGION_OF_BIRTH"
                    ,"COUNTRY_OF_BIRTH"
                    ,"GLOBAL_PERSON_ID"
                    ,"COORD_BEN_MED_PL_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_IDENT"
                    ,"COORD_BEN_MED_EXT_ER"
                    ,"COORD_BEN_MED_CVG_STRT_DT"
                    ,"COORD_BEN_MED_CVG_END_DT"
                    ,"PARTY_ID"
                    ,"NPW_NUMBER"
                    ,"CURRENT_NPW_FLAG"
                    ,"GLOBAL_NAME"
                    ,"LOCAL_NAME"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'Y' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "HSTG"."HSTG_EBS_PER_ALL_PEOPLE_F" H
                WHERE NOT EXISTS (SELECT 1 FROM "STG"."STG_EBS_PER_ALL_PEOPLE_F" S WHERE 
                    COALESCE(H."PERSON_ID",0) = COALESCE(S."PERSON_ID",0)
                    AND COALESCE(H."EFFECTIVE_START_DATE",'1900-01-01 00:00:00') = COALESCE(S."EFFECTIVE_START_DATE",'1900-01-01 00:00:00')
                    AND COALESCE(H."EFFECTIVE_END_DATE",'1900-01-01 00:00:00') = COALESCE(S."EFFECTIVE_END_DATE",'1900-01-01 00:00:00')
                )
                    AND H.OMD_CURRENT_RECORD_INDICATOR='Y' AND H.OMD_IS_RECORD_DELETED='N'


            /* Step 4:  UPDATE OMD_CURRENT_RECORD_INDICATOR FLAG*/
				UPDATE  H 				SET OMD_CURRENT_RECORD_INDICATOR='N'				FROM "HSTG"."HSTG_EBS_PER_ALL_PEOPLE_F" H					Join "STG"."STG_EBS_PER_ALL_PEOPLE_F" S						On H.PERSON_ID= S.PERSON_ID						And H.EFFECTIVE_START_DATE= S.EFFECTIVE_START_DATE						And H.EFFECTIVE_END_DATE= S.EFFECTIVE_END_DATE				WHERE "OMD_IS_RECORD_DELETED" = 'N'						AND H.OMD_HASH_FULL_RECORD <> S.OMD_HASH_FULL_RECORD
            
            --    UPDATE  H SET OMD_CURRENT_RECORD_INDICATOR='N' 
            --    FROM "HSTG"."HSTG_EBS_PER_ALL_PEOPLE_F" H
            --    WHERE "OMD_IS_RECORD_DELETED" = 'Y' AND EXISTS (SELECT 1 FROM "STG"."STG_EBS_PER_ALL_PEOPLE_F" S WHERE 
            --        COALESCE(H."PERSON_ID",0) = COALESCE(S."PERSON_ID",0)
            --        AND COALESCE(H."EFFECTIVE_START_DATE",'1900-01-01 00:00:00') = COALESCE(S."EFFECTIVE_START_DATE",'1900-01-01 00:00:00')
            --        AND COALESCE(H."EFFECTIVE_END_DATE",'1900-01-01 00:00:00') = COALESCE(S."EFFECTIVE_END_DATE",'1900-01-01 00:00:00')
            --)
            
            END
        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
/**********************************************************************************************************************************************************************************************************/
