

CREATE PROCEDURE [HSTG].[LOAD_HSTG_CA_INLOCAT]
AS 
BEGIN


    SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        16/09/2022 6:41:36 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "HSTG"."LOAD_HSTG_CA_INLOCAT";
    
    Source                    Destination              
    ----------------------    ----------------------- 
    STG"."STG_CA_INLOCAT"    "HSTG"."HSTG_CA_INLOCAT" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-09-16    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  CALL CHECK RECORD COUNT FROM STAGING TABLE*/
        DECLARE @ROW_COUNT BIGINT = 0;
        SELECT @ROW_COUNT = COUNT_BIG(*)  FROM  "STG"."STG_CA_INLOCAT"
        IF (@ROW_COUNT > 0)
        BEGIN
        /* Step 2:  IMPORT FROM STAGING TO HISTORY */
                INSERT INTO "HSTG"."HSTG_CA_INLOCAT"
                (
                    "Item Code"
                    ,"Loc"
                    ,"Value @ Cost"
                    ,"Stock Qty"
                    ,"Loc Lst Buy"
                    ,"MinLev"
                    ,"MaxLev"
                    ,"Commit Qty"
                    ,"Po Qty"
                    ,"Last Sale"
                    ,"2ndLstSale"
                    ,"Sales 1"
                    ,"Sales 2"
                    ,"Sales 3"
                    ,"Sales 4"
                    ,"Sales 5"
                    ,"Sales 6"
                    ,"Sales 7"
                    ,"Sales 8"
                    ,"Sales 9"
                    ,"Sales 10"
                    ,"Sales 11"
                    ,"Sales 12"
                    ,"Sales 13"
                    ,"Sales 14"
                    ,"Sales 15"
                    ,"Sales 16"
                    ,"Sales 17"
                    ,"Sales 18"
                    ,"Sales 19"
                    ,"Sales 20"
                    ,"Sales 21"
                    ,"Sales 22"
                    ,"Sales 23"
                    ,"Sales 24"
                    ,"Purch 1"
                    ,"Purch 2"
                    ,"Purch 3"
                    ,"Purch 4"
                    ,"Purch 5"
                    ,"Purch 6"
                    ,"Purch 7"
                    ,"Purch 8"
                    ,"Purch 9"
                    ,"Purch 10"
                    ,"Purch 11"
                    ,"Purch 12"
                    ,"Purch 13"
                    ,"Purch 14"
                    ,"Purch 15"
                    ,"Purch 16"
                    ,"Purch 17"
                    ,"Purch 18"
                    ,"Purch 19"
                    ,"Purch 20"
                    ,"Purch 21"
                    ,"Purch 22"
                    ,"Purch 23"
                    ,"Purch 24"
                    ,"Cogs 1"
                    ,"Cogs 2"
                    ,"Cogs 3"
                    ,"Cogs 4"
                    ,"Cogs 5"
                    ,"Cogs 6"
                    ,"Cogs 7"
                    ,"Cogs 8"
                    ,"Cogs 9"
                    ,"Cogs 10"
                    ,"Cogs 11"
                    ,"Cogs 12"
                    ,"Cogs 13"
                    ,"Cogs 14"
                    ,"Cogs 15"
                    ,"Cogs 16"
                    ,"Cogs 17"
                    ,"Cogs 18"
                    ,"Cogs 19"
                    ,"Cogs 20"
                    ,"Cogs 21"
                    ,"Cogs 22"
                    ,"Cogs 23"
                    ,"Cogs 24"
                    ,"Sale Qty 1"
                    ,"Sale Qty 2"
                    ,"Sale Qty 3"
                    ,"Sale Qty 4"
                    ,"Sale Qty 5"
                    ,"Sale Qty 6"
                    ,"Sale Qty 7"
                    ,"Sale Qty 8"
                    ,"Sale Qty 9"
                    ,"Sale Qty 10"
                    ,"Sale Qty 11"
                    ,"Sale Qty 12"
                    ,"Sale Qty 13"
                    ,"Sale Qty 14"
                    ,"Sale Qty 15"
                    ,"Sale Qty 16"
                    ,"Sale Qty 17"
                    ,"Sale Qty 18"
                    ,"Sale Qty 19"
                    ,"Sale Qty 20"
                    ,"Sale Qty 21"
                    ,"Sale Qty 22"
                    ,"Sale Qty 23"
                    ,"Sale Qty 24"
                    ,"Last Stake"
                    ,"LstStk Qoh"
                    ,"Curr Stake"
                    ,"CurStk QOH"
                    ,"Frozen Qoh"
                    ,"Incat"
                    ,"Last Purch"
                    ,"StockTurns"
                    ,"Gross Mgn"
                    ,"Gmroi"
                    ,"LSup"
                    ,"PurQty 1"
                    ,"PurQty 2"
                    ,"PurQty 3"
                    ,"PurQty 4"
                    ,"PurQty 5"
                    ,"PurQty 6"
                    ,"PurQty 7"
                    ,"PurQty 8"
                    ,"PurQty 9"
                    ,"PurQty10"
                    ,"PurQty11"
                    ,"PurQty12"
                    ,"PurQty13"
                    ,"PurQty14"
                    ,"PurQty15"
                    ,"PurQty16"
                    ,"PurQty17"
                    ,"PurQty18"
                    ,"PurQty19"
                    ,"PurQty20"
                    ,"PurQty21"
                    ,"PurQty22"
                    ,"PurQty23"
                    ,"PurQty24"
                    ,"Frozen Vac"
                    ,"FrozLstBuy"
                    ,"Border Qty"
                    ,"P"
                    ,"S"
                    ,"O"
                    ,"Qoh Eop"
                    ,"Vac Eop"
                    ,"ObsFlagUpd"
                    ,"1st Purch"
                    ,"TrOpen Qty"
                    ,"PerfSetDat"
                    ,"TfrUnaccQty"
                    ,"LowMin"
                    ,"GrniBal Qty"
                    ,"GrniBal Val"
                    ,"GsniBal Qty"
                    ,"GsniBal Val"
                    ,"Start Date"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "Item Code"
                    ,"Loc"
                    ,"Value @ Cost"
                    ,"Stock Qty"
                    ,"Loc Lst Buy"
                    ,"MinLev"
                    ,"MaxLev"
                    ,"Commit Qty"
                    ,"Po Qty"
                    ,"Last Sale"
                    ,"2ndLstSale"
                    ,"Sales 1"
                    ,"Sales 2"
                    ,"Sales 3"
                    ,"Sales 4"
                    ,"Sales 5"
                    ,"Sales 6"
                    ,"Sales 7"
                    ,"Sales 8"
                    ,"Sales 9"
                    ,"Sales 10"
                    ,"Sales 11"
                    ,"Sales 12"
                    ,"Sales 13"
                    ,"Sales 14"
                    ,"Sales 15"
                    ,"Sales 16"
                    ,"Sales 17"
                    ,"Sales 18"
                    ,"Sales 19"
                    ,"Sales 20"
                    ,"Sales 21"
                    ,"Sales 22"
                    ,"Sales 23"
                    ,"Sales 24"
                    ,"Purch 1"
                    ,"Purch 2"
                    ,"Purch 3"
                    ,"Purch 4"
                    ,"Purch 5"
                    ,"Purch 6"
                    ,"Purch 7"
                    ,"Purch 8"
                    ,"Purch 9"
                    ,"Purch 10"
                    ,"Purch 11"
                    ,"Purch 12"
                    ,"Purch 13"
                    ,"Purch 14"
                    ,"Purch 15"
                    ,"Purch 16"
                    ,"Purch 17"
                    ,"Purch 18"
                    ,"Purch 19"
                    ,"Purch 20"
                    ,"Purch 21"
                    ,"Purch 22"
                    ,"Purch 23"
                    ,"Purch 24"
                    ,"Cogs 1"
                    ,"Cogs 2"
                    ,"Cogs 3"
                    ,"Cogs 4"
                    ,"Cogs 5"
                    ,"Cogs 6"
                    ,"Cogs 7"
                    ,"Cogs 8"
                    ,"Cogs 9"
                    ,"Cogs 10"
                    ,"Cogs 11"
                    ,"Cogs 12"
                    ,"Cogs 13"
                    ,"Cogs 14"
                    ,"Cogs 15"
                    ,"Cogs 16"
                    ,"Cogs 17"
                    ,"Cogs 18"
                    ,"Cogs 19"
                    ,"Cogs 20"
                    ,"Cogs 21"
                    ,"Cogs 22"
                    ,"Cogs 23"
                    ,"Cogs 24"
                    ,"Sale Qty 1"
                    ,"Sale Qty 2"
                    ,"Sale Qty 3"
                    ,"Sale Qty 4"
                    ,"Sale Qty 5"
                    ,"Sale Qty 6"
                    ,"Sale Qty 7"
                    ,"Sale Qty 8"
                    ,"Sale Qty 9"
                    ,"Sale Qty 10"
                    ,"Sale Qty 11"
                    ,"Sale Qty 12"
                    ,"Sale Qty 13"
                    ,"Sale Qty 14"
                    ,"Sale Qty 15"
                    ,"Sale Qty 16"
                    ,"Sale Qty 17"
                    ,"Sale Qty 18"
                    ,"Sale Qty 19"
                    ,"Sale Qty 20"
                    ,"Sale Qty 21"
                    ,"Sale Qty 22"
                    ,"Sale Qty 23"
                    ,"Sale Qty 24"
                    ,"Last Stake"
                    ,"LstStk Qoh"
                    ,"Curr Stake"
                    ,"CurStk QOH"
                    ,"Frozen Qoh"
                    ,"Incat"
                    ,"Last Purch"
                    ,"StockTurns"
                    ,"Gross Mgn"
                    ,"Gmroi"
                    ,"LSup"
                    ,"PurQty 1"
                    ,"PurQty 2"
                    ,"PurQty 3"
                    ,"PurQty 4"
                    ,"PurQty 5"
                    ,"PurQty 6"
                    ,"PurQty 7"
                    ,"PurQty 8"
                    ,"PurQty 9"
                    ,"PurQty10"
                    ,"PurQty11"
                    ,"PurQty12"
                    ,"PurQty13"
                    ,"PurQty14"
                    ,"PurQty15"
                    ,"PurQty16"
                    ,"PurQty17"
                    ,"PurQty18"
                    ,"PurQty19"
                    ,"PurQty20"
                    ,"PurQty21"
                    ,"PurQty22"
                    ,"PurQty23"
                    ,"PurQty24"
                    ,"Frozen Vac"
                    ,"FrozLstBuy"
                    ,"Border Qty"
                    ,"P"
                    ,"S"
                    ,"O"
                    ,"Qoh Eop"
                    ,"Vac Eop"
                    ,"ObsFlagUpd"
                    ,"1st Purch"
                    ,"TrOpen Qty"
                    ,"PerfSetDat"
                    ,"TfrUnaccQty"
                    ,"LowMin"
                    ,"GrniBal Qty"
                    ,"GrniBal Val"
                    ,"GsniBal Qty"
                    ,"GsniBal Val"
                    ,"Start Date"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'N' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "STG"."STG_CA_INLOCAT" S
                WHERE NOT EXISTS(SELECT 1 FROM "HSTG"."HSTG_CA_INLOCAT" H WHERE H.OMD_CURRENT_RECORD_INDICATOR = 'Y' AND OMD_IS_RECORD_DELETED = 'N' AND H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)



            /* Step 3:  IMPORT DELETED RECORDS FROM HISTORY TO HISTORY */
                INSERT INTO "HSTG"."HSTG_CA_INLOCAT"
                (
                    "Item Code"
                    ,"Loc"
                    ,"Value @ Cost"
                    ,"Stock Qty"
                    ,"Loc Lst Buy"
                    ,"MinLev"
                    ,"MaxLev"
                    ,"Commit Qty"
                    ,"Po Qty"
                    ,"Last Sale"
                    ,"2ndLstSale"
                    ,"Sales 1"
                    ,"Sales 2"
                    ,"Sales 3"
                    ,"Sales 4"
                    ,"Sales 5"
                    ,"Sales 6"
                    ,"Sales 7"
                    ,"Sales 8"
                    ,"Sales 9"
                    ,"Sales 10"
                    ,"Sales 11"
                    ,"Sales 12"
                    ,"Sales 13"
                    ,"Sales 14"
                    ,"Sales 15"
                    ,"Sales 16"
                    ,"Sales 17"
                    ,"Sales 18"
                    ,"Sales 19"
                    ,"Sales 20"
                    ,"Sales 21"
                    ,"Sales 22"
                    ,"Sales 23"
                    ,"Sales 24"
                    ,"Purch 1"
                    ,"Purch 2"
                    ,"Purch 3"
                    ,"Purch 4"
                    ,"Purch 5"
                    ,"Purch 6"
                    ,"Purch 7"
                    ,"Purch 8"
                    ,"Purch 9"
                    ,"Purch 10"
                    ,"Purch 11"
                    ,"Purch 12"
                    ,"Purch 13"
                    ,"Purch 14"
                    ,"Purch 15"
                    ,"Purch 16"
                    ,"Purch 17"
                    ,"Purch 18"
                    ,"Purch 19"
                    ,"Purch 20"
                    ,"Purch 21"
                    ,"Purch 22"
                    ,"Purch 23"
                    ,"Purch 24"
                    ,"Cogs 1"
                    ,"Cogs 2"
                    ,"Cogs 3"
                    ,"Cogs 4"
                    ,"Cogs 5"
                    ,"Cogs 6"
                    ,"Cogs 7"
                    ,"Cogs 8"
                    ,"Cogs 9"
                    ,"Cogs 10"
                    ,"Cogs 11"
                    ,"Cogs 12"
                    ,"Cogs 13"
                    ,"Cogs 14"
                    ,"Cogs 15"
                    ,"Cogs 16"
                    ,"Cogs 17"
                    ,"Cogs 18"
                    ,"Cogs 19"
                    ,"Cogs 20"
                    ,"Cogs 21"
                    ,"Cogs 22"
                    ,"Cogs 23"
                    ,"Cogs 24"
                    ,"Sale Qty 1"
                    ,"Sale Qty 2"
                    ,"Sale Qty 3"
                    ,"Sale Qty 4"
                    ,"Sale Qty 5"
                    ,"Sale Qty 6"
                    ,"Sale Qty 7"
                    ,"Sale Qty 8"
                    ,"Sale Qty 9"
                    ,"Sale Qty 10"
                    ,"Sale Qty 11"
                    ,"Sale Qty 12"
                    ,"Sale Qty 13"
                    ,"Sale Qty 14"
                    ,"Sale Qty 15"
                    ,"Sale Qty 16"
                    ,"Sale Qty 17"
                    ,"Sale Qty 18"
                    ,"Sale Qty 19"
                    ,"Sale Qty 20"
                    ,"Sale Qty 21"
                    ,"Sale Qty 22"
                    ,"Sale Qty 23"
                    ,"Sale Qty 24"
                    ,"Last Stake"
                    ,"LstStk Qoh"
                    ,"Curr Stake"
                    ,"CurStk QOH"
                    ,"Frozen Qoh"
                    ,"Incat"
                    ,"Last Purch"
                    ,"StockTurns"
                    ,"Gross Mgn"
                    ,"Gmroi"
                    ,"LSup"
                    ,"PurQty 1"
                    ,"PurQty 2"
                    ,"PurQty 3"
                    ,"PurQty 4"
                    ,"PurQty 5"
                    ,"PurQty 6"
                    ,"PurQty 7"
                    ,"PurQty 8"
                    ,"PurQty 9"
                    ,"PurQty10"
                    ,"PurQty11"
                    ,"PurQty12"
                    ,"PurQty13"
                    ,"PurQty14"
                    ,"PurQty15"
                    ,"PurQty16"
                    ,"PurQty17"
                    ,"PurQty18"
                    ,"PurQty19"
                    ,"PurQty20"
                    ,"PurQty21"
                    ,"PurQty22"
                    ,"PurQty23"
                    ,"PurQty24"
                    ,"Frozen Vac"
                    ,"FrozLstBuy"
                    ,"Border Qty"
                    ,"P"
                    ,"S"
                    ,"O"
                    ,"Qoh Eop"
                    ,"Vac Eop"
                    ,"ObsFlagUpd"
                    ,"1st Purch"
                    ,"TrOpen Qty"
                    ,"PerfSetDat"
                    ,"TfrUnaccQty"
                    ,"LowMin"
                    ,"GrniBal Qty"
                    ,"GrniBal Val"
                    ,"GsniBal Qty"
                    ,"GsniBal Val"
                    ,"Start Date"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,"OMD_IS_RECORD_DELETED"
                    ,"OMD_CURRENT_RECORD_INDICATOR"
                )
                SELECT 
                    "Item Code"
                    ,"Loc"
                    ,"Value @ Cost"
                    ,"Stock Qty"
                    ,"Loc Lst Buy"
                    ,"MinLev"
                    ,"MaxLev"
                    ,"Commit Qty"
                    ,"Po Qty"
                    ,"Last Sale"
                    ,"2ndLstSale"
                    ,"Sales 1"
                    ,"Sales 2"
                    ,"Sales 3"
                    ,"Sales 4"
                    ,"Sales 5"
                    ,"Sales 6"
                    ,"Sales 7"
                    ,"Sales 8"
                    ,"Sales 9"
                    ,"Sales 10"
                    ,"Sales 11"
                    ,"Sales 12"
                    ,"Sales 13"
                    ,"Sales 14"
                    ,"Sales 15"
                    ,"Sales 16"
                    ,"Sales 17"
                    ,"Sales 18"
                    ,"Sales 19"
                    ,"Sales 20"
                    ,"Sales 21"
                    ,"Sales 22"
                    ,"Sales 23"
                    ,"Sales 24"
                    ,"Purch 1"
                    ,"Purch 2"
                    ,"Purch 3"
                    ,"Purch 4"
                    ,"Purch 5"
                    ,"Purch 6"
                    ,"Purch 7"
                    ,"Purch 8"
                    ,"Purch 9"
                    ,"Purch 10"
                    ,"Purch 11"
                    ,"Purch 12"
                    ,"Purch 13"
                    ,"Purch 14"
                    ,"Purch 15"
                    ,"Purch 16"
                    ,"Purch 17"
                    ,"Purch 18"
                    ,"Purch 19"
                    ,"Purch 20"
                    ,"Purch 21"
                    ,"Purch 22"
                    ,"Purch 23"
                    ,"Purch 24"
                    ,"Cogs 1"
                    ,"Cogs 2"
                    ,"Cogs 3"
                    ,"Cogs 4"
                    ,"Cogs 5"
                    ,"Cogs 6"
                    ,"Cogs 7"
                    ,"Cogs 8"
                    ,"Cogs 9"
                    ,"Cogs 10"
                    ,"Cogs 11"
                    ,"Cogs 12"
                    ,"Cogs 13"
                    ,"Cogs 14"
                    ,"Cogs 15"
                    ,"Cogs 16"
                    ,"Cogs 17"
                    ,"Cogs 18"
                    ,"Cogs 19"
                    ,"Cogs 20"
                    ,"Cogs 21"
                    ,"Cogs 22"
                    ,"Cogs 23"
                    ,"Cogs 24"
                    ,"Sale Qty 1"
                    ,"Sale Qty 2"
                    ,"Sale Qty 3"
                    ,"Sale Qty 4"
                    ,"Sale Qty 5"
                    ,"Sale Qty 6"
                    ,"Sale Qty 7"
                    ,"Sale Qty 8"
                    ,"Sale Qty 9"
                    ,"Sale Qty 10"
                    ,"Sale Qty 11"
                    ,"Sale Qty 12"
                    ,"Sale Qty 13"
                    ,"Sale Qty 14"
                    ,"Sale Qty 15"
                    ,"Sale Qty 16"
                    ,"Sale Qty 17"
                    ,"Sale Qty 18"
                    ,"Sale Qty 19"
                    ,"Sale Qty 20"
                    ,"Sale Qty 21"
                    ,"Sale Qty 22"
                    ,"Sale Qty 23"
                    ,"Sale Qty 24"
                    ,"Last Stake"
                    ,"LstStk Qoh"
                    ,"Curr Stake"
                    ,"CurStk QOH"
                    ,"Frozen Qoh"
                    ,"Incat"
                    ,"Last Purch"
                    ,"StockTurns"
                    ,"Gross Mgn"
                    ,"Gmroi"
                    ,"LSup"
                    ,"PurQty 1"
                    ,"PurQty 2"
                    ,"PurQty 3"
                    ,"PurQty 4"
                    ,"PurQty 5"
                    ,"PurQty 6"
                    ,"PurQty 7"
                    ,"PurQty 8"
                    ,"PurQty 9"
                    ,"PurQty10"
                    ,"PurQty11"
                    ,"PurQty12"
                    ,"PurQty13"
                    ,"PurQty14"
                    ,"PurQty15"
                    ,"PurQty16"
                    ,"PurQty17"
                    ,"PurQty18"
                    ,"PurQty19"
                    ,"PurQty20"
                    ,"PurQty21"
                    ,"PurQty22"
                    ,"PurQty23"
                    ,"PurQty24"
                    ,"Frozen Vac"
                    ,"FrozLstBuy"
                    ,"Border Qty"
                    ,"P"
                    ,"S"
                    ,"O"
                    ,"Qoh Eop"
                    ,"Vac Eop"
                    ,"ObsFlagUpd"
                    ,"1st Purch"
                    ,"TrOpen Qty"
                    ,"PerfSetDat"
                    ,"TfrUnaccQty"
                    ,"LowMin"
                    ,"GrniBal Qty"
                    ,"GrniBal Val"
                    ,"GsniBal Qty"
                    ,"GsniBal Val"
                    ,"Start Date"
                    ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                    ,'Y' AS "OMD_IS_RECORD_DELETED"
                    ,'Y' AS "OMD_CURRENT_RECORD_INDICATOR"
                FROM "HSTG"."HSTG_CA_INLOCAT" H
                WHERE NOT EXISTS (SELECT 1 FROM "STG"."STG_CA_INLOCAT" S WHERE 
                    COALESCE(H."ITEM CODE",'') = COALESCE(S."ITEM CODE",'')
                    AND COALESCE(H."LOC",0) = COALESCE(S."LOC",0)
                )
                    AND H.OMD_CURRENT_RECORD_INDICATOR='Y' AND H.OMD_IS_RECORD_DELETED='N'


            /* Step 4:  UPDATE OMD_CURRENT_RECORD_INDICATOR FLAG*/
                UPDATE  H SET OMD_CURRENT_RECORD_INDICATOR='N' 
                FROM "HSTG"."HSTG_CA_INLOCAT" H
                WHERE "OMD_IS_RECORD_DELETED" = 'N' AND NOT EXISTS (SELECT 1 FROM "STG"."STG_CA_INLOCAT" S WHERE H.OMD_HASH_FULL_RECORD = S.OMD_HASH_FULL_RECORD)
            
                UPDATE  H SET OMD_CURRENT_RECORD_INDICATOR='N' 
                FROM "HSTG"."HSTG_CA_INLOCAT" H
                WHERE "OMD_IS_RECORD_DELETED" = 'Y' AND EXISTS (SELECT 1 FROM "STG"."STG_CA_INLOCAT" S WHERE 
                    COALESCE(H."ITEM CODE",'') = COALESCE(S."ITEM CODE",'')
                    AND COALESCE(H."LOC",0) = COALESCE(S."LOC",0)
            )
            
            END
        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
