CREATE TABLE [STG].[STG_CA_SOCOMAST] (
    [So#]                  NVARCHAR (20)   NULL,
    [Co#]                  DECIMAL (36, 4) NULL,
    [Start Date]           DATETIME2 (7)   NULL,
    [STime]                TIME (7)        NULL,
    [Cust#]                DECIMAL (36, 4) NULL,
    [Order Date]           DATETIME2 (7)   NULL,
    [Customer Reference]   NVARCHAR (100)  NULL,
    [Deliv Date]           DATETIME2 (7)   NULL,
    [H]                    NVARCHAR (6)    NULL,
    [Spn]                  NVARCHAR (6)    NULL,
    [CusLnk]               DECIMAL (36, 4) NULL,
    [DelCod]               NVARCHAR (12)   NULL,
    [DelLnk]               DECIMAL (36, 4) NULL,
    [MesLnk]               DECIMAL (36, 4) NULL,
    [InsLnk]               DECIMAL (36, 4) NULL,
    [P]                    NVARCHAR (2)    NULL,
    [Order Value]          DECIMAL (36, 4) NULL,
    [T]                    NVARCHAR (2)    NULL,
    [Pr]                   DECIMAL (36, 4) NULL,
    [I]                    NVARCHAR (2)    NULL,
    [F]                    NVARCHAR (2)    NULL,
    [Disc Value]           DECIMAL (36, 4) NULL,
    [Loc]                  NVARCHAR (6)    NULL,
    [Gst Value]            DECIMAL (36, 4) NULL,
    [Short Message]        NVARCHAR (40)   NULL,
    [Short Delivery Instr] NVARCHAR (40)   NULL,
    [Req Ref]              NVARCHAR (60)   NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD] VARCHAR (1000)  NULL
);

