CREATE TABLE [STG].[STG_CA_DLMAST] (
    [Cust#]                   DECIMAL (36, 4) NULL,
    [Key]                     NVARCHAR (12)   NULL,
    [Customer Name]           NVARCHAR (120)  NULL,
    [Address Line 1]          NVARCHAR (120)  NULL,
    [Address Line 2]          NVARCHAR (120)  NULL,
    [Address Line 3]          NVARCHAR (80)   NULL,
    [Contact]                 NVARCHAR (60)   NULL,
    [Phone]                   NVARCHAR (28)   NULL,
    [Fax]                     NVARCHAR (28)   NULL,
    [Bal Future]              DECIMAL (36, 4) NULL,
    [BalCurrent]              DECIMAL (36, 4) NULL,
    [Bal 30Days]              DECIMAL (36, 4) NULL,
    [Bal 60Days]              DECIMAL (36, 4) NULL,
    [Bal 90Days]              DECIMAL (36, 4) NULL,
    [LastRcpVal]              DECIMAL (36, 4) NULL,
    [LstRcpDate]              DATETIME2 (7)   NULL,
    [Bnk]                     NVARCHAR (6)    NULL,
    [Bank Branch]             NVARCHAR (40)   NULL,
    [Cred Limit]              DECIMAL (36, 4) NULL,
    [S]                       NVARCHAR (2)    NULL,
    [W]                       NVARCHAR (20)   NULL,
    [Profile]                 NVARCHAR (24)   NULL,
    [Start Date]              DATETIME2 (7)   NULL,
    [Comment]                 NVARCHAR (80)   NULL,
    [Prc]                     NVARCHAR (6)    NULL,
    [CusTyp]                  NVARCHAR (12)   NULL,
    [Crl]                     NVARCHAR (6)    NULL,
    [Open Bal]                DECIMAL (36, 4) NULL,
    [Crmt]                    DECIMAL (36, 4) NULL,
    [InsLim]                  DECIMAL (36, 4) NULL,
    [TxCert]                  NVARCHAR (40)   NULL,
    [X]                       NVARCHAR (2)    NULL,
    [On Order]                DECIMAL (36, 4) NULL,
    [Sales 1]                 DECIMAL (36, 4) NULL,
    [Sales 2]                 DECIMAL (36, 4) NULL,
    [Sales 3]                 DECIMAL (36, 4) NULL,
    [Sales 4]                 DECIMAL (36, 4) NULL,
    [Sales 5]                 DECIMAL (36, 4) NULL,
    [Sales 6]                 DECIMAL (36, 4) NULL,
    [Sales 7]                 DECIMAL (36, 4) NULL,
    [Sales 8]                 DECIMAL (36, 4) NULL,
    [Sales 9]                 DECIMAL (36, 4) NULL,
    [Sales 10]                DECIMAL (36, 4) NULL,
    [Sales 11]                DECIMAL (36, 4) NULL,
    [Sales 12]                DECIMAL (36, 4) NULL,
    [Sales 13]                DECIMAL (36, 4) NULL,
    [Sales 14]                DECIMAL (36, 4) NULL,
    [Sales 15]                DECIMAL (36, 4) NULL,
    [Sales 16]                DECIMAL (36, 4) NULL,
    [Sales 17]                DECIMAL (36, 4) NULL,
    [Sales 18]                DECIMAL (36, 4) NULL,
    [Sales 19]                DECIMAL (36, 4) NULL,
    [Sales 20]                DECIMAL (36, 4) NULL,
    [Sales 21]                DECIMAL (36, 4) NULL,
    [Sales 22]                DECIMAL (36, 4) NULL,
    [Sales 23]                DECIMAL (36, 4) NULL,
    [Sales 24]                DECIMAL (36, 4) NULL,
    [Cogs 1]                  DECIMAL (36, 4) NULL,
    [Cogs 2]                  DECIMAL (36, 4) NULL,
    [Cogs 3]                  DECIMAL (36, 4) NULL,
    [Cogs 4]                  DECIMAL (36, 4) NULL,
    [Cogs 5]                  DECIMAL (36, 4) NULL,
    [Cogs 6]                  DECIMAL (36, 4) NULL,
    [Cogs 7]                  DECIMAL (36, 4) NULL,
    [Cogs 8]                  DECIMAL (36, 4) NULL,
    [Cogs 9]                  DECIMAL (36, 4) NULL,
    [Cogs 10]                 DECIMAL (36, 4) NULL,
    [Cogs 11]                 DECIMAL (36, 4) NULL,
    [Cogs 12]                 DECIMAL (36, 4) NULL,
    [Cogs 13]                 DECIMAL (36, 4) NULL,
    [Cogs 14]                 DECIMAL (36, 4) NULL,
    [Cogs 15]                 DECIMAL (36, 4) NULL,
    [Cogs 16]                 DECIMAL (36, 4) NULL,
    [Cogs 17]                 DECIMAL (36, 4) NULL,
    [Cogs 18]                 DECIMAL (36, 4) NULL,
    [Cogs 19]                 DECIMAL (36, 4) NULL,
    [Cogs 20]                 DECIMAL (36, 4) NULL,
    [Cogs 21]                 DECIMAL (36, 4) NULL,
    [Cogs 22]                 DECIMAL (36, 4) NULL,
    [Cogs 23]                 DECIMAL (36, 4) NULL,
    [Cogs 24]                 DECIMAL (36, 4) NULL,
    [Last Sale]               DATETIME2 (7)   NULL,
    [Spare Bal]               DECIMAL (36, 4) NULL,
    [DeliveryMeth]            NVARCHAR (24)   NULL,
    [C]                       NVARCHAR (32)   NULL,
    [Last Aged]               DATETIME2 (7)   NULL,
    [Stmt#]                   DECIMAL (36, 4) NULL,
    [Mobile]                  NVARCHAR (28)   NULL,
    [Pstcde]                  NVARCHAR (12)   NULL,
    [Acn]                     NVARCHAR (18)   NULL,
    [PrvYrSals5]              DECIMAL (36, 4) NULL,
    [PrvYrSals4]              DECIMAL (36, 4) NULL,
    [PrvYrSals3]              DECIMAL (36, 4) NULL,
    [PrvYrSals2]              DECIMAL (36, 4) NULL,
    [PrvYrCogs5]              DECIMAL (36, 4) NULL,
    [PrvYrCogs4]              DECIMAL (36, 4) NULL,
    [PrvYrCogs3]              DECIMAL (36, 4) NULL,
    [PrvYrCogs2]              DECIMAL (36, 4) NULL,
    [Comment2]                NVARCHAR (100)  NULL,
    [Email Contact]           NVARCHAR (400)  NULL,
    [R]                       NVARCHAR (100)  NULL,
    [P]                       NVARCHAR (100)  NULL,
    [H]                       NVARCHAR (100)  NULL,
    [M]                       NVARCHAR (100)  NULL,
    [N]                       NVARCHAR (100)  NULL,
    [G]                       NVARCHAR (100)  NULL,
    [O]                       NVARCHAR (100)  NULL,
    [F]                       NVARCHAR (100)  NULL,
    [D]                       NVARCHAR (100)  NULL,
    [A]                       NVARCHAR (100)  NULL,
    [Invoice Popup Message]   NVARCHAR (1000) NULL,
    [Debt Bal]                DECIMAL (36, 4) NULL,
    [Parm1]                   DECIMAL (36, 4) NULL,
    [I]                       NVARCHAR (2)    NULL,
    [Email Invoice]           NVARCHAR (500)  NULL,
    [T]                       NVARCHAR (500)  NULL,
    [Email Order Confimation] NVARCHAR (500)  NULL,
    [Email Quote]             NVARCHAR (500)  NULL,
    [DefDAd]                  NVARCHAR (12)   NULL,
    [OMD_INSERT_DATETIME]     DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]           VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD]    VARCHAR (1000)  NULL
);

