CREATE TABLE [STG].[STG_CA_SOMAST] (
    [So#]                     NVARCHAR (20)   NULL,
    [Cust#]                   DECIMAL (36, 4) NULL,
    [Order Date]              DATETIME2 (7)   NULL,
    [Customer Reference]      NVARCHAR (100)  NULL,
    [Deliv Date]              DATETIME2 (7)   NULL,
    [H]                       NVARCHAR (6)    NULL,
    [Spn]                     NVARCHAR (6)    NULL,
    [AdrCde]                  NVARCHAR (12)   NULL,
    [Delivery Name]           NVARCHAR (120)  NULL,
    [Delivery Address Line 1] NVARCHAR (120)  NULL,
    [Delivery Address Line 2] NVARCHAR (120)  NULL,
    [Delivery Address Line 3] NVARCHAR (80)   NULL,
    [Message]                 NVARCHAR (1000) NULL,
    [P]                       NVARCHAR (2)    NULL,
    [OV Gst Incl]             DECIMAL (36, 4) NULL,
    [Last Inv#]               DECIMAL (36, 4) NULL,
    [LstInvDate]              DATETIME2 (7)   NULL,
    [Inv Value]               NVARCHAR (10)   NULL,
    [T]                       NVARCHAR (2)    NULL,
    [S]                       NVARCHAR (2)    NULL,
    [Pr]                      DECIMAL (36, 4) NULL,
    [I]                       NVARCHAR (2)    NULL,
    [F]                       NVARCHAR (2)    NULL,
    [Req Ref]                 NVARCHAR (60)   NULL,
    [ProjPB]                  NVARCHAR (60)   NULL,
    [Freight Co]              NVARCHAR (40)   NULL,
    [Order Source]            NVARCHAR (60)   NULL,
    [Quote Salutation]        NVARCHAR (60)   NULL,
    [PckC]                    DECIMAL (36, 4) NULL,
    [TxCert]                  NVARCHAR (40)   NULL,
    [Loc]                     NVARCHAR (6)    NULL,
    [Delivery Address Line 4] NVARCHAR (60)   NULL,
    [Contact]                 NVARCHAR (60)   NULL,
    [Contact Phone]           NVARCHAR (28)   NULL,
    [Contact Fax]             NVARCHAR (28)   NULL,
    [Start Date]              DATETIME2 (7)   NULL,
    [Delivery Instructions]   NVARCHAR (1000) NULL,
    [Eby]                     NVARCHAR (6)    NULL,
    [Start By]                NVARCHAR (30)   NULL,
    [Contact Mobile]          NVARCHAR (28)   NULL,
    [Contact Email]           NVARCHAR (500)  NULL,
    [Gst Value]               DECIMAL (36, 4) NULL,
    [STime]                   TIME (7)        NULL,
    [Inby]                    DECIMAL (36, 4) NULL,
    [Aby]                     NVARCHAR (16)   NULL,
    [Edit Date]               DATETIME2 (7)   NULL,
    [ESTime]                  TIME (7)        NULL,
    [EFTime]                  TIME (7)        NULL,
    [Ste]                     NVARCHAR (6)    NULL,
    [Pstcde]                  NVARCHAR (12)   NULL,
    [Delivery District]       NVARCHAR (42)   NULL,
    [OMD_INSERT_DATETIME]     DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]           VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD]    VARCHAR (1000)  NULL
);

