CREATE TABLE [STG].[STG_EBS_PER_ALL_PEOPLE_F] (
    [PERSON_ID]                     FLOAT (53)     NULL,
    [EFFECTIVE_START_DATE]          DATETIME       NULL,
    [EFFECTIVE_END_DATE]            DATETIME       NULL,
    [BUSINESS_GROUP_ID]             FLOAT (53)     NULL,
    [PERSON_TYPE_ID]                FLOAT (53)     NULL,
    [LAST_NAME]                     VARCHAR (1000) NULL,
    [START_DATE]                    DATETIME       NULL,
    [APPLICANT_NUMBER]              VARCHAR (100)  NULL,
    [BACKGROUND_CHECK_STATUS]       VARCHAR (100)  NULL,
    [BACKGROUND_DATE_CHECK]         DATETIME       NULL,
    [BLOOD_TYPE]                    VARCHAR (100)  NULL,
    [COMMENT_ID]                    FLOAT (53)     NULL,
    [CORRESPONDENCE_LANGUAGE]       VARCHAR (100)  NULL,
    [CURRENT_APPLICANT_FLAG]        VARCHAR (100)  NULL,
    [CURRENT_EMP_OR_APL_FLAG]       VARCHAR (100)  NULL,
    [CURRENT_EMPLOYEE_FLAG]         VARCHAR (100)  NULL,
    [DATE_EMPLOYEE_DATA_VERIFIED]   DATETIME       NULL,
    [DATE_OF_BIRTH]                 DATETIME       NULL,
    [EMAIL_ADDRESS]                 VARCHAR (1000) NULL,
    [EMPLOYEE_NUMBER]               VARCHAR (100)  NULL,
    [EXPENSE_CHECK_SEND_TO_ADDRESS] VARCHAR (100)  NULL,
    [FAST_PATH_EMPLOYEE]            VARCHAR (100)  NULL,
    [FIRST_NAME]                    VARCHAR (1000) NULL,
    [FTE_CAPACITY]                  FLOAT (53)     NULL,
    [FULL_NAME]                     VARCHAR (1000) NULL,
    [HOLD_APPLICANT_DATE_UNTIL]     DATETIME       NULL,
    [HONORS]                        VARCHAR (100)  NULL,
    [INTERNAL_LOCATION]             VARCHAR (100)  NULL,
    [KNOWN_AS]                      VARCHAR (1000) NULL,
    [LAST_MEDICAL_TEST_BY]          VARCHAR (1000) NULL,
    [LAST_MEDICAL_TEST_DATE]        DATETIME       NULL,
    [MAILSTOP]                      VARCHAR (100)  NULL,
    [MARITAL_STATUS]                VARCHAR (100)  NULL,
    [MIDDLE_NAMES]                  VARCHAR (1000) NULL,
    [NATIONALITY]                   VARCHAR (100)  NULL,
    [NATIONAL_IDENTIFIER]           VARCHAR (100)  NULL,
    [OFFICE_NUMBER]                 VARCHAR (100)  NULL,
    [ON_MILITARY_SERVICE]           VARCHAR (100)  NULL,
    [ORDER_NAME]                    VARCHAR (1000) NULL,
    [PRE_NAME_ADJUNCT]              VARCHAR (100)  NULL,
    [PREVIOUS_LAST_NAME]            VARCHAR (1000) NULL,
    [PROJECTED_START_DATE]          DATETIME       NULL,
    [REHIRE_AUTHORIZOR]             VARCHAR (1000) NULL,
    [REHIRE_REASON]                 VARCHAR (1000) NULL,
    [REHIRE_RECOMMENDATION]         VARCHAR (100)  NULL,
    [RESUME_EXISTS]                 VARCHAR (100)  NULL,
    [RESUME_LAST_UPDATED]           DATETIME       NULL,
    [REGISTERED_DISABLED_FLAG]      VARCHAR (100)  NULL,
    [SECOND_PASSPORT_EXISTS]        VARCHAR (100)  NULL,
    [SEX]                           VARCHAR (100)  NULL,
    [STUDENT_STATUS]                VARCHAR (100)  NULL,
    [SUFFIX]                        VARCHAR (100)  NULL,
    [TITLE]                         VARCHAR (100)  NULL,
    [VENDOR_ID]                     FLOAT (53)     NULL,
    [WORK_SCHEDULE]                 VARCHAR (100)  NULL,
    [WORK_TELEPHONE]                VARCHAR (1000) NULL,
    [COORD_BEN_MED_PLN_NO]          VARCHAR (100)  NULL,
    [COORD_BEN_NO_CVG_FLAG]         VARCHAR (100)  NULL,
    [DPDNT_ADOPTION_DATE]           DATETIME       NULL,
    [DPDNT_VLNTRY_SVCE_FLAG]        VARCHAR (100)  NULL,
    [RECEIPT_OF_DEATH_CERT_DATE]    DATETIME       NULL,
    [USES_TOBACCO_FLAG]             VARCHAR (100)  NULL,
    [BENEFIT_GROUP_ID]              FLOAT (53)     NULL,
    [REQUEST_ID]                    FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]        FLOAT (53)     NULL,
    [PROGRAM_ID]                    FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]           DATETIME       NULL,
    [ATTRIBUTE_CATEGORY]            VARCHAR (100)  NULL,
    [ATTRIBUTE1]                    VARCHAR (1000) NULL,
    [ATTRIBUTE2]                    VARCHAR (1000) NULL,
    [ATTRIBUTE3]                    VARCHAR (1000) NULL,
    [ATTRIBUTE4]                    VARCHAR (1000) NULL,
    [ATTRIBUTE5]                    VARCHAR (1000) NULL,
    [ATTRIBUTE6]                    VARCHAR (1000) NULL,
    [ATTRIBUTE7]                    VARCHAR (1000) NULL,
    [ATTRIBUTE8]                    VARCHAR (1000) NULL,
    [ATTRIBUTE9]                    VARCHAR (1000) NULL,
    [ATTRIBUTE10]                   VARCHAR (1000) NULL,
    [ATTRIBUTE11]                   VARCHAR (1000) NULL,
    [ATTRIBUTE12]                   VARCHAR (1000) NULL,
    [ATTRIBUTE13]                   VARCHAR (1000) NULL,
    [ATTRIBUTE14]                   VARCHAR (1000) NULL,
    [ATTRIBUTE15]                   VARCHAR (1000) NULL,
    [ATTRIBUTE16]                   VARCHAR (1000) NULL,
    [ATTRIBUTE17]                   VARCHAR (1000) NULL,
    [ATTRIBUTE18]                   VARCHAR (1000) NULL,
    [ATTRIBUTE19]                   VARCHAR (1000) NULL,
    [ATTRIBUTE20]                   VARCHAR (1000) NULL,
    [ATTRIBUTE21]                   VARCHAR (1000) NULL,
    [ATTRIBUTE22]                   VARCHAR (1000) NULL,
    [ATTRIBUTE23]                   VARCHAR (1000) NULL,
    [ATTRIBUTE24]                   VARCHAR (1000) NULL,
    [ATTRIBUTE25]                   VARCHAR (1000) NULL,
    [ATTRIBUTE26]                   VARCHAR (1000) NULL,
    [ATTRIBUTE27]                   VARCHAR (1000) NULL,
    [ATTRIBUTE28]                   VARCHAR (1000) NULL,
    [ATTRIBUTE29]                   VARCHAR (1000) NULL,
    [ATTRIBUTE30]                   VARCHAR (1000) NULL,
    [LAST_UPDATE_DATE]              DATETIME       NULL,
    [LAST_UPDATED_BY]               FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]             FLOAT (53)     NULL,
    [CREATED_BY]                    FLOAT (53)     NULL,
    [CREATION_DATE]                 DATETIME       NULL,
    [PER_INFORMATION_CATEGORY]      VARCHAR (100)  NULL,
    [PER_INFORMATION1]              VARCHAR (1000) NULL,
    [PER_INFORMATION2]              VARCHAR (1000) NULL,
    [PER_INFORMATION3]              VARCHAR (1000) NULL,
    [PER_INFORMATION4]              VARCHAR (1000) NULL,
    [PER_INFORMATION5]              VARCHAR (1000) NULL,
    [PER_INFORMATION6]              VARCHAR (1000) NULL,
    [PER_INFORMATION7]              VARCHAR (1000) NULL,
    [PER_INFORMATION8]              VARCHAR (1000) NULL,
    [PER_INFORMATION9]              VARCHAR (1000) NULL,
    [PER_INFORMATION10]             VARCHAR (1000) NULL,
    [PER_INFORMATION11]             VARCHAR (1000) NULL,
    [PER_INFORMATION12]             VARCHAR (1000) NULL,
    [PER_INFORMATION13]             VARCHAR (1000) NULL,
    [PER_INFORMATION14]             VARCHAR (1000) NULL,
    [PER_INFORMATION15]             VARCHAR (1000) NULL,
    [PER_INFORMATION16]             VARCHAR (1000) NULL,
    [PER_INFORMATION17]             VARCHAR (1000) NULL,
    [PER_INFORMATION18]             VARCHAR (1000) NULL,
    [PER_INFORMATION19]             VARCHAR (1000) NULL,
    [PER_INFORMATION20]             VARCHAR (1000) NULL,
    [PER_INFORMATION21]             VARCHAR (1000) NULL,
    [PER_INFORMATION22]             VARCHAR (1000) NULL,
    [PER_INFORMATION23]             VARCHAR (1000) NULL,
    [PER_INFORMATION24]             VARCHAR (1000) NULL,
    [PER_INFORMATION25]             VARCHAR (1000) NULL,
    [PER_INFORMATION26]             VARCHAR (1000) NULL,
    [PER_INFORMATION27]             VARCHAR (1000) NULL,
    [PER_INFORMATION28]             VARCHAR (1000) NULL,
    [PER_INFORMATION29]             VARCHAR (1000) NULL,
    [PER_INFORMATION30]             VARCHAR (1000) NULL,
    [OBJECT_VERSION_NUMBER]         FLOAT (53)     NULL,
    [DATE_OF_DEATH]                 DATETIME       NULL,
    [ORIGINAL_DATE_OF_HIRE]         DATETIME       NULL,
    [TOWN_OF_BIRTH]                 VARCHAR (1000) NULL,
    [REGION_OF_BIRTH]               VARCHAR (1000) NULL,
    [COUNTRY_OF_BIRTH]              VARCHAR (1000) NULL,
    [GLOBAL_PERSON_ID]              VARCHAR (100)  NULL,
    [COORD_BEN_MED_PL_NAME]         VARCHAR (1000) NULL,
    [COORD_BEN_MED_INSR_CRR_NAME]   VARCHAR (1000) NULL,
    [COORD_BEN_MED_INSR_CRR_IDENT]  VARCHAR (1000) NULL,
    [COORD_BEN_MED_EXT_ER]          VARCHAR (1000) NULL,
    [COORD_BEN_MED_CVG_STRT_DT]     DATETIME       NULL,
    [COORD_BEN_MED_CVG_END_DT]      DATETIME       NULL,
    [PARTY_ID]                      FLOAT (53)     NULL,
    [NPW_NUMBER]                    VARCHAR (100)  NULL,
    [CURRENT_NPW_FLAG]              VARCHAR (100)  NULL,
    [GLOBAL_NAME]                   VARCHAR (1000) NULL,
    [LOCAL_NAME]                    VARCHAR (1000) NULL,
    [OMD_INSERT_DATETIME]           DATETIME2 (7)  NULL,
    [OMD_FILE_NAME]                 VARCHAR (8000) NULL,
    [OMD_HASH_FULL_RECORD]          VARCHAR (1000) NULL
);

