CREATE TABLE [STG].[STG_CA_INLOC] (
    [Loc]                  NVARCHAR (6)    NULL,
    [Location Name]        NVARCHAR (60)   NULL,
    [P]                    NVARCHAR (2)    NULL,
    [Address Line 1]       NVARCHAR (100)  NULL,
    [Address Line 2]       NVARCHAR (100)  NULL,
    [Address Line 3]       NVARCHAR (100)  NULL,
    [Phone]                NVARCHAR (40)   NULL,
    [Fax]                  NVARCHAR (40)   NULL,
    [Banner Location Name] NVARCHAR (160)  NULL,
    [O]                    NVARCHAR (36)   NULL,
    [DB]                   NVARCHAR (2)    NULL,
    [CurrDep0]             DECIMAL (36, 4) NULL,
    [Last Inv#]            DECIMAL (36, 4) NULL,
    [Last Rcp#]            DECIMAL (36, 4) NULL,
    [Last So#]             DECIMAL (36, 4) NULL,
    [Last Sq#]             DECIMAL (36, 4) NULL,
    [Last Po#]             DECIMAL (36, 4) NULL,
    [LastXfr#]             DECIMAL (36, 4) NULL,
    [LastBch#]             DECIMAL (36, 4) NULL,
    [LstInBch]             DECIMAL (36, 4) NULL,
    [Delivery Name]        NVARCHAR (160)  NULL,
    [Delivery Address 1]   NVARCHAR (120)  NULL,
    [Delivery Address 2]   NVARCHAR (120)  NULL,
    [Delivery Address 3]   NVARCHAR (80)   NULL,
    [Del Phone]            NVARCHAR (40)   NULL,
    [Deliv Fax]            NVARCHAR (40)   NULL,
    [B]                    NVARCHAR (2)    NULL,
    [X]                    NVARCHAR (100)  NULL,
    [Iar]                  NVARCHAR (12)   NULL,
    [Email]                NVARCHAR (100)  NULL,
    [Rg]                   NVARCHAR (4)    NULL,
    [A]                    NVARCHAR (4)    NULL,
    [Msp]                  NVARCHAR (6)    NULL,
    [Pstcde]               NVARCHAR (12)   NULL,
    [Last Stake]           DATETIME2 (7)   NULL,
    [Curr Stake]           DATETIME2 (7)   NULL,
    [S]                    NVARCHAR (2)    NULL,
    [W]                    NVARCHAR (2)    NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD] VARCHAR (1000)  NULL
);

