CREATE TABLE [STG].[STG_CA_INRFCHDR] (
    [Rfc#]                 DECIMAL (36, 4) NULL,
    [Sup#]                 DECIMAL (36, 4) NULL,
    [Batch#]               DECIMAL (36, 4) NULL,
    [Rts Reference]        NVARCHAR (100)  NULL,
    [Original Inv]         NVARCHAR (100)  NULL,
    [Gra]                  NVARCHAR (100)  NULL,
    [Gra IssDat]           DATE            NULL,
    [Reason]               NVARCHAR (100)  NULL,
    [Spn]                  NVARCHAR (100)  NULL,
    [ReturnDate]           DATE            NULL,
    [M]                    NVARCHAR (100)  NULL,
    [Match Date]           DATE            NULL,
    [AdrT]                 NVARCHAR (100)  NULL,
    [Loc]                  NVARCHAR (100)  NULL,
    [Start Date]           DATE            NULL,
    [STime]                TIME (7)        NULL,
    [Start By]             NVARCHAR (100)  NULL,
    [Rfc Value]            DECIMAL (36, 4) NULL,
    [Amend Date]           DATE            NULL,
    [ATime]                TIME (7)        NULL,
    [Amend By]             NVARCHAR (100)  NULL,
    [Ship Date]            DATE            NULL,
    [Con Note]             NVARCHAR (100)  NULL,
    [Carrier]              NVARCHAR (100)  NULL,
    [O]                    NVARCHAR (100)  NULL,
    [Notes]                NVARCHAR (1000) NULL,
    [Transmission]         NVARCHAR (100)  NULL,
    [MatchMeth]            NVARCHAR (100)  NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD] VARCHAR (1000)  NULL
);

