CREATE TABLE [STG].[STG_EBS_MTL_ITEM_CATEGORIES_V] (
    [ROW_ID]                    VARCHAR (100)  NULL,
    [INVENTORY_ITEM_ID]         FLOAT (53)     NULL,
    [ORGANIZATION_ID]           FLOAT (53)     NULL,
    [CATEGORY_SET_ID]           FLOAT (53)     NULL,
    [CATEGORY_ID]               FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]          DATETIME       NULL,
    [LAST_UPDATED_BY]           FLOAT (53)     NULL,
    [CREATION_DATE]             DATETIME       NULL,
    [CREATED_BY]                FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]         FLOAT (53)     NULL,
    [REQUEST_ID]                FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]    FLOAT (53)     NULL,
    [PROGRAM_ID]                FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]       DATETIME       NULL,
    [CATEGORY_SET_NAME]         VARCHAR (100)  NULL,
    [STRUCTURE_ID]              FLOAT (53)     NULL,
    [VALIDATE_FLAG]             VARCHAR (100)  NULL,
    [CONTROL_LEVEL]             FLOAT (53)     NULL,
    [CONTROL_LEVEL_DISP]        VARCHAR (1000) NULL,
    [CATEGORY_CONCAT_SEGS]      VARCHAR (1000) NULL,
    [MULT_ITEM_CAT_ASSIGN_FLAG] VARCHAR (100)  NULL,
    [CATEGORY_STRUCTURE_ID]     FLOAT (53)     NULL,
    [CATEGORY_DISABLE_DATE]     DATETIME       NULL,
    [SEGMENT1]                  VARCHAR (100)  NULL,
    [SEGMENT2]                  VARCHAR (100)  NULL,
    [SEGMENT3]                  VARCHAR (100)  NULL,
    [SEGMENT4]                  VARCHAR (100)  NULL,
    [SEGMENT5]                  VARCHAR (100)  NULL,
    [SEGMENT6]                  VARCHAR (100)  NULL,
    [SEGMENT7]                  VARCHAR (100)  NULL,
    [SEGMENT8]                  VARCHAR (100)  NULL,
    [SEGMENT9]                  VARCHAR (100)  NULL,
    [SEGMENT10]                 VARCHAR (100)  NULL,
    [SEGMENT11]                 VARCHAR (100)  NULL,
    [SEGMENT12]                 VARCHAR (100)  NULL,
    [SEGMENT13]                 VARCHAR (100)  NULL,
    [SEGMENT14]                 VARCHAR (100)  NULL,
    [SEGMENT15]                 VARCHAR (100)  NULL,
    [SEGMENT16]                 VARCHAR (100)  NULL,
    [SEGMENT17]                 VARCHAR (100)  NULL,
    [SEGMENT18]                 VARCHAR (100)  NULL,
    [SEGMENT19]                 VARCHAR (100)  NULL,
    [SEGMENT20]                 VARCHAR (100)  NULL,
    [SUMMARY_FLAG]              VARCHAR (100)  NULL,
    [ENABLED_FLAG]              VARCHAR (100)  NULL,
    [HIERARCHY_ENABLED]         VARCHAR (100)  NULL,
    [OMD_INSERT_DATETIME]       DATETIME2 (7)  NULL,
    [OMD_FILE_NAME]             VARCHAR (8000) NULL,
    [OMD_HASH_FULL_RECORD]      VARCHAR (1000) NULL
);

