CREATE TABLE [STG].[STG_CA_OEINVLIN] (
    [Invoice#]             DECIMAL (36, 4) NULL,
    [Inl#]                 DECIMAL (36, 4) NULL,
    [Item Code]            NVARCHAR (60)   NULL,
    [Memo#]                DECIMAL (36, 4) NULL,
    [Sale Qty]             DECIMAL (36, 4) NULL,
    [Disc %]               DECIMAL (36, 4) NULL,
    [Disc Value]           DECIMAL (36, 4) NULL,
    [LinePrice]            DECIMAL (36, 4) NULL,
    [SV Gst Incl]          DECIMAL (36, 4) NULL,
    [Loc]                  NVARCHAR (6)    NULL,
    [Lto]                  NVARCHAR (6)    NULL,
    [Cogs Value]           DECIMAL (36, 4) NULL,
    [Gst Value]            DECIMAL (36, 4) NULL,
    [Gst %]                DECIMAL (36, 4) NULL,
    [P]                    NVARCHAR (2)    NULL,
    [Reas]                 NVARCHAR (8)    NULL,
    [Backord Qty]          DECIMAL (36, 4) NULL,
    [Order Qty]            DECIMAL (36, 4) NULL,
    [CusTyp]               NVARCHAR (12)   NULL,
    [Spn]                  NVARCHAR (6)    NULL,
    [OeIncat]              NVARCHAR (20)   NULL,
    [Trans Date]           DATETIME2 (7)   NULL,
    [Pd]                   DECIMAL (36, 4) NULL,
    [Cust#]                DECIMAL (36, 4) NULL,
    [Start Date]           DATETIME2 (7)   NULL,
    [STime]                TIME (7)        NULL,
    [Start By]             NVARCHAR (30)   NULL,
    [Amend Date]           DATETIME2 (7)   NULL,
    [ATime]                TIME (7)        NULL,
    [Amend By]             NVARCHAR (30)   NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD] VARCHAR (1000)  NULL
);

