CREATE TABLE [STG].[STG_CA_SQLQUOTE] (
    [Sq#]                  NVARCHAR (20)   NULL,
    [Sql#]                 DECIMAL (36, 4) NULL,
    [Item Code]            NVARCHAR (60)   NULL,
    [Pr]                   DECIMAL (36, 4) NULL,
    [Deliv Date]           DATETIME2 (7)   NULL,
    [Comment]              NVARCHAR (2000) NULL,
    [Quote Qty]            DECIMAL (36, 4) NULL,
    [LinePrice]            DECIMAL (36, 4) NULL,
    [Disc %]               DECIMAL (36, 4) NULL,
    [QV Gst Incl]          DECIMAL (36, 4) NULL,
    [Quote Item Type]      NVARCHAR (60)   NULL,
    [Quote Item Ref]       NVARCHAR (60)   NULL,
    [Unit Cost]            DECIMAL (36, 4) NULL,
    [Cost Value]           DECIMAL (36, 4) NULL,
    [X]                    NVARCHAR (2)    NULL,
    [TxCert]               NVARCHAR (40)   NULL,
    [Gst Value]            DECIMAL (36, 4) NULL,
    [Disc Value]           DECIMAL (36, 4) NULL,
    [Gst%]                 DECIMAL (36, 4) NULL,
    [Loc]                  NVARCHAR (6)    NULL,
    [LSup]                 DECIMAL (36, 4) NULL,
    [Supplier Item Code]   NVARCHAR (80)   NULL,
    [Start Date]           DATETIME2 (7)   NULL,
    [STime]                TIME (7)        NULL,
    [Start By]             NVARCHAR (30)   NULL,
    [Mx NetPrc]            DECIMAL (36, 4) NULL,
    [Mx Price]             DECIMAL (36, 4) NULL,
    [MxDis%]               DECIMAL (36, 4) NULL,
    [T]                    NVARCHAR (2)    NULL,
    [Mx Item/Incat]        NVARCHAR (60)   NULL,
    [MxCust]               DECIMAL (36, 4) NULL,
    [Mx QVGstExc]          DECIMAL (36, 4) NULL,
    [Mx Val Fm]            DATETIME2 (7)   NULL,
    [Mx Val To]            DATETIME2 (7)   NULL,
    [MxPrbk]               NVARCHAR (12)   NULL,
    [MPC]                  NVARCHAR (6)    NULL,
    [Trade Prc]            DECIMAL (36, 4) NULL,
    [Msp]                  NVARCHAR (6)    NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD] VARCHAR (1000)  NULL
);

