CREATE TABLE [STG].[STG_EBS_IBY_EXTERNAL_PAYERS_ALL] (
    [EXT_PAYER_ID]                 FLOAT (53)     NULL,
    [PAYMENT_FUNCTION]             VARCHAR (100)  NULL,
    [PARTY_ID]                     FLOAT (53)     NULL,
    [ORG_TYPE]                     VARCHAR (100)  NULL,
    [ORG_ID]                       FLOAT (53)     NULL,
    [CUST_ACCOUNT_ID]              FLOAT (53)     NULL,
    [ACCT_SITE_USE_ID]             FLOAT (53)     NULL,
    [BANK_CHARGE_BEARER_CODE]      VARCHAR (100)  NULL,
    [DIRDEB_INSTRUCTION_CODE]      VARCHAR (100)  NULL,
    [CREATED_BY]                   FLOAT (53)     NULL,
    [CREATION_DATE]                DATETIME       NULL,
    [LAST_UPDATED_BY]              FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]             DATETIME       NULL,
    [LAST_UPDATE_LOGIN]            FLOAT (53)     NULL,
    [OBJECT_VERSION_NUMBER]        FLOAT (53)     NULL,
    [DEBIT_ADVICE_DELIVERY_METHOD] VARCHAR (100)  NULL,
    [DEBIT_ADVICE_EMAIL]           VARCHAR (1000) NULL,
    [DEBIT_ADVICE_FAX]             VARCHAR (1000) NULL,
    [LOCALINSTR]                   VARCHAR (100)  NULL,
    [SERVICE_LEVEL]                VARCHAR (100)  NULL,
    [PURPOSE_CODE]                 VARCHAR (100)  NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)  NULL,
    [OMD_FILE_NAME]                VARCHAR (8000) NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000) NULL
);

