CREATE TABLE [STG].[STG_CA_INMAST] (
    [Item Code]            NVARCHAR (60)   NULL,
    [Incat]                NVARCHAR (20)   NULL,
    [Item Description]     NVARCHAR (240)  NULL,
    [Uom]                  NVARCHAR (20)   NULL,
    [Value @ Cost]         DECIMAL (36, 4) NULL,
    [Stock Qty]            DECIMAL (36, 4) NULL,
    [Nat Buy Prc]          DECIMAL (36, 4) NULL,
    [Commit Qty]           DECIMAL (36, 4) NULL,
    [Order Qty]            DECIMAL (36, 4) NULL,
    [Trade Prc]            DECIMAL (36, 4) NULL,
    [RetailPrc]            DECIMAL (36, 4) NULL,
    [MSup]                 DECIMAL (36, 4) NULL,
    [Supplier Item Code]   NVARCHAR (80)   NULL,
    [Last Sale]            DATETIME2 (7)   NULL,
    [2ndLstSale]           DATETIME2 (7)   NULL,
    [Comment]              NVARCHAR (240)  NULL,
    [User1]                NVARCHAR (20)   NULL,
    [Sales 1]              DECIMAL (36, 4) NULL,
    [Sales 2]              DECIMAL (36, 4) NULL,
    [Sales 3]              DECIMAL (36, 4) NULL,
    [Sales 4]              DECIMAL (36, 4) NULL,
    [Sales 5]              DECIMAL (36, 4) NULL,
    [Sales 6]              DECIMAL (36, 4) NULL,
    [Sales 7]              DECIMAL (36, 4) NULL,
    [Sales 8]              DECIMAL (36, 4) NULL,
    [Sales 9]              DECIMAL (36, 4) NULL,
    [Sales 10]             DECIMAL (36, 4) NULL,
    [Sales 11]             DECIMAL (36, 4) NULL,
    [Sales 12]             DECIMAL (36, 4) NULL,
    [Sales 13]             DECIMAL (36, 4) NULL,
    [Sales 14]             DECIMAL (36, 4) NULL,
    [Sales 15]             DECIMAL (36, 4) NULL,
    [Sales 16]             DECIMAL (36, 4) NULL,
    [Sales 17]             DECIMAL (36, 4) NULL,
    [Sales 18]             DECIMAL (36, 4) NULL,
    [Sales 19]             DECIMAL (36, 4) NULL,
    [Sales 20]             DECIMAL (36, 4) NULL,
    [Sales 21]             DECIMAL (36, 4) NULL,
    [Sales 22]             DECIMAL (36, 4) NULL,
    [Sales 23]             DECIMAL (36, 4) NULL,
    [Sales 24]             DECIMAL (36, 4) NULL,
    [Purch 1]              DECIMAL (36, 4) NULL,
    [Purch 2]              DECIMAL (36, 4) NULL,
    [Purch 3]              DECIMAL (36, 4) NULL,
    [Purch 4]              DECIMAL (36, 4) NULL,
    [Purch 5]              DECIMAL (36, 4) NULL,
    [Purch 6]              DECIMAL (36, 4) NULL,
    [Purch 7]              DECIMAL (36, 4) NULL,
    [Purch 8]              DECIMAL (36, 4) NULL,
    [Purch 9]              DECIMAL (36, 4) NULL,
    [Purch 10]             DECIMAL (36, 4) NULL,
    [Purch 11]             DECIMAL (36, 4) NULL,
    [Purch 12]             DECIMAL (36, 4) NULL,
    [Purch 13]             DECIMAL (36, 4) NULL,
    [Purch 14]             DECIMAL (36, 4) NULL,
    [Purch 15]             DECIMAL (36, 4) NULL,
    [Purch 16]             DECIMAL (36, 4) NULL,
    [Purch 17]             DECIMAL (36, 4) NULL,
    [Purch 18]             DECIMAL (36, 4) NULL,
    [Purch 19]             DECIMAL (36, 4) NULL,
    [Purch 20]             DECIMAL (36, 4) NULL,
    [Purch 21]             DECIMAL (36, 4) NULL,
    [Purch 22]             DECIMAL (36, 4) NULL,
    [Purch 23]             DECIMAL (36, 4) NULL,
    [Purch 24]             DECIMAL (36, 4) NULL,
    [Cogs 1]               DECIMAL (36, 4) NULL,
    [Cogs 2]               DECIMAL (36, 4) NULL,
    [Cogs 3]               DECIMAL (36, 4) NULL,
    [Cogs 4]               DECIMAL (36, 4) NULL,
    [Cogs 5]               DECIMAL (36, 4) NULL,
    [Cogs 6]               DECIMAL (36, 4) NULL,
    [Cogs 7]               DECIMAL (36, 4) NULL,
    [Cogs 8]               DECIMAL (36, 4) NULL,
    [Cogs 9]               DECIMAL (36, 4) NULL,
    [Cogs 10]              DECIMAL (36, 4) NULL,
    [Cogs 11]              DECIMAL (36, 4) NULL,
    [Cogs 12]              DECIMAL (36, 4) NULL,
    [Cogs 13]              DECIMAL (36, 4) NULL,
    [Cogs 14]              DECIMAL (36, 4) NULL,
    [Cogs 15]              DECIMAL (36, 4) NULL,
    [Cogs 16]              DECIMAL (36, 4) NULL,
    [Cogs 17]              DECIMAL (36, 4) NULL,
    [Cogs 18]              DECIMAL (36, 4) NULL,
    [Cogs 19]              DECIMAL (36, 4) NULL,
    [Cogs 20]              DECIMAL (36, 4) NULL,
    [Cogs 21]              DECIMAL (36, 4) NULL,
    [Cogs 22]              DECIMAL (36, 4) NULL,
    [Cogs 23]              DECIMAL (36, 4) NULL,
    [Cogs 24]              DECIMAL (36, 4) NULL,
    [Sale Qty 1]           DECIMAL (36, 4) NULL,
    [Sale Qty 2]           DECIMAL (36, 4) NULL,
    [Sale Qty 3]           DECIMAL (36, 4) NULL,
    [Sale Qty 4]           DECIMAL (36, 4) NULL,
    [Sale Qty 5]           DECIMAL (36, 4) NULL,
    [Sale Qty 6]           DECIMAL (36, 4) NULL,
    [Sale Qty 7]           DECIMAL (36, 4) NULL,
    [Sale Qty 8]           DECIMAL (36, 4) NULL,
    [Sale Qty 9]           DECIMAL (36, 4) NULL,
    [Sale Qty 10]          DECIMAL (36, 4) NULL,
    [Sale Qty 11]          DECIMAL (36, 4) NULL,
    [Sale Qty 12]          DECIMAL (36, 4) NULL,
    [Sale Qty 13]          DECIMAL (36, 4) NULL,
    [Sale Qty 14]          DECIMAL (36, 4) NULL,
    [Sale Qty 15]          DECIMAL (36, 4) NULL,
    [Sale Qty 16]          DECIMAL (36, 4) NULL,
    [Sale Qty 17]          DECIMAL (36, 4) NULL,
    [Sale Qty 18]          DECIMAL (36, 4) NULL,
    [Sale Qty 19]          DECIMAL (36, 4) NULL,
    [Sale Qty 20]          DECIMAL (36, 4) NULL,
    [Sale Qty 21]          DECIMAL (36, 4) NULL,
    [Sale Qty 22]          DECIMAL (36, 4) NULL,
    [Sale Qty 23]          DECIMAL (36, 4) NULL,
    [Sale Qty 24]          DECIMAL (36, 4) NULL,
    [QohLastStake]         DECIMAL (36, 4) NULL,
    [Curr Stake]           DATETIME2 (7)   NULL,
    [QohCurrStake]         DECIMAL (36, 4) NULL,
    [Frozen Qoh]           DECIMAL (36, 4) NULL,
    [PO]                   NVARCHAR (2)    NULL,
    [VD]                   NVARCHAR (2)    NULL,
    [NS]                   NVARCHAR (2)    NULL,
    [User2]                NVARCHAR (20)   NULL,
    [User3]                NVARCHAR (20)   NULL,
    [VO]                   NVARCHAR (2)    NULL,
    [DO]                   NVARCHAR (2)    NULL,
    [F]                    NVARCHAR (2)    NULL,
    [Border Qty]           DECIMAL (36, 4) NULL,
    [B]                    NVARCHAR (100)  NULL,
    [S]                    NVARCHAR (100)  NULL,
    [O]                    NVARCHAR (100)  NULL,
    [Q]                    NVARCHAR (100)  NULL,
    [D]                    NVARCHAR (100)  NULL,
    [OQMult]               NVARCHAR (100)  NULL,
    [C]                    NVARCHAR (100)  NULL,
    [PkgL]                 NVARCHAR (100)  NULL,
    [Cut Fee]              NVARCHAR (100)  NULL,
    [Start Date]           DATETIME2 (7)   NULL,
    [Last Purch]           DATETIME2 (7)   NULL,
    [LastPrcUpd]           DATETIME2 (7)   NULL,
    [DC Price]             DECIMAL (36, 4) NULL,
    [Qoh Eop]              DECIMAL (36, 4) NULL,
    [Vac Eop]              DECIMAL (36, 4) NULL,
    [1st Purch]            DATETIME2 (7)   NULL,
    [ObsFlagUpd]           DATETIME2 (7)   NULL,
    [PurchQty 1]           DECIMAL (36, 4) NULL,
    [PurchQty 2]           DECIMAL (36, 4) NULL,
    [PurchQty 3]           DECIMAL (36, 4) NULL,
    [PurchQty 4]           DECIMAL (36, 4) NULL,
    [PurchQty 5]           DECIMAL (36, 4) NULL,
    [PurchQty 6]           DECIMAL (36, 4) NULL,
    [PurchQty 7]           DECIMAL (36, 4) NULL,
    [PurchQty 8]           DECIMAL (36, 4) NULL,
    [PurchQty 9]           DECIMAL (36, 4) NULL,
    [PurchQty10]           DECIMAL (36, 4) NULL,
    [PurchQty11]           DECIMAL (36, 4) NULL,
    [PurchQty12]           DECIMAL (36, 4) NULL,
    [PurchQty13]           DECIMAL (36, 4) NULL,
    [PurchQty14]           DECIMAL (36, 4) NULL,
    [PurchQty15]           DECIMAL (36, 4) NULL,
    [PurchQty16]           DECIMAL (36, 4) NULL,
    [PurchQty17]           DECIMAL (36, 4) NULL,
    [PurchQty18]           DECIMAL (36, 4) NULL,
    [PurchQty19]           DECIMAL (36, 4) NULL,
    [PurchQty20]           DECIMAL (36, 4) NULL,
    [PurchQty21]           DECIMAL (36, 4) NULL,
    [PurchQty22]           DECIMAL (36, 4) NULL,
    [PurchQty23]           DECIMAL (36, 4) NULL,
    [PurchQty24]           DECIMAL (36, 4) NULL,
    [Comment3]             NVARCHAR (240)  NULL,
    [OracleID]             DECIMAL (36, 4) NULL,
    [Barcode/Gtin]         NVARCHAR (40)   NULL,
    [Frozen Vac]           DECIMAL (36, 4) NULL,
    [User4]                NVARCHAR (40)   NULL,
    [Prcat]                NVARCHAR (20)   NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD] VARCHAR (1000)  NULL
);

