CREATE TABLE [STG].[STG_EBS_OE_ORDER_SOURCES] (
    [ORDER_SOURCE_ID]       FLOAT (53)     NULL,
    [CREATION_DATE]         DATETIME       NULL,
    [CREATED_BY]            FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]      DATETIME       NULL,
    [LAST_UPDATED_BY]       FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]     FLOAT (53)     NULL,
    [NAME]                  VARCHAR (1000) NULL,
    [DESCRIPTION]           VARCHAR (8000) NULL,
    [ENABLED_FLAG]          VARCHAR (100)  NULL,
    [CREATE_CUSTOMERS_FLAG] VARCHAR (100)  NULL,
    [USE_IDS_FLAG]          VARCHAR (100)  NULL,
    [AIA_ENABLED_FLAG]      VARCHAR (100)  NULL,
    [OMD_INSERT_DATETIME]   DATETIME2 (7)  NULL,
    [OMD_FILE_NAME]         VARCHAR (8000) NULL,
    [OMD_HASH_FULL_RECORD]  VARCHAR (1000) NULL
);

