CREATE TABLE [STG].[STG_CA_OEINVHDR] (
    [Invoice#]                DECIMAL (36, 4) NULL,
    [Cust#]                   DECIMAL (36, 4) NULL,
    [Batch#]                  DECIMAL (36, 4) NULL,
    [Trans Date]              DATETIME2 (7)   NULL,
    [Customer Reference]      NVARCHAR (100)  NULL,
    [P]                       NVARCHAR (2)    NULL,
    [SV Gst Incl]             DECIMAL (36, 4) NULL,
    [Message]                 NVARCHAR (1000) NULL,
    [Gst Value]               DECIMAL (36, 4) NULL,
    [Cogs Value]              DECIMAL (36, 4) NULL,
    [Line Total]              DECIMAL (36, 4) NULL,
    [So#]                     NVARCHAR (20)   NULL,
    [Delivery Name]           NVARCHAR (120)  NULL,
    [Delivery Address Line 1] NVARCHAR (120)  NULL,
    [Delivery Address Line 2] NVARCHAR (120)  NULL,
    [Delivery Address Line 3] NVARCHAR (80)   NULL,
    [Tax Certificate]         NVARCHAR (30)   NULL,
    [Spn]                     NVARCHAR (6)    NULL,
    [Job Ref]                 NVARCHAR (20)   NULL,
    [Credit#]                 NVARCHAR (60)   NULL,
    [Ins]                     NVARCHAR (100)  NULL,
    [C2OBch]                  NVARCHAR (12)   NULL,
    [Disp Via]                NVARCHAR (200)  NULL,
    [Consignment Note#]       NVARCHAR (200)  NULL,
    [Start Date]              DATETIME2 (7)   NULL,
    [STime]                   TIME (7)        NULL,
    [Start By]                NVARCHAR (30)   NULL,
    [Amend Date]              DATETIME2 (7)   NULL,
    [ATime]                   TIME (7)        NULL,
    [Amend By]                NVARCHAR (30)   NULL,
    [Loc]                     NVARCHAR (6)    NULL,
    [Line Gst Val]            DECIMAL (36, 4) NULL,
    [OMD_INSERT_DATETIME]     DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]           VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD]    VARCHAR (1000)  NULL
);

