CREATE TABLE [STG].[STG_CA_SOCOLINE] (
    [So#]                  NVARCHAR (20)   NULL,
    [Co#]                  DECIMAL (36, 4) NULL,
    [Sol#]                 DECIMAL (36, 4) NULL,
    [Item Code]            NVARCHAR (60)   NULL,
    [Deliv Date]           DATETIME2 (7)   NULL,
    [Comment]              NVARCHAR (2000) NULL,
    [Order Qty]            DECIMAL (36, 4) NULL,
    [LinePrice]            DECIMAL (36, 4) NULL,
    [Disc %]               DECIMAL (36, 4) NULL,
    [Order Value]          DECIMAL (36, 4) NULL,
    [Loc]                  NVARCHAR (6)    NULL,
    [X]                    NVARCHAR (2)    NULL,
    [Gst%]                 DECIMAL (36, 4) NULL,
    [Gst Value]            DECIMAL (36, 4) NULL,
    [Disc Value]           DECIMAL (36, 4) NULL,
    [Customer Reference]   NVARCHAR (100)  NULL,
    [Inmast Description]   NVARCHAR (240)  NULL,
    [InmTrdPrc]            DECIMAL (36, 4) NULL,
    [InmRetPrc]            DECIMAL (36, 4) NULL,
    [Uom]                  NVARCHAR (20)   NULL,
    [CancelQty]            DECIMAL (36, 4) NULL,
    [Net Qty]              DECIMAL (36, 4) NULL,
    [Net Value]            DECIMAL (36, 4) NULL,
    [Net Gst]              DECIMAL (36, 4) NULL,
    [OMD_INSERT_DATETIME]  DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]        VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD] VARCHAR (1000)  NULL
);

