CREATE TABLE [STG].[STG_CA_INCAT] (
    [Incat]                    NVARCHAR (20)   NULL,
    [Category Description]     NVARCHAR (120)  NULL,
    [L]                        DECIMAL (36, 4) NULL,
    [Gl Sales]                 NVARCHAR (20)   NULL,
    [Gl Purch]                 NVARCHAR (20)   NULL,
    [Gl Cogs]                  NVARCHAR (20)   NULL,
    [Gl Stock]                 NVARCHAR (20)   NULL,
    [Sales 1]                  DECIMAL (36, 4) NULL,
    [Sales 2]                  DECIMAL (36, 4) NULL,
    [Sales 3]                  DECIMAL (36, 4) NULL,
    [Sales 4]                  DECIMAL (36, 4) NULL,
    [Sales 5]                  DECIMAL (36, 4) NULL,
    [Sales 6]                  DECIMAL (36, 4) NULL,
    [Sales 7]                  DECIMAL (36, 4) NULL,
    [Sales 8]                  DECIMAL (36, 4) NULL,
    [Sales 9]                  DECIMAL (36, 4) NULL,
    [Sales 10]                 DECIMAL (36, 4) NULL,
    [Sales 11]                 DECIMAL (36, 4) NULL,
    [Sales 12]                 DECIMAL (36, 4) NULL,
    [Sales 13]                 DECIMAL (36, 4) NULL,
    [Sales 14]                 DECIMAL (36, 4) NULL,
    [Sales 15]                 DECIMAL (36, 4) NULL,
    [Sales 16]                 DECIMAL (36, 4) NULL,
    [Sales 17]                 DECIMAL (36, 4) NULL,
    [Sales 18]                 DECIMAL (36, 4) NULL,
    [Sales 19]                 DECIMAL (36, 4) NULL,
    [Sales 20]                 DECIMAL (36, 4) NULL,
    [Sales 21]                 DECIMAL (36, 4) NULL,
    [Sales 22]                 DECIMAL (36, 4) NULL,
    [Sales 23]                 DECIMAL (36, 4) NULL,
    [Sales 24]                 DECIMAL (36, 4) NULL,
    [Purch 1]                  DECIMAL (36, 4) NULL,
    [Purch 2]                  DECIMAL (36, 4) NULL,
    [Purch 3]                  DECIMAL (36, 4) NULL,
    [Purch 4]                  DECIMAL (36, 4) NULL,
    [Purch 5]                  DECIMAL (36, 4) NULL,
    [Purch 6]                  DECIMAL (36, 4) NULL,
    [Purch 7]                  DECIMAL (36, 4) NULL,
    [Purch 8]                  DECIMAL (36, 4) NULL,
    [Purch 9]                  DECIMAL (36, 4) NULL,
    [Purch 10]                 DECIMAL (36, 4) NULL,
    [Purch 11]                 DECIMAL (36, 4) NULL,
    [Purch 12]                 DECIMAL (36, 4) NULL,
    [Purch 13]                 DECIMAL (36, 4) NULL,
    [Purch 14]                 DECIMAL (36, 4) NULL,
    [Purch 15]                 DECIMAL (36, 4) NULL,
    [Purch 16]                 DECIMAL (36, 4) NULL,
    [Purch 17]                 DECIMAL (36, 4) NULL,
    [Purch 18]                 DECIMAL (36, 4) NULL,
    [Purch 19]                 DECIMAL (36, 4) NULL,
    [Purch 20]                 DECIMAL (36, 4) NULL,
    [Purch 21]                 DECIMAL (36, 4) NULL,
    [Purch 22]                 DECIMAL (36, 4) NULL,
    [Purch 23]                 DECIMAL (36, 4) NULL,
    [Purch 24]                 DECIMAL (36, 4) NULL,
    [Cogs 1]                   DECIMAL (36, 4) NULL,
    [Cogs 2]                   DECIMAL (36, 4) NULL,
    [Cogs 3]                   DECIMAL (36, 4) NULL,
    [Cogs 4]                   DECIMAL (36, 4) NULL,
    [Cogs 5]                   DECIMAL (36, 4) NULL,
    [Cogs 6]                   DECIMAL (36, 4) NULL,
    [Cogs 7]                   DECIMAL (36, 4) NULL,
    [Cogs 8]                   DECIMAL (36, 4) NULL,
    [Cogs 9]                   DECIMAL (36, 4) NULL,
    [Cogs 10]                  DECIMAL (36, 4) NULL,
    [Cogs 11]                  DECIMAL (36, 4) NULL,
    [Cogs 12]                  DECIMAL (36, 4) NULL,
    [Cogs 13]                  DECIMAL (36, 4) NULL,
    [Cogs 14]                  DECIMAL (36, 4) NULL,
    [Cogs 15]                  DECIMAL (36, 4) NULL,
    [Cogs 16]                  DECIMAL (36, 4) NULL,
    [Cogs 17]                  DECIMAL (36, 4) NULL,
    [Cogs 18]                  DECIMAL (36, 4) NULL,
    [Cogs 19]                  DECIMAL (36, 4) NULL,
    [Cogs 20]                  DECIMAL (36, 4) NULL,
    [Cogs 21]                  DECIMAL (36, 4) NULL,
    [Cogs 22]                  DECIMAL (36, 4) NULL,
    [Cogs 23]                  DECIMAL (36, 4) NULL,
    [Cogs 24]                  DECIMAL (36, 4) NULL,
    [Type]                     NVARCHAR (12)   NULL,
    [Minor]                    NVARCHAR (16)   NULL,
    [Mj]                       NVARCHAR (4)    NULL,
    [A]                        NVARCHAR (6)    NULL,
    [MaxDis]                   DECIMAL (36, 4) NULL,
    [Gl Stk Adj]               NVARCHAR (20)   NULL,
    [HG]                       NVARCHAR (6)    NULL,
    [CatReb]                   DECIMAL (36, 4) NULL,
    [MinDis]                   DECIMAL (36, 4) NULL,
    [Category Sub Description] NVARCHAR (120)  NULL,
    [Gl Grni]                  NVARCHAR (20)   NULL,
    [Gl Gsni]                  DECIMAL (36, 4) NULL,
    [OMD_INSERT_DATETIME]      DATETIME2 (7)   NULL,
    [OMD_FILE_NAME]            VARCHAR (8000)  NULL,
    [OMD_HASH_FULL_RECORD]     VARCHAR (1000)  NULL
);

