CREATE TABLE [HSTG].[HSTG_EBS_MTL_ITEM_CATEGORIES] (
    [INVENTORY_ITEM_ID]            FLOAT (53)     NULL,
    [ORGANIZATION_ID]              FLOAT (53)     NULL,
    [CATEGORY_SET_ID]              FLOAT (53)     NULL,
    [CATEGORY_ID]                  FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]             DATETIME       NULL,
    [LAST_UPDATED_BY]              FLOAT (53)     NULL,
    [CREATION_DATE]                DATETIME       NULL,
    [CREATED_BY]                   FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]            FLOAT (53)     NULL,
    [REQUEST_ID]                   FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]       FLOAT (53)     NULL,
    [PROGRAM_ID]                   FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]          DATETIME       NULL,
    [WH_UPDATE_DATE]               DATETIME       NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_HSTG_EBS_MTL_ITEM_CATEGORIES_OMD_HASH_FULL_RECORD]
    ON [HSTG].[HSTG_EBS_MTL_ITEM_CATEGORIES]([OMD_HASH_FULL_RECORD] ASC)
    INCLUDE([OMD_IS_RECORD_DELETED], [OMD_CURRENT_RECORD_INDICATOR]);

