CREATE TABLE [HSTG].[HSTG_EBS_OE_ORDER_HEADERS_ALL] (
    [HEADER_ID]                      FLOAT (53)     NULL,
    [ORG_ID]                         FLOAT (53)     NULL,
    [ORDER_TYPE_ID]                  FLOAT (53)     NULL,
    [ORDER_NUMBER]                   FLOAT (53)     NULL,
    [VERSION_NUMBER]                 FLOAT (53)     NULL,
    [EXPIRATION_DATE]                DATETIME       NULL,
    [ORDER_SOURCE_ID]                FLOAT (53)     NULL,
    [SOURCE_DOCUMENT_TYPE_ID]        FLOAT (53)     NULL,
    [ORIG_SYS_DOCUMENT_REF]          VARCHAR (1000) NULL,
    [SOURCE_DOCUMENT_ID]             FLOAT (53)     NULL,
    [ORDERED_DATE]                   DATETIME       NULL,
    [REQUEST_DATE]                   DATETIME       NULL,
    [PRICING_DATE]                   DATETIME       NULL,
    [SHIPMENT_PRIORITY_CODE]         VARCHAR (100)  NULL,
    [DEMAND_CLASS_CODE]              VARCHAR (100)  NULL,
    [PRICE_LIST_ID]                  FLOAT (53)     NULL,
    [TAX_EXEMPT_FLAG]                VARCHAR (100)  NULL,
    [TAX_EXEMPT_NUMBER]              VARCHAR (1000) NULL,
    [TAX_EXEMPT_REASON_CODE]         VARCHAR (100)  NULL,
    [CONVERSION_RATE]                FLOAT (53)     NULL,
    [CONVERSION_TYPE_CODE]           VARCHAR (100)  NULL,
    [CONVERSION_RATE_DATE]           DATETIME       NULL,
    [PARTIAL_SHIPMENTS_ALLOWED]      VARCHAR (100)  NULL,
    [SHIP_TOLERANCE_ABOVE]           FLOAT (53)     NULL,
    [SHIP_TOLERANCE_BELOW]           FLOAT (53)     NULL,
    [TRANSACTIONAL_CURR_CODE]        VARCHAR (100)  NULL,
    [AGREEMENT_ID]                   FLOAT (53)     NULL,
    [TAX_POINT_CODE]                 VARCHAR (100)  NULL,
    [CUST_PO_NUMBER]                 VARCHAR (1000) NULL,
    [INVOICING_RULE_ID]              FLOAT (53)     NULL,
    [ACCOUNTING_RULE_ID]             FLOAT (53)     NULL,
    [PAYMENT_TERM_ID]                FLOAT (53)     NULL,
    [SHIPPING_METHOD_CODE]           VARCHAR (100)  NULL,
    [FREIGHT_CARRIER_CODE]           VARCHAR (100)  NULL,
    [FOB_POINT_CODE]                 VARCHAR (100)  NULL,
    [FREIGHT_TERMS_CODE]             VARCHAR (100)  NULL,
    [SOLD_FROM_ORG_ID]               FLOAT (53)     NULL,
    [SOLD_TO_ORG_ID]                 FLOAT (53)     NULL,
    [SHIP_FROM_ORG_ID]               FLOAT (53)     NULL,
    [SHIP_TO_ORG_ID]                 FLOAT (53)     NULL,
    [INVOICE_TO_ORG_ID]              FLOAT (53)     NULL,
    [DELIVER_TO_ORG_ID]              FLOAT (53)     NULL,
    [SOLD_TO_CONTACT_ID]             FLOAT (53)     NULL,
    [SHIP_TO_CONTACT_ID]             FLOAT (53)     NULL,
    [INVOICE_TO_CONTACT_ID]          FLOAT (53)     NULL,
    [DELIVER_TO_CONTACT_ID]          FLOAT (53)     NULL,
    [CREATION_DATE]                  DATETIME       NULL,
    [CREATED_BY]                     FLOAT (53)     NULL,
    [LAST_UPDATED_BY]                FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]               DATETIME       NULL,
    [LAST_UPDATE_LOGIN]              FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]         FLOAT (53)     NULL,
    [PROGRAM_ID]                     FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]            DATETIME       NULL,
    [REQUEST_ID]                     FLOAT (53)     NULL,
    [CONTEXT]                        VARCHAR (100)  NULL,
    [ATTRIBUTE1]                     VARCHAR (1000) NULL,
    [ATTRIBUTE2]                     VARCHAR (1000) NULL,
    [ATTRIBUTE3]                     VARCHAR (1000) NULL,
    [ATTRIBUTE4]                     VARCHAR (1000) NULL,
    [ATTRIBUTE5]                     VARCHAR (1000) NULL,
    [ATTRIBUTE6]                     VARCHAR (1000) NULL,
    [ATTRIBUTE7]                     VARCHAR (1000) NULL,
    [ATTRIBUTE8]                     VARCHAR (1000) NULL,
    [ATTRIBUTE9]                     VARCHAR (1000) NULL,
    [ATTRIBUTE10]                    VARCHAR (1000) NULL,
    [ATTRIBUTE11]                    VARCHAR (1000) NULL,
    [ATTRIBUTE12]                    VARCHAR (1000) NULL,
    [ATTRIBUTE13]                    VARCHAR (1000) NULL,
    [ATTRIBUTE14]                    VARCHAR (1000) NULL,
    [ATTRIBUTE15]                    VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE_CATEGORY]      VARCHAR (100)  NULL,
    [GLOBAL_ATTRIBUTE1]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE2]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE3]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE4]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE5]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE6]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE7]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE8]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE9]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE10]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE11]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE12]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE13]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE14]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE15]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE16]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE17]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE18]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE19]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE20]             VARCHAR (1000) NULL,
    [CANCELLED_FLAG]                 VARCHAR (100)  NULL,
    [OPEN_FLAG]                      VARCHAR (100)  NULL,
    [BOOKED_FLAG]                    VARCHAR (100)  NULL,
    [SALESREP_ID]                    FLOAT (53)     NULL,
    [RETURN_REASON_CODE]             VARCHAR (100)  NULL,
    [ORDER_DATE_TYPE_CODE]           VARCHAR (100)  NULL,
    [EARLIEST_SCHEDULE_LIMIT]        FLOAT (53)     NULL,
    [LATEST_SCHEDULE_LIMIT]          FLOAT (53)     NULL,
    [PAYMENT_TYPE_CODE]              VARCHAR (100)  NULL,
    [PAYMENT_AMOUNT]                 FLOAT (53)     NULL,
    [CHECK_NUMBER]                   VARCHAR (1000) NULL,
    [CREDIT_CARD_CODE]               VARCHAR (1000) NULL,
    [CREDIT_CARD_HOLDER_NAME]        VARCHAR (1000) NULL,
    [CREDIT_CARD_NUMBER]             VARCHAR (1000) NULL,
    [CREDIT_CARD_EXPIRATION_DATE]    DATETIME       NULL,
    [CREDIT_CARD_APPROVAL_CODE]      VARCHAR (1000) NULL,
    [SALES_CHANNEL_CODE]             VARCHAR (100)  NULL,
    [FIRST_ACK_CODE]                 VARCHAR (100)  NULL,
    [FIRST_ACK_DATE]                 DATETIME       NULL,
    [LAST_ACK_CODE]                  VARCHAR (100)  NULL,
    [LAST_ACK_DATE]                  DATETIME       NULL,
    [ORDER_CATEGORY_CODE]            VARCHAR (100)  NULL,
    [CHANGE_SEQUENCE]                VARCHAR (1000) NULL,
    [DROP_SHIP_FLAG]                 VARCHAR (100)  NULL,
    [CUSTOMER_PAYMENT_TERM_ID]       FLOAT (53)     NULL,
    [SHIPPING_INSTRUCTIONS]          VARCHAR (8000) NULL,
    [PACKING_INSTRUCTIONS]           VARCHAR (8000) NULL,
    [TP_CONTEXT]                     VARCHAR (100)  NULL,
    [TP_ATTRIBUTE1]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE2]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE3]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE4]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE5]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE6]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE7]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE8]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE9]                  VARCHAR (1000) NULL,
    [TP_ATTRIBUTE10]                 VARCHAR (1000) NULL,
    [TP_ATTRIBUTE11]                 VARCHAR (1000) NULL,
    [TP_ATTRIBUTE12]                 VARCHAR (1000) NULL,
    [TP_ATTRIBUTE13]                 VARCHAR (1000) NULL,
    [TP_ATTRIBUTE14]                 VARCHAR (1000) NULL,
    [TP_ATTRIBUTE15]                 VARCHAR (1000) NULL,
    [FLOW_STATUS_CODE]               VARCHAR (100)  NULL,
    [MARKETING_SOURCE_CODE_ID]       FLOAT (53)     NULL,
    [CREDIT_CARD_APPROVAL_DATE]      DATETIME       NULL,
    [UPGRADED_FLAG]                  VARCHAR (100)  NULL,
    [CUSTOMER_PREFERENCE_SET_CODE]   VARCHAR (100)  NULL,
    [BOOKED_DATE]                    DATETIME       NULL,
    [LOCK_CONTROL]                   FLOAT (53)     NULL,
    [PRICE_REQUEST_CODE]             VARCHAR (1000) NULL,
    [BATCH_ID]                       FLOAT (53)     NULL,
    [XML_MESSAGE_ID]                 FLOAT (53)     NULL,
    [ACCOUNTING_RULE_DURATION]       FLOAT (53)     NULL,
    [ATTRIBUTE16]                    VARCHAR (1000) NULL,
    [ATTRIBUTE17]                    VARCHAR (1000) NULL,
    [ATTRIBUTE18]                    VARCHAR (1000) NULL,
    [ATTRIBUTE19]                    VARCHAR (1000) NULL,
    [ATTRIBUTE20]                    VARCHAR (1000) NULL,
    [BLANKET_NUMBER]                 FLOAT (53)     NULL,
    [SALES_DOCUMENT_TYPE_CODE]       VARCHAR (100)  NULL,
    [SOLD_TO_PHONE_ID]               FLOAT (53)     NULL,
    [FULFILLMENT_SET_NAME]           VARCHAR (100)  NULL,
    [LINE_SET_NAME]                  VARCHAR (100)  NULL,
    [DEFAULT_FULFILLMENT_SET]        VARCHAR (100)  NULL,
    [TRANSACTION_PHASE_CODE]         VARCHAR (100)  NULL,
    [SALES_DOCUMENT_NAME]            VARCHAR (1000) NULL,
    [QUOTE_NUMBER]                   FLOAT (53)     NULL,
    [QUOTE_DATE]                     DATETIME       NULL,
    [USER_STATUS_CODE]               VARCHAR (100)  NULL,
    [DRAFT_SUBMITTED_FLAG]           VARCHAR (100)  NULL,
    [SOURCE_DOCUMENT_VERSION_NUMBER] FLOAT (53)     NULL,
    [SOLD_TO_SITE_USE_ID]            FLOAT (53)     NULL,
    [SUPPLIER_SIGNATURE]             VARCHAR (1000) NULL,
    [SUPPLIER_SIGNATURE_DATE]        DATETIME       NULL,
    [CUSTOMER_SIGNATURE]             VARCHAR (1000) NULL,
    [CUSTOMER_SIGNATURE_DATE]        DATETIME       NULL,
    [MINISITE_ID]                    FLOAT (53)     NULL,
    [END_CUSTOMER_ID]                FLOAT (53)     NULL,
    [END_CUSTOMER_CONTACT_ID]        FLOAT (53)     NULL,
    [END_CUSTOMER_SITE_USE_ID]       FLOAT (53)     NULL,
    [IB_OWNER]                       VARCHAR (1000) NULL,
    [IB_CURRENT_LOCATION]            VARCHAR (1000) NULL,
    [IB_INSTALLED_AT_LOCATION]       VARCHAR (1000) NULL,
    [ORDER_FIRMED_DATE]              DATETIME       NULL,
    [OMD_INSERT_DATETIME]            DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                  VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]           VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]          VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR]   VARCHAR (1)    NULL
);

