CREATE TABLE [HSTG].[HSTG_EBS_HZ_CUST_ACCOUNTS_ALL] (
    [CUST_ACCOUNT_ID]                FLOAT (53)     NULL,
    [PARTY_ID]                       FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]               DATETIME       NULL,
    [ACCOUNT_NUMBER]                 VARCHAR (100)  NULL,
    [LAST_UPDATED_BY]                FLOAT (53)     NULL,
    [CREATION_DATE]                  DATETIME       NULL,
    [CREATED_BY]                     FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]              FLOAT (53)     NULL,
    [REQUEST_ID]                     FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]         FLOAT (53)     NULL,
    [PROGRAM_ID]                     FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]            DATETIME       NULL,
    [WH_UPDATE_DATE]                 DATETIME       NULL,
    [ATTRIBUTE_CATEGORY]             VARCHAR (100)  NULL,
    [ATTRIBUTE1]                     VARCHAR (1000) NULL,
    [ATTRIBUTE2]                     VARCHAR (1000) NULL,
    [ATTRIBUTE3]                     VARCHAR (1000) NULL,
    [ATTRIBUTE4]                     VARCHAR (1000) NULL,
    [ATTRIBUTE5]                     VARCHAR (1000) NULL,
    [ATTRIBUTE6]                     VARCHAR (1000) NULL,
    [ATTRIBUTE7]                     VARCHAR (1000) NULL,
    [ATTRIBUTE8]                     VARCHAR (1000) NULL,
    [ATTRIBUTE9]                     VARCHAR (1000) NULL,
    [ATTRIBUTE10]                    VARCHAR (1000) NULL,
    [ATTRIBUTE11]                    VARCHAR (1000) NULL,
    [ATTRIBUTE12]                    VARCHAR (1000) NULL,
    [ATTRIBUTE13]                    VARCHAR (1000) NULL,
    [ATTRIBUTE14]                    VARCHAR (1000) NULL,
    [ATTRIBUTE15]                    VARCHAR (1000) NULL,
    [ATTRIBUTE16]                    VARCHAR (1000) NULL,
    [ATTRIBUTE17]                    VARCHAR (1000) NULL,
    [ATTRIBUTE18]                    VARCHAR (1000) NULL,
    [ATTRIBUTE19]                    VARCHAR (1000) NULL,
    [ATTRIBUTE20]                    VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE_CATEGORY]      VARCHAR (100)  NULL,
    [GLOBAL_ATTRIBUTE1]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE2]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE3]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE4]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE5]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE6]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE7]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE8]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE9]              VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE10]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE11]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE12]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE13]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE14]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE15]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE16]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE17]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE18]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE19]             VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE20]             VARCHAR (1000) NULL,
    [ORIG_SYSTEM_REFERENCE]          VARCHAR (1000) NULL,
    [STATUS]                         VARCHAR (100)  NULL,
    [CUSTOMER_TYPE]                  VARCHAR (100)  NULL,
    [CUSTOMER_CLASS_CODE]            VARCHAR (100)  NULL,
    [PRIMARY_SALESREP_ID]            FLOAT (53)     NULL,
    [SALES_CHANNEL_CODE]             VARCHAR (100)  NULL,
    [ORDER_TYPE_ID]                  FLOAT (53)     NULL,
    [PRICE_LIST_ID]                  FLOAT (53)     NULL,
    [SUBCATEGORY_CODE]               VARCHAR (100)  NULL,
    [TAX_CODE]                       VARCHAR (1000) NULL,
    [FOB_POINT]                      VARCHAR (100)  NULL,
    [FREIGHT_TERM]                   VARCHAR (100)  NULL,
    [SHIP_PARTIAL]                   VARCHAR (100)  NULL,
    [SHIP_VIA]                       VARCHAR (100)  NULL,
    [WAREHOUSE_ID]                   FLOAT (53)     NULL,
    [PAYMENT_TERM_ID]                FLOAT (53)     NULL,
    [TAX_HEADER_LEVEL_FLAG]          VARCHAR (100)  NULL,
    [TAX_ROUNDING_RULE]              VARCHAR (100)  NULL,
    [COTERMINATE_DAY_MONTH]          VARCHAR (100)  NULL,
    [PRIMARY_SPECIALIST_ID]          FLOAT (53)     NULL,
    [SECONDARY_SPECIALIST_ID]        FLOAT (53)     NULL,
    [ACCOUNT_LIABLE_FLAG]            VARCHAR (100)  NULL,
    [RESTRICTION_LIMIT_AMOUNT]       FLOAT (53)     NULL,
    [CURRENT_BALANCE]                FLOAT (53)     NULL,
    [PASSWORD_TEXT]                  VARCHAR (1000) NULL,
    [HIGH_PRIORITY_INDICATOR]        VARCHAR (100)  NULL,
    [ACCOUNT_ESTABLISHED_DATE]       DATETIME       NULL,
    [ACCOUNT_TERMINATION_DATE]       DATETIME       NULL,
    [ACCOUNT_ACTIVATION_DATE]        DATETIME       NULL,
    [CREDIT_CLASSIFICATION_CODE]     VARCHAR (100)  NULL,
    [DEPARTMENT]                     VARCHAR (100)  NULL,
    [MAJOR_ACCOUNT_NUMBER]           VARCHAR (100)  NULL,
    [HOTWATCH_SERVICE_FLAG]          VARCHAR (100)  NULL,
    [HOTWATCH_SVC_BAL_IND]           VARCHAR (100)  NULL,
    [HELD_BILL_EXPIRATION_DATE]      DATETIME       NULL,
    [HOLD_BILL_FLAG]                 VARCHAR (100)  NULL,
    [HIGH_PRIORITY_REMARKS]          VARCHAR (1000) NULL,
    [PO_EFFECTIVE_DATE]              DATETIME       NULL,
    [PO_EXPIRATION_DATE]             DATETIME       NULL,
    [REALTIME_RATE_FLAG]             VARCHAR (100)  NULL,
    [SINGLE_USER_FLAG]               VARCHAR (100)  NULL,
    [WATCH_ACCOUNT_FLAG]             VARCHAR (100)  NULL,
    [WATCH_BALANCE_INDICATOR]        VARCHAR (100)  NULL,
    [GEO_CODE]                       VARCHAR (100)  NULL,
    [ACCT_LIFE_CYCLE_STATUS]         VARCHAR (100)  NULL,
    [ACCOUNT_NAME]                   VARCHAR (1000) NULL,
    [DEPOSIT_REFUND_METHOD]          VARCHAR (100)  NULL,
    [DORMANT_ACCOUNT_FLAG]           VARCHAR (100)  NULL,
    [NPA_NUMBER]                     VARCHAR (1000) NULL,
    [PIN_NUMBER]                     FLOAT (53)     NULL,
    [SUSPENSION_DATE]                DATETIME       NULL,
    [WRITE_OFF_ADJUSTMENT_AMOUNT]    FLOAT (53)     NULL,
    [WRITE_OFF_PAYMENT_AMOUNT]       FLOAT (53)     NULL,
    [WRITE_OFF_AMOUNT]               FLOAT (53)     NULL,
    [SOURCE_CODE]                    VARCHAR (1000) NULL,
    [COMPETITOR_TYPE]                VARCHAR (1000) NULL,
    [COMMENTS]                       VARCHAR (1000) NULL,
    [DATES_NEGATIVE_TOLERANCE]       FLOAT (53)     NULL,
    [DATES_POSITIVE_TOLERANCE]       FLOAT (53)     NULL,
    [DATE_TYPE_PREFERENCE]           VARCHAR (100)  NULL,
    [OVER_SHIPMENT_TOLERANCE]        FLOAT (53)     NULL,
    [UNDER_SHIPMENT_TOLERANCE]       FLOAT (53)     NULL,
    [OVER_RETURN_TOLERANCE]          FLOAT (53)     NULL,
    [UNDER_RETURN_TOLERANCE]         FLOAT (53)     NULL,
    [ITEM_CROSS_REF_PREF]            VARCHAR (100)  NULL,
    [SHIP_SETS_INCLUDE_LINES_FLAG]   VARCHAR (100)  NULL,
    [ARRIVALSETS_INCLUDE_LINES_FLAG] VARCHAR (100)  NULL,
    [SCHED_DATE_PUSH_FLAG]           VARCHAR (100)  NULL,
    [INVOICE_QUANTITY_RULE]          VARCHAR (100)  NULL,
    [PRICING_EVENT]                  VARCHAR (100)  NULL,
    [ACCOUNT_REPLICATION_KEY]        FLOAT (53)     NULL,
    [STATUS_UPDATE_DATE]             DATETIME       NULL,
    [AUTOPAY_FLAG]                   VARCHAR (100)  NULL,
    [NOTIFY_FLAG]                    VARCHAR (100)  NULL,
    [LAST_BATCH_ID]                  FLOAT (53)     NULL,
    [ORG_ID]                         FLOAT (53)     NULL,
    [OBJECT_VERSION_NUMBER]          FLOAT (53)     NULL,
    [CREATED_BY_MODULE]              VARCHAR (1000) NULL,
    [APPLICATION_ID]                 FLOAT (53)     NULL,
    [SELLING_PARTY_ID]               FLOAT (53)     NULL,
    [OMD_INSERT_DATETIME]            DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                  VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]           VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]          VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR]   VARCHAR (1)    NULL
);

