CREATE TABLE [HSTG].[HSTG_EBS_HZ_CUST_ACCT_SITES_ALL] (
    [CUST_ACCT_SITE_ID]            FLOAT (53)     NULL,
    [CUST_ACCOUNT_ID]              FLOAT (53)     NULL,
    [PARTY_SITE_ID]                FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]             DATETIME       NULL,
    [LAST_UPDATED_BY]              FLOAT (53)     NULL,
    [CREATION_DATE]                DATETIME       NULL,
    [CREATED_BY]                   FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]            FLOAT (53)     NULL,
    [REQUEST_ID]                   FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]       FLOAT (53)     NULL,
    [PROGRAM_ID]                   FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]          DATETIME       NULL,
    [WH_UPDATE_DATE]               DATETIME       NULL,
    [ATTRIBUTE_CATEGORY]           VARCHAR (100)  NULL,
    [ATTRIBUTE1]                   VARCHAR (1000) NULL,
    [ATTRIBUTE2]                   VARCHAR (1000) NULL,
    [ATTRIBUTE3]                   VARCHAR (1000) NULL,
    [ATTRIBUTE4]                   VARCHAR (1000) NULL,
    [ATTRIBUTE5]                   VARCHAR (1000) NULL,
    [ATTRIBUTE6]                   VARCHAR (1000) NULL,
    [ATTRIBUTE7]                   VARCHAR (1000) NULL,
    [ATTRIBUTE8]                   VARCHAR (1000) NULL,
    [ATTRIBUTE9]                   VARCHAR (1000) NULL,
    [ATTRIBUTE10]                  VARCHAR (1000) NULL,
    [ATTRIBUTE11]                  VARCHAR (1000) NULL,
    [ATTRIBUTE12]                  VARCHAR (1000) NULL,
    [ATTRIBUTE13]                  VARCHAR (1000) NULL,
    [ATTRIBUTE14]                  VARCHAR (1000) NULL,
    [ATTRIBUTE15]                  VARCHAR (1000) NULL,
    [ATTRIBUTE16]                  VARCHAR (1000) NULL,
    [ATTRIBUTE17]                  VARCHAR (1000) NULL,
    [ATTRIBUTE18]                  VARCHAR (1000) NULL,
    [ATTRIBUTE19]                  VARCHAR (1000) NULL,
    [ATTRIBUTE20]                  VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE_CATEGORY]    VARCHAR (100)  NULL,
    [GLOBAL_ATTRIBUTE1]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE2]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE3]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE4]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE5]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE6]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE7]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE8]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE9]            VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE10]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE11]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE12]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE13]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE14]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE15]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE16]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE17]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE18]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE19]           VARCHAR (1000) NULL,
    [GLOBAL_ATTRIBUTE20]           VARCHAR (1000) NULL,
    [ORIG_SYSTEM_REFERENCE]        VARCHAR (1000) NULL,
    [STATUS]                       VARCHAR (100)  NULL,
    [ORG_ID]                       FLOAT (53)     NULL,
    [BILL_TO_FLAG]                 VARCHAR (100)  NULL,
    [MARKET_FLAG]                  VARCHAR (100)  NULL,
    [SHIP_TO_FLAG]                 VARCHAR (100)  NULL,
    [CUSTOMER_CATEGORY_CODE]       VARCHAR (100)  NULL,
    [LANGUAGE]                     VARCHAR (100)  NULL,
    [KEY_ACCOUNT_FLAG]             VARCHAR (100)  NULL,
    [TP_HEADER_ID]                 FLOAT (53)     NULL,
    [ECE_TP_LOCATION_CODE]         VARCHAR (100)  NULL,
    [SERVICE_TERRITORY_ID]         FLOAT (53)     NULL,
    [PRIMARY_SPECIALIST_ID]        FLOAT (53)     NULL,
    [SECONDARY_SPECIALIST_ID]      FLOAT (53)     NULL,
    [TERRITORY_ID]                 FLOAT (53)     NULL,
    [ADDRESS_TEXT]                 VARCHAR (4000) NULL,
    [TERRITORY]                    VARCHAR (100)  NULL,
    [TRANSLATED_CUSTOMER_NAME]     VARCHAR (1000) NULL,
    [OBJECT_VERSION_NUMBER]        FLOAT (53)     NULL,
    [CREATED_BY_MODULE]            VARCHAR (1000) NULL,
    [APPLICATION_ID]               FLOAT (53)     NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)    NULL
);

