CREATE TABLE [HSTG].[HSTG_EBS_RD_BI_INV_VALUES_RPT] (
    [DC]                            VARCHAR (1000) NULL,
    [SUBINV_NAME]                   VARCHAR (1000) NULL,
    [LOCATOR_CODE]                  VARCHAR (1000) NULL,
    [ITEM_CODE]                     VARCHAR (1000) NULL,
    [CATEGORY_CODE]                 VARCHAR (1000) NULL,
    [STOCK_QTY]                     FLOAT (53)     NULL,
    [INTRANSIT_QTY]                 FLOAT (53)     NULL,
    [RECEIVING_QTY]                 FLOAT (53)     NULL,
    [STOCK_VALUE]                   FLOAT (53)     NULL,
    [INTRANSIT_VALUE]               FLOAT (53)     NULL,
    [RECEIVING_VALUE]               FLOAT (53)     NULL,
    [ITEM_COST]                     FLOAT (53)     NULL,
    [AS_OF_DATE]                    DATETIME2 (7)  NULL,
    [CREATION_DATE]                 DATETIME2 (7)  NULL,
    [TOTAL_QTY]                     FLOAT (53)     NULL,
    [UNRECEIVED_PO_QTY]             FLOAT (53)     NULL,
    [BO_QTY]                        FLOAT (53)     NULL,
    [META_RECORD_KEY]               VARCHAR (1000) NULL,
    [META_EFFECTIVE_DATETIME]       DATETIME2 (7)  NULL,
    [META_EXPIRY_DATETIME]          DATETIME2 (7)  NULL,
    [META_CDC_OPERATION]            VARCHAR (1000) NULL,
    [META_FILE_NAME]                VARCHAR (8000) NULL,
    [META_CURRENT_RECORD_INDICATOR] VARCHAR (1)    NULL,
    [META_DELETE_INDICATOR]         VARCHAR (1)    NULL,
    [META_RECORD_CHECKSUM]          VARCHAR (1000) NULL,
    [META_RECORD_SOURCE]            VARCHAR (8000) NULL,
    [META_ROW_ID]                   BIGINT         IDENTITY (1, 1) NOT NULL
);

