CREATE TABLE [HSTG].[HSTG_CA_INRFCLIN] (
    [Rfc#]                         DECIMAL (36, 4) NULL,
    [Rfcl]                         DECIMAL (36, 4) NULL,
    [Item Code]                    NVARCHAR (100)  NULL,
    [Buy Price]                    DECIMAL (36, 4) NULL,
    [Return Qty]                   DECIMAL (36, 4) NULL,
    [Cogs Value]                   DECIMAL (36, 4) NULL,
    [Comment]                      NVARCHAR (2000) NULL,
    [Start Date]                   DATE            NULL,
    [STime]                        TIME (7)        NULL,
    [Start By]                     NVARCHAR (100)  NULL,
    [Amend Date]                   DATE            NULL,
    [ATime]                        TIME (7)        NULL,
    [Amend By]                     NVARCHAR (100)  NULL,
    [Loc]                          NVARCHAR (100)  NULL,
    [Sup#]                         DECIMAL (36, 4) NULL,
    [Spn]                          NVARCHAR (100)  NULL,
    [Po Delivery Ref]              NVARCHAR (100)  NULL,
    [Po#]                          DECIMAL (36, 4) NULL,
    [Pol#]                         DECIMAL (36, 4) NULL,
    [Po BuyPrice]                  DECIMAL (36, 4) NULL,
    [Po Invoice Ref]               NVARCHAR (100)  NULL,
    [Credit Qty]                   DECIMAL (36, 4) NULL,
    [Credit Cogs]                  DECIMAL (36, 4) NULL,
    [Glacct#]                      NVARCHAR (100)  NULL,
    [LMatMeth]                     NVARCHAR (100)  NULL,
    [Matched Reference]            NVARCHAR (100)  NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000)  NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000)  NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)     NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)     NULL
);

