CREATE TABLE [HSTG].[HSTG_CA_INLOCAT] (
    [Item Code]                    NVARCHAR (100)  NULL,
    [Loc]                          DECIMAL (36, 4) NULL,
    [Value @ Cost]                 DECIMAL (36, 4) NULL,
    [Stock Qty]                    DECIMAL (36, 4) NULL,
    [Loc Lst Buy]                  DECIMAL (36, 4) NULL,
    [MinLev]                       DECIMAL (36, 4) NULL,
    [MaxLev]                       DECIMAL (36, 4) NULL,
    [Commit Qty]                   DECIMAL (36, 4) NULL,
    [Po Qty]                       DECIMAL (36, 4) NULL,
    [Last Sale]                    DATE            NULL,
    [2ndLstSale]                   DATE            NULL,
    [Sales 1]                      DECIMAL (36, 4) NULL,
    [Sales 2]                      DECIMAL (36, 4) NULL,
    [Sales 3]                      DECIMAL (36, 4) NULL,
    [Sales 4]                      DECIMAL (36, 4) NULL,
    [Sales 5]                      DECIMAL (36, 4) NULL,
    [Sales 6]                      DECIMAL (36, 4) NULL,
    [Sales 7]                      DECIMAL (36, 4) NULL,
    [Sales 8]                      DECIMAL (36, 4) NULL,
    [Sales 9]                      DECIMAL (36, 4) NULL,
    [Sales 10]                     DECIMAL (36, 4) NULL,
    [Sales 11]                     DECIMAL (36, 4) NULL,
    [Sales 12]                     DECIMAL (36, 4) NULL,
    [Sales 13]                     DECIMAL (36, 4) NULL,
    [Sales 14]                     DECIMAL (36, 4) NULL,
    [Sales 15]                     DECIMAL (36, 4) NULL,
    [Sales 16]                     DECIMAL (36, 4) NULL,
    [Sales 17]                     DECIMAL (36, 4) NULL,
    [Sales 18]                     DECIMAL (36, 4) NULL,
    [Sales 19]                     DECIMAL (36, 4) NULL,
    [Sales 20]                     DECIMAL (36, 4) NULL,
    [Sales 21]                     DECIMAL (36, 4) NULL,
    [Sales 22]                     DECIMAL (36, 4) NULL,
    [Sales 23]                     DECIMAL (36, 4) NULL,
    [Sales 24]                     DECIMAL (36, 4) NULL,
    [Purch 1]                      DECIMAL (36, 4) NULL,
    [Purch 2]                      DECIMAL (36, 4) NULL,
    [Purch 3]                      DECIMAL (36, 4) NULL,
    [Purch 4]                      DECIMAL (36, 4) NULL,
    [Purch 5]                      DECIMAL (36, 4) NULL,
    [Purch 6]                      DECIMAL (36, 4) NULL,
    [Purch 7]                      DECIMAL (36, 4) NULL,
    [Purch 8]                      DECIMAL (36, 4) NULL,
    [Purch 9]                      DECIMAL (36, 4) NULL,
    [Purch 10]                     DECIMAL (36, 4) NULL,
    [Purch 11]                     DECIMAL (36, 4) NULL,
    [Purch 12]                     DECIMAL (36, 4) NULL,
    [Purch 13]                     DECIMAL (36, 4) NULL,
    [Purch 14]                     DECIMAL (36, 4) NULL,
    [Purch 15]                     DECIMAL (36, 4) NULL,
    [Purch 16]                     DECIMAL (36, 4) NULL,
    [Purch 17]                     DECIMAL (36, 4) NULL,
    [Purch 18]                     DECIMAL (36, 4) NULL,
    [Purch 19]                     DECIMAL (36, 4) NULL,
    [Purch 20]                     DECIMAL (36, 4) NULL,
    [Purch 21]                     DECIMAL (36, 4) NULL,
    [Purch 22]                     DECIMAL (36, 4) NULL,
    [Purch 23]                     DECIMAL (36, 4) NULL,
    [Purch 24]                     DECIMAL (36, 4) NULL,
    [Cogs 1]                       DECIMAL (36, 4) NULL,
    [Cogs 2]                       DECIMAL (36, 4) NULL,
    [Cogs 3]                       DECIMAL (36, 4) NULL,
    [Cogs 4]                       DECIMAL (36, 4) NULL,
    [Cogs 5]                       DECIMAL (36, 4) NULL,
    [Cogs 6]                       DECIMAL (36, 4) NULL,
    [Cogs 7]                       DECIMAL (36, 4) NULL,
    [Cogs 8]                       DECIMAL (36, 4) NULL,
    [Cogs 9]                       DECIMAL (36, 4) NULL,
    [Cogs 10]                      DECIMAL (36, 4) NULL,
    [Cogs 11]                      DECIMAL (36, 4) NULL,
    [Cogs 12]                      DECIMAL (36, 4) NULL,
    [Cogs 13]                      DECIMAL (36, 4) NULL,
    [Cogs 14]                      DECIMAL (36, 4) NULL,
    [Cogs 15]                      DECIMAL (36, 4) NULL,
    [Cogs 16]                      DECIMAL (36, 4) NULL,
    [Cogs 17]                      DECIMAL (36, 4) NULL,
    [Cogs 18]                      DECIMAL (36, 4) NULL,
    [Cogs 19]                      DECIMAL (36, 4) NULL,
    [Cogs 20]                      DECIMAL (36, 4) NULL,
    [Cogs 21]                      DECIMAL (36, 4) NULL,
    [Cogs 22]                      DECIMAL (36, 4) NULL,
    [Cogs 23]                      DECIMAL (36, 4) NULL,
    [Cogs 24]                      DECIMAL (36, 4) NULL,
    [Sale Qty 1]                   DECIMAL (36, 4) NULL,
    [Sale Qty 2]                   DECIMAL (36, 4) NULL,
    [Sale Qty 3]                   DECIMAL (36, 4) NULL,
    [Sale Qty 4]                   DECIMAL (36, 4) NULL,
    [Sale Qty 5]                   DECIMAL (36, 4) NULL,
    [Sale Qty 6]                   DECIMAL (36, 4) NULL,
    [Sale Qty 7]                   DECIMAL (36, 4) NULL,
    [Sale Qty 8]                   DECIMAL (36, 4) NULL,
    [Sale Qty 9]                   DECIMAL (36, 4) NULL,
    [Sale Qty 10]                  DECIMAL (36, 4) NULL,
    [Sale Qty 11]                  DECIMAL (36, 4) NULL,
    [Sale Qty 12]                  DECIMAL (36, 4) NULL,
    [Sale Qty 13]                  DECIMAL (36, 4) NULL,
    [Sale Qty 14]                  DECIMAL (36, 4) NULL,
    [Sale Qty 15]                  DECIMAL (36, 4) NULL,
    [Sale Qty 16]                  DECIMAL (36, 4) NULL,
    [Sale Qty 17]                  DECIMAL (36, 4) NULL,
    [Sale Qty 18]                  DECIMAL (36, 4) NULL,
    [Sale Qty 19]                  DECIMAL (36, 4) NULL,
    [Sale Qty 20]                  DECIMAL (36, 4) NULL,
    [Sale Qty 21]                  DECIMAL (36, 4) NULL,
    [Sale Qty 22]                  DECIMAL (36, 4) NULL,
    [Sale Qty 23]                  DECIMAL (36, 4) NULL,
    [Sale Qty 24]                  DECIMAL (36, 4) NULL,
    [Last Stake]                   DATE            NULL,
    [LstStk Qoh]                   DECIMAL (36, 4) NULL,
    [Curr Stake]                   DATE            NULL,
    [CurStk QOH]                   DECIMAL (36, 4) NULL,
    [Frozen Qoh]                   DECIMAL (36, 4) NULL,
    [Incat]                        NVARCHAR (100)  NULL,
    [Last Purch]                   DATE            NULL,
    [StockTurns]                   DECIMAL (36, 4) NULL,
    [Gross Mgn]                    DECIMAL (36, 4) NULL,
    [Gmroi]                        DECIMAL (36, 4) NULL,
    [LSup]                         DECIMAL (36, 4) NULL,
    [PurQty 1]                     DECIMAL (36, 4) NULL,
    [PurQty 2]                     DECIMAL (36, 4) NULL,
    [PurQty 3]                     DECIMAL (36, 4) NULL,
    [PurQty 4]                     DECIMAL (36, 4) NULL,
    [PurQty 5]                     DECIMAL (36, 4) NULL,
    [PurQty 6]                     DECIMAL (36, 4) NULL,
    [PurQty 7]                     DECIMAL (36, 4) NULL,
    [PurQty 8]                     DECIMAL (36, 4) NULL,
    [PurQty 9]                     DECIMAL (36, 4) NULL,
    [PurQty10]                     DECIMAL (36, 4) NULL,
    [PurQty11]                     DECIMAL (36, 4) NULL,
    [PurQty12]                     DECIMAL (36, 4) NULL,
    [PurQty13]                     DECIMAL (36, 4) NULL,
    [PurQty14]                     DECIMAL (36, 4) NULL,
    [PurQty15]                     DECIMAL (36, 4) NULL,
    [PurQty16]                     DECIMAL (36, 4) NULL,
    [PurQty17]                     DECIMAL (36, 4) NULL,
    [PurQty18]                     DECIMAL (36, 4) NULL,
    [PurQty19]                     DECIMAL (36, 4) NULL,
    [PurQty20]                     DECIMAL (36, 4) NULL,
    [PurQty21]                     DECIMAL (36, 4) NULL,
    [PurQty22]                     DECIMAL (36, 4) NULL,
    [PurQty23]                     DECIMAL (36, 4) NULL,
    [PurQty24]                     DECIMAL (36, 4) NULL,
    [Frozen Vac]                   DECIMAL (36, 4) NULL,
    [FrozLstBuy]                   DECIMAL (36, 4) NULL,
    [Border Qty]                   DECIMAL (36, 4) NULL,
    [P]                            NVARCHAR (1)    NULL,
    [S]                            NVARCHAR (1)    NULL,
    [O]                            NVARCHAR (1)    NULL,
    [Qoh Eop]                      DECIMAL (36, 4) NULL,
    [Vac Eop]                      DECIMAL (36, 4) NULL,
    [ObsFlagUpd]                   DATE            NULL,
    [1st Purch]                    DATE            NULL,
    [TrOpen Qty]                   DECIMAL (36, 4) NULL,
    [PerfSetDat]                   DATE            NULL,
    [TfrUnaccQty]                  DECIMAL (36, 4) NULL,
    [LowMin]                       DECIMAL (36, 4) NULL,
    [GrniBal Qty]                  DECIMAL (36, 4) NULL,
    [GrniBal Val]                  DECIMAL (36, 4) NULL,
    [GsniBal Qty]                  DECIMAL (36, 4) NULL,
    [GsniBal Val]                  DECIMAL (36, 4) NULL,
    [Start Date]                   DATE            NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000)  NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000)  NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)     NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)     NULL
);

