CREATE TABLE [HSTG].[HSTG_EBS_HR_ALL_ORGANIZATION_UNITS] (
    [ORGANIZATION_ID]              FLOAT (53)     NULL,
    [BUSINESS_GROUP_ID]            FLOAT (53)     NULL,
    [COST_ALLOCATION_KEYFLEX_ID]   FLOAT (53)     NULL,
    [LOCATION_ID]                  FLOAT (53)     NULL,
    [SOFT_CODING_KEYFLEX_ID]       FLOAT (53)     NULL,
    [DATE_FROM]                    DATETIME       NULL,
    [NAME]                         VARCHAR (1000) NULL,
    [DATE_TO]                      DATETIME       NULL,
    [INTERNAL_EXTERNAL_FLAG]       VARCHAR (100)  NULL,
    [INTERNAL_ADDRESS_LINE]        VARCHAR (1000) NULL,
    [TYPE]                         VARCHAR (100)  NULL,
    [REQUEST_ID]                   FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]       FLOAT (53)     NULL,
    [PROGRAM_ID]                   FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]          DATETIME       NULL,
    [ATTRIBUTE_CATEGORY]           VARCHAR (100)  NULL,
    [ATTRIBUTE1]                   VARCHAR (1000) NULL,
    [ATTRIBUTE2]                   VARCHAR (1000) NULL,
    [ATTRIBUTE3]                   VARCHAR (1000) NULL,
    [ATTRIBUTE4]                   VARCHAR (1000) NULL,
    [ATTRIBUTE5]                   VARCHAR (1000) NULL,
    [ATTRIBUTE6]                   VARCHAR (1000) NULL,
    [ATTRIBUTE7]                   VARCHAR (1000) NULL,
    [ATTRIBUTE8]                   VARCHAR (1000) NULL,
    [ATTRIBUTE9]                   VARCHAR (1000) NULL,
    [ATTRIBUTE10]                  VARCHAR (1000) NULL,
    [ATTRIBUTE11]                  VARCHAR (1000) NULL,
    [ATTRIBUTE12]                  VARCHAR (1000) NULL,
    [ATTRIBUTE13]                  VARCHAR (1000) NULL,
    [ATTRIBUTE14]                  VARCHAR (1000) NULL,
    [ATTRIBUTE15]                  VARCHAR (1000) NULL,
    [ATTRIBUTE16]                  VARCHAR (1000) NULL,
    [ATTRIBUTE17]                  VARCHAR (1000) NULL,
    [ATTRIBUTE18]                  VARCHAR (1000) NULL,
    [ATTRIBUTE19]                  VARCHAR (1000) NULL,
    [ATTRIBUTE20]                  VARCHAR (1000) NULL,
    [LAST_UPDATE_DATE]             DATETIME       NULL,
    [LAST_UPDATED_BY]              FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]            FLOAT (53)     NULL,
    [CREATED_BY]                   FLOAT (53)     NULL,
    [CREATION_DATE]                DATETIME       NULL,
    [OBJECT_VERSION_NUMBER]        FLOAT (53)     NULL,
    [PARTY_ID]                     FLOAT (53)     NULL,
    [COMMENTS]                     VARCHAR (8000) NULL,
    [ATTRIBUTE21]                  VARCHAR (1000) NULL,
    [ATTRIBUTE22]                  VARCHAR (1000) NULL,
    [ATTRIBUTE23]                  VARCHAR (1000) NULL,
    [ATTRIBUTE24]                  VARCHAR (1000) NULL,
    [ATTRIBUTE25]                  VARCHAR (1000) NULL,
    [ATTRIBUTE26]                  VARCHAR (1000) NULL,
    [ATTRIBUTE27]                  VARCHAR (1000) NULL,
    [ATTRIBUTE28]                  VARCHAR (1000) NULL,
    [ATTRIBUTE29]                  VARCHAR (1000) NULL,
    [ATTRIBUTE30]                  VARCHAR (1000) NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_HSTG_EBS_HR_ALL_ORGANIZATION_UNITS_OMD_HASH_FULL_RECORD]
    ON [HSTG].[HSTG_EBS_HR_ALL_ORGANIZATION_UNITS]([OMD_HASH_FULL_RECORD] ASC)
    INCLUDE([OMD_IS_RECORD_DELETED], [OMD_CURRENT_RECORD_INDICATOR]);

