CREATE TABLE [HSTG].[HSTG_EBS_IBY_EXTERNAL_PAYEES_ALL] (
    [EXT_PAYEE_ID]                 FLOAT (53)     NULL,
    [PAYEE_PARTY_ID]               FLOAT (53)     NULL,
    [PAYMENT_FUNCTION]             VARCHAR (100)  NULL,
    [EXCLUSIVE_PAYMENT_FLAG]       VARCHAR (100)  NULL,
    [CREATED_BY]                   FLOAT (53)     NULL,
    [CREATION_DATE]                DATETIME       NULL,
    [LAST_UPDATED_BY]              FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]             DATETIME       NULL,
    [LAST_UPDATE_LOGIN]            FLOAT (53)     NULL,
    [OBJECT_VERSION_NUMBER]        FLOAT (53)     NULL,
    [PARTY_SITE_ID]                FLOAT (53)     NULL,
    [SUPPLIER_SITE_ID]             FLOAT (53)     NULL,
    [ORG_ID]                       FLOAT (53)     NULL,
    [ORG_TYPE]                     VARCHAR (100)  NULL,
    [DEFAULT_PAYMENT_METHOD_CODE]  VARCHAR (100)  NULL,
    [ECE_TP_LOCATION_CODE]         VARCHAR (1000) NULL,
    [BANK_CHARGE_BEARER]           VARCHAR (100)  NULL,
    [BANK_INSTRUCTION1_CODE]       VARCHAR (100)  NULL,
    [BANK_INSTRUCTION2_CODE]       VARCHAR (100)  NULL,
    [BANK_INSTRUCTION_DETAILS]     VARCHAR (1000) NULL,
    [PAYMENT_REASON_CODE]          VARCHAR (100)  NULL,
    [PAYMENT_REASON_COMMENTS]      VARCHAR (1000) NULL,
    [INACTIVE_DATE]                DATETIME       NULL,
    [PAYMENT_TEXT_MESSAGE1]        VARCHAR (1000) NULL,
    [PAYMENT_TEXT_MESSAGE2]        VARCHAR (1000) NULL,
    [PAYMENT_TEXT_MESSAGE3]        VARCHAR (1000) NULL,
    [DELIVERY_CHANNEL_CODE]        VARCHAR (100)  NULL,
    [PAYMENT_FORMAT_CODE]          VARCHAR (100)  NULL,
    [SETTLEMENT_PRIORITY]          VARCHAR (100)  NULL,
    [REMIT_ADVICE_DELIVERY_METHOD] VARCHAR (100)  NULL,
    [REMIT_ADVICE_EMAIL]           VARCHAR (1000) NULL,
    [REMIT_ADVICE_FAX]             VARCHAR (1000) NULL,
    [SERVICE_LEVEL_CODE]           VARCHAR (100)  NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_HSTG_EBS_IBY_EXTERNAL_PAYEES_ALL_OMD_HASH_FULL_RECORD]
    ON [HSTG].[HSTG_EBS_IBY_EXTERNAL_PAYEES_ALL]([OMD_HASH_FULL_RECORD] ASC)
    INCLUDE([OMD_IS_RECORD_DELETED], [OMD_CURRENT_RECORD_INDICATOR]);

