CREATE TABLE [HSTG].[HSTG_CA_INTR] (
    [Request#]                     DECIMAL (36)    NULL,
    [Lfm]                          DECIMAL (36)    NULL,
    [Lto]                          DECIMAL (36)    NULL,
    [XfrBatch]                     DECIMAL (36)    NULL,
    [So#]                          DECIMAL (36)    NULL,
    [Sol#]                         DECIMAL (36)    NULL,
    [Po#]                          DECIMAL (36)    NULL,
    [Pol#]                         DECIMAL (36)    NULL,
    [Item Code]                    NVARCHAR (100)  NULL,
    [S]                            NVARCHAR (1)    NULL,
    [Request Qty]                  DECIMAL (36)    NULL,
    [Reject Qty]                   DECIMAL (36)    NULL,
    [Dispatch Qty]                 DECIMAL (36)    NULL,
    [RequestDat]                   DATE            NULL,
    [Req Time]                     TIME (7)        NULL,
    [Rby]                          NVARCHAR (3)    NULL,
    [AcceptDate]                   DATE            NULL,
    [Fill Date]                    DATE            NULL,
    [FillTime]                     TIME (7)        NULL,
    [Fby]                          NVARCHAR (3)    NULL,
    [Comment]                      NVARCHAR (1000) NULL,
    [Notes]                        NVARCHAR (1000) NULL,
    [To#]                          DECIMAL (36)    NULL,
    [Tol#]                         DECIMAL (36)    NULL,
    [PublishDat]                   DATE            NULL,
    [ExpectDate]                   DATE            NULL,
    [Reason]                       NVARCHAR (1000) NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000)  NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000)  NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)     NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)     NULL
);

