CREATE TABLE [HSTG].[HSTG_EBS_OE_ORDER_SOURCES] (
    [ORDER_SOURCE_ID]              FLOAT (53)     NULL,
    [CREATION_DATE]                DATETIME       NULL,
    [CREATED_BY]                   FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]             DATETIME       NULL,
    [LAST_UPDATED_BY]              FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]            FLOAT (53)     NULL,
    [NAME]                         VARCHAR (1000) NULL,
    [DESCRIPTION]                  VARCHAR (8000) NULL,
    [ENABLED_FLAG]                 VARCHAR (100)  NULL,
    [CREATE_CUSTOMERS_FLAG]        VARCHAR (100)  NULL,
    [USE_IDS_FLAG]                 VARCHAR (100)  NULL,
    [AIA_ENABLED_FLAG]             VARCHAR (100)  NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_HSTG_EBS_OE_ORDER_SOURCES_OMD_HASH_FULL_RECORD]
    ON [HSTG].[HSTG_EBS_OE_ORDER_SOURCES]([OMD_HASH_FULL_RECORD] ASC)
    INCLUDE([OMD_IS_RECORD_DELETED], [OMD_CURRENT_RECORD_INDICATOR]);

