CREATE TABLE [HSTG].[HSTG_CA_DLREBATE] (
    [Cust#]                        DECIMAL (36, 4) NULL,
    [T]                            NVARCHAR (2)    NULL,
    [Reb%]                         DECIMAL (36, 4) NULL,
    [GlLiabAcc#]                   NVARCHAR (20)   NULL,
    [Plan#]                        DECIMAL (36, 4) NULL,
    [Plan Start]                   DATETIME2 (7)   NULL,
    [RebVal 1]                     DECIMAL (36, 4) NULL,
    [RebVal 2]                     DECIMAL (36, 4) NULL,
    [RebVal 3]                     DECIMAL (36, 4) NULL,
    [RebVal 4]                     DECIMAL (36, 4) NULL,
    [RebVal 5]                     DECIMAL (36, 4) NULL,
    [RebVal 6]                     DECIMAL (36, 4) NULL,
    [RebVal 7]                     DECIMAL (36, 4) NULL,
    [RebVal 8]                     DECIMAL (36, 4) NULL,
    [RebVal 9]                     DECIMAL (36, 4) NULL,
    [RebVal10]                     DECIMAL (36, 4) NULL,
    [RebVal11]                     DECIMAL (36, 4) NULL,
    [RebVal12]                     DECIMAL (36, 4) NULL,
    [RebVal13]                     DECIMAL (36, 4) NULL,
    [RebVal14]                     DECIMAL (36, 4) NULL,
    [RebVal15]                     DECIMAL (36, 4) NULL,
    [RebVal16]                     DECIMAL (36, 4) NULL,
    [RebVal17]                     DECIMAL (36, 4) NULL,
    [RebVal18]                     DECIMAL (36, 4) NULL,
    [RebVal19]                     DECIMAL (36, 4) NULL,
    [RebVal20]                     DECIMAL (36, 4) NULL,
    [RebVal21]                     DECIMAL (36, 4) NULL,
    [RebVal22]                     DECIMAL (36, 4) NULL,
    [RebVal23]                     DECIMAL (36, 4) NULL,
    [RebVal24]                     DECIMAL (36, 4) NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000)  NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000)  NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)     NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)     NULL
);

