CREATE TABLE [HSTG].[HSTG_CA_POLINE] (
    [Po#]                          DECIMAL (36, 4) NULL,
    [Pol#]                         DECIMAL (36, 4) NULL,
    [Item Code]                    NVARCHAR (100)  NULL,
    [Loc]                          NVARCHAR (100)  NULL,
    [Order Qty]                    DECIMAL (36, 4) NULL,
    [Buy Price]                    DECIMAL (36, 4) NULL,
    [InvoiceCost]                  DECIMAL (36, 4) NULL,
    [Order Value]                  DECIMAL (36, 4) NULL,
    [ExpectDate]                   DATE            NULL,
    [Receipt Qty]                  DECIMAL (36, 4) NULL,
    [Receipt Val]                  DECIMAL (36, 4) NULL,
    [Invoice Qty]                  DECIMAL (36, 4) NULL,
    [Invoice Val]                  DECIMAL (36, 4) NULL,
    [Cancel Qty]                   DECIMAL (36, 4) NULL,
    [Sup#]                         DECIMAL (36, 4) NULL,
    [Job Ref]                      NVARCHAR (100)  NULL,
    [L]                            NVARCHAR (100)  NULL,
    [Comment]                      NVARCHAR (2000) NULL,
    [Factor]                       DECIMAL (36, 4) NULL,
    [Prc Fact]                     DECIMAL (36, 4) NULL,
    [GlAcct#]                      NVARCHAR (100)  NULL,
    [Supplier Item Code]           NVARCHAR (100)  NULL,
    [Start Date]                   DATE            NULL,
    [STime]                        TIME (7)        NULL,
    [Start By]                     NVARCHAR (100)  NULL,
    [Amend Date]                   DATE            NULL,
    [ATime]                        TIME (7)        NULL,
    [Amend By]                     NVARCHAR (100)  NULL,
    [O Price M2]                   DECIMAL (36, 4) NULL,
    [InmLastCost]                  DECIMAL (36, 4) NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)   NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000)  NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000)  NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)     NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)     NULL
);

