CREATE TABLE [HSTG].[HSTG_EBS_MTL_MATERIAL_TRANSACTIONS] (
    [TRANSACTION_ID]                 FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]               DATETIME       NULL,
    [LAST_UPDATED_BY]                FLOAT (53)     NULL,
    [CREATION_DATE]                  DATETIME       NULL,
    [CREATED_BY]                     FLOAT (53)     NULL,
    [LAST_UPDATE_LOGIN]              FLOAT (53)     NULL,
    [REQUEST_ID]                     FLOAT (53)     NULL,
    [PROGRAM_APPLICATION_ID]         FLOAT (53)     NULL,
    [PROGRAM_ID]                     FLOAT (53)     NULL,
    [PROGRAM_UPDATE_DATE]            DATETIME       NULL,
    [INVENTORY_ITEM_ID]              FLOAT (53)     NULL,
    [REVISION]                       VARCHAR (100)  NULL,
    [ORGANIZATION_ID]                FLOAT (53)     NULL,
    [SUBINVENTORY_CODE]              VARCHAR (100)  NULL,
    [LOCATOR_ID]                     FLOAT (53)     NULL,
    [TRANSACTION_TYPE_ID]            FLOAT (53)     NULL,
    [TRANSACTION_ACTION_ID]          FLOAT (53)     NULL,
    [TRANSACTION_SOURCE_TYPE_ID]     FLOAT (53)     NULL,
    [TRANSACTION_SOURCE_ID]          FLOAT (53)     NULL,
    [TRANSACTION_SOURCE_NAME]        VARCHAR (1000) NULL,
    [TRANSACTION_QUANTITY]           FLOAT (53)     NULL,
    [TRANSACTION_UOM]                VARCHAR (100)  NULL,
    [PRIMARY_QUANTITY]               FLOAT (53)     NULL,
    [TRANSACTION_DATE]               DATETIME       NULL,
    [VARIANCE_AMOUNT]                FLOAT (53)     NULL,
    [ACCT_PERIOD_ID]                 FLOAT (53)     NULL,
    [TRANSACTION_REFERENCE]          VARCHAR (1000) NULL,
    [REASON_ID]                      FLOAT (53)     NULL,
    [DISTRIBUTION_ACCOUNT_ID]        FLOAT (53)     NULL,
    [ENCUMBRANCE_ACCOUNT]            FLOAT (53)     NULL,
    [ENCUMBRANCE_AMOUNT]             FLOAT (53)     NULL,
    [COST_UPDATE_ID]                 FLOAT (53)     NULL,
    [COSTED_FLAG]                    VARCHAR (100)  NULL,
    [TRANSACTION_GROUP_ID]           FLOAT (53)     NULL,
    [INVOICED_FLAG]                  VARCHAR (100)  NULL,
    [ACTUAL_COST]                    FLOAT (53)     NULL,
    [TRANSACTION_COST]               FLOAT (53)     NULL,
    [PRIOR_COST]                     FLOAT (53)     NULL,
    [NEW_COST]                       FLOAT (53)     NULL,
    [CURRENCY_CODE]                  VARCHAR (100)  NULL,
    [CURRENCY_CONVERSION_RATE]       FLOAT (53)     NULL,
    [CURRENCY_CONVERSION_TYPE]       VARCHAR (100)  NULL,
    [CURRENCY_CONVERSION_DATE]       DATETIME       NULL,
    [USSGL_TRANSACTION_CODE]         VARCHAR (100)  NULL,
    [QUANTITY_ADJUSTED]              FLOAT (53)     NULL,
    [EMPLOYEE_CODE]                  VARCHAR (100)  NULL,
    [DEPARTMENT_ID]                  FLOAT (53)     NULL,
    [OPERATION_SEQ_NUM]              FLOAT (53)     NULL,
    [MASTER_SCHEDULE_UPDATE_CODE]    VARCHAR (100)  NULL,
    [RECEIVING_DOCUMENT]             VARCHAR (100)  NULL,
    [PICKING_LINE_ID]                FLOAT (53)     NULL,
    [TRX_SOURCE_LINE_ID]             FLOAT (53)     NULL,
    [TRX_SOURCE_DELIVERY_ID]         FLOAT (53)     NULL,
    [REPETITIVE_LINE_ID]             FLOAT (53)     NULL,
    [PHYSICAL_ADJUSTMENT_ID]         FLOAT (53)     NULL,
    [CYCLE_COUNT_ID]                 FLOAT (53)     NULL,
    [RMA_LINE_ID]                    FLOAT (53)     NULL,
    [TRANSFER_TRANSACTION_ID]        FLOAT (53)     NULL,
    [TRANSACTION_SET_ID]             FLOAT (53)     NULL,
    [RCV_TRANSACTION_ID]             FLOAT (53)     NULL,
    [MOVE_TRANSACTION_ID]            FLOAT (53)     NULL,
    [COMPLETION_TRANSACTION_ID]      FLOAT (53)     NULL,
    [SHORTAGE_PROCESS_CODE]          FLOAT (53)     NULL,
    [SOURCE_CODE]                    VARCHAR (100)  NULL,
    [SOURCE_LINE_ID]                 FLOAT (53)     NULL,
    [VENDOR_LOT_NUMBER]              VARCHAR (100)  NULL,
    [TRANSFER_ORGANIZATION_ID]       FLOAT (53)     NULL,
    [TRANSFER_SUBINVENTORY]          VARCHAR (100)  NULL,
    [TRANSFER_LOCATOR_ID]            FLOAT (53)     NULL,
    [SHIPMENT_NUMBER]                VARCHAR (100)  NULL,
    [TRANSFER_COST]                  FLOAT (53)     NULL,
    [TRANSPORTATION_DIST_ACCOUNT]    FLOAT (53)     NULL,
    [TRANSPORTATION_COST]            FLOAT (53)     NULL,
    [TRANSFER_COST_DIST_ACCOUNT]     FLOAT (53)     NULL,
    [WAYBILL_AIRBILL]                VARCHAR (100)  NULL,
    [FREIGHT_CODE]                   VARCHAR (100)  NULL,
    [NUMBER_OF_CONTAINERS]           FLOAT (53)     NULL,
    [VALUE_CHANGE]                   FLOAT (53)     NULL,
    [PERCENTAGE_CHANGE]              FLOAT (53)     NULL,
    [ATTRIBUTE_CATEGORY]             VARCHAR (100)  NULL,
    [ATTRIBUTE1]                     VARCHAR (1000) NULL,
    [ATTRIBUTE2]                     VARCHAR (1000) NULL,
    [ATTRIBUTE3]                     VARCHAR (1000) NULL,
    [ATTRIBUTE4]                     VARCHAR (1000) NULL,
    [ATTRIBUTE5]                     VARCHAR (1000) NULL,
    [ATTRIBUTE6]                     VARCHAR (1000) NULL,
    [ATTRIBUTE7]                     VARCHAR (1000) NULL,
    [ATTRIBUTE8]                     VARCHAR (1000) NULL,
    [ATTRIBUTE9]                     VARCHAR (1000) NULL,
    [ATTRIBUTE10]                    VARCHAR (1000) NULL,
    [ATTRIBUTE11]                    VARCHAR (1000) NULL,
    [ATTRIBUTE12]                    VARCHAR (1000) NULL,
    [ATTRIBUTE13]                    VARCHAR (1000) NULL,
    [ATTRIBUTE14]                    VARCHAR (1000) NULL,
    [ATTRIBUTE15]                    VARCHAR (1000) NULL,
    [MOVEMENT_ID]                    FLOAT (53)     NULL,
    [TASK_ID]                        FLOAT (53)     NULL,
    [TO_TASK_ID]                     FLOAT (53)     NULL,
    [PROJECT_ID]                     FLOAT (53)     NULL,
    [TO_PROJECT_ID]                  FLOAT (53)     NULL,
    [SOURCE_PROJECT_ID]              FLOAT (53)     NULL,
    [PA_EXPENDITURE_ORG_ID]          FLOAT (53)     NULL,
    [SOURCE_TASK_ID]                 FLOAT (53)     NULL,
    [EXPENDITURE_TYPE]               VARCHAR (100)  NULL,
    [ERROR_CODE]                     VARCHAR (1000) NULL,
    [ERROR_EXPLANATION]              VARCHAR (1000) NULL,
    [PRIOR_COSTED_QUANTITY]          FLOAT (53)     NULL,
    [TRANSFER_PRIOR_COSTED_QUANTITY] FLOAT (53)     NULL,
    [FINAL_COMPLETION_FLAG]          VARCHAR (100)  NULL,
    [PM_COST_COLLECTED]              VARCHAR (100)  NULL,
    [PM_COST_COLLECTOR_GROUP_ID]     FLOAT (53)     NULL,
    [SHIPMENT_COSTED]                VARCHAR (100)  NULL,
    [TRANSFER_PERCENTAGE]            FLOAT (53)     NULL,
    [MATERIAL_ACCOUNT]               FLOAT (53)     NULL,
    [MATERIAL_OVERHEAD_ACCOUNT]      FLOAT (53)     NULL,
    [RESOURCE_ACCOUNT]               FLOAT (53)     NULL,
    [OUTSIDE_PROCESSING_ACCOUNT]     FLOAT (53)     NULL,
    [OVERHEAD_ACCOUNT]               FLOAT (53)     NULL,
    [COST_GROUP_ID]                  FLOAT (53)     NULL,
    [TRANSFER_COST_GROUP_ID]         FLOAT (53)     NULL,
    [FLOW_SCHEDULE]                  VARCHAR (100)  NULL,
    [QA_COLLECTION_ID]               FLOAT (53)     NULL,
    [OVERCOMPLETION_TRANSACTION_QTY] FLOAT (53)     NULL,
    [OVERCOMPLETION_PRIMARY_QTY]     FLOAT (53)     NULL,
    [OVERCOMPLETION_TRANSACTION_ID]  FLOAT (53)     NULL,
    [MVT_STAT_STATUS]                VARCHAR (1000) NULL,
    [COMMON_BOM_SEQ_ID]              FLOAT (53)     NULL,
    [COMMON_ROUTING_SEQ_ID]          FLOAT (53)     NULL,
    [ORG_COST_GROUP_ID]              FLOAT (53)     NULL,
    [COST_TYPE_ID]                   FLOAT (53)     NULL,
    [PERIODIC_PRIMARY_QUANTITY]      FLOAT (53)     NULL,
    [MOVE_ORDER_LINE_ID]             FLOAT (53)     NULL,
    [TASK_GROUP_ID]                  FLOAT (53)     NULL,
    [PICK_SLIP_NUMBER]               FLOAT (53)     NULL,
    [LPN_ID]                         FLOAT (53)     NULL,
    [TRANSFER_LPN_ID]                FLOAT (53)     NULL,
    [PICK_STRATEGY_ID]               FLOAT (53)     NULL,
    [PICK_RULE_ID]                   FLOAT (53)     NULL,
    [PUT_AWAY_STRATEGY_ID]           FLOAT (53)     NULL,
    [PUT_AWAY_RULE_ID]               FLOAT (53)     NULL,
    [CONTENT_LPN_ID]                 FLOAT (53)     NULL,
    [PICK_SLIP_DATE]                 DATETIME       NULL,
    [COST_CATEGORY_ID]               FLOAT (53)     NULL,
    [ORGANIZATION_TYPE]              FLOAT (53)     NULL,
    [TRANSFER_ORGANIZATION_TYPE]     FLOAT (53)     NULL,
    [OWNING_ORGANIZATION_ID]         FLOAT (53)     NULL,
    [OWNING_TP_TYPE]                 FLOAT (53)     NULL,
    [XFR_OWNING_ORGANIZATION_ID]     FLOAT (53)     NULL,
    [TRANSFER_OWNING_TP_TYPE]        FLOAT (53)     NULL,
    [PLANNING_ORGANIZATION_ID]       FLOAT (53)     NULL,
    [PLANNING_TP_TYPE]               FLOAT (53)     NULL,
    [XFR_PLANNING_ORGANIZATION_ID]   FLOAT (53)     NULL,
    [TRANSFER_PLANNING_TP_TYPE]      FLOAT (53)     NULL,
    [SECONDARY_UOM_CODE]             VARCHAR (100)  NULL,
    [SECONDARY_TRANSACTION_QUANTITY] FLOAT (53)     NULL,
    [TRANSACTION_GROUP_SEQ]          FLOAT (53)     NULL,
    [SHIP_TO_LOCATION_ID]            FLOAT (53)     NULL,
    [RESERVATION_ID]                 FLOAT (53)     NULL,
    [TRANSACTION_MODE]               FLOAT (53)     NULL,
    [TRANSACTION_BATCH_ID]           FLOAT (53)     NULL,
    [TRANSACTION_BATCH_SEQ]          FLOAT (53)     NULL,
    [INTRANSIT_ACCOUNT]              FLOAT (53)     NULL,
    [FOB_POINT]                      FLOAT (53)     NULL,
    [PARENT_TRANSACTION_ID]          FLOAT (53)     NULL,
    [LOGICAL_TRX_TYPE_CODE]          FLOAT (53)     NULL,
    [TRX_FLOW_HEADER_ID]             FLOAT (53)     NULL,
    [LOGICAL_TRANSACTIONS_CREATED]   FLOAT (53)     NULL,
    [LOGICAL_TRANSACTION]            FLOAT (53)     NULL,
    [INTERCOMPANY_COST]              FLOAT (53)     NULL,
    [INTERCOMPANY_PRICING_OPTION]    FLOAT (53)     NULL,
    [INTERCOMPANY_CURRENCY_CODE]     VARCHAR (100)  NULL,
    [ORIGINAL_TRANSACTION_TEMP_ID]   FLOAT (53)     NULL,
    [TRANSFER_PRICE]                 FLOAT (53)     NULL,
    [EXPENSE_ACCOUNT_ID]             FLOAT (53)     NULL,
    [COGS_RECOGNITION_PERCENT]       FLOAT (53)     NULL,
    [SO_ISSUE_ACCOUNT_TYPE]          FLOAT (53)     NULL,
    [OPM_COSTED_FLAG]                VARCHAR (100)  NULL,
    [MATERIAL_EXPENSE_ACCOUNT]       FLOAT (53)     NULL,
    [TRANSACTION_EXTRACTED]          VARCHAR (100)  NULL,
    [XML_DOCUMENT_ID]                FLOAT (53)     NULL,
    [OMD_INSERT_DATETIME]            DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                  VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]           VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]          VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR]   VARCHAR (1)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_HSTG_EBS_MTL_MATERIAL_TRANSACTIONS_TRANSACTION_TYPE_ID]
    ON [HSTG].[HSTG_EBS_MTL_MATERIAL_TRANSACTIONS]([TRANSACTION_TYPE_ID] ASC)
    INCLUDE([INVENTORY_ITEM_ID], [TRANSACTION_DATE]);


GO
CREATE NONCLUSTERED INDEX [IX_HSTG_EBS_MTL_MATERIAL_TRANSACTIONS_CURRENT_RECORD_TRANSACTION_TYPE]
    ON [HSTG].[HSTG_EBS_MTL_MATERIAL_TRANSACTIONS]([OMD_CURRENT_RECORD_INDICATOR] ASC, [TRANSACTION_TYPE_ID] ASC)
    INCLUDE([TRANSACTION_DATE], [TRX_SOURCE_LINE_ID]);


GO
CREATE NONCLUSTERED INDEX [IDX_HSTG_EBS_MTL_MATERIAL_TRANSACTIONS_TRANSACTION_TYPE_CURRENT_RECORD]
    ON [HSTG].[HSTG_EBS_MTL_MATERIAL_TRANSACTIONS]([TRANSACTION_TYPE_ID] ASC, [OMD_CURRENT_RECORD_INDICATOR] ASC)
    INCLUDE([ACTUAL_COST], [TRX_SOURCE_LINE_ID]);

