CREATE TABLE [HSTG].[HSTG_EBS_AR_CUSTOMERS_ALL_V] (
    [CUSTOMER_ID]                  FLOAT (53)     NULL,
    [CUSTOMER_NAME]                VARCHAR (1000) NULL,
    [CUSTOMER_NUMBER]              VARCHAR (100)  NULL,
    [CUSTOMER_KEY]                 VARCHAR (1000) NULL,
    [STATUS]                       VARCHAR (100)  NULL,
    [ORIG_SYSTEM_REFERENCE]        VARCHAR (1000) NULL,
    [CUSTOMER_PROSPECT_CODE]       CHAR (100)     NULL,
    [CUSTOMER_CATEGORY_CODE]       VARCHAR (100)  NULL,
    [CUSTOMER_CLASS_CODE]          VARCHAR (100)  NULL,
    [CUSTOMER_TYPE]                VARCHAR (100)  NULL,
    [PRIMARY_SALESREP_ID]          FLOAT (53)     NULL,
    [SIC_CODE]                     VARCHAR (100)  NULL,
    [TAX_REFERENCE]                VARCHAR (1000) NULL,
    [TAX_CODE]                     VARCHAR (1000) NULL,
    [FOB_POINT]                    VARCHAR (100)  NULL,
    [SHIP_VIA]                     VARCHAR (100)  NULL,
    [GSA_INDICATOR]                VARCHAR (100)  NULL,
    [SHIP_PARTIAL]                 VARCHAR (100)  NULL,
    [TAXPAYER_ID]                  VARCHAR (100)  NULL,
    [PRICE_LIST_ID]                FLOAT (53)     NULL,
    [FREIGHT_TERM]                 VARCHAR (100)  NULL,
    [ORDER_TYPE_ID]                FLOAT (53)     NULL,
    [SALES_CHANNEL_CODE]           VARCHAR (100)  NULL,
    [WAREHOUSE_ID]                 FLOAT (53)     NULL,
    [MISSION_STATEMENT]            VARCHAR (8000) NULL,
    [NUM_OF_EMPLOYEES]             FLOAT (53)     NULL,
    [POTENTIAL_REVENUE_CURR_FY]    FLOAT (53)     NULL,
    [POTENTIAL_REVENUE_NEXT_FY]    FLOAT (53)     NULL,
    [FISCAL_YEAREND_MONTH]         VARCHAR (100)  NULL,
    [YEAR_ESTABLISHED]             FLOAT (53)     NULL,
    [ANALYSIS_FY]                  VARCHAR (100)  NULL,
    [COMPETITOR_FLAG]              VARCHAR (100)  NULL,
    [REFERENCE_USE_FLAG]           VARCHAR (100)  NULL,
    [THIRD_PARTY_FLAG]             VARCHAR (100)  NULL,
    [ATTRIBUTE_CATEGORY]           VARCHAR (100)  NULL,
    [ATTRIBUTE1]                   VARCHAR (1000) NULL,
    [ATTRIBUTE2]                   VARCHAR (1000) NULL,
    [ATTRIBUTE3]                   VARCHAR (1000) NULL,
    [ATTRIBUTE4]                   VARCHAR (1000) NULL,
    [ATTRIBUTE5]                   VARCHAR (1000) NULL,
    [ATTRIBUTE6]                   VARCHAR (1000) NULL,
    [ATTRIBUTE7]                   VARCHAR (1000) NULL,
    [ATTRIBUTE8]                   VARCHAR (1000) NULL,
    [ATTRIBUTE9]                   VARCHAR (1000) NULL,
    [ATTRIBUTE10]                  VARCHAR (1000) NULL,
    [ATTRIBUTE11]                  VARCHAR (1000) NULL,
    [ATTRIBUTE12]                  VARCHAR (1000) NULL,
    [ATTRIBUTE13]                  VARCHAR (1000) NULL,
    [ATTRIBUTE14]                  VARCHAR (1000) NULL,
    [ATTRIBUTE15]                  VARCHAR (1000) NULL,
    [LAST_UPDATED_BY]              FLOAT (53)     NULL,
    [LAST_UPDATE_DATE]             DATETIME       NULL,
    [LAST_UPDATE_LOGIN]            FLOAT (53)     NULL,
    [CREATED_BY]                   FLOAT (53)     NULL,
    [CREATION_DATE]                DATETIME       NULL,
    [CUSTOMER_NAME_PHONETIC]       VARCHAR (1000) NULL,
    [TAX_HEADER_LEVEL_FLAG]        VARCHAR (100)  NULL,
    [TAX_ROUNDING_RULE]            VARCHAR (100)  NULL,
    [ACCOUNT_DESCRIPTION]          VARCHAR (1000) NULL,
    [OMD_INSERT_DATETIME]          DATETIME2 (7)  NOT NULL,
    [OMD_FILE_NAME]                VARCHAR (8000) NOT NULL,
    [OMD_HASH_FULL_RECORD]         VARCHAR (1000) NULL,
    [OMD_IS_RECORD_DELETED]        VARCHAR (1)    NULL,
    [OMD_CURRENT_RECORD_INDICATOR] VARCHAR (1)    NULL
);

