
CREATE PROCEDURE [STG].[LOAD_STG_EBS_AR_PAYMENT_SCHEDULES_ALL]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        5/05/2022 11:48:46 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_AR_PAYMENT_SCHEDULES_ALL";
    
    
    Source                                      Destination                              
    ----------------------------------------    ---------------------------------------- 
    LND"."LND_EBS_AR_PAYMENT_SCHEDULES_ALL"    "STG"."STG_EBS_AR_PAYMENT_SCHEDULES_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-05    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_AR_PAYMENT_SCHEDULES_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_AR_PAYMENT_SCHEDULES_ALL"
                (
                    "PAYMENT_SCHEDULE_ID"
                    ,"STAGED_DUNNING_LEVEL"
                    ,"DUNNING_LEVEL_OVERRIDE_DATE"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"DUE_DATE"
                    ,"AMOUNT_DUE_ORIGINAL"
                    ,"AMOUNT_DUE_REMAINING"
                    ,"NUMBER_OF_DUE_DATES"
                    ,"STATUS"
                    ,"INVOICE_CURRENCY_CODE"
                    ,"CLASS"
                    ,"CUST_TRX_TYPE_ID"
                    ,"CUSTOMER_ID"
                    ,"CUSTOMER_SITE_USE_ID"
                    ,"CUSTOMER_TRX_ID"
                    ,"CASH_RECEIPT_ID"
                    ,"ASSOCIATED_CASH_RECEIPT_ID"
                    ,"TERM_ID"
                    ,"TERMS_SEQUENCE_NUMBER"
                    ,"GL_DATE_CLOSED"
                    ,"ACTUAL_DATE_CLOSED"
                    ,"DISCOUNT_DATE"
                    ,"AMOUNT_LINE_ITEMS_ORIGINAL"
                    ,"AMOUNT_LINE_ITEMS_REMAINING"
                    ,"AMOUNT_APPLIED"
                    ,"AMOUNT_ADJUSTED"
                    ,"AMOUNT_IN_DISPUTE"
                    ,"AMOUNT_CREDITED"
                    ,"RECEIVABLES_CHARGES_CHARGED"
                    ,"RECEIVABLES_CHARGES_REMAINING"
                    ,"FREIGHT_ORIGINAL"
                    ,"FREIGHT_REMAINING"
                    ,"TAX_ORIGINAL"
                    ,"TAX_REMAINING"
                    ,"DISCOUNT_ORIGINAL"
                    ,"DISCOUNT_REMAINING"
                    ,"DISCOUNT_TAKEN_EARNED"
                    ,"DISCOUNT_TAKEN_UNEARNED"
                    ,"IN_COLLECTION"
                    ,"CASH_APPLIED_ID_LAST"
                    ,"CASH_APPLIED_DATE_LAST"
                    ,"CASH_APPLIED_AMOUNT_LAST"
                    ,"CASH_APPLIED_STATUS_LAST"
                    ,"CASH_GL_DATE_LAST"
                    ,"CASH_RECEIPT_ID_LAST"
                    ,"CASH_RECEIPT_DATE_LAST"
                    ,"CASH_RECEIPT_AMOUNT_LAST"
                    ,"CASH_RECEIPT_STATUS_LAST"
                    ,"EXCHANGE_RATE_TYPE"
                    ,"EXCHANGE_DATE"
                    ,"EXCHANGE_RATE"
                    ,"ADJUSTMENT_ID_LAST"
                    ,"ADJUSTMENT_DATE_LAST"
                    ,"ADJUSTMENT_GL_DATE_LAST"
                    ,"ADJUSTMENT_AMOUNT_LAST"
                    ,"FOLLOW_UP_DATE_LAST"
                    ,"FOLLOW_UP_CODE_LAST"
                    ,"PROMISE_DATE_LAST"
                    ,"PROMISE_AMOUNT_LAST"
                    ,"COLLECTOR_LAST"
                    ,"CALL_DATE_LAST"
                    ,"TRX_NUMBER"
                    ,"TRX_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"REVERSED_CASH_RECEIPT_ID"
                    ,"AMOUNT_ADJUSTED_PENDING"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"GL_DATE"
                    ,"ACCTD_AMOUNT_DUE_REMAINING"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"RECEIPT_CONFIRMED_FLAG"
                    ,"REQUEST_ID"
                    ,"SELECTED_FOR_RECEIPT_BATCH_ID"
                    ,"LAST_CHARGE_DATE"
                    ,"SECOND_LAST_CHARGE_DATE"
                    ,"DISPUTE_DATE"
                    ,"ORG_ID"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"CONS_INV_ID"
                    ,"CONS_INV_ID_REV"
                    ,"EXCLUDE_FROM_DUNNING_FLAG"
                    ,"MRC_CUSTOMER_TRX_ID"
                    ,"MRC_EXCHANGE_RATE_TYPE"
                    ,"MRC_EXCHANGE_DATE"
                    ,"MRC_EXCHANGE_RATE"
                    ,"MRC_ACCTD_AMOUNT_DUE_REMAINING"
                    ,"BR_AMOUNT_ASSIGNED"
                    ,"RESERVED_TYPE"
                    ,"RESERVED_VALUE"
                    ,"ACTIVE_CLAIM_FLAG"
                    ,"EXCLUDE_FROM_CONS_BILL_FLAG"
                    ,"PAYMENT_APPROVAL"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("PAYMENT_SCHEDULE_ID" AS float) AS "PAYMENT_SCHEDULE_ID"
                        ,CAST("STAGED_DUNNING_LEVEL" AS float) AS "STAGED_DUNNING_LEVEL"
                        ,CAST("DUNNING_LEVEL_OVERRIDE_DATE"  AS datetime2) AS "DUNNING_LEVEL_OVERRIDE_DATE"
                        ,CAST("LAST_UPDATE_DATE"  AS datetime2) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("CREATION_DATE"  AS datetime2) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("DUE_DATE"  AS datetime2) AS "DUE_DATE"
                        ,CAST("AMOUNT_DUE_ORIGINAL" AS float) AS "AMOUNT_DUE_ORIGINAL"
                        ,CAST("AMOUNT_DUE_REMAINING" AS float) AS "AMOUNT_DUE_REMAINING"
                        ,CAST("NUMBER_OF_DUE_DATES" AS float) AS "NUMBER_OF_DUE_DATES"
                        ,CAST("STATUS" AS varchar(100) ) AS "STATUS"
                        ,CAST("INVOICE_CURRENCY_CODE" AS varchar(100) ) AS "INVOICE_CURRENCY_CODE"
                        ,CAST("CLASS" AS varchar(100) ) AS "CLASS"
                        ,CAST("CUST_TRX_TYPE_ID" AS float) AS "CUST_TRX_TYPE_ID"
                        ,CAST("CUSTOMER_ID" AS float) AS "CUSTOMER_ID"
                        ,CAST("CUSTOMER_SITE_USE_ID" AS float) AS "CUSTOMER_SITE_USE_ID"
                        ,CAST("CUSTOMER_TRX_ID" AS float) AS "CUSTOMER_TRX_ID"
                        ,CAST("CASH_RECEIPT_ID" AS float) AS "CASH_RECEIPT_ID"
                        ,CAST("ASSOCIATED_CASH_RECEIPT_ID" AS float) AS "ASSOCIATED_CASH_RECEIPT_ID"
                        ,CAST("TERM_ID" AS float) AS "TERM_ID"
                        ,CAST("TERMS_SEQUENCE_NUMBER" AS float) AS "TERMS_SEQUENCE_NUMBER"
                        ,CAST("GL_DATE_CLOSED"  AS datetime2) AS "GL_DATE_CLOSED"
                        ,CAST("ACTUAL_DATE_CLOSED"  AS datetime2) AS "ACTUAL_DATE_CLOSED"
                        ,CAST("DISCOUNT_DATE"  AS datetime2) AS "DISCOUNT_DATE"
                        ,CAST("AMOUNT_LINE_ITEMS_ORIGINAL" AS float) AS "AMOUNT_LINE_ITEMS_ORIGINAL"
                        ,CAST("AMOUNT_LINE_ITEMS_REMAINING" AS float) AS "AMOUNT_LINE_ITEMS_REMAINING"
                        ,CAST("AMOUNT_APPLIED" AS float) AS "AMOUNT_APPLIED"
                        ,CAST("AMOUNT_ADJUSTED" AS float) AS "AMOUNT_ADJUSTED"
                        ,CAST("AMOUNT_IN_DISPUTE" AS float) AS "AMOUNT_IN_DISPUTE"
                        ,CAST("AMOUNT_CREDITED" AS float) AS "AMOUNT_CREDITED"
                        ,CAST("RECEIVABLES_CHARGES_CHARGED" AS float) AS "RECEIVABLES_CHARGES_CHARGED"
                        ,CAST("RECEIVABLES_CHARGES_REMAINING" AS float) AS "RECEIVABLES_CHARGES_REMAINING"
                        ,CAST("FREIGHT_ORIGINAL" AS float) AS "FREIGHT_ORIGINAL"
                        ,CAST("FREIGHT_REMAINING" AS float) AS "FREIGHT_REMAINING"
                        ,CAST("TAX_ORIGINAL" AS float) AS "TAX_ORIGINAL"
                        ,CAST("TAX_REMAINING" AS float) AS "TAX_REMAINING"
                        ,CAST("DISCOUNT_ORIGINAL" AS float) AS "DISCOUNT_ORIGINAL"
                        ,CAST("DISCOUNT_REMAINING" AS float) AS "DISCOUNT_REMAINING"
                        ,CAST("DISCOUNT_TAKEN_EARNED" AS float) AS "DISCOUNT_TAKEN_EARNED"
                        ,CAST("DISCOUNT_TAKEN_UNEARNED" AS float) AS "DISCOUNT_TAKEN_UNEARNED"
                        ,CAST("IN_COLLECTION" AS varchar(100) ) AS "IN_COLLECTION"
                        ,CAST("CASH_APPLIED_ID_LAST" AS float) AS "CASH_APPLIED_ID_LAST"
                        ,CAST("CASH_APPLIED_DATE_LAST"  AS datetime2) AS "CASH_APPLIED_DATE_LAST"
                        ,CAST("CASH_APPLIED_AMOUNT_LAST" AS float) AS "CASH_APPLIED_AMOUNT_LAST"
                        ,CAST("CASH_APPLIED_STATUS_LAST" AS varchar(100) ) AS "CASH_APPLIED_STATUS_LAST"
                        ,CAST("CASH_GL_DATE_LAST"  AS datetime2) AS "CASH_GL_DATE_LAST"
                        ,CAST("CASH_RECEIPT_ID_LAST" AS float) AS "CASH_RECEIPT_ID_LAST"
                        ,CAST("CASH_RECEIPT_DATE_LAST"  AS datetime2) AS "CASH_RECEIPT_DATE_LAST"
                        ,CAST("CASH_RECEIPT_AMOUNT_LAST" AS float) AS "CASH_RECEIPT_AMOUNT_LAST"
                        ,CAST("CASH_RECEIPT_STATUS_LAST" AS varchar(100) ) AS "CASH_RECEIPT_STATUS_LAST"
                        ,CAST("EXCHANGE_RATE_TYPE" AS varchar(100) ) AS "EXCHANGE_RATE_TYPE"
                        ,CAST("EXCHANGE_DATE"  AS datetime2) AS "EXCHANGE_DATE"
                        ,CAST("EXCHANGE_RATE" AS float) AS "EXCHANGE_RATE"
                        ,CAST("ADJUSTMENT_ID_LAST" AS float) AS "ADJUSTMENT_ID_LAST"
                        ,CAST("ADJUSTMENT_DATE_LAST"  AS datetime2) AS "ADJUSTMENT_DATE_LAST"
                        ,CAST("ADJUSTMENT_GL_DATE_LAST"  AS datetime2) AS "ADJUSTMENT_GL_DATE_LAST"
                        ,CAST("ADJUSTMENT_AMOUNT_LAST" AS float) AS "ADJUSTMENT_AMOUNT_LAST"
                        ,CAST("FOLLOW_UP_DATE_LAST"  AS datetime2) AS "FOLLOW_UP_DATE_LAST"
                        ,CAST("FOLLOW_UP_CODE_LAST" AS varchar(100) ) AS "FOLLOW_UP_CODE_LAST"
                        ,CAST("PROMISE_DATE_LAST"  AS datetime2) AS "PROMISE_DATE_LAST"
                        ,CAST("PROMISE_AMOUNT_LAST" AS float) AS "PROMISE_AMOUNT_LAST"
                        ,CAST("COLLECTOR_LAST" AS float) AS "COLLECTOR_LAST"
                        ,CAST("CALL_DATE_LAST"  AS datetime2) AS "CALL_DATE_LAST"
                        ,CAST("TRX_NUMBER" AS varchar(100) ) AS "TRX_NUMBER"
                        ,CAST("TRX_DATE"  AS datetime2) AS "TRX_DATE"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("REVERSED_CASH_RECEIPT_ID" AS float) AS "REVERSED_CASH_RECEIPT_ID"
                        ,CAST("AMOUNT_ADJUSTED_PENDING" AS float) AS "AMOUNT_ADJUSTED_PENDING"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("GL_DATE"  AS datetime2) AS "GL_DATE"
                        ,CAST("ACCTD_AMOUNT_DUE_REMAINING" AS float) AS "ACCTD_AMOUNT_DUE_REMAINING"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,CAST("PROGRAM_UPDATE_DATE"  AS datetime2) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("RECEIPT_CONFIRMED_FLAG" AS varchar(100) ) AS "RECEIPT_CONFIRMED_FLAG"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("SELECTED_FOR_RECEIPT_BATCH_ID" AS float) AS "SELECTED_FOR_RECEIPT_BATCH_ID"
                        ,CAST("LAST_CHARGE_DATE"  AS datetime2) AS "LAST_CHARGE_DATE"
                        ,CAST("SECOND_LAST_CHARGE_DATE"  AS datetime2) AS "SECOND_LAST_CHARGE_DATE"
                        ,CAST("DISPUTE_DATE"  AS datetime2) AS "DISPUTE_DATE"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("CONS_INV_ID" AS float) AS "CONS_INV_ID"
                        ,CAST("CONS_INV_ID_REV" AS float) AS "CONS_INV_ID_REV"
                        ,CAST("EXCLUDE_FROM_DUNNING_FLAG" AS varchar(100) ) AS "EXCLUDE_FROM_DUNNING_FLAG"
                        ,CAST("MRC_CUSTOMER_TRX_ID" AS varchar(8000) ) AS "MRC_CUSTOMER_TRX_ID"
                        ,CAST("MRC_EXCHANGE_RATE_TYPE" AS varchar(8000) ) AS "MRC_EXCHANGE_RATE_TYPE"
                        ,CAST("MRC_EXCHANGE_DATE" AS varchar(8000) ) AS "MRC_EXCHANGE_DATE"
                        ,CAST("MRC_EXCHANGE_RATE" AS varchar(8000) ) AS "MRC_EXCHANGE_RATE"
                        ,CAST("MRC_ACCTD_AMOUNT_DUE_REMAINING" AS varchar(8000) ) AS "MRC_ACCTD_AMOUNT_DUE_REMAINING"
                        ,CAST("BR_AMOUNT_ASSIGNED" AS float) AS "BR_AMOUNT_ASSIGNED"
                        ,CAST("RESERVED_TYPE" AS varchar(100) ) AS "RESERVED_TYPE"
                        ,CAST("RESERVED_VALUE" AS float) AS "RESERVED_VALUE"
                        ,CAST("ACTIVE_CLAIM_FLAG" AS varchar(100) ) AS "ACTIVE_CLAIM_FLAG"
                        ,CAST("EXCLUDE_FROM_CONS_BILL_FLAG" AS varchar(100) ) AS "EXCLUDE_FROM_CONS_BILL_FLAG"
                        ,CAST("PAYMENT_APPROVAL" AS varchar(100) ) AS "PAYMENT_APPROVAL"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "PAYMENT_SCHEDULE_ID"
                            , "STAGED_DUNNING_LEVEL"
                            , "DUNNING_LEVEL_OVERRIDE_DATE"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "DUE_DATE"
                            , "AMOUNT_DUE_ORIGINAL"
                            , "AMOUNT_DUE_REMAINING"
                            , "NUMBER_OF_DUE_DATES"
                            , "STATUS"
                            , "INVOICE_CURRENCY_CODE"
                            , "CLASS"
                            , "CUST_TRX_TYPE_ID"
                            , "CUSTOMER_ID"
                            , "CUSTOMER_SITE_USE_ID"
                            , "CUSTOMER_TRX_ID"
                            , "CASH_RECEIPT_ID"
                            , "ASSOCIATED_CASH_RECEIPT_ID"
                            , "TERM_ID"
                            , "TERMS_SEQUENCE_NUMBER"
                            , "GL_DATE_CLOSED"
                            , "ACTUAL_DATE_CLOSED"
                            , "DISCOUNT_DATE"
                            , "AMOUNT_LINE_ITEMS_ORIGINAL"
                            , "AMOUNT_LINE_ITEMS_REMAINING"
                            , "AMOUNT_APPLIED"
                            , "AMOUNT_ADJUSTED"
                            , "AMOUNT_IN_DISPUTE"
                            , "AMOUNT_CREDITED"
                            , "RECEIVABLES_CHARGES_CHARGED"
                            , "RECEIVABLES_CHARGES_REMAINING"
                            , "FREIGHT_ORIGINAL"
                            , "FREIGHT_REMAINING"
                            , "TAX_ORIGINAL"
                            , "TAX_REMAINING"
                            , "DISCOUNT_ORIGINAL"
                            , "DISCOUNT_REMAINING"
                            , "DISCOUNT_TAKEN_EARNED"
                            , "DISCOUNT_TAKEN_UNEARNED"
                            , "IN_COLLECTION"
                            , "CASH_APPLIED_ID_LAST"
                            , "CASH_APPLIED_DATE_LAST"
                            , "CASH_APPLIED_AMOUNT_LAST"
                            , "CASH_APPLIED_STATUS_LAST"
                            , "CASH_GL_DATE_LAST"
                            , "CASH_RECEIPT_ID_LAST"
                            , "CASH_RECEIPT_DATE_LAST"
                            , "CASH_RECEIPT_AMOUNT_LAST"
                            , "CASH_RECEIPT_STATUS_LAST"
                            , "EXCHANGE_RATE_TYPE"
                            , "EXCHANGE_DATE"
                            , "EXCHANGE_RATE"
                            , "ADJUSTMENT_ID_LAST"
                            , "ADJUSTMENT_DATE_LAST"
                            , "ADJUSTMENT_GL_DATE_LAST"
                            , "ADJUSTMENT_AMOUNT_LAST"
                            , "FOLLOW_UP_DATE_LAST"
                            , "FOLLOW_UP_CODE_LAST"
                            , "PROMISE_DATE_LAST"
                            , "PROMISE_AMOUNT_LAST"
                            , "COLLECTOR_LAST"
                            , "CALL_DATE_LAST"
                            , "TRX_NUMBER"
                            , "TRX_DATE"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "REVERSED_CASH_RECEIPT_ID"
                            , "AMOUNT_ADJUSTED_PENDING"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "GL_DATE"
                            , "ACCTD_AMOUNT_DUE_REMAINING"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "RECEIPT_CONFIRMED_FLAG"
                            , "REQUEST_ID"
                            , "SELECTED_FOR_RECEIPT_BATCH_ID"
                            , "LAST_CHARGE_DATE"
                            , "SECOND_LAST_CHARGE_DATE"
                            , "DISPUTE_DATE"
                            , "ORG_ID"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "CONS_INV_ID"
                            , "CONS_INV_ID_REV"
                            , "EXCLUDE_FROM_DUNNING_FLAG"
                            , "MRC_CUSTOMER_TRX_ID"
                            , "MRC_EXCHANGE_RATE_TYPE"
                            , "MRC_EXCHANGE_DATE"
                            , "MRC_EXCHANGE_RATE"
                            , "MRC_ACCTD_AMOUNT_DUE_REMAINING"
                            , "BR_AMOUNT_ASSIGNED"
                            , "RESERVED_TYPE"
                            , "RESERVED_VALUE"
                            , "ACTIVE_CLAIM_FLAG"
                            , "EXCLUDE_FROM_CONS_BILL_FLAG"
                            , "PAYMENT_APPROVAL"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_AR_PAYMENT_SCHEDULES_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END