

CREATE PROCEDURE [STG].[LOAD_STG_EBS_HZ_CUST_ACCOUNTS_ALL]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        10/03/2022 5:31:04 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_HZ_CUST_ACCOUNTS_ALL";
    
    
    Source                                  Destination                          
    ------------------------------------    ------------------------------------ 
    LND"."LND_EBS_HZ_CUST_ACCOUNTS_ALL"    "STG"."STG_EBS_HZ_CUST_ACCOUNTS_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-10    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_HZ_CUST_ACCOUNTS_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_HZ_CUST_ACCOUNTS_ALL"
                (
                    "CUST_ACCOUNT_ID"
                    ,"PARTY_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"ACCOUNT_NUMBER"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"WH_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"ORIG_SYSTEM_REFERENCE"
                    ,"STATUS"
                    ,"CUSTOMER_TYPE"
                    ,"CUSTOMER_CLASS_CODE"
                    ,"PRIMARY_SALESREP_ID"
                    ,"SALES_CHANNEL_CODE"
                    ,"ORDER_TYPE_ID"
                    ,"PRICE_LIST_ID"
                    ,"SUBCATEGORY_CODE"
                    ,"TAX_CODE"
                    ,"FOB_POINT"
                    ,"FREIGHT_TERM"
                    ,"SHIP_PARTIAL"
                    ,"SHIP_VIA"
                    ,"WAREHOUSE_ID"
                    ,"PAYMENT_TERM_ID"
                    ,"TAX_HEADER_LEVEL_FLAG"
                    ,"TAX_ROUNDING_RULE"
                    ,"COTERMINATE_DAY_MONTH"
                    ,"PRIMARY_SPECIALIST_ID"
                    ,"SECONDARY_SPECIALIST_ID"
                    ,"ACCOUNT_LIABLE_FLAG"
                    ,"RESTRICTION_LIMIT_AMOUNT"
                    ,"CURRENT_BALANCE"
                    ,"PASSWORD_TEXT"
                    ,"HIGH_PRIORITY_INDICATOR"
                    ,"ACCOUNT_ESTABLISHED_DATE"
                    ,"ACCOUNT_TERMINATION_DATE"
                    ,"ACCOUNT_ACTIVATION_DATE"
                    ,"CREDIT_CLASSIFICATION_CODE"
                    ,"DEPARTMENT"
                    ,"MAJOR_ACCOUNT_NUMBER"
                    ,"HOTWATCH_SERVICE_FLAG"
                    ,"HOTWATCH_SVC_BAL_IND"
                    ,"HELD_BILL_EXPIRATION_DATE"
                    ,"HOLD_BILL_FLAG"
                    ,"HIGH_PRIORITY_REMARKS"
                    ,"PO_EFFECTIVE_DATE"
                    ,"PO_EXPIRATION_DATE"
                    ,"REALTIME_RATE_FLAG"
                    ,"SINGLE_USER_FLAG"
                    ,"WATCH_ACCOUNT_FLAG"
                    ,"WATCH_BALANCE_INDICATOR"
                    ,"GEO_CODE"
                    ,"ACCT_LIFE_CYCLE_STATUS"
                    ,"ACCOUNT_NAME"
                    ,"DEPOSIT_REFUND_METHOD"
                    ,"DORMANT_ACCOUNT_FLAG"
                    ,"NPA_NUMBER"
                    ,"PIN_NUMBER"
                    ,"SUSPENSION_DATE"
                    ,"WRITE_OFF_ADJUSTMENT_AMOUNT"
                    ,"WRITE_OFF_PAYMENT_AMOUNT"
                    ,"WRITE_OFF_AMOUNT"
                    ,"SOURCE_CODE"
                    ,"COMPETITOR_TYPE"
                    ,"COMMENTS"
                    ,"DATES_NEGATIVE_TOLERANCE"
                    ,"DATES_POSITIVE_TOLERANCE"
                    ,"DATE_TYPE_PREFERENCE"
                    ,"OVER_SHIPMENT_TOLERANCE"
                    ,"UNDER_SHIPMENT_TOLERANCE"
                    ,"OVER_RETURN_TOLERANCE"
                    ,"UNDER_RETURN_TOLERANCE"
                    ,"ITEM_CROSS_REF_PREF"
                    ,"SHIP_SETS_INCLUDE_LINES_FLAG"
                    ,"ARRIVALSETS_INCLUDE_LINES_FLAG"
                    ,"SCHED_DATE_PUSH_FLAG"
                    ,"INVOICE_QUANTITY_RULE"
                    ,"PRICING_EVENT"
                    ,"ACCOUNT_REPLICATION_KEY"
                    ,"STATUS_UPDATE_DATE"
                    ,"AUTOPAY_FLAG"
                    ,"NOTIFY_FLAG"
                    ,"LAST_BATCH_ID"
                    ,"ORG_ID"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"CREATED_BY_MODULE"
                    ,"APPLICATION_ID"
                    ,"SELLING_PARTY_ID"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("CUST_ACCOUNT_ID" AS float) AS "CUST_ACCOUNT_ID"
                        ,CAST("PARTY_ID" AS float) AS "PARTY_ID"
                        ,TRY_CONVERT(datetime2,"LAST_UPDATE_DATE",121) AS "LAST_UPDATE_DATE"
                        ,CAST("ACCOUNT_NUMBER" AS varchar(100) ) AS "ACCOUNT_NUMBER"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,TRY_CONVERT(datetime2,"CREATION_DATE",121) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,TRY_CONVERT(datetime2,"PROGRAM_UPDATE_DATE",121) AS "PROGRAM_UPDATE_DATE"
                        ,TRY_CONVERT(datetime2,"WH_UPDATE_DATE",121) AS "WH_UPDATE_DATE"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("ATTRIBUTE16" AS varchar(1000) ) AS "ATTRIBUTE16"
                        ,CAST("ATTRIBUTE17" AS varchar(1000) ) AS "ATTRIBUTE17"
                        ,CAST("ATTRIBUTE18" AS varchar(1000) ) AS "ATTRIBUTE18"
                        ,CAST("ATTRIBUTE19" AS varchar(1000) ) AS "ATTRIBUTE19"
                        ,CAST("ATTRIBUTE20" AS varchar(1000) ) AS "ATTRIBUTE20"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("ORIG_SYSTEM_REFERENCE" AS varchar(1000) ) AS "ORIG_SYSTEM_REFERENCE"
                        ,CAST("STATUS" AS varchar(100) ) AS "STATUS"
                        ,CAST("CUSTOMER_TYPE" AS varchar(100) ) AS "CUSTOMER_TYPE"
                        ,CAST("CUSTOMER_CLASS_CODE" AS varchar(100) ) AS "CUSTOMER_CLASS_CODE"
                        ,CAST("PRIMARY_SALESREP_ID" AS float) AS "PRIMARY_SALESREP_ID"
                        ,CAST("SALES_CHANNEL_CODE" AS varchar(100) ) AS "SALES_CHANNEL_CODE"
                        ,CAST("ORDER_TYPE_ID" AS float) AS "ORDER_TYPE_ID"
                        ,CAST("PRICE_LIST_ID" AS float) AS "PRICE_LIST_ID"
                        ,CAST("SUBCATEGORY_CODE" AS varchar(100) ) AS "SUBCATEGORY_CODE"
                        ,CAST("TAX_CODE" AS varchar(1000) ) AS "TAX_CODE"
                        ,CAST("FOB_POINT" AS varchar(100) ) AS "FOB_POINT"
                        ,CAST("FREIGHT_TERM" AS varchar(100) ) AS "FREIGHT_TERM"
                        ,CAST("SHIP_PARTIAL" AS varchar(100) ) AS "SHIP_PARTIAL"
                        ,CAST("SHIP_VIA" AS varchar(100) ) AS "SHIP_VIA"
                        ,CAST("WAREHOUSE_ID" AS float) AS "WAREHOUSE_ID"
                        ,CAST("PAYMENT_TERM_ID" AS float) AS "PAYMENT_TERM_ID"
                        ,CAST("TAX_HEADER_LEVEL_FLAG" AS varchar(100) ) AS "TAX_HEADER_LEVEL_FLAG"
                        ,CAST("TAX_ROUNDING_RULE" AS varchar(100) ) AS "TAX_ROUNDING_RULE"
                        ,CAST("COTERMINATE_DAY_MONTH" AS varchar(100) ) AS "COTERMINATE_DAY_MONTH"
                        ,CAST("PRIMARY_SPECIALIST_ID" AS float) AS "PRIMARY_SPECIALIST_ID"
                        ,CAST("SECONDARY_SPECIALIST_ID" AS float) AS "SECONDARY_SPECIALIST_ID"
                        ,CAST("ACCOUNT_LIABLE_FLAG" AS varchar(100) ) AS "ACCOUNT_LIABLE_FLAG"
                        ,CAST("RESTRICTION_LIMIT_AMOUNT" AS float) AS "RESTRICTION_LIMIT_AMOUNT"
                        ,CAST("CURRENT_BALANCE" AS float) AS "CURRENT_BALANCE"
                        ,CAST("PASSWORD_TEXT" AS varchar(1000) ) AS "PASSWORD_TEXT"
                        ,CAST("HIGH_PRIORITY_INDICATOR" AS varchar(100) ) AS "HIGH_PRIORITY_INDICATOR"
                        ,TRY_CONVERT(datetime2,"ACCOUNT_ESTABLISHED_DATE",121) AS "ACCOUNT_ESTABLISHED_DATE"
                        ,TRY_CONVERT(datetime2,"ACCOUNT_TERMINATION_DATE",121) AS "ACCOUNT_TERMINATION_DATE"
                        ,TRY_CONVERT(datetime2,"ACCOUNT_ACTIVATION_DATE",121) AS "ACCOUNT_ACTIVATION_DATE"
                        ,CAST("CREDIT_CLASSIFICATION_CODE" AS varchar(100) ) AS "CREDIT_CLASSIFICATION_CODE"
                        ,CAST("DEPARTMENT" AS varchar(100) ) AS "DEPARTMENT"
                        ,CAST("MAJOR_ACCOUNT_NUMBER" AS varchar(100) ) AS "MAJOR_ACCOUNT_NUMBER"
                        ,CAST("HOTWATCH_SERVICE_FLAG" AS varchar(100) ) AS "HOTWATCH_SERVICE_FLAG"
                        ,CAST("HOTWATCH_SVC_BAL_IND" AS varchar(100) ) AS "HOTWATCH_SVC_BAL_IND"
                        ,TRY_CONVERT(datetime2,"HELD_BILL_EXPIRATION_DATE",121) AS "HELD_BILL_EXPIRATION_DATE"
                        ,CAST("HOLD_BILL_FLAG" AS varchar(100) ) AS "HOLD_BILL_FLAG"
                        ,CAST("HIGH_PRIORITY_REMARKS" AS varchar(1000) ) AS "HIGH_PRIORITY_REMARKS"
                        ,TRY_CONVERT(datetime2,"PO_EFFECTIVE_DATE",121) AS "PO_EFFECTIVE_DATE"
                        ,TRY_CONVERT(datetime2,"PO_EXPIRATION_DATE",121) AS "PO_EXPIRATION_DATE"
                        ,CAST("REALTIME_RATE_FLAG" AS varchar(100) ) AS "REALTIME_RATE_FLAG"
                        ,CAST("SINGLE_USER_FLAG" AS varchar(100) ) AS "SINGLE_USER_FLAG"
                        ,CAST("WATCH_ACCOUNT_FLAG" AS varchar(100) ) AS "WATCH_ACCOUNT_FLAG"
                        ,CAST("WATCH_BALANCE_INDICATOR" AS varchar(100) ) AS "WATCH_BALANCE_INDICATOR"
                        ,CAST("GEO_CODE" AS varchar(100) ) AS "GEO_CODE"
                        ,CAST("ACCT_LIFE_CYCLE_STATUS" AS varchar(100) ) AS "ACCT_LIFE_CYCLE_STATUS"
                        ,CAST("ACCOUNT_NAME" AS varchar(1000) ) AS "ACCOUNT_NAME"
                        ,CAST("DEPOSIT_REFUND_METHOD" AS varchar(100) ) AS "DEPOSIT_REFUND_METHOD"
                        ,CAST("DORMANT_ACCOUNT_FLAG" AS varchar(100) ) AS "DORMANT_ACCOUNT_FLAG"
                        ,CAST("NPA_NUMBER" AS varchar(1000) ) AS "NPA_NUMBER"
                        ,CAST("PIN_NUMBER" AS float) AS "PIN_NUMBER"
                        ,TRY_CONVERT(datetime2,"SUSPENSION_DATE",121) AS "SUSPENSION_DATE"
                        ,CAST("WRITE_OFF_ADJUSTMENT_AMOUNT" AS float) AS "WRITE_OFF_ADJUSTMENT_AMOUNT"
                        ,CAST("WRITE_OFF_PAYMENT_AMOUNT" AS float) AS "WRITE_OFF_PAYMENT_AMOUNT"
                        ,CAST("WRITE_OFF_AMOUNT" AS float) AS "WRITE_OFF_AMOUNT"
                        ,CAST("SOURCE_CODE" AS varchar(1000) ) AS "SOURCE_CODE"
                        ,CAST("COMPETITOR_TYPE" AS varchar(1000) ) AS "COMPETITOR_TYPE"
                        ,CAST("COMMENTS" AS varchar(1000) ) AS "COMMENTS"
                        ,CAST("DATES_NEGATIVE_TOLERANCE" AS float) AS "DATES_NEGATIVE_TOLERANCE"
                        ,CAST("DATES_POSITIVE_TOLERANCE" AS float) AS "DATES_POSITIVE_TOLERANCE"
                        ,CAST("DATE_TYPE_PREFERENCE" AS varchar(100) ) AS "DATE_TYPE_PREFERENCE"
                        ,CAST("OVER_SHIPMENT_TOLERANCE" AS float) AS "OVER_SHIPMENT_TOLERANCE"
                        ,CAST("UNDER_SHIPMENT_TOLERANCE" AS float) AS "UNDER_SHIPMENT_TOLERANCE"
                        ,CAST("OVER_RETURN_TOLERANCE" AS float) AS "OVER_RETURN_TOLERANCE"
                        ,CAST("UNDER_RETURN_TOLERANCE" AS float) AS "UNDER_RETURN_TOLERANCE"
                        ,CAST("ITEM_CROSS_REF_PREF" AS varchar(100) ) AS "ITEM_CROSS_REF_PREF"
                        ,CAST("SHIP_SETS_INCLUDE_LINES_FLAG" AS varchar(100) ) AS "SHIP_SETS_INCLUDE_LINES_FLAG"
                        ,CAST("ARRIVALSETS_INCLUDE_LINES_FLAG" AS varchar(100) ) AS "ARRIVALSETS_INCLUDE_LINES_FLAG"
                        ,CAST("SCHED_DATE_PUSH_FLAG" AS varchar(100) ) AS "SCHED_DATE_PUSH_FLAG"
                        ,CAST("INVOICE_QUANTITY_RULE" AS varchar(100) ) AS "INVOICE_QUANTITY_RULE"
                        ,CAST("PRICING_EVENT" AS varchar(100) ) AS "PRICING_EVENT"
                        ,CAST("ACCOUNT_REPLICATION_KEY" AS float) AS "ACCOUNT_REPLICATION_KEY"
                        ,TRY_CONVERT(datetime2,"STATUS_UPDATE_DATE",121) AS "STATUS_UPDATE_DATE"
                        ,CAST("AUTOPAY_FLAG" AS varchar(100) ) AS "AUTOPAY_FLAG"
                        ,CAST("NOTIFY_FLAG" AS varchar(100) ) AS "NOTIFY_FLAG"
                        ,CAST("LAST_BATCH_ID" AS float) AS "LAST_BATCH_ID"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,CAST("OBJECT_VERSION_NUMBER" AS float) AS "OBJECT_VERSION_NUMBER"
                        ,CAST("CREATED_BY_MODULE" AS varchar(1000) ) AS "CREATED_BY_MODULE"
                        ,CAST("APPLICATION_ID" AS float) AS "APPLICATION_ID"
                        ,CAST("SELLING_PARTY_ID" AS float) AS "SELLING_PARTY_ID"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "CUST_ACCOUNT_ID"
                            , "PARTY_ID"
                            , "LAST_UPDATE_DATE"
                            , "ACCOUNT_NUMBER"
                            , "LAST_UPDATED_BY"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "WH_UPDATE_DATE"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "ATTRIBUTE16"
                            , "ATTRIBUTE17"
                            , "ATTRIBUTE18"
                            , "ATTRIBUTE19"
                            , "ATTRIBUTE20"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "ORIG_SYSTEM_REFERENCE"
                            , "STATUS"
                            , "CUSTOMER_TYPE"
                            , "CUSTOMER_CLASS_CODE"
                            , "PRIMARY_SALESREP_ID"
                            , "SALES_CHANNEL_CODE"
                            , "ORDER_TYPE_ID"
                            , "PRICE_LIST_ID"
                            , "SUBCATEGORY_CODE"
                            , "TAX_CODE"
                            , "FOB_POINT"
                            , "FREIGHT_TERM"
                            , "SHIP_PARTIAL"
                            , "SHIP_VIA"
                            , "WAREHOUSE_ID"
                            , "PAYMENT_TERM_ID"
                            , "TAX_HEADER_LEVEL_FLAG"
                            , "TAX_ROUNDING_RULE"
                            , "COTERMINATE_DAY_MONTH"
                            , "PRIMARY_SPECIALIST_ID"
                            , "SECONDARY_SPECIALIST_ID"
                            , "ACCOUNT_LIABLE_FLAG"
                            , "RESTRICTION_LIMIT_AMOUNT"
                            , "CURRENT_BALANCE"
                            , "PASSWORD_TEXT"
                            , "HIGH_PRIORITY_INDICATOR"
                            , "ACCOUNT_ESTABLISHED_DATE"
                            , "ACCOUNT_TERMINATION_DATE"
                            , "ACCOUNT_ACTIVATION_DATE"
                            , "CREDIT_CLASSIFICATION_CODE"
                            , "DEPARTMENT"
                            , "MAJOR_ACCOUNT_NUMBER"
                            , "HOTWATCH_SERVICE_FLAG"
                            , "HOTWATCH_SVC_BAL_IND"
                            , "HELD_BILL_EXPIRATION_DATE"
                            , "HOLD_BILL_FLAG"
                            , "HIGH_PRIORITY_REMARKS"
                            , "PO_EFFECTIVE_DATE"
                            , "PO_EXPIRATION_DATE"
                            , "REALTIME_RATE_FLAG"
                            , "SINGLE_USER_FLAG"
                            , "WATCH_ACCOUNT_FLAG"
                            , "WATCH_BALANCE_INDICATOR"
                            , "GEO_CODE"
                            , "ACCT_LIFE_CYCLE_STATUS"
                            , "ACCOUNT_NAME"
                            , "DEPOSIT_REFUND_METHOD"
                            , "DORMANT_ACCOUNT_FLAG"
                            , "NPA_NUMBER"
                            , "PIN_NUMBER"
                            , "SUSPENSION_DATE"
                            , "WRITE_OFF_ADJUSTMENT_AMOUNT"
                            , "WRITE_OFF_PAYMENT_AMOUNT"
                            , "WRITE_OFF_AMOUNT"
                            , "SOURCE_CODE"
                            , "COMPETITOR_TYPE"
                            , "COMMENTS"
                            , "DATES_NEGATIVE_TOLERANCE"
                            , "DATES_POSITIVE_TOLERANCE"
                            , "DATE_TYPE_PREFERENCE"
                            , "OVER_SHIPMENT_TOLERANCE"
                            , "UNDER_SHIPMENT_TOLERANCE"
                            , "OVER_RETURN_TOLERANCE"
                            , "UNDER_RETURN_TOLERANCE"
                            , "ITEM_CROSS_REF_PREF"
                            , "SHIP_SETS_INCLUDE_LINES_FLAG"
                            , "ARRIVALSETS_INCLUDE_LINES_FLAG"
                            , "SCHED_DATE_PUSH_FLAG"
                            , "INVOICE_QUANTITY_RULE"
                            , "PRICING_EVENT"
                            , "ACCOUNT_REPLICATION_KEY"
                            , "STATUS_UPDATE_DATE"
                            , "AUTOPAY_FLAG"
                            , "NOTIFY_FLAG"
                            , "LAST_BATCH_ID"
                            , "ORG_ID"
                            , "OBJECT_VERSION_NUMBER"
                            , "CREATED_BY_MODULE"
                            , "APPLICATION_ID"
                            , "SELLING_PARTY_ID"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_HZ_CUST_ACCOUNTS_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
