CREATE PROCEDURE "STG"."LOAD_STG_EBS_PO_LINES_ALL"
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        5/05/2022 11:48:53 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_PO_LINES_ALL";
    
    
    Source                          Destination                  
    ----------------------------    ---------------------------- 
    LND"."LND_EBS_PO_LINES_ALL"    "STG"."STG_EBS_PO_LINES_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-05    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_PO_LINES_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_PO_LINES_ALL"
                (
                    "PO_LINE_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"PO_HEADER_ID"
                    ,"LINE_TYPE_ID"
                    ,"LINE_NUM"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"ITEM_ID"
                    ,"ITEM_REVISION"
                    ,"CATEGORY_ID"
                    ,"ITEM_DESCRIPTION"
                    ,"UNIT_MEAS_LOOKUP_CODE"
                    ,"QUANTITY_COMMITTED"
                    ,"COMMITTED_AMOUNT"
                    ,"ALLOW_PRICE_OVERRIDE_FLAG"
                    ,"NOT_TO_EXCEED_PRICE"
                    ,"LIST_PRICE_PER_UNIT"
                    ,"UNIT_PRICE"
                    ,"QUANTITY"
                    ,"UN_NUMBER_ID"
                    ,"HAZARD_CLASS_ID"
                    ,"NOTE_TO_VENDOR"
                    ,"FROM_HEADER_ID"
                    ,"FROM_LINE_ID"
                    ,"MIN_ORDER_QUANTITY"
                    ,"MAX_ORDER_QUANTITY"
                    ,"QTY_RCV_TOLERANCE"
                    ,"OVER_TOLERANCE_ERROR_FLAG"
                    ,"MARKET_PRICE"
                    ,"UNORDERED_FLAG"
                    ,"CLOSED_FLAG"
                    ,"USER_HOLD_FLAG"
                    ,"CANCEL_FLAG"
                    ,"CANCELLED_BY"
                    ,"CANCEL_DATE"
                    ,"CANCEL_REASON"
                    ,"FIRM_STATUS_LOOKUP_CODE"
                    ,"FIRM_DATE"
                    ,"VENDOR_PRODUCT_NUM"
                    ,"CONTRACT_NUM"
                    ,"TAXABLE_FLAG"
                    ,"TAX_NAME"
                    ,"TYPE_1099"
                    ,"CAPITAL_EXPENSE_FLAG"
                    ,"NEGOTIATED_BY_PREPARER_FLAG"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"REFERENCE_NUM"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"MIN_RELEASE_AMOUNT"
                    ,"PRICE_TYPE_LOOKUP_CODE"
                    ,"CLOSED_CODE"
                    ,"PRICE_BREAK_LOOKUP_CODE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"GOVERNMENT_CONTEXT"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"CLOSED_DATE"
                    ,"CLOSED_REASON"
                    ,"CLOSED_BY"
                    ,"TRANSACTION_REASON_CODE"
                    ,"ORG_ID"
                    ,"QC_GRADE"
                    ,"BASE_UOM"
                    ,"BASE_QTY"
                    ,"SECONDARY_UOM"
                    ,"SECONDARY_QTY"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"LINE_REFERENCE_NUM"
                    ,"PROJECT_ID"
                    ,"TASK_ID"
                    ,"EXPIRATION_DATE"
                    ,"TAX_CODE_ID"
                    ,"OKE_CONTRACT_HEADER_ID"
                    ,"OKE_CONTRACT_VERSION_ID"
                    ,"SECONDARY_QUANTITY"
                    ,"SECONDARY_UNIT_OF_MEASURE"
                    ,"PREFERRED_GRADE"
                    ,"AUCTION_HEADER_ID"
                    ,"AUCTION_DISPLAY_NUMBER"
                    ,"AUCTION_LINE_NUMBER"
                    ,"BID_NUMBER"
                    ,"BID_LINE_NUMBER"
                    ,"RETROACTIVE_DATE"
                    ,"FROM_LINE_LOCATION_ID"
                    ,"SUPPLIER_REF_NUMBER"
                    ,"CONTRACT_ID"
                    ,"START_DATE"
                    ,"AMOUNT"
                    ,"JOB_ID"
                    ,"CONTRACTOR_FIRST_NAME"
                    ,"CONTRACTOR_LAST_NAME"
                    ,"ORDER_TYPE_LOOKUP_CODE"
                    ,"PURCHASE_BASIS"
                    ,"MATCHING_BASIS"
                    ,"SVC_AMOUNT_NOTIF_SENT"
                    ,"SVC_COMPLETION_NOTIF_SENT"
                    ,"BASE_UNIT_PRICE"
                    ,"MANUAL_PRICE_CHANGE_FLAG"
                    ,"RETAINAGE_RATE"
                    ,"MAX_RETAINAGE_AMOUNT"
                    ,"PROGRESS_PAYMENT_RATE"
                    ,"RECOUPMENT_RATE"
                    ,"CATALOG_NAME"
                    ,"SUPPLIER_PART_AUXID"
                    ,"IP_CATEGORY_ID"
                    ,"TAX_ATTRIBUTE_UPDATE_CODE"
                    ,"LAST_UPDATED_PROGRAM"
                    ,"GROUP_LINE_ID"
                    ,"LINE_NUM_DISPLAY"
                    ,"CLM_INFO_FLAG"
                    ,"CLM_OPTION_INDICATOR"
                    ,"CLM_BASE_LINE_NUM"
                    ,"CLM_OPTION_NUM"
                    ,"CLM_OPTION_FROM_DATE"
                    ,"CLM_OPTION_TO_DATE"
                    ,"CLM_FUNDED_FLAG"
                    ,"CONTRACT_TYPE"
                    ,"COST_CONSTRAINT"
                    ,"CLM_IDC_TYPE"
                    ,"UDA_TEMPLATE_ID"
                    ,"USER_DOCUMENT_STATUS"
                    ,"DRAFT_ID"
                    ,"CLM_EXERCISED_FLAG"
                    ,"CLM_EXERCISED_DATE"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("PO_LINE_ID" AS float) AS "PO_LINE_ID"
                        ,CAST("LAST_UPDATE_DATE"  AS datetime2) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("PO_HEADER_ID" AS float) AS "PO_HEADER_ID"
                        ,CAST("LINE_TYPE_ID" AS float) AS "LINE_TYPE_ID"
                        ,CAST("LINE_NUM" AS float) AS "LINE_NUM"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("CREATION_DATE"  AS datetime2) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("ITEM_ID" AS float) AS "ITEM_ID"
                        ,CAST("ITEM_REVISION" AS varchar(100) ) AS "ITEM_REVISION"
                        ,CAST("CATEGORY_ID" AS float) AS "CATEGORY_ID"
                        ,CAST("ITEM_DESCRIPTION" AS varchar(1000) ) AS "ITEM_DESCRIPTION"
                        ,CAST("UNIT_MEAS_LOOKUP_CODE" AS varchar(100) ) AS "UNIT_MEAS_LOOKUP_CODE"
                        ,CAST("QUANTITY_COMMITTED" AS float) AS "QUANTITY_COMMITTED"
                        ,CAST("COMMITTED_AMOUNT" AS float) AS "COMMITTED_AMOUNT"
                        ,CAST("ALLOW_PRICE_OVERRIDE_FLAG" AS varchar(100) ) AS "ALLOW_PRICE_OVERRIDE_FLAG"
                        ,CAST("NOT_TO_EXCEED_PRICE" AS float) AS "NOT_TO_EXCEED_PRICE"
                        ,CAST("LIST_PRICE_PER_UNIT" AS float) AS "LIST_PRICE_PER_UNIT"
                        ,CAST("UNIT_PRICE" AS float) AS "UNIT_PRICE"
                        ,CAST("QUANTITY" AS float) AS "QUANTITY"
                        ,CAST("UN_NUMBER_ID" AS float) AS "UN_NUMBER_ID"
                        ,CAST("HAZARD_CLASS_ID" AS float) AS "HAZARD_CLASS_ID"
                        ,CAST("NOTE_TO_VENDOR" AS varchar(1000) ) AS "NOTE_TO_VENDOR"
                        ,CAST("FROM_HEADER_ID" AS float) AS "FROM_HEADER_ID"
                        ,CAST("FROM_LINE_ID" AS float) AS "FROM_LINE_ID"
                        ,CAST("MIN_ORDER_QUANTITY" AS float) AS "MIN_ORDER_QUANTITY"
                        ,CAST("MAX_ORDER_QUANTITY" AS float) AS "MAX_ORDER_QUANTITY"
                        ,CAST("QTY_RCV_TOLERANCE" AS float) AS "QTY_RCV_TOLERANCE"
                        ,CAST("OVER_TOLERANCE_ERROR_FLAG" AS varchar(100) ) AS "OVER_TOLERANCE_ERROR_FLAG"
                        ,CAST("MARKET_PRICE" AS float) AS "MARKET_PRICE"
                        ,CAST("UNORDERED_FLAG" AS varchar(100) ) AS "UNORDERED_FLAG"
                        ,CAST("CLOSED_FLAG" AS varchar(100) ) AS "CLOSED_FLAG"
                        ,CAST("USER_HOLD_FLAG" AS varchar(100) ) AS "USER_HOLD_FLAG"
                        ,CAST("CANCEL_FLAG" AS varchar(100) ) AS "CANCEL_FLAG"
                        ,CAST("CANCELLED_BY" AS float) AS "CANCELLED_BY"
                        ,CAST("CANCEL_DATE"  AS datetime2) AS "CANCEL_DATE"
                        ,CAST("CANCEL_REASON" AS varchar(1000) ) AS "CANCEL_REASON"
                        ,CAST("FIRM_STATUS_LOOKUP_CODE" AS varchar(100) ) AS "FIRM_STATUS_LOOKUP_CODE"
                        ,CAST("FIRM_DATE"  AS datetime2) AS "FIRM_DATE"
                        ,CAST("VENDOR_PRODUCT_NUM" AS varchar(100) ) AS "VENDOR_PRODUCT_NUM"
                        ,CAST("CONTRACT_NUM" AS varchar(100) ) AS "CONTRACT_NUM"
                        ,CAST("TAXABLE_FLAG" AS varchar(100) ) AS "TAXABLE_FLAG"
                        ,CAST("TAX_NAME" AS varchar(100) ) AS "TAX_NAME"
                        ,CAST("TYPE_1099" AS varchar(100) ) AS "TYPE_1099"
                        ,CAST("CAPITAL_EXPENSE_FLAG" AS varchar(100) ) AS "CAPITAL_EXPENSE_FLAG"
                        ,CAST("NEGOTIATED_BY_PREPARER_FLAG" AS varchar(100) ) AS "NEGOTIATED_BY_PREPARER_FLAG"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("REFERENCE_NUM" AS varchar(100) ) AS "REFERENCE_NUM"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("MIN_RELEASE_AMOUNT" AS float) AS "MIN_RELEASE_AMOUNT"
                        ,CAST("PRICE_TYPE_LOOKUP_CODE" AS varchar(100) ) AS "PRICE_TYPE_LOOKUP_CODE"
                        ,CAST("CLOSED_CODE" AS varchar(100) ) AS "CLOSED_CODE"
                        ,CAST("PRICE_BREAK_LOOKUP_CODE" AS varchar(100) ) AS "PRICE_BREAK_LOOKUP_CODE"
                        ,CAST("USSGL_TRANSACTION_CODE" AS varchar(100) ) AS "USSGL_TRANSACTION_CODE"
                        ,CAST("GOVERNMENT_CONTEXT" AS varchar(100) ) AS "GOVERNMENT_CONTEXT"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,CAST("PROGRAM_UPDATE_DATE"  AS datetime2) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("CLOSED_DATE"  AS datetime2) AS "CLOSED_DATE"
                        ,CAST("CLOSED_REASON" AS varchar(1000) ) AS "CLOSED_REASON"
                        ,CAST("CLOSED_BY" AS float) AS "CLOSED_BY"
                        ,CAST("TRANSACTION_REASON_CODE" AS varchar(100) ) AS "TRANSACTION_REASON_CODE"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,CAST("QC_GRADE" AS varchar(100) ) AS "QC_GRADE"
                        ,CAST("BASE_UOM" AS varchar(100) ) AS "BASE_UOM"
                        ,CAST("BASE_QTY" AS float) AS "BASE_QTY"
                        ,CAST("SECONDARY_UOM" AS varchar(100) ) AS "SECONDARY_UOM"
                        ,CAST("SECONDARY_QTY" AS float) AS "SECONDARY_QTY"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("LINE_REFERENCE_NUM" AS varchar(100) ) AS "LINE_REFERENCE_NUM"
                        ,CAST("PROJECT_ID" AS float) AS "PROJECT_ID"
                        ,CAST("TASK_ID" AS float) AS "TASK_ID"
                        ,CAST("EXPIRATION_DATE"  AS datetime2) AS "EXPIRATION_DATE"
                        ,CAST("TAX_CODE_ID" AS float) AS "TAX_CODE_ID"
                        ,CAST("OKE_CONTRACT_HEADER_ID" AS float) AS "OKE_CONTRACT_HEADER_ID"
                        ,CAST("OKE_CONTRACT_VERSION_ID" AS float) AS "OKE_CONTRACT_VERSION_ID"
                        ,CAST("SECONDARY_QUANTITY" AS float) AS "SECONDARY_QUANTITY"
                        ,CAST("SECONDARY_UNIT_OF_MEASURE" AS varchar(100) ) AS "SECONDARY_UNIT_OF_MEASURE"
                        ,CAST("PREFERRED_GRADE" AS varchar(1000) ) AS "PREFERRED_GRADE"
                        ,CAST("AUCTION_HEADER_ID" AS float) AS "AUCTION_HEADER_ID"
                        ,CAST("AUCTION_DISPLAY_NUMBER" AS varchar(100) ) AS "AUCTION_DISPLAY_NUMBER"
                        ,CAST("AUCTION_LINE_NUMBER" AS float) AS "AUCTION_LINE_NUMBER"
                        ,CAST("BID_NUMBER" AS float) AS "BID_NUMBER"
                        ,CAST("BID_LINE_NUMBER" AS float) AS "BID_LINE_NUMBER"
                        ,CAST("RETROACTIVE_DATE"  AS datetime2) AS "RETROACTIVE_DATE"
                        ,CAST("FROM_LINE_LOCATION_ID" AS float) AS "FROM_LINE_LOCATION_ID"
                        ,CAST("SUPPLIER_REF_NUMBER" AS varchar(1000) ) AS "SUPPLIER_REF_NUMBER"
                        ,CAST("CONTRACT_ID" AS float) AS "CONTRACT_ID"
                        ,CAST("START_DATE"  AS datetime2) AS "START_DATE"
                        ,CAST("AMOUNT" AS float) AS "AMOUNT"
                        ,CAST("JOB_ID" AS float) AS "JOB_ID"
                        ,CAST("CONTRACTOR_FIRST_NAME" AS varchar(1000) ) AS "CONTRACTOR_FIRST_NAME"
                        ,CAST("CONTRACTOR_LAST_NAME" AS varchar(1000) ) AS "CONTRACTOR_LAST_NAME"
                        ,CAST("ORDER_TYPE_LOOKUP_CODE" AS varchar(100) ) AS "ORDER_TYPE_LOOKUP_CODE"
                        ,CAST("PURCHASE_BASIS" AS varchar(100) ) AS "PURCHASE_BASIS"
                        ,CAST("MATCHING_BASIS" AS varchar(100) ) AS "MATCHING_BASIS"
                        ,CAST("SVC_AMOUNT_NOTIF_SENT" AS varchar(100) ) AS "SVC_AMOUNT_NOTIF_SENT"
                        ,CAST("SVC_COMPLETION_NOTIF_SENT" AS varchar(100) ) AS "SVC_COMPLETION_NOTIF_SENT"
                        ,CAST("BASE_UNIT_PRICE" AS float) AS "BASE_UNIT_PRICE"
                        ,CAST("MANUAL_PRICE_CHANGE_FLAG" AS varchar(100) ) AS "MANUAL_PRICE_CHANGE_FLAG"
                        ,CAST("RETAINAGE_RATE" AS float) AS "RETAINAGE_RATE"
                        ,CAST("MAX_RETAINAGE_AMOUNT" AS float) AS "MAX_RETAINAGE_AMOUNT"
                        ,CAST("PROGRESS_PAYMENT_RATE" AS float) AS "PROGRESS_PAYMENT_RATE"
                        ,CAST("RECOUPMENT_RATE" AS float) AS "RECOUPMENT_RATE"
                        ,CAST("CATALOG_NAME" AS varchar(1000) ) AS "CATALOG_NAME"
                        ,CAST("SUPPLIER_PART_AUXID" AS varchar(1000) ) AS "SUPPLIER_PART_AUXID"
                        ,CAST("IP_CATEGORY_ID" AS float) AS "IP_CATEGORY_ID"
                        ,CAST("TAX_ATTRIBUTE_UPDATE_CODE" AS varchar(100) ) AS "TAX_ATTRIBUTE_UPDATE_CODE"
                        ,CAST("LAST_UPDATED_PROGRAM" AS varchar(1000) ) AS "LAST_UPDATED_PROGRAM"
                        ,CAST("GROUP_LINE_ID" AS float) AS "GROUP_LINE_ID"
                        ,CAST("LINE_NUM_DISPLAY" AS varchar(1000) ) AS "LINE_NUM_DISPLAY"
                        ,CAST("CLM_INFO_FLAG" AS varchar(100) ) AS "CLM_INFO_FLAG"
                        ,CAST("CLM_OPTION_INDICATOR" AS varchar(100) ) AS "CLM_OPTION_INDICATOR"
                        ,CAST("CLM_BASE_LINE_NUM" AS float) AS "CLM_BASE_LINE_NUM"
                        ,CAST("CLM_OPTION_NUM" AS float) AS "CLM_OPTION_NUM"
                        ,CAST("CLM_OPTION_FROM_DATE"  AS datetime2) AS "CLM_OPTION_FROM_DATE"
                        ,CAST("CLM_OPTION_TO_DATE"  AS datetime2) AS "CLM_OPTION_TO_DATE"
                        ,CAST("CLM_FUNDED_FLAG" AS varchar(100) ) AS "CLM_FUNDED_FLAG"
                        ,CAST("CONTRACT_TYPE" AS varchar(1000) ) AS "CONTRACT_TYPE"
                        ,CAST("COST_CONSTRAINT" AS varchar(1000) ) AS "COST_CONSTRAINT"
                        ,CAST("CLM_IDC_TYPE" AS varchar(1000) ) AS "CLM_IDC_TYPE"
                        ,CAST("UDA_TEMPLATE_ID" AS float) AS "UDA_TEMPLATE_ID"
                        ,CAST("USER_DOCUMENT_STATUS" AS varchar(100) ) AS "USER_DOCUMENT_STATUS"
                        ,CAST("DRAFT_ID" AS float) AS "DRAFT_ID"
                        ,CAST("CLM_EXERCISED_FLAG" AS varchar(100) ) AS "CLM_EXERCISED_FLAG"
                        ,CAST("CLM_EXERCISED_DATE"  AS datetime2) AS "CLM_EXERCISED_DATE"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "PO_LINE_ID"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "PO_HEADER_ID"
                            , "LINE_TYPE_ID"
                            , "LINE_NUM"
                            , "LAST_UPDATE_LOGIN"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "ITEM_ID"
                            , "ITEM_REVISION"
                            , "CATEGORY_ID"
                            , "ITEM_DESCRIPTION"
                            , "UNIT_MEAS_LOOKUP_CODE"
                            , "QUANTITY_COMMITTED"
                            , "COMMITTED_AMOUNT"
                            , "ALLOW_PRICE_OVERRIDE_FLAG"
                            , "NOT_TO_EXCEED_PRICE"
                            , "LIST_PRICE_PER_UNIT"
                            , "UNIT_PRICE"
                            , "QUANTITY"
                            , "UN_NUMBER_ID"
                            , "HAZARD_CLASS_ID"
                            , "NOTE_TO_VENDOR"
                            , "FROM_HEADER_ID"
                            , "FROM_LINE_ID"
                            , "MIN_ORDER_QUANTITY"
                            , "MAX_ORDER_QUANTITY"
                            , "QTY_RCV_TOLERANCE"
                            , "OVER_TOLERANCE_ERROR_FLAG"
                            , "MARKET_PRICE"
                            , "UNORDERED_FLAG"
                            , "CLOSED_FLAG"
                            , "USER_HOLD_FLAG"
                            , "CANCEL_FLAG"
                            , "CANCELLED_BY"
                            , "CANCEL_DATE"
                            , "CANCEL_REASON"
                            , "FIRM_STATUS_LOOKUP_CODE"
                            , "FIRM_DATE"
                            , "VENDOR_PRODUCT_NUM"
                            , "CONTRACT_NUM"
                            , "TAXABLE_FLAG"
                            , "TAX_NAME"
                            , "TYPE_1099"
                            , "CAPITAL_EXPENSE_FLAG"
                            , "NEGOTIATED_BY_PREPARER_FLAG"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "REFERENCE_NUM"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "MIN_RELEASE_AMOUNT"
                            , "PRICE_TYPE_LOOKUP_CODE"
                            , "CLOSED_CODE"
                            , "PRICE_BREAK_LOOKUP_CODE"
                            , "USSGL_TRANSACTION_CODE"
                            , "GOVERNMENT_CONTEXT"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "CLOSED_DATE"
                            , "CLOSED_REASON"
                            , "CLOSED_BY"
                            , "TRANSACTION_REASON_CODE"
                            , "ORG_ID"
                            , "QC_GRADE"
                            , "BASE_UOM"
                            , "BASE_QTY"
                            , "SECONDARY_UOM"
                            , "SECONDARY_QTY"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "LINE_REFERENCE_NUM"
                            , "PROJECT_ID"
                            , "TASK_ID"
                            , "EXPIRATION_DATE"
                            , "TAX_CODE_ID"
                            , "OKE_CONTRACT_HEADER_ID"
                            , "OKE_CONTRACT_VERSION_ID"
                            , "SECONDARY_QUANTITY"
                            , "SECONDARY_UNIT_OF_MEASURE"
                            , "PREFERRED_GRADE"
                            , "AUCTION_HEADER_ID"
                            , "AUCTION_DISPLAY_NUMBER"
                            , "AUCTION_LINE_NUMBER"
                            , "BID_NUMBER"
                            , "BID_LINE_NUMBER"
                            , "RETROACTIVE_DATE"
                            , "FROM_LINE_LOCATION_ID"
                            , "SUPPLIER_REF_NUMBER"
                            , "CONTRACT_ID"
                            , "START_DATE"
                            , "AMOUNT"
                            , "JOB_ID"
                            , "CONTRACTOR_FIRST_NAME"
                            , "CONTRACTOR_LAST_NAME"
                            , "ORDER_TYPE_LOOKUP_CODE"
                            , "PURCHASE_BASIS"
                            , "MATCHING_BASIS"
                            , "SVC_AMOUNT_NOTIF_SENT"
                            , "SVC_COMPLETION_NOTIF_SENT"
                            , "BASE_UNIT_PRICE"
                            , "MANUAL_PRICE_CHANGE_FLAG"
                            , "RETAINAGE_RATE"
                            , "MAX_RETAINAGE_AMOUNT"
                            , "PROGRESS_PAYMENT_RATE"
                            , "RECOUPMENT_RATE"
                            , "CATALOG_NAME"
                            , "SUPPLIER_PART_AUXID"
                            , "IP_CATEGORY_ID"
                            , "TAX_ATTRIBUTE_UPDATE_CODE"
                            , "LAST_UPDATED_PROGRAM"
                            , "GROUP_LINE_ID"
                            , "LINE_NUM_DISPLAY"
                            , "CLM_INFO_FLAG"
                            , "CLM_OPTION_INDICATOR"
                            , "CLM_BASE_LINE_NUM"
                            , "CLM_OPTION_NUM"
                            , "CLM_OPTION_FROM_DATE"
                            , "CLM_OPTION_TO_DATE"
                            , "CLM_FUNDED_FLAG"
                            , "CONTRACT_TYPE"
                            , "COST_CONSTRAINT"
                            , "CLM_IDC_TYPE"
                            , "UDA_TEMPLATE_ID"
                            , "USER_DOCUMENT_STATUS"
                            , "DRAFT_ID"
                            , "CLM_EXERCISED_FLAG"
                            , "CLM_EXERCISED_DATE"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_PO_LINES_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
