CREATE PROCEDURE "STG"."LOAD_STG_EBS_HZ_LOCATIONS"
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        5/05/2022 11:48:51 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_HZ_LOCATIONS";
    
    
    Source                          Destination                  
    ----------------------------    ---------------------------- 
    LND"."LND_EBS_HZ_LOCATIONS"    "STG"."STG_EBS_HZ_LOCATIONS" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-05    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_HZ_LOCATIONS";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_HZ_LOCATIONS"
                (
                    "LOCATION_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"WH_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"ORIG_SYSTEM_REFERENCE"
                    ,"COUNTRY"
                    ,"ADDRESS1"
                    ,"ADDRESS2"
                    ,"ADDRESS3"
                    ,"ADDRESS4"
                    ,"CITY"
                    ,"POSTAL_CODE"
                    ,"STATE"
                    ,"PROVINCE"
                    ,"COUNTY"
                    ,"ADDRESS_KEY"
                    ,"ADDRESS_STYLE"
                    ,"VALIDATED_FLAG"
                    ,"ADDRESS_LINES_PHONETIC"
                    ,"APARTMENT_FLAG"
                    ,"PO_BOX_NUMBER"
                    ,"HOUSE_NUMBER"
                    ,"STREET_SUFFIX"
                    ,"APARTMENT_NUMBER"
                    ,"SECONDARY_SUFFIX_ELEMENT"
                    ,"STREET"
                    ,"RURAL_ROUTE_TYPE"
                    ,"RURAL_ROUTE_NUMBER"
                    ,"STREET_NUMBER"
                    ,"BUILDING"
                    ,"FLOOR"
                    ,"SUITE"
                    ,"ROOM"
                    ,"POSTAL_PLUS4_CODE"
                    ,"TIME_ZONE"
                    ,"OVERSEAS_ADDRESS_FLAG"
                    ,"POST_OFFICE"
                    ,"POSITION"
                    ,"DELIVERY_POINT_CODE"
                    ,"LOCATION_DIRECTIONS"
                    ,"ADDRESS_EFFECTIVE_DATE"
                    ,"ADDRESS_EXPIRATION_DATE"
                    ,"ADDRESS_ERROR_CODE"
                    ,"CLLI_CODE"
                    ,"DODAAC"
                    ,"TRAILING_DIRECTORY_CODE"
                    ,"LANGUAGE"
                    ,"LIFE_CYCLE_STATUS"
                    ,"SHORT_DESCRIPTION"
                    ,"DESCRIPTION"
                    ,"CONTENT_SOURCE_TYPE"
                    ,"LOC_HIERARCHY_ID"
                    ,"SALES_TAX_GEOCODE"
                    ,"SALES_TAX_INSIDE_CITY_LIMITS"
                    ,"FA_LOCATION_ID"
                    ,"GEOMETRY"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"CREATED_BY_MODULE"
                    ,"APPLICATION_ID"
                    ,"TIMEZONE_ID"
                    ,"GEOMETRY_STATUS_CODE"
                    ,"ACTUAL_CONTENT_SOURCE"
                    ,"VALIDATION_STATUS_CODE"
                    ,"DATE_VALIDATED"
                    ,"DO_NOT_VALIDATE_FLAG"
                    ,"GEOMETRY_SOURCE"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("LOCATION_ID" AS float) AS "LOCATION_ID"
                        ,CAST("LAST_UPDATE_DATE"  AS datetime2) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("CREATION_DATE"  AS datetime2) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,CAST("PROGRAM_UPDATE_DATE"  AS datetime2) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("WH_UPDATE_DATE"  AS datetime2) AS "WH_UPDATE_DATE"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("ATTRIBUTE16" AS varchar(1000) ) AS "ATTRIBUTE16"
                        ,CAST("ATTRIBUTE17" AS varchar(1000) ) AS "ATTRIBUTE17"
                        ,CAST("ATTRIBUTE18" AS varchar(1000) ) AS "ATTRIBUTE18"
                        ,CAST("ATTRIBUTE19" AS varchar(1000) ) AS "ATTRIBUTE19"
                        ,CAST("ATTRIBUTE20" AS varchar(1000) ) AS "ATTRIBUTE20"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("ORIG_SYSTEM_REFERENCE" AS varchar(1000) ) AS "ORIG_SYSTEM_REFERENCE"
                        ,CAST("COUNTRY" AS varchar(1000) ) AS "COUNTRY"
                        ,CAST("ADDRESS1" AS varchar(1000) ) AS "ADDRESS1"
                        ,CAST("ADDRESS2" AS varchar(1000) ) AS "ADDRESS2"
                        ,CAST("ADDRESS3" AS varchar(1000) ) AS "ADDRESS3"
                        ,CAST("ADDRESS4" AS varchar(1000) ) AS "ADDRESS4"
                        ,CAST("CITY" AS varchar(1000) ) AS "CITY"
                        ,CAST("POSTAL_CODE" AS varchar(1000) ) AS "POSTAL_CODE"
                        ,CAST("STATE" AS varchar(1000) ) AS "STATE"
                        ,CAST("PROVINCE" AS varchar(1000) ) AS "PROVINCE"
                        ,CAST("COUNTY" AS varchar(1000) ) AS "COUNTY"
                        ,CAST("ADDRESS_KEY" AS varchar(1000) ) AS "ADDRESS_KEY"
                        ,CAST("ADDRESS_STYLE" AS varchar(100) ) AS "ADDRESS_STYLE"
                        ,CAST("VALIDATED_FLAG" AS varchar(100) ) AS "VALIDATED_FLAG"
                        ,CAST("ADDRESS_LINES_PHONETIC" AS varchar(8000) ) AS "ADDRESS_LINES_PHONETIC"
                        ,CAST("APARTMENT_FLAG" AS varchar(100) ) AS "APARTMENT_FLAG"
                        ,CAST("PO_BOX_NUMBER" AS varchar(1000) ) AS "PO_BOX_NUMBER"
                        ,CAST("HOUSE_NUMBER" AS varchar(1000) ) AS "HOUSE_NUMBER"
                        ,CAST("STREET_SUFFIX" AS varchar(1000) ) AS "STREET_SUFFIX"
                        ,CAST("APARTMENT_NUMBER" AS varchar(1000) ) AS "APARTMENT_NUMBER"
                        ,CAST("SECONDARY_SUFFIX_ELEMENT" AS varchar(1000) ) AS "SECONDARY_SUFFIX_ELEMENT"
                        ,CAST("STREET" AS varchar(1000) ) AS "STREET"
                        ,CAST("RURAL_ROUTE_TYPE" AS varchar(1000) ) AS "RURAL_ROUTE_TYPE"
                        ,CAST("RURAL_ROUTE_NUMBER" AS varchar(1000) ) AS "RURAL_ROUTE_NUMBER"
                        ,CAST("STREET_NUMBER" AS varchar(1000) ) AS "STREET_NUMBER"
                        ,CAST("BUILDING" AS varchar(1000) ) AS "BUILDING"
                        ,CAST("FLOOR" AS varchar(1000) ) AS "FLOOR"
                        ,CAST("SUITE" AS varchar(1000) ) AS "SUITE"
                        ,CAST("ROOM" AS varchar(1000) ) AS "ROOM"
                        ,CAST("POSTAL_PLUS4_CODE" AS varchar(100) ) AS "POSTAL_PLUS4_CODE"
                        ,CAST("TIME_ZONE" AS varchar(1000) ) AS "TIME_ZONE"
                        ,CAST("OVERSEAS_ADDRESS_FLAG" AS varchar(100) ) AS "OVERSEAS_ADDRESS_FLAG"
                        ,CAST("POST_OFFICE" AS varchar(1000) ) AS "POST_OFFICE"
                        ,CAST("POSITION" AS varchar(1000) ) AS "POSITION"
                        ,CAST("DELIVERY_POINT_CODE" AS varchar(1000) ) AS "DELIVERY_POINT_CODE"
                        ,CAST("LOCATION_DIRECTIONS" AS varchar(8000) ) AS "LOCATION_DIRECTIONS"
                        ,CAST("ADDRESS_EFFECTIVE_DATE"  AS datetime2) AS "ADDRESS_EFFECTIVE_DATE"
                        ,CAST("ADDRESS_EXPIRATION_DATE"  AS datetime2) AS "ADDRESS_EXPIRATION_DATE"
                        ,CAST("ADDRESS_ERROR_CODE" AS varchar(1000) ) AS "ADDRESS_ERROR_CODE"
                        ,CAST("CLLI_CODE" AS varchar(1000) ) AS "CLLI_CODE"
                        ,CAST("DODAAC" AS varchar(100) ) AS "DODAAC"
                        ,CAST("TRAILING_DIRECTORY_CODE" AS varchar(1000) ) AS "TRAILING_DIRECTORY_CODE"
                        ,CAST("LANGUAGE" AS varchar(100) ) AS "LANGUAGE"
                        ,CAST("LIFE_CYCLE_STATUS" AS varchar(100) ) AS "LIFE_CYCLE_STATUS"
                        ,CAST("SHORT_DESCRIPTION" AS varchar(1000) ) AS "SHORT_DESCRIPTION"
                        ,CAST("DESCRIPTION" AS varchar(8000) ) AS "DESCRIPTION"
                        ,CAST("CONTENT_SOURCE_TYPE" AS varchar(100) ) AS "CONTENT_SOURCE_TYPE"
                        ,CAST("LOC_HIERARCHY_ID" AS float) AS "LOC_HIERARCHY_ID"
                        ,CAST("SALES_TAX_GEOCODE" AS varchar(100) ) AS "SALES_TAX_GEOCODE"
                        ,CAST("SALES_TAX_INSIDE_CITY_LIMITS" AS varchar(100) ) AS "SALES_TAX_INSIDE_CITY_LIMITS"
                        ,CAST("FA_LOCATION_ID" AS float) AS "FA_LOCATION_ID"
                        ,CAST("GEOMETRY" AS varchar(1000) ) AS "GEOMETRY"
                        ,CAST("OBJECT_VERSION_NUMBER" AS float) AS "OBJECT_VERSION_NUMBER"
                        ,CAST("CREATED_BY_MODULE" AS varchar(1000) ) AS "CREATED_BY_MODULE"
                        ,CAST("APPLICATION_ID" AS float) AS "APPLICATION_ID"
                        ,CAST("TIMEZONE_ID" AS float) AS "TIMEZONE_ID"
                        ,CAST("GEOMETRY_STATUS_CODE" AS varchar(100) ) AS "GEOMETRY_STATUS_CODE"
                        ,CAST("ACTUAL_CONTENT_SOURCE" AS varchar(100) ) AS "ACTUAL_CONTENT_SOURCE"
                        ,CAST("VALIDATION_STATUS_CODE" AS varchar(100) ) AS "VALIDATION_STATUS_CODE"
                        ,CAST("DATE_VALIDATED"  AS datetime2) AS "DATE_VALIDATED"
                        ,CAST("DO_NOT_VALIDATE_FLAG" AS varchar(100) ) AS "DO_NOT_VALIDATE_FLAG"
                        ,CAST("GEOMETRY_SOURCE" AS varchar(100) ) AS "GEOMETRY_SOURCE"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "LOCATION_ID"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "WH_UPDATE_DATE"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "ATTRIBUTE16"
                            , "ATTRIBUTE17"
                            , "ATTRIBUTE18"
                            , "ATTRIBUTE19"
                            , "ATTRIBUTE20"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "ORIG_SYSTEM_REFERENCE"
                            , "COUNTRY"
                            , "ADDRESS1"
                            , "ADDRESS2"
                            , "ADDRESS3"
                            , "ADDRESS4"
                            , "CITY"
                            , "POSTAL_CODE"
                            , "STATE"
                            , "PROVINCE"
                            , "COUNTY"
                            , "ADDRESS_KEY"
                            , "ADDRESS_STYLE"
                            , "VALIDATED_FLAG"
                            , "ADDRESS_LINES_PHONETIC"
                            , "APARTMENT_FLAG"
                            , "PO_BOX_NUMBER"
                            , "HOUSE_NUMBER"
                            , "STREET_SUFFIX"
                            , "APARTMENT_NUMBER"
                            , "SECONDARY_SUFFIX_ELEMENT"
                            , "STREET"
                            , "RURAL_ROUTE_TYPE"
                            , "RURAL_ROUTE_NUMBER"
                            , "STREET_NUMBER"
                            , "BUILDING"
                            , "FLOOR"
                            , "SUITE"
                            , "ROOM"
                            , "POSTAL_PLUS4_CODE"
                            , "TIME_ZONE"
                            , "OVERSEAS_ADDRESS_FLAG"
                            , "POST_OFFICE"
                            , "POSITION"
                            , "DELIVERY_POINT_CODE"
                            , "LOCATION_DIRECTIONS"
                            , "ADDRESS_EFFECTIVE_DATE"
                            , "ADDRESS_EXPIRATION_DATE"
                            , "ADDRESS_ERROR_CODE"
                            , "CLLI_CODE"
                            , "DODAAC"
                            , "TRAILING_DIRECTORY_CODE"
                            , "LANGUAGE"
                            , "LIFE_CYCLE_STATUS"
                            , "SHORT_DESCRIPTION"
                            , "DESCRIPTION"
                            , "CONTENT_SOURCE_TYPE"
                            , "LOC_HIERARCHY_ID"
                            , "SALES_TAX_GEOCODE"
                            , "SALES_TAX_INSIDE_CITY_LIMITS"
                            , "FA_LOCATION_ID"
                            , "GEOMETRY"
                            , "OBJECT_VERSION_NUMBER"
                            , "CREATED_BY_MODULE"
                            , "APPLICATION_ID"
                            , "TIMEZONE_ID"
                            , "GEOMETRY_STATUS_CODE"
                            , "ACTUAL_CONTENT_SOURCE"
                            , "VALIDATION_STATUS_CODE"
                            , "DATE_VALIDATED"
                            , "DO_NOT_VALIDATE_FLAG"
                            , "GEOMETRY_SOURCE"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_HZ_LOCATIONS"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END