

CREATE PROCEDURE "STG"."LOAD_STG_CA_INCAT"
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        4/03/2022 6:46:55 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_CA_INCAT";
    
    
    Source                  Destination          
    --------------------    -------------------- 
    LND"."LND_CA_INCAT"    "STG"."STG_CA_INCAT" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-04    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_CA_INCAT";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_CA_INCAT"
                (
                    "Incat"
                    ,"Category Description"
                    ,"L"
                    ,"Gl Sales"
                    ,"Gl Purch"
                    ,"Gl Cogs"
                    ,"Gl Stock"
                    ,"Sales 1"
                    ,"Sales 2"
                    ,"Sales 3"
                    ,"Sales 4"
                    ,"Sales 5"
                    ,"Sales 6"
                    ,"Sales 7"
                    ,"Sales 8"
                    ,"Sales 9"
                    ,"Sales 10"
                    ,"Sales 11"
                    ,"Sales 12"
                    ,"Sales 13"
                    ,"Sales 14"
                    ,"Sales 15"
                    ,"Sales 16"
                    ,"Sales 17"
                    ,"Sales 18"
                    ,"Sales 19"
                    ,"Sales 20"
                    ,"Sales 21"
                    ,"Sales 22"
                    ,"Sales 23"
                    ,"Sales 24"
                    ,"Purch 1"
                    ,"Purch 2"
                    ,"Purch 3"
                    ,"Purch 4"
                    ,"Purch 5"
                    ,"Purch 6"
                    ,"Purch 7"
                    ,"Purch 8"
                    ,"Purch 9"
                    ,"Purch 10"
                    ,"Purch 11"
                    ,"Purch 12"
                    ,"Purch 13"
                    ,"Purch 14"
                    ,"Purch 15"
                    ,"Purch 16"
                    ,"Purch 17"
                    ,"Purch 18"
                    ,"Purch 19"
                    ,"Purch 20"
                    ,"Purch 21"
                    ,"Purch 22"
                    ,"Purch 23"
                    ,"Purch 24"
                    ,"Cogs 1"
                    ,"Cogs 2"
                    ,"Cogs 3"
                    ,"Cogs 4"
                    ,"Cogs 5"
                    ,"Cogs 6"
                    ,"Cogs 7"
                    ,"Cogs 8"
                    ,"Cogs 9"
                    ,"Cogs 10"
                    ,"Cogs 11"
                    ,"Cogs 12"
                    ,"Cogs 13"
                    ,"Cogs 14"
                    ,"Cogs 15"
                    ,"Cogs 16"
                    ,"Cogs 17"
                    ,"Cogs 18"
                    ,"Cogs 19"
                    ,"Cogs 20"
                    ,"Cogs 21"
                    ,"Cogs 22"
                    ,"Cogs 23"
                    ,"Cogs 24"
                    ,"Type"
                    ,"Minor"
                    ,"Mj"
                    ,"A"
                    ,"MaxDis"
                    ,"Gl Stk Adj"
                    ,"HG"
                    ,"CatReb"
                    ,"MinDis"
                    ,"Category Sub Description"
                    ,"Gl Grni"
                    ,"Gl Gsni"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("INCAT" AS nvarchar(20) ) AS "INCAT"
                        ,CAST("CATEGORY DESCRIPTION" AS nvarchar(120) ) AS "CATEGORY DESCRIPTION"
                        ,CAST("L" AS decimal(36,4)) AS "L"
                        ,CAST("GL SALES" AS nvarchar(20) ) AS "GL SALES"
                        ,CAST("GL PURCH" AS nvarchar(20) ) AS "GL PURCH"
                        ,CAST("GL COGS" AS nvarchar(20) ) AS "GL COGS"
                        ,CAST("GL STOCK" AS nvarchar(20) ) AS "GL STOCK"
                        ,CAST("SALES 1" AS decimal(36,4)) AS "SALES 1"
                        ,CAST("SALES 2" AS decimal(36,4)) AS "SALES 2"
                        ,CAST("SALES 3" AS decimal(36,4)) AS "SALES 3"
                        ,CAST("SALES 4" AS decimal(36,4)) AS "SALES 4"
                        ,CAST("SALES 5" AS decimal(36,4)) AS "SALES 5"
                        ,CAST("SALES 6" AS decimal(36,4)) AS "SALES 6"
                        ,CAST("SALES 7" AS decimal(36,4)) AS "SALES 7"
                        ,CAST("SALES 8" AS decimal(36,4)) AS "SALES 8"
                        ,CAST("SALES 9" AS decimal(36,4)) AS "SALES 9"
                        ,CAST("SALES 10" AS decimal(36,4)) AS "SALES 10"
                        ,CAST("SALES 11" AS decimal(36,4)) AS "SALES 11"
                        ,CAST("SALES 12" AS decimal(36,4)) AS "SALES 12"
                        ,CAST("SALES 13" AS decimal(36,4)) AS "SALES 13"
                        ,CAST("SALES 14" AS decimal(36,4)) AS "SALES 14"
                        ,CAST("SALES 15" AS decimal(36,4)) AS "SALES 15"
                        ,CAST("SALES 16" AS decimal(36,4)) AS "SALES 16"
                        ,CAST("SALES 17" AS decimal(36,4)) AS "SALES 17"
                        ,CAST("SALES 18" AS decimal(36,4)) AS "SALES 18"
                        ,CAST("SALES 19" AS decimal(36,4)) AS "SALES 19"
                        ,CAST("SALES 20" AS decimal(36,4)) AS "SALES 20"
                        ,CAST("SALES 21" AS decimal(36,4)) AS "SALES 21"
                        ,CAST("SALES 22" AS decimal(36,4)) AS "SALES 22"
                        ,CAST("SALES 23" AS decimal(36,4)) AS "SALES 23"
                        ,CAST("SALES 24" AS decimal(36,4)) AS "SALES 24"
                        ,CAST("PURCH 1" AS decimal(36,4)) AS "PURCH 1"
                        ,CAST("PURCH 2" AS decimal(36,4)) AS "PURCH 2"
                        ,CAST("PURCH 3" AS decimal(36,4)) AS "PURCH 3"
                        ,CAST("PURCH 4" AS decimal(36,4)) AS "PURCH 4"
                        ,CAST("PURCH 5" AS decimal(36,4)) AS "PURCH 5"
                        ,CAST("PURCH 6" AS decimal(36,4)) AS "PURCH 6"
                        ,CAST("PURCH 7" AS decimal(36,4)) AS "PURCH 7"
                        ,CAST("PURCH 8" AS decimal(36,4)) AS "PURCH 8"
                        ,CAST("PURCH 9" AS decimal(36,4)) AS "PURCH 9"
                        ,CAST("PURCH 10" AS decimal(36,4)) AS "PURCH 10"
                        ,CAST("PURCH 11" AS decimal(36,4)) AS "PURCH 11"
                        ,CAST("PURCH 12" AS decimal(36,4)) AS "PURCH 12"
                        ,CAST("PURCH 13" AS decimal(36,4)) AS "PURCH 13"
                        ,CAST("PURCH 14" AS decimal(36,4)) AS "PURCH 14"
                        ,CAST("PURCH 15" AS decimal(36,4)) AS "PURCH 15"
                        ,CAST("PURCH 16" AS decimal(36,4)) AS "PURCH 16"
                        ,CAST("PURCH 17" AS decimal(36,4)) AS "PURCH 17"
                        ,CAST("PURCH 18" AS decimal(36,4)) AS "PURCH 18"
                        ,CAST("PURCH 19" AS decimal(36,4)) AS "PURCH 19"
                        ,CAST("PURCH 20" AS decimal(36,4)) AS "PURCH 20"
                        ,CAST("PURCH 21" AS decimal(36,4)) AS "PURCH 21"
                        ,CAST("PURCH 22" AS decimal(36,4)) AS "PURCH 22"
                        ,CAST("PURCH 23" AS decimal(36,4)) AS "PURCH 23"
                        ,CAST("PURCH 24" AS decimal(36,4)) AS "PURCH 24"
                        ,CAST("COGS 1" AS decimal(36,4)) AS "COGS 1"
                        ,CAST("COGS 2" AS decimal(36,4)) AS "COGS 2"
                        ,CAST("COGS 3" AS decimal(36,4)) AS "COGS 3"
                        ,CAST("COGS 4" AS decimal(36,4)) AS "COGS 4"
                        ,CAST("COGS 5" AS decimal(36,4)) AS "COGS 5"
                        ,CAST("COGS 6" AS decimal(36,4)) AS "COGS 6"
                        ,CAST("COGS 7" AS decimal(36,4)) AS "COGS 7"
                        ,CAST("COGS 8" AS decimal(36,4)) AS "COGS 8"
                        ,CAST("COGS 9" AS decimal(36,4)) AS "COGS 9"
                        ,CAST("COGS 10" AS decimal(36,4)) AS "COGS 10"
                        ,CAST("COGS 11" AS decimal(36,4)) AS "COGS 11"
                        ,CAST("COGS 12" AS decimal(36,4)) AS "COGS 12"
                        ,CAST("COGS 13" AS decimal(36,4)) AS "COGS 13"
                        ,CAST("COGS 14" AS decimal(36,4)) AS "COGS 14"
                        ,CAST("COGS 15" AS decimal(36,4)) AS "COGS 15"
                        ,CAST("COGS 16" AS decimal(36,4)) AS "COGS 16"
                        ,CAST("COGS 17" AS decimal(36,4)) AS "COGS 17"
                        ,CAST("COGS 18" AS decimal(36,4)) AS "COGS 18"
                        ,CAST("COGS 19" AS decimal(36,4)) AS "COGS 19"
                        ,CAST("COGS 20" AS decimal(36,4)) AS "COGS 20"
                        ,CAST("COGS 21" AS decimal(36,4)) AS "COGS 21"
                        ,CAST("COGS 22" AS decimal(36,4)) AS "COGS 22"
                        ,CAST("COGS 23" AS decimal(36,4)) AS "COGS 23"
                        ,CAST("COGS 24" AS decimal(36,4)) AS "COGS 24"
                        ,CAST("TYPE" AS nvarchar(12) ) AS "TYPE"
                        ,CAST("MINOR" AS nvarchar(16) ) AS "MINOR"
                        ,CAST("MJ" AS nvarchar(4) ) AS "MJ"
                        ,CAST("A" AS nvarchar(6) ) AS "A"
                        ,CAST("MAXDIS" AS decimal(36,4)) AS "MAXDIS"
                        ,CAST("GL STK ADJ" AS nvarchar(20) ) AS "GL STK ADJ"
                        ,CAST("HG" AS nvarchar(6) ) AS "HG"
                        ,CAST("CATREB" AS decimal(36,4)) AS "CATREB"
                        ,CAST("MINDIS" AS decimal(36,4)) AS "MINDIS"
                        ,CAST("CATEGORY SUB DESCRIPTION" AS nvarchar(120) ) AS "CATEGORY SUB DESCRIPTION"
                        ,CAST("GL GRNI" AS nvarchar(20) ) AS "GL GRNI"
                        ,CAST("GL GSNI" AS decimal(36,4)) AS "GL GSNI"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "Incat"
                            , "Category Description"
                            , "L"
                            , "Gl Sales"
                            , "Gl Purch"
                            , "Gl Cogs"
                            , "Gl Stock"
                            , "Sales 1"
                            , "Sales 2"
                            , "Sales 3"
                            , "Sales 4"
                            , "Sales 5"
                            , "Sales 6"
                            , "Sales 7"
                            , "Sales 8"
                            , "Sales 9"
                            , "Sales 10"
                            , "Sales 11"
                            , "Sales 12"
                            , "Sales 13"
                            , "Sales 14"
                            , "Sales 15"
                            , "Sales 16"
                            , "Sales 17"
                            , "Sales 18"
                            , "Sales 19"
                            , "Sales 20"
                            , "Sales 21"
                            , "Sales 22"
                            , "Sales 23"
                            , "Sales 24"
                            , "Purch 1"
                            , "Purch 2"
                            , "Purch 3"
                            , "Purch 4"
                            , "Purch 5"
                            , "Purch 6"
                            , "Purch 7"
                            , "Purch 8"
                            , "Purch 9"
                            , "Purch 10"
                            , "Purch 11"
                            , "Purch 12"
                            , "Purch 13"
                            , "Purch 14"
                            , "Purch 15"
                            , "Purch 16"
                            , "Purch 17"
                            , "Purch 18"
                            , "Purch 19"
                            , "Purch 20"
                            , "Purch 21"
                            , "Purch 22"
                            , "Purch 23"
                            , "Purch 24"
                            , "Cogs 1"
                            , "Cogs 2"
                            , "Cogs 3"
                            , "Cogs 4"
                            , "Cogs 5"
                            , "Cogs 6"
                            , "Cogs 7"
                            , "Cogs 8"
                            , "Cogs 9"
                            , "Cogs 10"
                            , "Cogs 11"
                            , "Cogs 12"
                            , "Cogs 13"
                            , "Cogs 14"
                            , "Cogs 15"
                            , "Cogs 16"
                            , "Cogs 17"
                            , "Cogs 18"
                            , "Cogs 19"
                            , "Cogs 20"
                            , "Cogs 21"
                            , "Cogs 22"
                            , "Cogs 23"
                            , "Cogs 24"
                            , "Type"
                            , "Minor"
                            , "Mj"
                            , "A"
                            , "MaxDis"
                            , "Gl Stk Adj"
                            , "HG"
                            , "CatReb"
                            , "MinDis"
                            , "Category Sub Description"
                            , "Gl Grni"
                            , "Gl Gsni"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_CA_INCAT"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
