

CREATE PROCEDURE [STG].[LOAD_STG_EBS_OE_ORDER_LINES_ALL]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        9/03/2022 3:57:16 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_OE_ORDER_LINES_ALL";
    
    
    Source                                Destination                        
    ----------------------------------    ---------------------------------- 
    LND"."LND_EBS_OE_ORDER_LINES_ALL"    "STG"."STG_EBS_OE_ORDER_LINES_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-09    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_OE_ORDER_LINES_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_OE_ORDER_LINES_ALL"
                (
                    "LINE_ID"
                    ,"ORG_ID"
                    ,"HEADER_ID"
                    ,"LINE_TYPE_ID"
                    ,"LINE_NUMBER"
                    ,"ORDERED_ITEM"
                    ,"REQUEST_DATE"
                    ,"PROMISE_DATE"
                    ,"SCHEDULE_SHIP_DATE"
                    ,"ORDER_QUANTITY_UOM"
                    ,"PRICING_QUANTITY"
                    ,"PRICING_QUANTITY_UOM"
                    ,"CANCELLED_QUANTITY"
                    ,"SHIPPED_QUANTITY"
                    ,"ORDERED_QUANTITY"
                    ,"FULFILLED_QUANTITY"
                    ,"SHIPPING_QUANTITY"
                    ,"SHIPPING_QUANTITY_UOM"
                    ,"DELIVERY_LEAD_TIME"
                    ,"TAX_EXEMPT_FLAG"
                    ,"TAX_EXEMPT_NUMBER"
                    ,"TAX_EXEMPT_REASON_CODE"
                    ,"SHIP_FROM_ORG_ID"
                    ,"SHIP_TO_ORG_ID"
                    ,"INVOICE_TO_ORG_ID"
                    ,"DELIVER_TO_ORG_ID"
                    ,"SHIP_TO_CONTACT_ID"
                    ,"DELIVER_TO_CONTACT_ID"
                    ,"INVOICE_TO_CONTACT_ID"
                    ,"INTMED_SHIP_TO_ORG_ID"
                    ,"INTMED_SHIP_TO_CONTACT_ID"
                    ,"SOLD_FROM_ORG_ID"
                    ,"SOLD_TO_ORG_ID"
                    ,"CUST_PO_NUMBER"
                    ,"SHIP_TOLERANCE_ABOVE"
                    ,"SHIP_TOLERANCE_BELOW"
                    ,"DEMAND_BUCKET_TYPE_CODE"
                    ,"VEH_CUS_ITEM_CUM_KEY_ID"
                    ,"RLA_SCHEDULE_TYPE_CODE"
                    ,"CUSTOMER_DOCK_CODE"
                    ,"CUSTOMER_JOB"
                    ,"CUSTOMER_PRODUCTION_LINE"
                    ,"CUST_MODEL_SERIAL_NUMBER"
                    ,"PROJECT_ID"
                    ,"TASK_ID"
                    ,"INVENTORY_ITEM_ID"
                    ,"TAX_DATE"
                    ,"TAX_CODE"
                    ,"TAX_RATE"
                    ,"INVOICE_INTERFACE_STATUS_CODE"
                    ,"DEMAND_CLASS_CODE"
                    ,"PRICE_LIST_ID"
                    ,"PRICING_DATE"
                    ,"SHIPMENT_NUMBER"
                    ,"AGREEMENT_ID"
                    ,"SHIPMENT_PRIORITY_CODE"
                    ,"SHIPPING_METHOD_CODE"
                    ,"FREIGHT_CARRIER_CODE"
                    ,"FREIGHT_TERMS_CODE"
                    ,"FOB_POINT_CODE"
                    ,"TAX_POINT_CODE"
                    ,"PAYMENT_TERM_ID"
                    ,"INVOICING_RULE_ID"
                    ,"ACCOUNTING_RULE_ID"
                    ,"SOURCE_DOCUMENT_TYPE_ID"
                    ,"ORIG_SYS_DOCUMENT_REF"
                    ,"SOURCE_DOCUMENT_ID"
                    ,"ORIG_SYS_LINE_REF"
                    ,"SOURCE_DOCUMENT_LINE_ID"
                    ,"REFERENCE_LINE_ID"
                    ,"REFERENCE_TYPE"
                    ,"REFERENCE_HEADER_ID"
                    ,"ITEM_REVISION"
                    ,"UNIT_SELLING_PRICE"
                    ,"UNIT_LIST_PRICE"
                    ,"TAX_VALUE"
                    ,"CONTEXT"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"PRICING_CONTEXT"
                    ,"PRICING_ATTRIBUTE1"
                    ,"PRICING_ATTRIBUTE2"
                    ,"PRICING_ATTRIBUTE3"
                    ,"PRICING_ATTRIBUTE4"
                    ,"PRICING_ATTRIBUTE5"
                    ,"PRICING_ATTRIBUTE6"
                    ,"PRICING_ATTRIBUTE7"
                    ,"PRICING_ATTRIBUTE8"
                    ,"PRICING_ATTRIBUTE9"
                    ,"PRICING_ATTRIBUTE10"
                    ,"INDUSTRY_CONTEXT"
                    ,"INDUSTRY_ATTRIBUTE1"
                    ,"INDUSTRY_ATTRIBUTE2"
                    ,"INDUSTRY_ATTRIBUTE3"
                    ,"INDUSTRY_ATTRIBUTE4"
                    ,"INDUSTRY_ATTRIBUTE5"
                    ,"INDUSTRY_ATTRIBUTE6"
                    ,"INDUSTRY_ATTRIBUTE7"
                    ,"INDUSTRY_ATTRIBUTE8"
                    ,"INDUSTRY_ATTRIBUTE9"
                    ,"INDUSTRY_ATTRIBUTE10"
                    ,"INDUSTRY_ATTRIBUTE11"
                    ,"INDUSTRY_ATTRIBUTE13"
                    ,"INDUSTRY_ATTRIBUTE12"
                    ,"INDUSTRY_ATTRIBUTE14"
                    ,"INDUSTRY_ATTRIBUTE15"
                    ,"INDUSTRY_ATTRIBUTE16"
                    ,"INDUSTRY_ATTRIBUTE17"
                    ,"INDUSTRY_ATTRIBUTE18"
                    ,"INDUSTRY_ATTRIBUTE19"
                    ,"INDUSTRY_ATTRIBUTE20"
                    ,"INDUSTRY_ATTRIBUTE21"
                    ,"INDUSTRY_ATTRIBUTE22"
                    ,"INDUSTRY_ATTRIBUTE23"
                    ,"INDUSTRY_ATTRIBUTE24"
                    ,"INDUSTRY_ATTRIBUTE25"
                    ,"INDUSTRY_ATTRIBUTE26"
                    ,"INDUSTRY_ATTRIBUTE27"
                    ,"INDUSTRY_ATTRIBUTE28"
                    ,"INDUSTRY_ATTRIBUTE29"
                    ,"INDUSTRY_ATTRIBUTE30"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"REQUEST_ID"
                    ,"TOP_MODEL_LINE_ID"
                    ,"LINK_TO_LINE_ID"
                    ,"COMPONENT_SEQUENCE_ID"
                    ,"COMPONENT_CODE"
                    ,"CONFIG_DISPLAY_SEQUENCE"
                    ,"SORT_ORDER"
                    ,"ITEM_TYPE_CODE"
                    ,"OPTION_NUMBER"
                    ,"OPTION_FLAG"
                    ,"DEP_PLAN_REQUIRED_FLAG"
                    ,"VISIBLE_DEMAND_FLAG"
                    ,"LINE_CATEGORY_CODE"
                    ,"ACTUAL_SHIPMENT_DATE"
                    ,"CUSTOMER_TRX_LINE_ID"
                    ,"RETURN_CONTEXT"
                    ,"RETURN_ATTRIBUTE1"
                    ,"RETURN_ATTRIBUTE2"
                    ,"RETURN_ATTRIBUTE3"
                    ,"RETURN_ATTRIBUTE4"
                    ,"RETURN_ATTRIBUTE5"
                    ,"RETURN_ATTRIBUTE6"
                    ,"RETURN_ATTRIBUTE7"
                    ,"RETURN_ATTRIBUTE8"
                    ,"RETURN_ATTRIBUTE9"
                    ,"RETURN_ATTRIBUTE10"
                    ,"RETURN_ATTRIBUTE11"
                    ,"RETURN_ATTRIBUTE12"
                    ,"RETURN_ATTRIBUTE13"
                    ,"RETURN_ATTRIBUTE14"
                    ,"RETURN_ATTRIBUTE15"
                    ,"ACTUAL_ARRIVAL_DATE"
                    ,"ATO_LINE_ID"
                    ,"AUTO_SELECTED_QUANTITY"
                    ,"COMPONENT_NUMBER"
                    ,"EARLIEST_ACCEPTABLE_DATE"
                    ,"EXPLOSION_DATE"
                    ,"LATEST_ACCEPTABLE_DATE"
                    ,"MODEL_GROUP_NUMBER"
                    ,"SCHEDULE_ARRIVAL_DATE"
                    ,"SHIP_MODEL_COMPLETE_FLAG"
                    ,"SCHEDULE_STATUS_CODE"
                    ,"SOURCE_TYPE_CODE"
                    ,"CANCELLED_FLAG"
                    ,"OPEN_FLAG"
                    ,"BOOKED_FLAG"
                    ,"SALESREP_ID"
                    ,"RETURN_REASON_CODE"
                    ,"ARRIVAL_SET_ID"
                    ,"SHIP_SET_ID"
                    ,"SPLIT_FROM_LINE_ID"
                    ,"CUST_PRODUCTION_SEQ_NUM"
                    ,"AUTHORIZED_TO_SHIP_FLAG"
                    ,"OVER_SHIP_REASON_CODE"
                    ,"OVER_SHIP_RESOLVED_FLAG"
                    ,"ORDERED_ITEM_ID"
                    ,"ITEM_IDENTIFIER_TYPE"
                    ,"CONFIGURATION_ID"
                    ,"COMMITMENT_ID"
                    ,"SHIPPING_INTERFACED_FLAG"
                    ,"CREDIT_INVOICE_LINE_ID"
                    ,"FIRST_ACK_CODE"
                    ,"FIRST_ACK_DATE"
                    ,"LAST_ACK_CODE"
                    ,"LAST_ACK_DATE"
                    ,"PLANNING_PRIORITY"
                    ,"ORDER_SOURCE_ID"
                    ,"ORIG_SYS_SHIPMENT_REF"
                    ,"CHANGE_SEQUENCE"
                    ,"DROP_SHIP_FLAG"
                    ,"CUSTOMER_LINE_NUMBER"
                    ,"CUSTOMER_SHIPMENT_NUMBER"
                    ,"CUSTOMER_ITEM_NET_PRICE"
                    ,"CUSTOMER_PAYMENT_TERM_ID"
                    ,"FULFILLED_FLAG"
                    ,"END_ITEM_UNIT_NUMBER"
                    ,"CONFIG_HEADER_ID"
                    ,"CONFIG_REV_NBR"
                    ,"MFG_COMPONENT_SEQUENCE_ID"
                    ,"SHIPPING_INSTRUCTIONS"
                    ,"PACKING_INSTRUCTIONS"
                    ,"INVOICED_QUANTITY"
                    ,"REFERENCE_CUSTOMER_TRX_LINE_ID"
                    ,"SPLIT_BY"
                    ,"LINE_SET_ID"
                    ,"SERVICE_TXN_REASON_CODE"
                    ,"SERVICE_TXN_COMMENTS"
                    ,"SERVICE_DURATION"
                    ,"SERVICE_START_DATE"
                    ,"SERVICE_END_DATE"
                    ,"SERVICE_COTERMINATE_FLAG"
                    ,"UNIT_LIST_PERCENT"
                    ,"UNIT_SELLING_PERCENT"
                    ,"UNIT_PERCENT_BASE_PRICE"
                    ,"SERVICE_NUMBER"
                    ,"SERVICE_PERIOD"
                    ,"SHIPPABLE_FLAG"
                    ,"MODEL_REMNANT_FLAG"
                    ,"RE_SOURCE_FLAG"
                    ,"FLOW_STATUS_CODE"
                    ,"TP_CONTEXT"
                    ,"TP_ATTRIBUTE1"
                    ,"TP_ATTRIBUTE2"
                    ,"TP_ATTRIBUTE3"
                    ,"TP_ATTRIBUTE4"
                    ,"TP_ATTRIBUTE5"
                    ,"TP_ATTRIBUTE6"
                    ,"TP_ATTRIBUTE7"
                    ,"TP_ATTRIBUTE8"
                    ,"TP_ATTRIBUTE9"
                    ,"TP_ATTRIBUTE10"
                    ,"TP_ATTRIBUTE11"
                    ,"TP_ATTRIBUTE12"
                    ,"TP_ATTRIBUTE13"
                    ,"TP_ATTRIBUTE14"
                    ,"TP_ATTRIBUTE15"
                    ,"FULFILLMENT_METHOD_CODE"
                    ,"MARKETING_SOURCE_CODE_ID"
                    ,"SERVICE_REFERENCE_TYPE_CODE"
                    ,"SERVICE_REFERENCE_LINE_ID"
                    ,"SERVICE_REFERENCE_SYSTEM_ID"
                    ,"CALCULATE_PRICE_FLAG"
                    ,"UPGRADED_FLAG"
                    ,"REVENUE_AMOUNT"
                    ,"FULFILLMENT_DATE"
                    ,"PREFERRED_GRADE"
                    ,"ORDERED_QUANTITY2"
                    ,"ORDERED_QUANTITY_UOM2"
                    ,"SHIPPING_QUANTITY2"
                    ,"CANCELLED_QUANTITY2"
                    ,"SHIPPED_QUANTITY2"
                    ,"SHIPPING_QUANTITY_UOM2"
                    ,"FULFILLED_QUANTITY2"
                    ,"MFG_LEAD_TIME"
                    ,"LOCK_CONTROL"
                    ,"SUBINVENTORY"
                    ,"UNIT_LIST_PRICE_PER_PQTY"
                    ,"UNIT_SELLING_PRICE_PER_PQTY"
                    ,"PRICE_REQUEST_CODE"
                    ,"ORIGINAL_INVENTORY_ITEM_ID"
                    ,"ORIGINAL_ORDERED_ITEM_ID"
                    ,"ORIGINAL_ORDERED_ITEM"
                    ,"ORIGINAL_ITEM_IDENTIFIER_TYPE"
                    ,"ITEM_SUBSTITUTION_TYPE_CODE"
                    ,"OVERRIDE_ATP_DATE_CODE"
                    ,"LATE_DEMAND_PENALTY_FACTOR"
                    ,"ACCOUNTING_RULE_DURATION"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"USER_ITEM_DESCRIPTION"
                    ,"UNIT_COST"
                    ,"ITEM_RELATIONSHIP_TYPE"
                    ,"BLANKET_LINE_NUMBER"
                    ,"BLANKET_NUMBER"
                    ,"BLANKET_VERSION_NUMBER"
                    ,"SALES_DOCUMENT_TYPE_CODE"
                    ,"FIRM_DEMAND_FLAG"
                    ,"EARLIEST_SHIP_DATE"
                    ,"TRANSACTION_PHASE_CODE"
                    ,"SOURCE_DOCUMENT_VERSION_NUMBER"
                    ,"PAYMENT_TYPE_CODE"
                    ,"MINISITE_ID"
                    ,"END_CUSTOMER_ID"
                    ,"END_CUSTOMER_CONTACT_ID"
                    ,"END_CUSTOMER_SITE_USE_ID"
                    ,"IB_OWNER"
                    ,"IB_CURRENT_LOCATION"
                    ,"IB_INSTALLED_AT_LOCATION"
                    ,"RETROBILL_REQUEST_ID"
                    ,"ORIGINAL_LIST_PRICE"
                    ,"SERVICE_CREDIT_ELIGIBLE_CODE"
                    ,"ORDER_FIRMED_DATE"
                    ,"ACTUAL_FULFILLMENT_DATE"
                    ,"CHARGE_PERIODICITY_CODE"
                    ,"CONTINGENCY_ID"
                    ,"REVREC_EVENT_CODE"
                    ,"REVREC_EXPIRATION_DAYS"
                    ,"ACCEPTED_QUANTITY"
                    ,"ACCEPTED_BY"
                    ,"REVREC_COMMENTS"
                    ,"REVREC_REFERENCE_DOCUMENT"
                    ,"REVREC_SIGNATURE"
                    ,"REVREC_SIGNATURE_DATE"
                    ,"REVREC_IMPLICIT_FLAG"
                    ,"BYPASS_SCH_FLAG"
                    ,"PRE_EXPLODED_FLAG"
                    ,"EQUIPMENT_ID"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("LINE_ID" AS float) AS "LINE_ID"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,CAST("HEADER_ID" AS float) AS "HEADER_ID"
                        ,CAST("LINE_TYPE_ID" AS float) AS "LINE_TYPE_ID"
                        ,CAST("LINE_NUMBER" AS float) AS "LINE_NUMBER"
                        ,CAST("ORDERED_ITEM" AS varchar(8000) ) AS "ORDERED_ITEM"
                        ,TRY_CONVERT(datetime2,"REQUEST_DATE",121) AS "REQUEST_DATE"
                        ,TRY_CONVERT(datetime2,"PROMISE_DATE",121) AS "PROMISE_DATE"
                        ,TRY_CONVERT(datetime2,"SCHEDULE_SHIP_DATE",121) AS "SCHEDULE_SHIP_DATE"
                        ,CAST("ORDER_QUANTITY_UOM" AS varchar(100) ) AS "ORDER_QUANTITY_UOM"
                        ,CAST("PRICING_QUANTITY" AS float) AS "PRICING_QUANTITY"
                        ,CAST("PRICING_QUANTITY_UOM" AS varchar(100) ) AS "PRICING_QUANTITY_UOM"
                        ,CAST("CANCELLED_QUANTITY" AS float) AS "CANCELLED_QUANTITY"
                        ,CAST("SHIPPED_QUANTITY" AS float) AS "SHIPPED_QUANTITY"
                        ,CAST("ORDERED_QUANTITY" AS float) AS "ORDERED_QUANTITY"
                        ,CAST("FULFILLED_QUANTITY" AS float) AS "FULFILLED_QUANTITY"
                        ,CAST("SHIPPING_QUANTITY" AS float) AS "SHIPPING_QUANTITY"
                        ,CAST("SHIPPING_QUANTITY_UOM" AS varchar(100) ) AS "SHIPPING_QUANTITY_UOM"
                        ,CAST("DELIVERY_LEAD_TIME" AS float) AS "DELIVERY_LEAD_TIME"
                        ,CAST("TAX_EXEMPT_FLAG" AS varchar(100) ) AS "TAX_EXEMPT_FLAG"
                        ,CAST("TAX_EXEMPT_NUMBER" AS varchar(1000) ) AS "TAX_EXEMPT_NUMBER"
                        ,CAST("TAX_EXEMPT_REASON_CODE" AS varchar(100) ) AS "TAX_EXEMPT_REASON_CODE"
                        ,CAST("SHIP_FROM_ORG_ID" AS float) AS "SHIP_FROM_ORG_ID"
                        ,CAST("SHIP_TO_ORG_ID" AS float) AS "SHIP_TO_ORG_ID"
                        ,CAST("INVOICE_TO_ORG_ID" AS float) AS "INVOICE_TO_ORG_ID"
                        ,CAST("DELIVER_TO_ORG_ID" AS float) AS "DELIVER_TO_ORG_ID"
                        ,CAST("SHIP_TO_CONTACT_ID" AS float) AS "SHIP_TO_CONTACT_ID"
                        ,CAST("DELIVER_TO_CONTACT_ID" AS float) AS "DELIVER_TO_CONTACT_ID"
                        ,CAST("INVOICE_TO_CONTACT_ID" AS float) AS "INVOICE_TO_CONTACT_ID"
                        ,CAST("INTMED_SHIP_TO_ORG_ID" AS float) AS "INTMED_SHIP_TO_ORG_ID"
                        ,CAST("INTMED_SHIP_TO_CONTACT_ID" AS float) AS "INTMED_SHIP_TO_CONTACT_ID"
                        ,CAST("SOLD_FROM_ORG_ID" AS float) AS "SOLD_FROM_ORG_ID"
                        ,CAST("SOLD_TO_ORG_ID" AS float) AS "SOLD_TO_ORG_ID"
                        ,CAST("CUST_PO_NUMBER" AS varchar(1000) ) AS "CUST_PO_NUMBER"
                        ,CAST("SHIP_TOLERANCE_ABOVE" AS float) AS "SHIP_TOLERANCE_ABOVE"
                        ,CAST("SHIP_TOLERANCE_BELOW" AS float) AS "SHIP_TOLERANCE_BELOW"
                        ,CAST("DEMAND_BUCKET_TYPE_CODE" AS varchar(100) ) AS "DEMAND_BUCKET_TYPE_CODE"
                        ,CAST("VEH_CUS_ITEM_CUM_KEY_ID" AS float) AS "VEH_CUS_ITEM_CUM_KEY_ID"
                        ,CAST("RLA_SCHEDULE_TYPE_CODE" AS varchar(100) ) AS "RLA_SCHEDULE_TYPE_CODE"
                        ,CAST("CUSTOMER_DOCK_CODE" AS varchar(1000) ) AS "CUSTOMER_DOCK_CODE"
                        ,CAST("CUSTOMER_JOB" AS varchar(1000) ) AS "CUSTOMER_JOB"
                        ,CAST("CUSTOMER_PRODUCTION_LINE" AS varchar(1000) ) AS "CUSTOMER_PRODUCTION_LINE"
                        ,CAST("CUST_MODEL_SERIAL_NUMBER" AS varchar(1000) ) AS "CUST_MODEL_SERIAL_NUMBER"
                        ,CAST("PROJECT_ID" AS float) AS "PROJECT_ID"
                        ,CAST("TASK_ID" AS float) AS "TASK_ID"
                        ,CAST("INVENTORY_ITEM_ID" AS float) AS "INVENTORY_ITEM_ID"
                        ,TRY_CONVERT(datetime2,"TAX_DATE",121) AS "TAX_DATE"
                        ,CAST("TAX_CODE" AS varchar(1000) ) AS "TAX_CODE"
                        ,CAST("TAX_RATE" AS float) AS "TAX_RATE"
                        ,CAST("INVOICE_INTERFACE_STATUS_CODE" AS varchar(100) ) AS "INVOICE_INTERFACE_STATUS_CODE"
                        ,CAST("DEMAND_CLASS_CODE" AS varchar(100) ) AS "DEMAND_CLASS_CODE"
                        ,CAST("PRICE_LIST_ID" AS float) AS "PRICE_LIST_ID"
                        ,TRY_CONVERT(datetime2,"PRICING_DATE",121) AS "PRICING_DATE"
                        ,CAST("SHIPMENT_NUMBER" AS float) AS "SHIPMENT_NUMBER"
                        ,CAST("AGREEMENT_ID" AS float) AS "AGREEMENT_ID"
                        ,CAST("SHIPMENT_PRIORITY_CODE" AS varchar(100) ) AS "SHIPMENT_PRIORITY_CODE"
                        ,CAST("SHIPPING_METHOD_CODE" AS varchar(100) ) AS "SHIPPING_METHOD_CODE"
                        ,CAST("FREIGHT_CARRIER_CODE" AS varchar(100) ) AS "FREIGHT_CARRIER_CODE"
                        ,CAST("FREIGHT_TERMS_CODE" AS varchar(100) ) AS "FREIGHT_TERMS_CODE"
                        ,CAST("FOB_POINT_CODE" AS varchar(100) ) AS "FOB_POINT_CODE"
                        ,CAST("TAX_POINT_CODE" AS varchar(100) ) AS "TAX_POINT_CODE"
                        ,CAST("PAYMENT_TERM_ID" AS float) AS "PAYMENT_TERM_ID"
                        ,CAST("INVOICING_RULE_ID" AS float) AS "INVOICING_RULE_ID"
                        ,CAST("ACCOUNTING_RULE_ID" AS float) AS "ACCOUNTING_RULE_ID"
                        ,CAST("SOURCE_DOCUMENT_TYPE_ID" AS float) AS "SOURCE_DOCUMENT_TYPE_ID"
                        ,CAST("ORIG_SYS_DOCUMENT_REF" AS varchar(1000) ) AS "ORIG_SYS_DOCUMENT_REF"
                        ,CAST("SOURCE_DOCUMENT_ID" AS float) AS "SOURCE_DOCUMENT_ID"
                        ,CAST("ORIG_SYS_LINE_REF" AS varchar(1000) ) AS "ORIG_SYS_LINE_REF"
                        ,CAST("SOURCE_DOCUMENT_LINE_ID" AS float) AS "SOURCE_DOCUMENT_LINE_ID"
                        ,CAST("REFERENCE_LINE_ID" AS float) AS "REFERENCE_LINE_ID"
                        ,CAST("REFERENCE_TYPE" AS varchar(100) ) AS "REFERENCE_TYPE"
                        ,CAST("REFERENCE_HEADER_ID" AS float) AS "REFERENCE_HEADER_ID"
                        ,CAST("ITEM_REVISION" AS varchar(100) ) AS "ITEM_REVISION"
                        ,CAST("UNIT_SELLING_PRICE" AS float) AS "UNIT_SELLING_PRICE"
                        ,CAST("UNIT_LIST_PRICE" AS float) AS "UNIT_LIST_PRICE"
                        ,CAST("TAX_VALUE" AS float) AS "TAX_VALUE"
                        ,CAST("CONTEXT" AS varchar(100) ) AS "CONTEXT"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("PRICING_CONTEXT" AS varchar(100) ) AS "PRICING_CONTEXT"
                        ,CAST("PRICING_ATTRIBUTE1" AS varchar(1000) ) AS "PRICING_ATTRIBUTE1"
                        ,CAST("PRICING_ATTRIBUTE2" AS varchar(1000) ) AS "PRICING_ATTRIBUTE2"
                        ,CAST("PRICING_ATTRIBUTE3" AS varchar(1000) ) AS "PRICING_ATTRIBUTE3"
                        ,CAST("PRICING_ATTRIBUTE4" AS varchar(1000) ) AS "PRICING_ATTRIBUTE4"
                        ,CAST("PRICING_ATTRIBUTE5" AS varchar(1000) ) AS "PRICING_ATTRIBUTE5"
                        ,CAST("PRICING_ATTRIBUTE6" AS varchar(1000) ) AS "PRICING_ATTRIBUTE6"
                        ,CAST("PRICING_ATTRIBUTE7" AS varchar(1000) ) AS "PRICING_ATTRIBUTE7"
                        ,CAST("PRICING_ATTRIBUTE8" AS varchar(1000) ) AS "PRICING_ATTRIBUTE8"
                        ,CAST("PRICING_ATTRIBUTE9" AS varchar(1000) ) AS "PRICING_ATTRIBUTE9"
                        ,CAST("PRICING_ATTRIBUTE10" AS varchar(1000) ) AS "PRICING_ATTRIBUTE10"
                        ,CAST("INDUSTRY_CONTEXT" AS varchar(100) ) AS "INDUSTRY_CONTEXT"
                        ,CAST("INDUSTRY_ATTRIBUTE1" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE1"
                        ,CAST("INDUSTRY_ATTRIBUTE2" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE2"
                        ,CAST("INDUSTRY_ATTRIBUTE3" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE3"
                        ,CAST("INDUSTRY_ATTRIBUTE4" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE4"
                        ,CAST("INDUSTRY_ATTRIBUTE5" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE5"
                        ,CAST("INDUSTRY_ATTRIBUTE6" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE6"
                        ,CAST("INDUSTRY_ATTRIBUTE7" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE7"
                        ,CAST("INDUSTRY_ATTRIBUTE8" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE8"
                        ,CAST("INDUSTRY_ATTRIBUTE9" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE9"
                        ,CAST("INDUSTRY_ATTRIBUTE10" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE10"
                        ,CAST("INDUSTRY_ATTRIBUTE11" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE11"
                        ,CAST("INDUSTRY_ATTRIBUTE13" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE13"
                        ,CAST("INDUSTRY_ATTRIBUTE12" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE12"
                        ,CAST("INDUSTRY_ATTRIBUTE14" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE14"
                        ,CAST("INDUSTRY_ATTRIBUTE15" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE15"
                        ,CAST("INDUSTRY_ATTRIBUTE16" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE16"
                        ,CAST("INDUSTRY_ATTRIBUTE17" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE17"
                        ,CAST("INDUSTRY_ATTRIBUTE18" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE18"
                        ,CAST("INDUSTRY_ATTRIBUTE19" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE19"
                        ,CAST("INDUSTRY_ATTRIBUTE20" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE20"
                        ,CAST("INDUSTRY_ATTRIBUTE21" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE21"
                        ,CAST("INDUSTRY_ATTRIBUTE22" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE22"
                        ,CAST("INDUSTRY_ATTRIBUTE23" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE23"
                        ,CAST("INDUSTRY_ATTRIBUTE24" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE24"
                        ,CAST("INDUSTRY_ATTRIBUTE25" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE25"
                        ,CAST("INDUSTRY_ATTRIBUTE26" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE26"
                        ,CAST("INDUSTRY_ATTRIBUTE27" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE27"
                        ,CAST("INDUSTRY_ATTRIBUTE28" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE28"
                        ,CAST("INDUSTRY_ATTRIBUTE29" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE29"
                        ,CAST("INDUSTRY_ATTRIBUTE30" AS varchar(1000) ) AS "INDUSTRY_ATTRIBUTE30"
                        ,TRY_CONVERT(datetime2,"CREATION_DATE",121) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,TRY_CONVERT(datetime2,"LAST_UPDATE_DATE",121) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,TRY_CONVERT(datetime2,"PROGRAM_UPDATE_DATE",121) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("TOP_MODEL_LINE_ID" AS float) AS "TOP_MODEL_LINE_ID"
                        ,CAST("LINK_TO_LINE_ID" AS float) AS "LINK_TO_LINE_ID"
                        ,CAST("COMPONENT_SEQUENCE_ID" AS float) AS "COMPONENT_SEQUENCE_ID"
                        ,CAST("COMPONENT_CODE" AS varchar(8000) ) AS "COMPONENT_CODE"
                        ,CAST("CONFIG_DISPLAY_SEQUENCE" AS float) AS "CONFIG_DISPLAY_SEQUENCE"
                        ,CAST("SORT_ORDER" AS varchar(8000) ) AS "SORT_ORDER"
                        ,CAST("ITEM_TYPE_CODE" AS varchar(100) ) AS "ITEM_TYPE_CODE"
                        ,CAST("OPTION_NUMBER" AS float) AS "OPTION_NUMBER"
                        ,CAST("OPTION_FLAG" AS varchar(100) ) AS "OPTION_FLAG"
                        ,CAST("DEP_PLAN_REQUIRED_FLAG" AS varchar(100) ) AS "DEP_PLAN_REQUIRED_FLAG"
                        ,CAST("VISIBLE_DEMAND_FLAG" AS varchar(100) ) AS "VISIBLE_DEMAND_FLAG"
                        ,CAST("LINE_CATEGORY_CODE" AS varchar(100) ) AS "LINE_CATEGORY_CODE"
                        ,TRY_CONVERT(datetime2,"ACTUAL_SHIPMENT_DATE",121) AS "ACTUAL_SHIPMENT_DATE"
                        ,CAST("CUSTOMER_TRX_LINE_ID" AS float) AS "CUSTOMER_TRX_LINE_ID"
                        ,CAST("RETURN_CONTEXT" AS varchar(100) ) AS "RETURN_CONTEXT"
                        ,CAST("RETURN_ATTRIBUTE1" AS varchar(1000) ) AS "RETURN_ATTRIBUTE1"
                        ,CAST("RETURN_ATTRIBUTE2" AS varchar(1000) ) AS "RETURN_ATTRIBUTE2"
                        ,CAST("RETURN_ATTRIBUTE3" AS varchar(1000) ) AS "RETURN_ATTRIBUTE3"
                        ,CAST("RETURN_ATTRIBUTE4" AS varchar(1000) ) AS "RETURN_ATTRIBUTE4"
                        ,CAST("RETURN_ATTRIBUTE5" AS varchar(1000) ) AS "RETURN_ATTRIBUTE5"
                        ,CAST("RETURN_ATTRIBUTE6" AS varchar(1000) ) AS "RETURN_ATTRIBUTE6"
                        ,CAST("RETURN_ATTRIBUTE7" AS varchar(1000) ) AS "RETURN_ATTRIBUTE7"
                        ,CAST("RETURN_ATTRIBUTE8" AS varchar(1000) ) AS "RETURN_ATTRIBUTE8"
                        ,CAST("RETURN_ATTRIBUTE9" AS varchar(1000) ) AS "RETURN_ATTRIBUTE9"
                        ,CAST("RETURN_ATTRIBUTE10" AS varchar(1000) ) AS "RETURN_ATTRIBUTE10"
                        ,CAST("RETURN_ATTRIBUTE11" AS varchar(1000) ) AS "RETURN_ATTRIBUTE11"
                        ,CAST("RETURN_ATTRIBUTE12" AS varchar(1000) ) AS "RETURN_ATTRIBUTE12"
                        ,CAST("RETURN_ATTRIBUTE13" AS varchar(1000) ) AS "RETURN_ATTRIBUTE13"
                        ,CAST("RETURN_ATTRIBUTE14" AS varchar(1000) ) AS "RETURN_ATTRIBUTE14"
                        ,CAST("RETURN_ATTRIBUTE15" AS varchar(1000) ) AS "RETURN_ATTRIBUTE15"
                        ,TRY_CONVERT(datetime2,"ACTUAL_ARRIVAL_DATE",121) AS "ACTUAL_ARRIVAL_DATE"
                        ,CAST("ATO_LINE_ID" AS float) AS "ATO_LINE_ID"
                        ,CAST("AUTO_SELECTED_QUANTITY" AS float) AS "AUTO_SELECTED_QUANTITY"
                        ,CAST("COMPONENT_NUMBER" AS float) AS "COMPONENT_NUMBER"
                        ,TRY_CONVERT(datetime2,"EARLIEST_ACCEPTABLE_DATE",121) AS "EARLIEST_ACCEPTABLE_DATE"
                        ,TRY_CONVERT(datetime2,"EXPLOSION_DATE",121) AS "EXPLOSION_DATE"
                        ,TRY_CONVERT(datetime2,"LATEST_ACCEPTABLE_DATE",121) AS "LATEST_ACCEPTABLE_DATE"
                        ,CAST("MODEL_GROUP_NUMBER" AS float) AS "MODEL_GROUP_NUMBER"
                        ,TRY_CONVERT(datetime2,"SCHEDULE_ARRIVAL_DATE",121) AS "SCHEDULE_ARRIVAL_DATE"
                        ,CAST("SHIP_MODEL_COMPLETE_FLAG" AS varchar(100) ) AS "SHIP_MODEL_COMPLETE_FLAG"
                        ,CAST("SCHEDULE_STATUS_CODE" AS varchar(100) ) AS "SCHEDULE_STATUS_CODE"
                        ,CAST("SOURCE_TYPE_CODE" AS varchar(100) ) AS "SOURCE_TYPE_CODE"
                        ,CAST("CANCELLED_FLAG" AS varchar(100) ) AS "CANCELLED_FLAG"
                        ,CAST("OPEN_FLAG" AS varchar(100) ) AS "OPEN_FLAG"
                        ,CAST("BOOKED_FLAG" AS varchar(100) ) AS "BOOKED_FLAG"
                        ,CAST("SALESREP_ID" AS float) AS "SALESREP_ID"
                        ,CAST("RETURN_REASON_CODE" AS varchar(100) ) AS "RETURN_REASON_CODE"
                        ,CAST("ARRIVAL_SET_ID" AS float) AS "ARRIVAL_SET_ID"
                        ,CAST("SHIP_SET_ID" AS float) AS "SHIP_SET_ID"
                        ,CAST("SPLIT_FROM_LINE_ID" AS float) AS "SPLIT_FROM_LINE_ID"
                        ,CAST("CUST_PRODUCTION_SEQ_NUM" AS varchar(1000) ) AS "CUST_PRODUCTION_SEQ_NUM"
                        ,CAST("AUTHORIZED_TO_SHIP_FLAG" AS varchar(100) ) AS "AUTHORIZED_TO_SHIP_FLAG"
                        ,CAST("OVER_SHIP_REASON_CODE" AS varchar(100) ) AS "OVER_SHIP_REASON_CODE"
                        ,CAST("OVER_SHIP_RESOLVED_FLAG" AS varchar(100) ) AS "OVER_SHIP_RESOLVED_FLAG"
                        ,CAST("ORDERED_ITEM_ID" AS float) AS "ORDERED_ITEM_ID"
                        ,CAST("ITEM_IDENTIFIER_TYPE" AS varchar(100) ) AS "ITEM_IDENTIFIER_TYPE"
                        ,CAST("CONFIGURATION_ID" AS float) AS "CONFIGURATION_ID"
                        ,CAST("COMMITMENT_ID" AS float) AS "COMMITMENT_ID"
                        ,CAST("SHIPPING_INTERFACED_FLAG" AS varchar(100) ) AS "SHIPPING_INTERFACED_FLAG"
                        ,CAST("CREDIT_INVOICE_LINE_ID" AS float) AS "CREDIT_INVOICE_LINE_ID"
                        ,CAST("FIRST_ACK_CODE" AS varchar(100) ) AS "FIRST_ACK_CODE"
                        ,TRY_CONVERT(datetime2,"FIRST_ACK_DATE",121) AS "FIRST_ACK_DATE"
                        ,CAST("LAST_ACK_CODE" AS varchar(100) ) AS "LAST_ACK_CODE"
                        ,TRY_CONVERT(datetime2,"LAST_ACK_DATE",121) AS "LAST_ACK_DATE"
                        ,CAST("PLANNING_PRIORITY" AS float) AS "PLANNING_PRIORITY"
                        ,CAST("ORDER_SOURCE_ID" AS float) AS "ORDER_SOURCE_ID"
                        ,CAST("ORIG_SYS_SHIPMENT_REF" AS varchar(1000) ) AS "ORIG_SYS_SHIPMENT_REF"
                        ,CAST("CHANGE_SEQUENCE" AS varchar(1000) ) AS "CHANGE_SEQUENCE"
                        ,CAST("DROP_SHIP_FLAG" AS varchar(100) ) AS "DROP_SHIP_FLAG"
                        ,CAST("CUSTOMER_LINE_NUMBER" AS varchar(1000) ) AS "CUSTOMER_LINE_NUMBER"
                        ,CAST("CUSTOMER_SHIPMENT_NUMBER" AS varchar(1000) ) AS "CUSTOMER_SHIPMENT_NUMBER"
                        ,CAST("CUSTOMER_ITEM_NET_PRICE" AS float) AS "CUSTOMER_ITEM_NET_PRICE"
                        ,CAST("CUSTOMER_PAYMENT_TERM_ID" AS float) AS "CUSTOMER_PAYMENT_TERM_ID"
                        ,CAST("FULFILLED_FLAG" AS varchar(100) ) AS "FULFILLED_FLAG"
                        ,CAST("END_ITEM_UNIT_NUMBER" AS varchar(100) ) AS "END_ITEM_UNIT_NUMBER"
                        ,CAST("CONFIG_HEADER_ID" AS float) AS "CONFIG_HEADER_ID"
                        ,CAST("CONFIG_REV_NBR" AS float) AS "CONFIG_REV_NBR"
                        ,CAST("MFG_COMPONENT_SEQUENCE_ID" AS float) AS "MFG_COMPONENT_SEQUENCE_ID"
                        ,CAST("SHIPPING_INSTRUCTIONS" AS varchar(8000) ) AS "SHIPPING_INSTRUCTIONS"
                        ,CAST("PACKING_INSTRUCTIONS" AS varchar(8000) ) AS "PACKING_INSTRUCTIONS"
                        ,CAST("INVOICED_QUANTITY" AS float) AS "INVOICED_QUANTITY"
                        ,CAST("REFERENCE_CUSTOMER_TRX_LINE_ID" AS float) AS "REFERENCE_CUSTOMER_TRX_LINE_ID"
                        ,CAST("SPLIT_BY" AS varchar(100) ) AS "SPLIT_BY"
                        ,CAST("LINE_SET_ID" AS float) AS "LINE_SET_ID"
                        ,CAST("SERVICE_TXN_REASON_CODE" AS varchar(100) ) AS "SERVICE_TXN_REASON_CODE"
                        ,CAST("SERVICE_TXN_COMMENTS" AS varchar(8000) ) AS "SERVICE_TXN_COMMENTS"
                        ,CAST("SERVICE_DURATION" AS float) AS "SERVICE_DURATION"
                        ,TRY_CONVERT(datetime2,"SERVICE_START_DATE",121) AS "SERVICE_START_DATE"
                        ,TRY_CONVERT(datetime2,"SERVICE_END_DATE",121) AS "SERVICE_END_DATE"
                        ,CAST("SERVICE_COTERMINATE_FLAG" AS varchar(100) ) AS "SERVICE_COTERMINATE_FLAG"
                        ,CAST("UNIT_LIST_PERCENT" AS float) AS "UNIT_LIST_PERCENT"
                        ,CAST("UNIT_SELLING_PERCENT" AS float) AS "UNIT_SELLING_PERCENT"
                        ,CAST("UNIT_PERCENT_BASE_PRICE" AS float) AS "UNIT_PERCENT_BASE_PRICE"
                        ,CAST("SERVICE_NUMBER" AS float) AS "SERVICE_NUMBER"
                        ,CAST("SERVICE_PERIOD" AS varchar(100) ) AS "SERVICE_PERIOD"
                        ,CAST("SHIPPABLE_FLAG" AS varchar(100) ) AS "SHIPPABLE_FLAG"
                        ,CAST("MODEL_REMNANT_FLAG" AS varchar(100) ) AS "MODEL_REMNANT_FLAG"
                        ,CAST("RE_SOURCE_FLAG" AS varchar(100) ) AS "RE_SOURCE_FLAG"
                        ,CAST("FLOW_STATUS_CODE" AS varchar(100) ) AS "FLOW_STATUS_CODE"
                        ,CAST("TP_CONTEXT" AS varchar(100) ) AS "TP_CONTEXT"
                        ,CAST("TP_ATTRIBUTE1" AS varchar(1000) ) AS "TP_ATTRIBUTE1"
                        ,CAST("TP_ATTRIBUTE2" AS varchar(1000) ) AS "TP_ATTRIBUTE2"
                        ,CAST("TP_ATTRIBUTE3" AS varchar(1000) ) AS "TP_ATTRIBUTE3"
                        ,CAST("TP_ATTRIBUTE4" AS varchar(1000) ) AS "TP_ATTRIBUTE4"
                        ,CAST("TP_ATTRIBUTE5" AS varchar(1000) ) AS "TP_ATTRIBUTE5"
                        ,CAST("TP_ATTRIBUTE6" AS varchar(1000) ) AS "TP_ATTRIBUTE6"
                        ,CAST("TP_ATTRIBUTE7" AS varchar(1000) ) AS "TP_ATTRIBUTE7"
                        ,CAST("TP_ATTRIBUTE8" AS varchar(1000) ) AS "TP_ATTRIBUTE8"
                        ,CAST("TP_ATTRIBUTE9" AS varchar(1000) ) AS "TP_ATTRIBUTE9"
                        ,CAST("TP_ATTRIBUTE10" AS varchar(1000) ) AS "TP_ATTRIBUTE10"
                        ,CAST("TP_ATTRIBUTE11" AS varchar(1000) ) AS "TP_ATTRIBUTE11"
                        ,CAST("TP_ATTRIBUTE12" AS varchar(1000) ) AS "TP_ATTRIBUTE12"
                        ,CAST("TP_ATTRIBUTE13" AS varchar(1000) ) AS "TP_ATTRIBUTE13"
                        ,CAST("TP_ATTRIBUTE14" AS varchar(1000) ) AS "TP_ATTRIBUTE14"
                        ,CAST("TP_ATTRIBUTE15" AS varchar(1000) ) AS "TP_ATTRIBUTE15"
                        ,CAST("FULFILLMENT_METHOD_CODE" AS varchar(100) ) AS "FULFILLMENT_METHOD_CODE"
                        ,CAST("MARKETING_SOURCE_CODE_ID" AS float) AS "MARKETING_SOURCE_CODE_ID"
                        ,CAST("SERVICE_REFERENCE_TYPE_CODE" AS varchar(100) ) AS "SERVICE_REFERENCE_TYPE_CODE"
                        ,CAST("SERVICE_REFERENCE_LINE_ID" AS float) AS "SERVICE_REFERENCE_LINE_ID"
                        ,CAST("SERVICE_REFERENCE_SYSTEM_ID" AS float) AS "SERVICE_REFERENCE_SYSTEM_ID"
                        ,CAST("CALCULATE_PRICE_FLAG" AS varchar(100) ) AS "CALCULATE_PRICE_FLAG"
                        ,CAST("UPGRADED_FLAG" AS varchar(100) ) AS "UPGRADED_FLAG"
                        ,CAST("REVENUE_AMOUNT" AS float) AS "REVENUE_AMOUNT"
                        ,TRY_CONVERT(datetime2,"FULFILLMENT_DATE",121) AS "FULFILLMENT_DATE"
                        ,CAST("PREFERRED_GRADE" AS varchar(1000) ) AS "PREFERRED_GRADE"
                        ,CAST("ORDERED_QUANTITY2" AS float) AS "ORDERED_QUANTITY2"
                        ,CAST("ORDERED_QUANTITY_UOM2" AS varchar(100) ) AS "ORDERED_QUANTITY_UOM2"
                        ,CAST("SHIPPING_QUANTITY2" AS float) AS "SHIPPING_QUANTITY2"
                        ,CAST("CANCELLED_QUANTITY2" AS float) AS "CANCELLED_QUANTITY2"
                        ,CAST("SHIPPED_QUANTITY2" AS float) AS "SHIPPED_QUANTITY2"
                        ,CAST("SHIPPING_QUANTITY_UOM2" AS varchar(100) ) AS "SHIPPING_QUANTITY_UOM2"
                        ,CAST("FULFILLED_QUANTITY2" AS float) AS "FULFILLED_QUANTITY2"
                        ,CAST("MFG_LEAD_TIME" AS float) AS "MFG_LEAD_TIME"
                        ,CAST("LOCK_CONTROL" AS float) AS "LOCK_CONTROL"
                        ,CAST("SUBINVENTORY" AS varchar(100) ) AS "SUBINVENTORY"
                        ,CAST("UNIT_LIST_PRICE_PER_PQTY" AS float) AS "UNIT_LIST_PRICE_PER_PQTY"
                        ,CAST("UNIT_SELLING_PRICE_PER_PQTY" AS float) AS "UNIT_SELLING_PRICE_PER_PQTY"
                        ,CAST("PRICE_REQUEST_CODE" AS varchar(1000) ) AS "PRICE_REQUEST_CODE"
                        ,CAST("ORIGINAL_INVENTORY_ITEM_ID" AS float) AS "ORIGINAL_INVENTORY_ITEM_ID"
                        ,CAST("ORIGINAL_ORDERED_ITEM_ID" AS float) AS "ORIGINAL_ORDERED_ITEM_ID"
                        ,CAST("ORIGINAL_ORDERED_ITEM" AS varchar(8000) ) AS "ORIGINAL_ORDERED_ITEM"
                        ,CAST("ORIGINAL_ITEM_IDENTIFIER_TYPE" AS varchar(100) ) AS "ORIGINAL_ITEM_IDENTIFIER_TYPE"
                        ,CAST("ITEM_SUBSTITUTION_TYPE_CODE" AS varchar(100) ) AS "ITEM_SUBSTITUTION_TYPE_CODE"
                        ,CAST("OVERRIDE_ATP_DATE_CODE" AS varchar(100) ) AS "OVERRIDE_ATP_DATE_CODE"
                        ,CAST("LATE_DEMAND_PENALTY_FACTOR" AS float) AS "LATE_DEMAND_PENALTY_FACTOR"
                        ,CAST("ACCOUNTING_RULE_DURATION" AS float) AS "ACCOUNTING_RULE_DURATION"
                        ,CAST("ATTRIBUTE16" AS varchar(1000) ) AS "ATTRIBUTE16"
                        ,CAST("ATTRIBUTE17" AS varchar(1000) ) AS "ATTRIBUTE17"
                        ,CAST("ATTRIBUTE18" AS varchar(1000) ) AS "ATTRIBUTE18"
                        ,CAST("ATTRIBUTE19" AS varchar(1000) ) AS "ATTRIBUTE19"
                        ,CAST("ATTRIBUTE20" AS varchar(1000) ) AS "ATTRIBUTE20"
                        ,CAST("USER_ITEM_DESCRIPTION" AS varchar(8000) ) AS "USER_ITEM_DESCRIPTION"
                        ,CAST("UNIT_COST" AS float) AS "UNIT_COST"
                        ,CAST("ITEM_RELATIONSHIP_TYPE" AS float) AS "ITEM_RELATIONSHIP_TYPE"
                        ,CAST("BLANKET_LINE_NUMBER" AS float) AS "BLANKET_LINE_NUMBER"
                        ,CAST("BLANKET_NUMBER" AS float) AS "BLANKET_NUMBER"
                        ,CAST("BLANKET_VERSION_NUMBER" AS float) AS "BLANKET_VERSION_NUMBER"
                        ,CAST("SALES_DOCUMENT_TYPE_CODE" AS varchar(100) ) AS "SALES_DOCUMENT_TYPE_CODE"
                        ,CAST("FIRM_DEMAND_FLAG" AS varchar(100) ) AS "FIRM_DEMAND_FLAG"
                        ,TRY_CONVERT(datetime2,"EARLIEST_SHIP_DATE",121) AS "EARLIEST_SHIP_DATE"
                        ,CAST("TRANSACTION_PHASE_CODE" AS varchar(100) ) AS "TRANSACTION_PHASE_CODE"
                        ,CAST("SOURCE_DOCUMENT_VERSION_NUMBER" AS float) AS "SOURCE_DOCUMENT_VERSION_NUMBER"
                        ,CAST("PAYMENT_TYPE_CODE" AS varchar(100) ) AS "PAYMENT_TYPE_CODE"
                        ,CAST("MINISITE_ID" AS float) AS "MINISITE_ID"
                        ,CAST("END_CUSTOMER_ID" AS float) AS "END_CUSTOMER_ID"
                        ,CAST("END_CUSTOMER_CONTACT_ID" AS float) AS "END_CUSTOMER_CONTACT_ID"
                        ,CAST("END_CUSTOMER_SITE_USE_ID" AS float) AS "END_CUSTOMER_SITE_USE_ID"
                        ,CAST("IB_OWNER" AS varchar(1000) ) AS "IB_OWNER"
                        ,CAST("IB_CURRENT_LOCATION" AS varchar(1000) ) AS "IB_CURRENT_LOCATION"
                        ,CAST("IB_INSTALLED_AT_LOCATION" AS varchar(1000) ) AS "IB_INSTALLED_AT_LOCATION"
                        ,CAST("RETROBILL_REQUEST_ID" AS float) AS "RETROBILL_REQUEST_ID"
                        ,CAST("ORIGINAL_LIST_PRICE" AS float) AS "ORIGINAL_LIST_PRICE"
                        ,CAST("SERVICE_CREDIT_ELIGIBLE_CODE" AS varchar(100) ) AS "SERVICE_CREDIT_ELIGIBLE_CODE"
                        ,TRY_CONVERT(datetime2,"ORDER_FIRMED_DATE",121) AS "ORDER_FIRMED_DATE"
                        ,TRY_CONVERT(datetime2,"ACTUAL_FULFILLMENT_DATE",121) AS "ACTUAL_FULFILLMENT_DATE"
                        ,CAST("CHARGE_PERIODICITY_CODE" AS varchar(100) ) AS "CHARGE_PERIODICITY_CODE"
                        ,CAST("CONTINGENCY_ID" AS float) AS "CONTINGENCY_ID"
                        ,CAST("REVREC_EVENT_CODE" AS varchar(100) ) AS "REVREC_EVENT_CODE"
                        ,CAST("REVREC_EXPIRATION_DAYS" AS float) AS "REVREC_EXPIRATION_DAYS"
                        ,CAST("ACCEPTED_QUANTITY" AS float) AS "ACCEPTED_QUANTITY"
                        ,CAST("ACCEPTED_BY" AS float) AS "ACCEPTED_BY"
                        ,CAST("REVREC_COMMENTS" AS varchar(8000) ) AS "REVREC_COMMENTS"
                        ,CAST("REVREC_REFERENCE_DOCUMENT" AS varchar(1000) ) AS "REVREC_REFERENCE_DOCUMENT"
                        ,CAST("REVREC_SIGNATURE" AS varchar(1000) ) AS "REVREC_SIGNATURE"
                        ,TRY_CONVERT(datetime2,"REVREC_SIGNATURE_DATE",121) AS "REVREC_SIGNATURE_DATE"
                        ,CAST("REVREC_IMPLICIT_FLAG" AS varchar(100) ) AS "REVREC_IMPLICIT_FLAG"
                        ,CAST("BYPASS_SCH_FLAG" AS varchar(100) ) AS "BYPASS_SCH_FLAG"
                        ,CAST("PRE_EXPLODED_FLAG" AS varchar(100) ) AS "PRE_EXPLODED_FLAG"
                        ,CAST("EQUIPMENT_ID" AS float) AS "EQUIPMENT_ID"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "LINE_ID"
                            , "ORG_ID"
                            , "HEADER_ID"
                            , "LINE_TYPE_ID"
                            , "LINE_NUMBER"
                            , "ORDERED_ITEM"
                            , "REQUEST_DATE"
                            , "PROMISE_DATE"
                            , "SCHEDULE_SHIP_DATE"
                            , "ORDER_QUANTITY_UOM"
                            , "PRICING_QUANTITY"
                            , "PRICING_QUANTITY_UOM"
                            , "CANCELLED_QUANTITY"
                            , "SHIPPED_QUANTITY"
                            , "ORDERED_QUANTITY"
                            , "FULFILLED_QUANTITY"
                            , "SHIPPING_QUANTITY"
                            , "SHIPPING_QUANTITY_UOM"
                            , "DELIVERY_LEAD_TIME"
                            , "TAX_EXEMPT_FLAG"
                            , "TAX_EXEMPT_NUMBER"
                            , "TAX_EXEMPT_REASON_CODE"
                            , "SHIP_FROM_ORG_ID"
                            , "SHIP_TO_ORG_ID"
                            , "INVOICE_TO_ORG_ID"
                            , "DELIVER_TO_ORG_ID"
                            , "SHIP_TO_CONTACT_ID"
                            , "DELIVER_TO_CONTACT_ID"
                            , "INVOICE_TO_CONTACT_ID"
                            , "INTMED_SHIP_TO_ORG_ID"
                            , "INTMED_SHIP_TO_CONTACT_ID"
                            , "SOLD_FROM_ORG_ID"
                            , "SOLD_TO_ORG_ID"
                            , "CUST_PO_NUMBER"
                            , "SHIP_TOLERANCE_ABOVE"
                            , "SHIP_TOLERANCE_BELOW"
                            , "DEMAND_BUCKET_TYPE_CODE"
                            , "VEH_CUS_ITEM_CUM_KEY_ID"
                            , "RLA_SCHEDULE_TYPE_CODE"
                            , "CUSTOMER_DOCK_CODE"
                            , "CUSTOMER_JOB"
                            , "CUSTOMER_PRODUCTION_LINE"
                            , "CUST_MODEL_SERIAL_NUMBER"
                            , "PROJECT_ID"
                            , "TASK_ID"
                            , "INVENTORY_ITEM_ID"
                            , "TAX_DATE"
                            , "TAX_CODE"
                            , "TAX_RATE"
                            , "INVOICE_INTERFACE_STATUS_CODE"
                            , "DEMAND_CLASS_CODE"
                            , "PRICE_LIST_ID"
                            , "PRICING_DATE"
                            , "SHIPMENT_NUMBER"
                            , "AGREEMENT_ID"
                            , "SHIPMENT_PRIORITY_CODE"
                            , "SHIPPING_METHOD_CODE"
                            , "FREIGHT_CARRIER_CODE"
                            , "FREIGHT_TERMS_CODE"
                            , "FOB_POINT_CODE"
                            , "TAX_POINT_CODE"
                            , "PAYMENT_TERM_ID"
                            , "INVOICING_RULE_ID"
                            , "ACCOUNTING_RULE_ID"
                            , "SOURCE_DOCUMENT_TYPE_ID"
                            , "ORIG_SYS_DOCUMENT_REF"
                            , "SOURCE_DOCUMENT_ID"
                            , "ORIG_SYS_LINE_REF"
                            , "SOURCE_DOCUMENT_LINE_ID"
                            , "REFERENCE_LINE_ID"
                            , "REFERENCE_TYPE"
                            , "REFERENCE_HEADER_ID"
                            , "ITEM_REVISION"
                            , "UNIT_SELLING_PRICE"
                            , "UNIT_LIST_PRICE"
                            , "TAX_VALUE"
                            , "CONTEXT"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "PRICING_CONTEXT"
                            , "PRICING_ATTRIBUTE1"
                            , "PRICING_ATTRIBUTE2"
                            , "PRICING_ATTRIBUTE3"
                            , "PRICING_ATTRIBUTE4"
                            , "PRICING_ATTRIBUTE5"
                            , "PRICING_ATTRIBUTE6"
                            , "PRICING_ATTRIBUTE7"
                            , "PRICING_ATTRIBUTE8"
                            , "PRICING_ATTRIBUTE9"
                            , "PRICING_ATTRIBUTE10"
                            , "INDUSTRY_CONTEXT"
                            , "INDUSTRY_ATTRIBUTE1"
                            , "INDUSTRY_ATTRIBUTE2"
                            , "INDUSTRY_ATTRIBUTE3"
                            , "INDUSTRY_ATTRIBUTE4"
                            , "INDUSTRY_ATTRIBUTE5"
                            , "INDUSTRY_ATTRIBUTE6"
                            , "INDUSTRY_ATTRIBUTE7"
                            , "INDUSTRY_ATTRIBUTE8"
                            , "INDUSTRY_ATTRIBUTE9"
                            , "INDUSTRY_ATTRIBUTE10"
                            , "INDUSTRY_ATTRIBUTE11"
                            , "INDUSTRY_ATTRIBUTE13"
                            , "INDUSTRY_ATTRIBUTE12"
                            , "INDUSTRY_ATTRIBUTE14"
                            , "INDUSTRY_ATTRIBUTE15"
                            , "INDUSTRY_ATTRIBUTE16"
                            , "INDUSTRY_ATTRIBUTE17"
                            , "INDUSTRY_ATTRIBUTE18"
                            , "INDUSTRY_ATTRIBUTE19"
                            , "INDUSTRY_ATTRIBUTE20"
                            , "INDUSTRY_ATTRIBUTE21"
                            , "INDUSTRY_ATTRIBUTE22"
                            , "INDUSTRY_ATTRIBUTE23"
                            , "INDUSTRY_ATTRIBUTE24"
                            , "INDUSTRY_ATTRIBUTE25"
                            , "INDUSTRY_ATTRIBUTE26"
                            , "INDUSTRY_ATTRIBUTE27"
                            , "INDUSTRY_ATTRIBUTE28"
                            , "INDUSTRY_ATTRIBUTE29"
                            , "INDUSTRY_ATTRIBUTE30"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "REQUEST_ID"
                            , "TOP_MODEL_LINE_ID"
                            , "LINK_TO_LINE_ID"
                            , "COMPONENT_SEQUENCE_ID"
                            , "COMPONENT_CODE"
                            , "CONFIG_DISPLAY_SEQUENCE"
                            , "SORT_ORDER"
                            , "ITEM_TYPE_CODE"
                            , "OPTION_NUMBER"
                            , "OPTION_FLAG"
                            , "DEP_PLAN_REQUIRED_FLAG"
                            , "VISIBLE_DEMAND_FLAG"
                            , "LINE_CATEGORY_CODE"
                            , "ACTUAL_SHIPMENT_DATE"
                            , "CUSTOMER_TRX_LINE_ID"
                            , "RETURN_CONTEXT"
                            , "RETURN_ATTRIBUTE1"
                            , "RETURN_ATTRIBUTE2"
                            , "RETURN_ATTRIBUTE3"
                            , "RETURN_ATTRIBUTE4"
                            , "RETURN_ATTRIBUTE5"
                            , "RETURN_ATTRIBUTE6"
                            , "RETURN_ATTRIBUTE7"
                            , "RETURN_ATTRIBUTE8"
                            , "RETURN_ATTRIBUTE9"
                            , "RETURN_ATTRIBUTE10"
                            , "RETURN_ATTRIBUTE11"
                            , "RETURN_ATTRIBUTE12"
                            , "RETURN_ATTRIBUTE13"
                            , "RETURN_ATTRIBUTE14"
                            , "RETURN_ATTRIBUTE15"
                            , "ACTUAL_ARRIVAL_DATE"
                            , "ATO_LINE_ID"
                            , "AUTO_SELECTED_QUANTITY"
                            , "COMPONENT_NUMBER"
                            , "EARLIEST_ACCEPTABLE_DATE"
                            , "EXPLOSION_DATE"
                        ,'||')+CONCAT_WS( '||','||'
                            , "LATEST_ACCEPTABLE_DATE"
                            , "MODEL_GROUP_NUMBER"
                            , "SCHEDULE_ARRIVAL_DATE"
                            , "SHIP_MODEL_COMPLETE_FLAG"
                            , "SCHEDULE_STATUS_CODE"
                            , "SOURCE_TYPE_CODE"
                            , "CANCELLED_FLAG"
                            , "OPEN_FLAG"
                            , "BOOKED_FLAG"
                            , "SALESREP_ID"
                            , "RETURN_REASON_CODE"
                            , "ARRIVAL_SET_ID"
                            , "SHIP_SET_ID"
                            , "SPLIT_FROM_LINE_ID"
                            , "CUST_PRODUCTION_SEQ_NUM"
                            , "AUTHORIZED_TO_SHIP_FLAG"
                            , "OVER_SHIP_REASON_CODE"
                            , "OVER_SHIP_RESOLVED_FLAG"
                            , "ORDERED_ITEM_ID"
                            , "ITEM_IDENTIFIER_TYPE"
                            , "CONFIGURATION_ID"
                            , "COMMITMENT_ID"
                            , "SHIPPING_INTERFACED_FLAG"
                            , "CREDIT_INVOICE_LINE_ID"
                            , "FIRST_ACK_CODE"
                            , "FIRST_ACK_DATE"
                            , "LAST_ACK_CODE"
                            , "LAST_ACK_DATE"
                            , "PLANNING_PRIORITY"
                            , "ORDER_SOURCE_ID"
                            , "ORIG_SYS_SHIPMENT_REF"
                            , "CHANGE_SEQUENCE"
                            , "DROP_SHIP_FLAG"
                            , "CUSTOMER_LINE_NUMBER"
                            , "CUSTOMER_SHIPMENT_NUMBER"
                            , "CUSTOMER_ITEM_NET_PRICE"
                            , "CUSTOMER_PAYMENT_TERM_ID"
                            , "FULFILLED_FLAG"
                            , "END_ITEM_UNIT_NUMBER"
                            , "CONFIG_HEADER_ID"
                            , "CONFIG_REV_NBR"
                            , "MFG_COMPONENT_SEQUENCE_ID"
                            , "SHIPPING_INSTRUCTIONS"
                            , "PACKING_INSTRUCTIONS"
                            , "INVOICED_QUANTITY"
                            , "REFERENCE_CUSTOMER_TRX_LINE_ID"
                            , "SPLIT_BY"
                            , "LINE_SET_ID"
                            , "SERVICE_TXN_REASON_CODE"
                            , "SERVICE_TXN_COMMENTS"
                            , "SERVICE_DURATION"
                            , "SERVICE_START_DATE"
                            , "SERVICE_END_DATE"
                            , "SERVICE_COTERMINATE_FLAG"
                            , "UNIT_LIST_PERCENT"
                            , "UNIT_SELLING_PERCENT"
                            , "UNIT_PERCENT_BASE_PRICE"
                            , "SERVICE_NUMBER"
                            , "SERVICE_PERIOD"
                            , "SHIPPABLE_FLAG"
                            , "MODEL_REMNANT_FLAG"
                            , "RE_SOURCE_FLAG"
                            , "FLOW_STATUS_CODE"
                            , "TP_CONTEXT"
                            , "TP_ATTRIBUTE1"
                            , "TP_ATTRIBUTE2"
                            , "TP_ATTRIBUTE3"
                            , "TP_ATTRIBUTE4"
                            , "TP_ATTRIBUTE5"
                            , "TP_ATTRIBUTE6"
                            , "TP_ATTRIBUTE7"
                            , "TP_ATTRIBUTE8"
                            , "TP_ATTRIBUTE9"
                            , "TP_ATTRIBUTE10"
                            , "TP_ATTRIBUTE11"
                            , "TP_ATTRIBUTE12"
                            , "TP_ATTRIBUTE13"
                            , "TP_ATTRIBUTE14"
                            , "TP_ATTRIBUTE15"
                            , "FULFILLMENT_METHOD_CODE"
                            , "MARKETING_SOURCE_CODE_ID"
                            , "SERVICE_REFERENCE_TYPE_CODE"
                            , "SERVICE_REFERENCE_LINE_ID"
                            , "SERVICE_REFERENCE_SYSTEM_ID"
                            , "CALCULATE_PRICE_FLAG"
                            , "UPGRADED_FLAG"
                            , "REVENUE_AMOUNT"
                            , "FULFILLMENT_DATE"
                            , "PREFERRED_GRADE"
                            , "ORDERED_QUANTITY2"
                            , "ORDERED_QUANTITY_UOM2"
                            , "SHIPPING_QUANTITY2"
                            , "CANCELLED_QUANTITY2"
                            , "SHIPPED_QUANTITY2"
                            , "SHIPPING_QUANTITY_UOM2"
                            , "FULFILLED_QUANTITY2"
                            , "MFG_LEAD_TIME"
                            , "LOCK_CONTROL"
                            , "SUBINVENTORY"
                            , "UNIT_LIST_PRICE_PER_PQTY"
                            , "UNIT_SELLING_PRICE_PER_PQTY"
                            , "PRICE_REQUEST_CODE"
                            , "ORIGINAL_INVENTORY_ITEM_ID"
                            , "ORIGINAL_ORDERED_ITEM_ID"
                            , "ORIGINAL_ORDERED_ITEM"
                            , "ORIGINAL_ITEM_IDENTIFIER_TYPE"
                            , "ITEM_SUBSTITUTION_TYPE_CODE"
                            , "OVERRIDE_ATP_DATE_CODE"
                            , "LATE_DEMAND_PENALTY_FACTOR"
                            , "ACCOUNTING_RULE_DURATION"
                            , "ATTRIBUTE16"
                            , "ATTRIBUTE17"
                            , "ATTRIBUTE18"
                            , "ATTRIBUTE19"
                            , "ATTRIBUTE20"
                            , "USER_ITEM_DESCRIPTION"
                            , "UNIT_COST"
                            , "ITEM_RELATIONSHIP_TYPE"
                            , "BLANKET_LINE_NUMBER"
                            , "BLANKET_NUMBER"
                            , "BLANKET_VERSION_NUMBER"
                            , "SALES_DOCUMENT_TYPE_CODE"
                            , "FIRM_DEMAND_FLAG"
                            , "EARLIEST_SHIP_DATE"
                            , "TRANSACTION_PHASE_CODE"
                            , "SOURCE_DOCUMENT_VERSION_NUMBER"
                            , "PAYMENT_TYPE_CODE"
                            , "MINISITE_ID"
                            , "END_CUSTOMER_ID"
                            , "END_CUSTOMER_CONTACT_ID"
                            , "END_CUSTOMER_SITE_USE_ID"
                            , "IB_OWNER"
                            , "IB_CURRENT_LOCATION"
                            , "IB_INSTALLED_AT_LOCATION"
                            , "RETROBILL_REQUEST_ID"
                            , "ORIGINAL_LIST_PRICE"
                            , "SERVICE_CREDIT_ELIGIBLE_CODE"
                            , "ORDER_FIRMED_DATE"
                            , "ACTUAL_FULFILLMENT_DATE"
                            , "CHARGE_PERIODICITY_CODE"
                            , "CONTINGENCY_ID"
                            , "REVREC_EVENT_CODE"
                            , "REVREC_EXPIRATION_DAYS"
                            , "ACCEPTED_QUANTITY"
                            , "ACCEPTED_BY"
                            , "REVREC_COMMENTS"
                            , "REVREC_REFERENCE_DOCUMENT"
                            , "REVREC_SIGNATURE"
                            , "REVREC_SIGNATURE_DATE"
                            , "REVREC_IMPLICIT_FLAG"
                            , "BYPASS_SCH_FLAG"
                            , "PRE_EXPLODED_FLAG"
                            , "EQUIPMENT_ID"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_OE_ORDER_LINES_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
