
CREATE PROCEDURE "STG"."LOAD_STG_EBS_PO_LINE_LOCATIONS_ALL"
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        5/05/2022 11:48:53 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_PO_LINE_LOCATIONS_ALL";
    
    
    Source                                   Destination                           
    -------------------------------------    ------------------------------------- 
    LND"."LND_EBS_PO_LINE_LOCATIONS_ALL"    "STG"."STG_EBS_PO_LINE_LOCATIONS_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-05    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_PO_LINE_LOCATIONS_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_PO_LINE_LOCATIONS_ALL"
                (
                    "LINE_LOCATION_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"PO_HEADER_ID"
                    ,"PO_LINE_ID"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"QUANTITY"
                    ,"QUANTITY_RECEIVED"
                    ,"QUANTITY_ACCEPTED"
                    ,"QUANTITY_REJECTED"
                    ,"QUANTITY_BILLED"
                    ,"QUANTITY_CANCELLED"
                    ,"UNIT_MEAS_LOOKUP_CODE"
                    ,"PO_RELEASE_ID"
                    ,"SHIP_TO_LOCATION_ID"
                    ,"SHIP_VIA_LOOKUP_CODE"
                    ,"NEED_BY_DATE"
                    ,"PROMISED_DATE"
                    ,"LAST_ACCEPT_DATE"
                    ,"PRICE_OVERRIDE"
                    ,"ENCUMBERED_FLAG"
                    ,"ENCUMBERED_DATE"
                    ,"UNENCUMBERED_QUANTITY"
                    ,"FOB_LOOKUP_CODE"
                    ,"FREIGHT_TERMS_LOOKUP_CODE"
                    ,"TAXABLE_FLAG"
                    ,"TAX_NAME"
                    ,"ESTIMATED_TAX_AMOUNT"
                    ,"FROM_HEADER_ID"
                    ,"FROM_LINE_ID"
                    ,"FROM_LINE_LOCATION_ID"
                    ,"START_DATE"
                    ,"END_DATE"
                    ,"LEAD_TIME"
                    ,"LEAD_TIME_UNIT"
                    ,"PRICE_DISCOUNT"
                    ,"TERMS_ID"
                    ,"APPROVED_FLAG"
                    ,"APPROVED_DATE"
                    ,"CLOSED_FLAG"
                    ,"CANCEL_FLAG"
                    ,"CANCELLED_BY"
                    ,"CANCEL_DATE"
                    ,"CANCEL_REASON"
                    ,"FIRM_STATUS_LOOKUP_CODE"
                    ,"FIRM_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"UNIT_OF_MEASURE_CLASS"
                    ,"ENCUMBER_NOW"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"INSPECTION_REQUIRED_FLAG"
                    ,"RECEIPT_REQUIRED_FLAG"
                    ,"QTY_RCV_TOLERANCE"
                    ,"QTY_RCV_EXCEPTION_CODE"
                    ,"ENFORCE_SHIP_TO_LOCATION_CODE"
                    ,"ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                    ,"DAYS_EARLY_RECEIPT_ALLOWED"
                    ,"DAYS_LATE_RECEIPT_ALLOWED"
                    ,"RECEIPT_DAYS_EXCEPTION_CODE"
                    ,"INVOICE_CLOSE_TOLERANCE"
                    ,"RECEIVE_CLOSE_TOLERANCE"
                    ,"SHIP_TO_ORGANIZATION_ID"
                    ,"SHIPMENT_NUM"
                    ,"SOURCE_SHIPMENT_ID"
                    ,"SHIPMENT_TYPE"
                    ,"CLOSED_CODE"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"GOVERNMENT_CONTEXT"
                    ,"RECEIVING_ROUTING_ID"
                    ,"ACCRUE_ON_RECEIPT_FLAG"
                    ,"CLOSED_REASON"
                    ,"CLOSED_DATE"
                    ,"CLOSED_BY"
                    ,"ORG_ID"
                    ,"QUANTITY_SHIPPED"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"COUNTRY_OF_ORIGIN_CODE"
                    ,"TAX_USER_OVERRIDE_FLAG"
                    ,"MATCH_OPTION"
                    ,"TAX_CODE_ID"
                    ,"CALCULATE_TAX_FLAG"
                    ,"CHANGE_PROMISED_DATE_REASON"
                    ,"NOTE_TO_RECEIVER"
                    ,"SECONDARY_QUANTITY"
                    ,"SECONDARY_UNIT_OF_MEASURE"
                    ,"PREFERRED_GRADE"
                    ,"SECONDARY_QUANTITY_RECEIVED"
                    ,"SECONDARY_QUANTITY_ACCEPTED"
                    ,"SECONDARY_QUANTITY_REJECTED"
                    ,"SECONDARY_QUANTITY_CANCELLED"
                    ,"VMI_FLAG"
                    ,"CONSIGNED_FLAG"
                    ,"RETROACTIVE_DATE"
                    ,"SUPPLIER_ORDER_LINE_NUMBER"
                    ,"AMOUNT"
                    ,"AMOUNT_RECEIVED"
                    ,"AMOUNT_BILLED"
                    ,"AMOUNT_CANCELLED"
                    ,"AMOUNT_REJECTED"
                    ,"AMOUNT_ACCEPTED"
                    ,"DROP_SHIP_FLAG"
                    ,"SALES_ORDER_UPDATE_DATE"
                    ,"TRANSACTION_FLOW_HEADER_ID"
                    ,"FINAL_MATCH_FLAG"
                    ,"MANUAL_PRICE_CHANGE_FLAG"
                    ,"SHIPMENT_CLOSED_DATE"
                    ,"CLOSED_FOR_RECEIVING_DATE"
                    ,"CLOSED_FOR_INVOICE_DATE"
                    ,"SECONDARY_QUANTITY_SHIPPED"
                    ,"VALUE_BASIS"
                    ,"MATCHING_BASIS"
                    ,"PAYMENT_TYPE"
                    ,"DESCRIPTION"
                    ,"WORK_APPROVER_ID"
                    ,"BID_PAYMENT_ID"
                    ,"QUANTITY_FINANCED"
                    ,"AMOUNT_FINANCED"
                    ,"QUANTITY_RECOUPED"
                    ,"AMOUNT_RECOUPED"
                    ,"RETAINAGE_WITHHELD_AMOUNT"
                    ,"RETAINAGE_RELEASED_AMOUNT"
                    ,"AMOUNT_SHIPPED"
                    ,"OUTSOURCED_ASSEMBLY"
                    ,"TAX_ATTRIBUTE_UPDATE_CODE"
                    ,"ORIGINAL_SHIPMENT_ID"
                    ,"LCM_FLAG"
                    ,"UDA_TEMPLATE_ID"
                    ,"DRAFT_ID"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("LINE_LOCATION_ID" AS float) AS "LINE_LOCATION_ID"
                        ,CAST("LAST_UPDATE_DATE"  AS datetime2) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("PO_HEADER_ID" AS float) AS "PO_HEADER_ID"
                        ,CAST("PO_LINE_ID" AS float) AS "PO_LINE_ID"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("CREATION_DATE"  AS datetime2) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("QUANTITY" AS float) AS "QUANTITY"
                        ,CAST("QUANTITY_RECEIVED" AS float) AS "QUANTITY_RECEIVED"
                        ,CAST("QUANTITY_ACCEPTED" AS float) AS "QUANTITY_ACCEPTED"
                        ,CAST("QUANTITY_REJECTED" AS float) AS "QUANTITY_REJECTED"
                        ,CAST("QUANTITY_BILLED" AS float) AS "QUANTITY_BILLED"
                        ,CAST("QUANTITY_CANCELLED" AS float) AS "QUANTITY_CANCELLED"
                        ,CAST("UNIT_MEAS_LOOKUP_CODE" AS varchar(100) ) AS "UNIT_MEAS_LOOKUP_CODE"
                        ,CAST("PO_RELEASE_ID" AS float) AS "PO_RELEASE_ID"
                        ,CAST("SHIP_TO_LOCATION_ID" AS float) AS "SHIP_TO_LOCATION_ID"
                        ,CAST("SHIP_VIA_LOOKUP_CODE" AS varchar(100) ) AS "SHIP_VIA_LOOKUP_CODE"
                        ,CAST("NEED_BY_DATE"  AS datetime2) AS "NEED_BY_DATE"
                        ,CAST("PROMISED_DATE"  AS datetime2) AS "PROMISED_DATE"
                        ,CAST("LAST_ACCEPT_DATE"  AS datetime2) AS "LAST_ACCEPT_DATE"
                        ,CAST("PRICE_OVERRIDE" AS float) AS "PRICE_OVERRIDE"
                        ,CAST("ENCUMBERED_FLAG" AS varchar(100) ) AS "ENCUMBERED_FLAG"
                        ,CAST("ENCUMBERED_DATE"  AS datetime2) AS "ENCUMBERED_DATE"
                        ,CAST("UNENCUMBERED_QUANTITY" AS float) AS "UNENCUMBERED_QUANTITY"
                        ,CAST("FOB_LOOKUP_CODE" AS varchar(100) ) AS "FOB_LOOKUP_CODE"
                        ,CAST("FREIGHT_TERMS_LOOKUP_CODE" AS varchar(100) ) AS "FREIGHT_TERMS_LOOKUP_CODE"
                        ,CAST("TAXABLE_FLAG" AS varchar(100) ) AS "TAXABLE_FLAG"
                        ,CAST("TAX_NAME" AS varchar(100) ) AS "TAX_NAME"
                        ,CAST("ESTIMATED_TAX_AMOUNT" AS float) AS "ESTIMATED_TAX_AMOUNT"
                        ,CAST("FROM_HEADER_ID" AS float) AS "FROM_HEADER_ID"
                        ,CAST("FROM_LINE_ID" AS float) AS "FROM_LINE_ID"
                        ,CAST("FROM_LINE_LOCATION_ID" AS float) AS "FROM_LINE_LOCATION_ID"
                        ,CAST("START_DATE"  AS datetime2) AS "START_DATE"
                        ,CAST("END_DATE"  AS datetime2) AS "END_DATE"
                        ,CAST("LEAD_TIME" AS float) AS "LEAD_TIME"
                        ,CAST("LEAD_TIME_UNIT" AS varchar(100) ) AS "LEAD_TIME_UNIT"
                        ,CAST("PRICE_DISCOUNT" AS float) AS "PRICE_DISCOUNT"
                        ,CAST("TERMS_ID" AS float) AS "TERMS_ID"
                        ,CAST("APPROVED_FLAG" AS varchar(100) ) AS "APPROVED_FLAG"
                        ,CAST("APPROVED_DATE"  AS datetime2) AS "APPROVED_DATE"
                        ,CAST("CLOSED_FLAG" AS varchar(100) ) AS "CLOSED_FLAG"
                        ,CAST("CANCEL_FLAG" AS varchar(100) ) AS "CANCEL_FLAG"
                        ,CAST("CANCELLED_BY" AS float) AS "CANCELLED_BY"
                        ,CAST("CANCEL_DATE"  AS datetime2) AS "CANCEL_DATE"
                        ,CAST("CANCEL_REASON" AS varchar(1000) ) AS "CANCEL_REASON"
                        ,CAST("FIRM_STATUS_LOOKUP_CODE" AS varchar(100) ) AS "FIRM_STATUS_LOOKUP_CODE"
                        ,CAST("FIRM_DATE"  AS datetime2) AS "FIRM_DATE"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("UNIT_OF_MEASURE_CLASS" AS varchar(100) ) AS "UNIT_OF_MEASURE_CLASS"
                        ,CAST("ENCUMBER_NOW" AS varchar(100) ) AS "ENCUMBER_NOW"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("INSPECTION_REQUIRED_FLAG" AS varchar(100) ) AS "INSPECTION_REQUIRED_FLAG"
                        ,CAST("RECEIPT_REQUIRED_FLAG" AS varchar(100) ) AS "RECEIPT_REQUIRED_FLAG"
                        ,CAST("QTY_RCV_TOLERANCE" AS float) AS "QTY_RCV_TOLERANCE"
                        ,CAST("QTY_RCV_EXCEPTION_CODE" AS varchar(100) ) AS "QTY_RCV_EXCEPTION_CODE"
                        ,CAST("ENFORCE_SHIP_TO_LOCATION_CODE" AS varchar(100) ) AS "ENFORCE_SHIP_TO_LOCATION_CODE"
                        ,CAST("ALLOW_SUBSTITUTE_RECEIPTS_FLAG" AS varchar(100) ) AS "ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                        ,CAST("DAYS_EARLY_RECEIPT_ALLOWED" AS float) AS "DAYS_EARLY_RECEIPT_ALLOWED"
                        ,CAST("DAYS_LATE_RECEIPT_ALLOWED" AS float) AS "DAYS_LATE_RECEIPT_ALLOWED"
                        ,CAST("RECEIPT_DAYS_EXCEPTION_CODE" AS varchar(100) ) AS "RECEIPT_DAYS_EXCEPTION_CODE"
                        ,CAST("INVOICE_CLOSE_TOLERANCE" AS float) AS "INVOICE_CLOSE_TOLERANCE"
                        ,CAST("RECEIVE_CLOSE_TOLERANCE" AS float) AS "RECEIVE_CLOSE_TOLERANCE"
                        ,CAST("SHIP_TO_ORGANIZATION_ID" AS float) AS "SHIP_TO_ORGANIZATION_ID"
                        ,CAST("SHIPMENT_NUM" AS float) AS "SHIPMENT_NUM"
                        ,CAST("SOURCE_SHIPMENT_ID" AS float) AS "SOURCE_SHIPMENT_ID"
                        ,CAST("SHIPMENT_TYPE" AS varchar(100) ) AS "SHIPMENT_TYPE"
                        ,CAST("CLOSED_CODE" AS varchar(100) ) AS "CLOSED_CODE"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,CAST("PROGRAM_UPDATE_DATE"  AS datetime2) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("USSGL_TRANSACTION_CODE" AS varchar(100) ) AS "USSGL_TRANSACTION_CODE"
                        ,CAST("GOVERNMENT_CONTEXT" AS varchar(100) ) AS "GOVERNMENT_CONTEXT"
                        ,CAST("RECEIVING_ROUTING_ID" AS float) AS "RECEIVING_ROUTING_ID"
                        ,CAST("ACCRUE_ON_RECEIPT_FLAG" AS varchar(100) ) AS "ACCRUE_ON_RECEIPT_FLAG"
                        ,CAST("CLOSED_REASON" AS varchar(1000) ) AS "CLOSED_REASON"
                        ,CAST("CLOSED_DATE"  AS datetime2) AS "CLOSED_DATE"
                        ,CAST("CLOSED_BY" AS float) AS "CLOSED_BY"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,CAST("QUANTITY_SHIPPED" AS float) AS "QUANTITY_SHIPPED"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("COUNTRY_OF_ORIGIN_CODE" AS varchar(100) ) AS "COUNTRY_OF_ORIGIN_CODE"
                        ,CAST("TAX_USER_OVERRIDE_FLAG" AS varchar(100) ) AS "TAX_USER_OVERRIDE_FLAG"
                        ,CAST("MATCH_OPTION" AS varchar(100) ) AS "MATCH_OPTION"
                        ,CAST("TAX_CODE_ID" AS float) AS "TAX_CODE_ID"
                        ,CAST("CALCULATE_TAX_FLAG" AS varchar(100) ) AS "CALCULATE_TAX_FLAG"
                        ,CAST("CHANGE_PROMISED_DATE_REASON" AS varchar(1000) ) AS "CHANGE_PROMISED_DATE_REASON"
                        ,CAST("NOTE_TO_RECEIVER" AS varchar(1000) ) AS "NOTE_TO_RECEIVER"
                        ,CAST("SECONDARY_QUANTITY" AS float) AS "SECONDARY_QUANTITY"
                        ,CAST("SECONDARY_UNIT_OF_MEASURE" AS varchar(100) ) AS "SECONDARY_UNIT_OF_MEASURE"
                        ,CAST("PREFERRED_GRADE" AS varchar(1000) ) AS "PREFERRED_GRADE"
                        ,CAST("SECONDARY_QUANTITY_RECEIVED" AS float) AS "SECONDARY_QUANTITY_RECEIVED"
                        ,CAST("SECONDARY_QUANTITY_ACCEPTED" AS float) AS "SECONDARY_QUANTITY_ACCEPTED"
                        ,CAST("SECONDARY_QUANTITY_REJECTED" AS float) AS "SECONDARY_QUANTITY_REJECTED"
                        ,CAST("SECONDARY_QUANTITY_CANCELLED" AS float) AS "SECONDARY_QUANTITY_CANCELLED"
                        ,CAST("VMI_FLAG" AS varchar(100) ) AS "VMI_FLAG"
                        ,CAST("CONSIGNED_FLAG" AS varchar(100) ) AS "CONSIGNED_FLAG"
                        ,CAST("RETROACTIVE_DATE"  AS datetime2) AS "RETROACTIVE_DATE"
                        ,CAST("SUPPLIER_ORDER_LINE_NUMBER" AS varchar(100) ) AS "SUPPLIER_ORDER_LINE_NUMBER"
                        ,CAST("AMOUNT" AS float) AS "AMOUNT"
                        ,CAST("AMOUNT_RECEIVED" AS float) AS "AMOUNT_RECEIVED"
                        ,CAST("AMOUNT_BILLED" AS float) AS "AMOUNT_BILLED"
                        ,CAST("AMOUNT_CANCELLED" AS float) AS "AMOUNT_CANCELLED"
                        ,CAST("AMOUNT_REJECTED" AS float) AS "AMOUNT_REJECTED"
                        ,CAST("AMOUNT_ACCEPTED" AS float) AS "AMOUNT_ACCEPTED"
                        ,CAST("DROP_SHIP_FLAG" AS varchar(100) ) AS "DROP_SHIP_FLAG"
                        ,CAST("SALES_ORDER_UPDATE_DATE"  AS datetime2) AS "SALES_ORDER_UPDATE_DATE"
                        ,CAST("TRANSACTION_FLOW_HEADER_ID" AS float) AS "TRANSACTION_FLOW_HEADER_ID"
                        ,CAST("FINAL_MATCH_FLAG" AS varchar(100) ) AS "FINAL_MATCH_FLAG"
                        ,CAST("MANUAL_PRICE_CHANGE_FLAG" AS varchar(100) ) AS "MANUAL_PRICE_CHANGE_FLAG"
                        ,CAST("SHIPMENT_CLOSED_DATE"  AS datetime2) AS "SHIPMENT_CLOSED_DATE"
                        ,CAST("CLOSED_FOR_RECEIVING_DATE"  AS datetime2) AS "CLOSED_FOR_RECEIVING_DATE"
                        ,CAST("CLOSED_FOR_INVOICE_DATE"  AS datetime2) AS "CLOSED_FOR_INVOICE_DATE"
                        ,CAST("SECONDARY_QUANTITY_SHIPPED" AS float) AS "SECONDARY_QUANTITY_SHIPPED"
                        ,CAST("VALUE_BASIS" AS varchar(100) ) AS "VALUE_BASIS"
                        ,CAST("MATCHING_BASIS" AS varchar(100) ) AS "MATCHING_BASIS"
                        ,CAST("PAYMENT_TYPE" AS varchar(100) ) AS "PAYMENT_TYPE"
                        ,CAST("DESCRIPTION" AS varchar(1000) ) AS "DESCRIPTION"
                        ,CAST("WORK_APPROVER_ID" AS float) AS "WORK_APPROVER_ID"
                        ,CAST("BID_PAYMENT_ID" AS float) AS "BID_PAYMENT_ID"
                        ,CAST("QUANTITY_FINANCED" AS float) AS "QUANTITY_FINANCED"
                        ,CAST("AMOUNT_FINANCED" AS float) AS "AMOUNT_FINANCED"
                        ,CAST("QUANTITY_RECOUPED" AS float) AS "QUANTITY_RECOUPED"
                        ,CAST("AMOUNT_RECOUPED" AS float) AS "AMOUNT_RECOUPED"
                        ,CAST("RETAINAGE_WITHHELD_AMOUNT" AS float) AS "RETAINAGE_WITHHELD_AMOUNT"
                        ,CAST("RETAINAGE_RELEASED_AMOUNT" AS float) AS "RETAINAGE_RELEASED_AMOUNT"
                        ,CAST("AMOUNT_SHIPPED" AS float) AS "AMOUNT_SHIPPED"
                        ,CAST("OUTSOURCED_ASSEMBLY" AS float) AS "OUTSOURCED_ASSEMBLY"
                        ,CAST("TAX_ATTRIBUTE_UPDATE_CODE" AS varchar(100) ) AS "TAX_ATTRIBUTE_UPDATE_CODE"
                        ,CAST("ORIGINAL_SHIPMENT_ID" AS float) AS "ORIGINAL_SHIPMENT_ID"
                        ,CAST("LCM_FLAG" AS varchar(100) ) AS "LCM_FLAG"
                        ,CAST("UDA_TEMPLATE_ID" AS float) AS "UDA_TEMPLATE_ID"
                        ,CAST("DRAFT_ID" AS float) AS "DRAFT_ID"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "LINE_LOCATION_ID"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "PO_HEADER_ID"
                            , "PO_LINE_ID"
                            , "LAST_UPDATE_LOGIN"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "QUANTITY"
                            , "QUANTITY_RECEIVED"
                            , "QUANTITY_ACCEPTED"
                            , "QUANTITY_REJECTED"
                            , "QUANTITY_BILLED"
                            , "QUANTITY_CANCELLED"
                            , "UNIT_MEAS_LOOKUP_CODE"
                            , "PO_RELEASE_ID"
                            , "SHIP_TO_LOCATION_ID"
                            , "SHIP_VIA_LOOKUP_CODE"
                            , "NEED_BY_DATE"
                            , "PROMISED_DATE"
                            , "LAST_ACCEPT_DATE"
                            , "PRICE_OVERRIDE"
                            , "ENCUMBERED_FLAG"
                            , "ENCUMBERED_DATE"
                            , "UNENCUMBERED_QUANTITY"
                            , "FOB_LOOKUP_CODE"
                            , "FREIGHT_TERMS_LOOKUP_CODE"
                            , "TAXABLE_FLAG"
                            , "TAX_NAME"
                            , "ESTIMATED_TAX_AMOUNT"
                            , "FROM_HEADER_ID"
                            , "FROM_LINE_ID"
                            , "FROM_LINE_LOCATION_ID"
                            , "START_DATE"
                            , "END_DATE"
                            , "LEAD_TIME"
                            , "LEAD_TIME_UNIT"
                            , "PRICE_DISCOUNT"
                            , "TERMS_ID"
                            , "APPROVED_FLAG"
                            , "APPROVED_DATE"
                            , "CLOSED_FLAG"
                            , "CANCEL_FLAG"
                            , "CANCELLED_BY"
                            , "CANCEL_DATE"
                            , "CANCEL_REASON"
                            , "FIRM_STATUS_LOOKUP_CODE"
                            , "FIRM_DATE"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "UNIT_OF_MEASURE_CLASS"
                            , "ENCUMBER_NOW"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "INSPECTION_REQUIRED_FLAG"
                            , "RECEIPT_REQUIRED_FLAG"
                            , "QTY_RCV_TOLERANCE"
                            , "QTY_RCV_EXCEPTION_CODE"
                            , "ENFORCE_SHIP_TO_LOCATION_CODE"
                            , "ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                            , "DAYS_EARLY_RECEIPT_ALLOWED"
                            , "DAYS_LATE_RECEIPT_ALLOWED"
                            , "RECEIPT_DAYS_EXCEPTION_CODE"
                            , "INVOICE_CLOSE_TOLERANCE"
                            , "RECEIVE_CLOSE_TOLERANCE"
                            , "SHIP_TO_ORGANIZATION_ID"
                            , "SHIPMENT_NUM"
                            , "SOURCE_SHIPMENT_ID"
                            , "SHIPMENT_TYPE"
                            , "CLOSED_CODE"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "USSGL_TRANSACTION_CODE"
                            , "GOVERNMENT_CONTEXT"
                            , "RECEIVING_ROUTING_ID"
                            , "ACCRUE_ON_RECEIPT_FLAG"
                            , "CLOSED_REASON"
                            , "CLOSED_DATE"
                            , "CLOSED_BY"
                            , "ORG_ID"
                            , "QUANTITY_SHIPPED"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "COUNTRY_OF_ORIGIN_CODE"
                            , "TAX_USER_OVERRIDE_FLAG"
                            , "MATCH_OPTION"
                            , "TAX_CODE_ID"
                            , "CALCULATE_TAX_FLAG"
                            , "CHANGE_PROMISED_DATE_REASON"
                            , "NOTE_TO_RECEIVER"
                            , "SECONDARY_QUANTITY"
                            , "SECONDARY_UNIT_OF_MEASURE"
                            , "PREFERRED_GRADE"
                            , "SECONDARY_QUANTITY_RECEIVED"
                            , "SECONDARY_QUANTITY_ACCEPTED"
                            , "SECONDARY_QUANTITY_REJECTED"
                            , "SECONDARY_QUANTITY_CANCELLED"
                            , "VMI_FLAG"
                            , "CONSIGNED_FLAG"
                            , "RETROACTIVE_DATE"
                            , "SUPPLIER_ORDER_LINE_NUMBER"
                            , "AMOUNT"
                            , "AMOUNT_RECEIVED"
                            , "AMOUNT_BILLED"
                            , "AMOUNT_CANCELLED"
                            , "AMOUNT_REJECTED"
                            , "AMOUNT_ACCEPTED"
                            , "DROP_SHIP_FLAG"
                            , "SALES_ORDER_UPDATE_DATE"
                            , "TRANSACTION_FLOW_HEADER_ID"
                            , "FINAL_MATCH_FLAG"
                            , "MANUAL_PRICE_CHANGE_FLAG"
                            , "SHIPMENT_CLOSED_DATE"
                            , "CLOSED_FOR_RECEIVING_DATE"
                            , "CLOSED_FOR_INVOICE_DATE"
                            , "SECONDARY_QUANTITY_SHIPPED"
                            , "VALUE_BASIS"
                            , "MATCHING_BASIS"
                            , "PAYMENT_TYPE"
                            , "DESCRIPTION"
                            , "WORK_APPROVER_ID"
                            , "BID_PAYMENT_ID"
                            , "QUANTITY_FINANCED"
                            , "AMOUNT_FINANCED"
                            , "QUANTITY_RECOUPED"
                            , "AMOUNT_RECOUPED"
                            , "RETAINAGE_WITHHELD_AMOUNT"
                            , "RETAINAGE_RELEASED_AMOUNT"
                            , "AMOUNT_SHIPPED"
                            , "OUTSOURCED_ASSEMBLY"
                            , "TAX_ATTRIBUTE_UPDATE_CODE"
                            , "ORIGINAL_SHIPMENT_ID"
                            , "LCM_FLAG"
                            , "UDA_TEMPLATE_ID"
                            , "DRAFT_ID"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_PO_LINE_LOCATIONS_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
/**********************************************************************************************************************************************************************************************************/
