

CREATE PROCEDURE [STG].[LOAD_STG_EBS_HZ_PARTIES]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        8/03/2022 5:52:57 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_HZ_PARTIES";
    
    
    Source                        Destination                
    --------------------------    -------------------------- 
    LND"."LND_EBS_HZ_PARTIES"    "STG"."STG_EBS_HZ_PARTIES" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-08    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_HZ_PARTIES";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_HZ_PARTIES"
                (
                    "PARTY_ID"
                    ,"PARTY_NUMBER"
                    ,"PARTY_NAME"
                    ,"PARTY_TYPE"
                    ,"VALIDATED_FLAG"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"LAST_UPDATE_LOGIN"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_DATE"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"WH_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"ATTRIBUTE21"
                    ,"ATTRIBUTE22"
                    ,"ATTRIBUTE23"
                    ,"ATTRIBUTE24"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"ORIG_SYSTEM_REFERENCE"
                    ,"SIC_CODE"
                    ,"HQ_BRANCH_IND"
                    ,"CUSTOMER_KEY"
                    ,"TAX_REFERENCE"
                    ,"JGZZ_FISCAL_CODE"
                    ,"DUNS_NUMBER"
                    ,"TAX_NAME"
                    ,"PERSON_PRE_NAME_ADJUNCT"
                    ,"PERSON_FIRST_NAME"
                    ,"PERSON_MIDDLE_NAME"
                    ,"PERSON_LAST_NAME"
                    ,"PERSON_NAME_SUFFIX"
                    ,"PERSON_TITLE"
                    ,"PERSON_ACADEMIC_TITLE"
                    ,"PERSON_PREVIOUS_LAST_NAME"
                    ,"KNOWN_AS"
                    ,"PERSON_IDEN_TYPE"
                    ,"PERSON_IDENTIFIER"
                    ,"GROUP_TYPE"
                    ,"COUNTRY"
                    ,"ADDRESS1"
                    ,"ADDRESS2"
                    ,"ADDRESS3"
                    ,"ADDRESS4"
                    ,"CITY"
                    ,"POSTAL_CODE"
                    ,"STATE"
                    ,"PROVINCE"
                    ,"STATUS"
                    ,"COUNTY"
                    ,"SIC_CODE_TYPE"
                    ,"TOTAL_NUM_OF_ORDERS"
                    ,"TOTAL_ORDERED_AMOUNT"
                    ,"LAST_ORDERED_DATE"
                    ,"URL"
                    ,"EMAIL_ADDRESS"
                    ,"DO_NOT_MAIL_FLAG"
                    ,"ANALYSIS_FY"
                    ,"FISCAL_YEAREND_MONTH"
                    ,"EMPLOYEES_TOTAL"
                    ,"CURR_FY_POTENTIAL_REVENUE"
                    ,"NEXT_FY_POTENTIAL_REVENUE"
                    ,"YEAR_ESTABLISHED"
                    ,"GSA_INDICATOR_FLAG"
                    ,"MISSION_STATEMENT"
                    ,"ORGANIZATION_NAME_PHONETIC"
                    ,"PERSON_FIRST_NAME_PHONETIC"
                    ,"PERSON_LAST_NAME_PHONETIC"
                    ,"LANGUAGE_NAME"
                    ,"CATEGORY_CODE"
                    ,"REFERENCE_USE_FLAG"
                    ,"THIRD_PARTY_FLAG"
                    ,"COMPETITOR_FLAG"
                    ,"SALUTATION"
                    ,"KNOWN_AS2"
                    ,"KNOWN_AS3"
                    ,"KNOWN_AS4"
                    ,"KNOWN_AS5"
                    ,"DUNS_NUMBER_C"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"CREATED_BY_MODULE"
                    ,"APPLICATION_ID"
                    ,"PRIMARY_PHONE_CONTACT_PT_ID"
                    ,"PRIMARY_PHONE_PURPOSE"
                    ,"PRIMARY_PHONE_LINE_TYPE"
                    ,"PRIMARY_PHONE_COUNTRY_CODE"
                    ,"PRIMARY_PHONE_AREA_CODE"
                    ,"PRIMARY_PHONE_NUMBER"
                    ,"PRIMARY_PHONE_EXTENSION"
                    ,"CERTIFICATION_LEVEL"
                    ,"CERT_REASON_CODE"
                    ,"PREFERRED_CONTACT_METHOD"
                    ,"HOME_COUNTRY"
                    ,"PERSON_BO_VERSION"
                    ,"ORG_BO_VERSION"
                    ,"PERSON_CUST_BO_VERSION"
                    ,"ORG_CUST_BO_VERSION"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("PARTY_ID" AS float) AS "PARTY_ID"
                        ,CAST("PARTY_NUMBER" AS varchar(100) ) AS "PARTY_NUMBER"
                        ,CAST("PARTY_NAME" AS varchar(1000) ) AS "PARTY_NAME"
                        ,CAST("PARTY_TYPE" AS varchar(100) ) AS "PARTY_TYPE"
                        ,CAST("VALIDATED_FLAG" AS varchar(100) ) AS "VALIDATED_FLAG"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,TRY_CONVERT(datetime2,"CREATION_DATE",121) AS "CREATION_DATE"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,TRY_CONVERT(datetime2,"LAST_UPDATE_DATE",121) AS "LAST_UPDATE_DATE"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,TRY_CONVERT(datetime2,"PROGRAM_UPDATE_DATE",121) AS "PROGRAM_UPDATE_DATE"
                        ,TRY_CONVERT(datetime2,"WH_UPDATE_DATE",121) AS "WH_UPDATE_DATE"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("ATTRIBUTE16" AS varchar(1000) ) AS "ATTRIBUTE16"
                        ,CAST("ATTRIBUTE17" AS varchar(1000) ) AS "ATTRIBUTE17"
                        ,CAST("ATTRIBUTE18" AS varchar(1000) ) AS "ATTRIBUTE18"
                        ,CAST("ATTRIBUTE19" AS varchar(1000) ) AS "ATTRIBUTE19"
                        ,CAST("ATTRIBUTE20" AS varchar(1000) ) AS "ATTRIBUTE20"
                        ,CAST("ATTRIBUTE21" AS varchar(1000) ) AS "ATTRIBUTE21"
                        ,CAST("ATTRIBUTE22" AS varchar(1000) ) AS "ATTRIBUTE22"
                        ,CAST("ATTRIBUTE23" AS varchar(1000) ) AS "ATTRIBUTE23"
                        ,CAST("ATTRIBUTE24" AS varchar(1000) ) AS "ATTRIBUTE24"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("ORIG_SYSTEM_REFERENCE" AS varchar(1000) ) AS "ORIG_SYSTEM_REFERENCE"
                        ,CAST("SIC_CODE" AS varchar(100) ) AS "SIC_CODE"
                        ,CAST("HQ_BRANCH_IND" AS varchar(100) ) AS "HQ_BRANCH_IND"
                        ,CAST("CUSTOMER_KEY" AS varchar(1000) ) AS "CUSTOMER_KEY"
                        ,CAST("TAX_REFERENCE" AS varchar(1000) ) AS "TAX_REFERENCE"
                        ,CAST("JGZZ_FISCAL_CODE" AS varchar(100) ) AS "JGZZ_FISCAL_CODE"
                        ,CAST("DUNS_NUMBER" AS float) AS "DUNS_NUMBER"
                        ,CAST("TAX_NAME" AS varchar(1000) ) AS "TAX_NAME"
                        ,CAST("PERSON_PRE_NAME_ADJUNCT" AS varchar(100) ) AS "PERSON_PRE_NAME_ADJUNCT"
                        ,CAST("PERSON_FIRST_NAME" AS varchar(1000) ) AS "PERSON_FIRST_NAME"
                        ,CAST("PERSON_MIDDLE_NAME" AS varchar(1000) ) AS "PERSON_MIDDLE_NAME"
                        ,CAST("PERSON_LAST_NAME" AS varchar(1000) ) AS "PERSON_LAST_NAME"
                        ,CAST("PERSON_NAME_SUFFIX" AS varchar(100) ) AS "PERSON_NAME_SUFFIX"
                        ,CAST("PERSON_TITLE" AS varchar(1000) ) AS "PERSON_TITLE"
                        ,CAST("PERSON_ACADEMIC_TITLE" AS varchar(100) ) AS "PERSON_ACADEMIC_TITLE"
                        ,CAST("PERSON_PREVIOUS_LAST_NAME" AS varchar(1000) ) AS "PERSON_PREVIOUS_LAST_NAME"
                        ,CAST("KNOWN_AS" AS varchar(1000) ) AS "KNOWN_AS"
                        ,CAST("PERSON_IDEN_TYPE" AS varchar(100) ) AS "PERSON_IDEN_TYPE"
                        ,CAST("PERSON_IDENTIFIER" AS varchar(1000) ) AS "PERSON_IDENTIFIER"
                        ,CAST("GROUP_TYPE" AS varchar(100) ) AS "GROUP_TYPE"
                        ,CAST("COUNTRY" AS varchar(1000) ) AS "COUNTRY"
                        ,CAST("ADDRESS1" AS varchar(1000) ) AS "ADDRESS1"
                        ,CAST("ADDRESS2" AS varchar(1000) ) AS "ADDRESS2"
                        ,CAST("ADDRESS3" AS varchar(1000) ) AS "ADDRESS3"
                        ,CAST("ADDRESS4" AS varchar(1000) ) AS "ADDRESS4"
                        ,CAST("CITY" AS varchar(1000) ) AS "CITY"
                        ,CAST("POSTAL_CODE" AS varchar(1000) ) AS "POSTAL_CODE"
                        ,CAST("STATE" AS varchar(1000) ) AS "STATE"
                        ,CAST("PROVINCE" AS varchar(1000) ) AS "PROVINCE"
                        ,CAST("STATUS" AS varchar(100) ) AS "STATUS"
                        ,CAST("COUNTY" AS varchar(1000) ) AS "COUNTY"
                        ,CAST("SIC_CODE_TYPE" AS varchar(100) ) AS "SIC_CODE_TYPE"
                        ,CAST("TOTAL_NUM_OF_ORDERS" AS float) AS "TOTAL_NUM_OF_ORDERS"
                        ,CAST("TOTAL_ORDERED_AMOUNT" AS float) AS "TOTAL_ORDERED_AMOUNT"
                        ,TRY_CONVERT(datetime2,"LAST_ORDERED_DATE",121) AS "LAST_ORDERED_DATE"
                        ,CAST("URL" AS varchar(8000) ) AS "URL"
                        ,CAST("EMAIL_ADDRESS" AS varchar(8000) ) AS "EMAIL_ADDRESS"
                        ,CAST("DO_NOT_MAIL_FLAG" AS varchar(100) ) AS "DO_NOT_MAIL_FLAG"
                        ,CAST("ANALYSIS_FY" AS varchar(100) ) AS "ANALYSIS_FY"
                        ,CAST("FISCAL_YEAREND_MONTH" AS varchar(100) ) AS "FISCAL_YEAREND_MONTH"
                        ,CAST("EMPLOYEES_TOTAL" AS float) AS "EMPLOYEES_TOTAL"
                        ,CAST("CURR_FY_POTENTIAL_REVENUE" AS float) AS "CURR_FY_POTENTIAL_REVENUE"
                        ,CAST("NEXT_FY_POTENTIAL_REVENUE" AS float) AS "NEXT_FY_POTENTIAL_REVENUE"
                        ,CAST("YEAR_ESTABLISHED" AS float) AS "YEAR_ESTABLISHED"
                        ,CAST("GSA_INDICATOR_FLAG" AS varchar(100) ) AS "GSA_INDICATOR_FLAG"
                        ,CAST("MISSION_STATEMENT" AS varchar(8000) ) AS "MISSION_STATEMENT"
                        ,CAST("ORGANIZATION_NAME_PHONETIC" AS varchar(1000) ) AS "ORGANIZATION_NAME_PHONETIC"
                        ,CAST("PERSON_FIRST_NAME_PHONETIC" AS varchar(1000) ) AS "PERSON_FIRST_NAME_PHONETIC"
                        ,CAST("PERSON_LAST_NAME_PHONETIC" AS varchar(1000) ) AS "PERSON_LAST_NAME_PHONETIC"
                        ,CAST("LANGUAGE_NAME" AS varchar(100) ) AS "LANGUAGE_NAME"
                        ,CAST("CATEGORY_CODE" AS varchar(100) ) AS "CATEGORY_CODE"
                        ,CAST("REFERENCE_USE_FLAG" AS varchar(100) ) AS "REFERENCE_USE_FLAG"
                        ,CAST("THIRD_PARTY_FLAG" AS varchar(100) ) AS "THIRD_PARTY_FLAG"
                        ,CAST("COMPETITOR_FLAG" AS varchar(100) ) AS "COMPETITOR_FLAG"
                        ,CAST("SALUTATION" AS varchar(1000) ) AS "SALUTATION"
                        ,CAST("KNOWN_AS2" AS varchar(1000) ) AS "KNOWN_AS2"
                        ,CAST("KNOWN_AS3" AS varchar(1000) ) AS "KNOWN_AS3"
                        ,CAST("KNOWN_AS4" AS varchar(1000) ) AS "KNOWN_AS4"
                        ,CAST("KNOWN_AS5" AS varchar(1000) ) AS "KNOWN_AS5"
                        ,CAST("DUNS_NUMBER_C" AS varchar(100) ) AS "DUNS_NUMBER_C"
                        ,CAST("OBJECT_VERSION_NUMBER" AS float) AS "OBJECT_VERSION_NUMBER"
                        ,CAST("CREATED_BY_MODULE" AS varchar(1000) ) AS "CREATED_BY_MODULE"
                        ,CAST("APPLICATION_ID" AS float) AS "APPLICATION_ID"
                        ,CAST("PRIMARY_PHONE_CONTACT_PT_ID" AS float) AS "PRIMARY_PHONE_CONTACT_PT_ID"
                        ,CAST("PRIMARY_PHONE_PURPOSE" AS varchar(100) ) AS "PRIMARY_PHONE_PURPOSE"
                        ,CAST("PRIMARY_PHONE_LINE_TYPE" AS varchar(100) ) AS "PRIMARY_PHONE_LINE_TYPE"
                        ,CAST("PRIMARY_PHONE_COUNTRY_CODE" AS varchar(100) ) AS "PRIMARY_PHONE_COUNTRY_CODE"
                        ,CAST("PRIMARY_PHONE_AREA_CODE" AS varchar(100) ) AS "PRIMARY_PHONE_AREA_CODE"
                        ,CAST("PRIMARY_PHONE_NUMBER" AS varchar(100) ) AS "PRIMARY_PHONE_NUMBER"
                        ,CAST("PRIMARY_PHONE_EXTENSION" AS varchar(100) ) AS "PRIMARY_PHONE_EXTENSION"
                        ,CAST("CERTIFICATION_LEVEL" AS varchar(100) ) AS "CERTIFICATION_LEVEL"
                        ,CAST("CERT_REASON_CODE" AS varchar(100) ) AS "CERT_REASON_CODE"
                        ,CAST("PREFERRED_CONTACT_METHOD" AS varchar(100) ) AS "PREFERRED_CONTACT_METHOD"
                        ,CAST("HOME_COUNTRY" AS varchar(100) ) AS "HOME_COUNTRY"
                        ,CAST("PERSON_BO_VERSION" AS float) AS "PERSON_BO_VERSION"
                        ,CAST("ORG_BO_VERSION" AS float) AS "ORG_BO_VERSION"
                        ,CAST("PERSON_CUST_BO_VERSION" AS float) AS "PERSON_CUST_BO_VERSION"
                        ,CAST("ORG_CUST_BO_VERSION" AS float) AS "ORG_CUST_BO_VERSION"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "PARTY_ID"
                            , "PARTY_NUMBER"
                            , "PARTY_NAME"
                            , "PARTY_TYPE"
                            , "VALIDATED_FLAG"
                            , "LAST_UPDATED_BY"
                            , "CREATION_DATE"
                            , "LAST_UPDATE_LOGIN"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "CREATED_BY"
                            , "LAST_UPDATE_DATE"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "WH_UPDATE_DATE"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "ATTRIBUTE16"
                            , "ATTRIBUTE17"
                            , "ATTRIBUTE18"
                            , "ATTRIBUTE19"
                            , "ATTRIBUTE20"
                            , "ATTRIBUTE21"
                            , "ATTRIBUTE22"
                            , "ATTRIBUTE23"
                            , "ATTRIBUTE24"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "ORIG_SYSTEM_REFERENCE"
                            , "SIC_CODE"
                            , "HQ_BRANCH_IND"
                            , "CUSTOMER_KEY"
                            , "TAX_REFERENCE"
                            , "JGZZ_FISCAL_CODE"
                            , "DUNS_NUMBER"
                            , "TAX_NAME"
                            , "PERSON_PRE_NAME_ADJUNCT"
                            , "PERSON_FIRST_NAME"
                            , "PERSON_MIDDLE_NAME"
                            , "PERSON_LAST_NAME"
                            , "PERSON_NAME_SUFFIX"
                            , "PERSON_TITLE"
                            , "PERSON_ACADEMIC_TITLE"
                            , "PERSON_PREVIOUS_LAST_NAME"
                            , "KNOWN_AS"
                            , "PERSON_IDEN_TYPE"
                            , "PERSON_IDENTIFIER"
                            , "GROUP_TYPE"
                            , "COUNTRY"
                            , "ADDRESS1"
                            , "ADDRESS2"
                            , "ADDRESS3"
                            , "ADDRESS4"
                            , "CITY"
                            , "POSTAL_CODE"
                            , "STATE"
                            , "PROVINCE"
                            , "STATUS"
                            , "COUNTY"
                            , "SIC_CODE_TYPE"
                            , "TOTAL_NUM_OF_ORDERS"
                            , "TOTAL_ORDERED_AMOUNT"
                            , "LAST_ORDERED_DATE"
                            , "URL"
                            , "EMAIL_ADDRESS"
                            , "DO_NOT_MAIL_FLAG"
                            , "ANALYSIS_FY"
                            , "FISCAL_YEAREND_MONTH"
                            , "EMPLOYEES_TOTAL"
                            , "CURR_FY_POTENTIAL_REVENUE"
                            , "NEXT_FY_POTENTIAL_REVENUE"
                            , "YEAR_ESTABLISHED"
                            , "GSA_INDICATOR_FLAG"
                            , "MISSION_STATEMENT"
                            , "ORGANIZATION_NAME_PHONETIC"
                            , "PERSON_FIRST_NAME_PHONETIC"
                            , "PERSON_LAST_NAME_PHONETIC"
                            , "LANGUAGE_NAME"
                            , "CATEGORY_CODE"
                            , "REFERENCE_USE_FLAG"
                            , "THIRD_PARTY_FLAG"
                            , "COMPETITOR_FLAG"
                            , "SALUTATION"
                            , "KNOWN_AS2"
                            , "KNOWN_AS3"
                            , "KNOWN_AS4"
                            , "KNOWN_AS5"
                            , "DUNS_NUMBER_C"
                            , "OBJECT_VERSION_NUMBER"
                            , "CREATED_BY_MODULE"
                            , "APPLICATION_ID"
                            , "PRIMARY_PHONE_CONTACT_PT_ID"
                            , "PRIMARY_PHONE_PURPOSE"
                            , "PRIMARY_PHONE_LINE_TYPE"
                            , "PRIMARY_PHONE_COUNTRY_CODE"
                            , "PRIMARY_PHONE_AREA_CODE"
                            , "PRIMARY_PHONE_NUMBER"
                            , "PRIMARY_PHONE_EXTENSION"
                            , "CERTIFICATION_LEVEL"
                            , "CERT_REASON_CODE"
                            , "PREFERRED_CONTACT_METHOD"
                            , "HOME_COUNTRY"
                            , "PERSON_BO_VERSION"
                            , "ORG_BO_VERSION"
                            , "PERSON_CUST_BO_VERSION"
                            , "ORG_CUST_BO_VERSION"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_HZ_PARTIES"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
