

CREATE PROCEDURE [STG].[LOAD_STG_EBS_WSH_NEW_DELIVERIES]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        8/03/2022 5:53:55 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_WSH_NEW_DELIVERIES";
    
    
    Source                                Destination                        
    ----------------------------------    ---------------------------------- 
    LND"."LND_EBS_WSH_NEW_DELIVERIES"    "STG"."STG_EBS_WSH_NEW_DELIVERIES" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-08    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_WSH_NEW_DELIVERIES";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_WSH_NEW_DELIVERIES"
                (
                    "DELIVERY_ID"
                    ,"NAME"
                    ,"PLANNED_FLAG"
                    ,"STATUS_CODE"
                    ,"INITIAL_PICKUP_DATE"
                    ,"INITIAL_PICKUP_LOCATION_ID"
                    ,"ULTIMATE_DROPOFF_LOCATION_ID"
                    ,"ULTIMATE_DROPOFF_DATE"
                    ,"CUSTOMER_ID"
                    ,"INTMED_SHIP_TO_LOCATION_ID"
                    ,"POOLED_SHIP_TO_LOCATION_ID"
                    ,"FREIGHT_TERMS_CODE"
                    ,"FOB_CODE"
                    ,"FOB_LOCATION_ID"
                    ,"WAYBILL"
                    ,"ACCEPTANCE_FLAG"
                    ,"ACCEPTED_BY"
                    ,"ACCEPTED_DATE"
                    ,"ACKNOWLEDGED_BY"
                    ,"CONFIRMED_BY"
                    ,"ASN_DATE_SENT"
                    ,"ASN_STATUS_CODE"
                    ,"ASN_SEQ_NUMBER"
                    ,"REASON_OF_TRANSPORT"
                    ,"DESCRIPTION"
                    ,"GROSS_WEIGHT"
                    ,"NET_WEIGHT"
                    ,"WEIGHT_UOM_CODE"
                    ,"VOLUME"
                    ,"VOLUME_UOM_CODE"
                    ,"ADDITIONAL_SHIPMENT_INFO"
                    ,"PORT_OF_DISCHARGE"
                    ,"BOOKING_NUMBER"
                    ,"COD_AMOUNT"
                    ,"COD_CURRENCY_CODE"
                    ,"SERVICE_CONTRACT"
                    ,"COD_REMIT_TO"
                    ,"COD_CHARGE_PAID_BY"
                    ,"PROBLEM_CONTACT_REFERENCE"
                    ,"BILL_FREIGHT_TO"
                    ,"CARRIED_BY"
                    ,"PORT_OF_LOADING"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"TP_ATTRIBUTE_CATEGORY"
                    ,"TP_ATTRIBUTE1"
                    ,"TP_ATTRIBUTE2"
                    ,"TP_ATTRIBUTE3"
                    ,"TP_ATTRIBUTE4"
                    ,"TP_ATTRIBUTE5"
                    ,"TP_ATTRIBUTE6"
                    ,"TP_ATTRIBUTE7"
                    ,"TP_ATTRIBUTE8"
                    ,"TP_ATTRIBUTE9"
                    ,"TP_ATTRIBUTE10"
                    ,"TP_ATTRIBUTE11"
                    ,"TP_ATTRIBUTE12"
                    ,"TP_ATTRIBUTE13"
                    ,"TP_ATTRIBUTE14"
                    ,"TP_ATTRIBUTE15"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"REQUEST_ID"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"CONFIRM_DATE"
                    ,"SHIP_METHOD_CODE"
                    ,"DOCK_CODE"
                    ,"DELIVERY_TYPE"
                    ,"CARRIER_ID"
                    ,"CURRENCY_CODE"
                    ,"ORGANIZATION_ID"
                    ,"LOADING_SEQUENCE"
                    ,"LOADING_ORDER_FLAG"
                    ,"NUMBER_OF_LPN"
                    ,"BATCH_ID"
                    ,"SOURCE_HEADER_ID"
                    ,"HASH_VALUE"
                    ,"FTZ_NUMBER"
                    ,"ROUTED_EXPORT_TXN"
                    ,"ENTRY_NUMBER"
                    ,"ROUTING_INSTRUCTIONS"
                    ,"IN_BOND_CODE"
                    ,"SHIPPING_MARKS"
                    ,"SERVICE_LEVEL"
                    ,"MODE_OF_TRANSPORT"
                    ,"ASSIGNED_TO_FTE_TRIPS"
                    ,"AUTO_SC_EXCLUDE_FLAG"
                    ,"AUTO_AP_EXCLUDE_FLAG"
                    ,"AP_BATCH_ID"
                    ,"TP_DELIVERY_NUMBER"
                    ,"TP_PLAN_NAME"
                    ,"VENDOR_ID"
                    ,"EARLIEST_PICKUP_DATE"
                    ,"LATEST_PICKUP_DATE"
                    ,"EARLIEST_DROPOFF_DATE"
                    ,"LATEST_DROPOFF_DATE"
                    ,"IGNORE_FOR_PLANNING"
                    ,"PARTY_ID"
                    ,"ROUTING_RESPONSE_ID"
                    ,"RCV_SHIPMENT_HEADER_ID"
                    ,"ASN_SHIPMENT_HEADER_ID"
                    ,"SHIPMENT_DIRECTION"
                    ,"SHIPPING_CONTROL"
                    ,"WV_FROZEN_FLAG"
                    ,"HASH_STRING"
                    ,"ITINERARY_COMPLETE"
                    ,"DELIVERED_DATE"
                    ,"DELIVERY_WF_PROCESS"
                    ,"DEL_WF_INTRANSIT_ATTR"
                    ,"DEL_WF_INTERFACE_ATTR"
                    ,"DEL_WF_CLOSE_ATTR"
                    ,"DELIVERY_SCPOD_WF_PROCESS"
                    ,"TMS_VERSION_NUMBER"
                    ,"TMS_INTERFACE_FLAG"
                    ,"PENDING_ADVICE_FLAG"
                    ,"CLIENT_ID"
                    ,"CONSIGNEE_FLAG"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("DELIVERY_ID" AS float) AS "DELIVERY_ID"
                        ,CAST("NAME" AS varchar(100) ) AS "NAME"
                        ,CAST("PLANNED_FLAG" AS varchar(100) ) AS "PLANNED_FLAG"
                        ,CAST("STATUS_CODE" AS varchar(100) ) AS "STATUS_CODE"
                        ,TRY_CONVERT(datetime2,"INITIAL_PICKUP_DATE",121) AS "INITIAL_PICKUP_DATE"
                        ,CAST("INITIAL_PICKUP_LOCATION_ID" AS float) AS "INITIAL_PICKUP_LOCATION_ID"
                        ,CAST("ULTIMATE_DROPOFF_LOCATION_ID" AS float) AS "ULTIMATE_DROPOFF_LOCATION_ID"
                        ,TRY_CONVERT(datetime2,"ULTIMATE_DROPOFF_DATE",121) AS "ULTIMATE_DROPOFF_DATE"
                        ,CAST("CUSTOMER_ID" AS float) AS "CUSTOMER_ID"
                        ,CAST("INTMED_SHIP_TO_LOCATION_ID" AS float) AS "INTMED_SHIP_TO_LOCATION_ID"
                        ,CAST("POOLED_SHIP_TO_LOCATION_ID" AS float) AS "POOLED_SHIP_TO_LOCATION_ID"
                        ,CAST("FREIGHT_TERMS_CODE" AS varchar(100) ) AS "FREIGHT_TERMS_CODE"
                        ,CAST("FOB_CODE" AS varchar(100) ) AS "FOB_CODE"
                        ,CAST("FOB_LOCATION_ID" AS float) AS "FOB_LOCATION_ID"
                        ,CAST("WAYBILL" AS varchar(100) ) AS "WAYBILL"
                        ,CAST("ACCEPTANCE_FLAG" AS varchar(100) ) AS "ACCEPTANCE_FLAG"
                        ,CAST("ACCEPTED_BY" AS varchar(1000) ) AS "ACCEPTED_BY"
                        ,TRY_CONVERT(datetime2,"ACCEPTED_DATE",121) AS "ACCEPTED_DATE"
                        ,CAST("ACKNOWLEDGED_BY" AS varchar(1000) ) AS "ACKNOWLEDGED_BY"
                        ,CAST("CONFIRMED_BY" AS varchar(1000) ) AS "CONFIRMED_BY"
                        ,TRY_CONVERT(datetime2,"ASN_DATE_SENT",121) AS "ASN_DATE_SENT"
                        ,CAST("ASN_STATUS_CODE" AS varchar(100) ) AS "ASN_STATUS_CODE"
                        ,CAST("ASN_SEQ_NUMBER" AS float) AS "ASN_SEQ_NUMBER"
                        ,CAST("REASON_OF_TRANSPORT" AS varchar(100) ) AS "REASON_OF_TRANSPORT"
                        ,CAST("DESCRIPTION" AS varchar(100) ) AS "DESCRIPTION"
                        ,CAST("GROSS_WEIGHT" AS float) AS "GROSS_WEIGHT"
                        ,CAST("NET_WEIGHT" AS float) AS "NET_WEIGHT"
                        ,CAST("WEIGHT_UOM_CODE" AS varchar(100) ) AS "WEIGHT_UOM_CODE"
                        ,CAST("VOLUME" AS float) AS "VOLUME"
                        ,CAST("VOLUME_UOM_CODE" AS varchar(100) ) AS "VOLUME_UOM_CODE"
                        ,CAST("ADDITIONAL_SHIPMENT_INFO" AS varchar(1000) ) AS "ADDITIONAL_SHIPMENT_INFO"
                        ,CAST("PORT_OF_DISCHARGE" AS varchar(1000) ) AS "PORT_OF_DISCHARGE"
                        ,CAST("BOOKING_NUMBER" AS varchar(100) ) AS "BOOKING_NUMBER"
                        ,CAST("COD_AMOUNT" AS float) AS "COD_AMOUNT"
                        ,CAST("COD_CURRENCY_CODE" AS varchar(100) ) AS "COD_CURRENCY_CODE"
                        ,CAST("SERVICE_CONTRACT" AS varchar(100) ) AS "SERVICE_CONTRACT"
                        ,CAST("COD_REMIT_TO" AS varchar(1000) ) AS "COD_REMIT_TO"
                        ,CAST("COD_CHARGE_PAID_BY" AS varchar(1000) ) AS "COD_CHARGE_PAID_BY"
                        ,CAST("PROBLEM_CONTACT_REFERENCE" AS varchar(1000) ) AS "PROBLEM_CONTACT_REFERENCE"
                        ,CAST("BILL_FREIGHT_TO" AS varchar(8000) ) AS "BILL_FREIGHT_TO"
                        ,CAST("CARRIED_BY" AS varchar(1000) ) AS "CARRIED_BY"
                        ,CAST("PORT_OF_LOADING" AS varchar(1000) ) AS "PORT_OF_LOADING"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(1000) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("TP_ATTRIBUTE_CATEGORY" AS varchar(1000) ) AS "TP_ATTRIBUTE_CATEGORY"
                        ,CAST("TP_ATTRIBUTE1" AS varchar(1000) ) AS "TP_ATTRIBUTE1"
                        ,CAST("TP_ATTRIBUTE2" AS varchar(1000) ) AS "TP_ATTRIBUTE2"
                        ,CAST("TP_ATTRIBUTE3" AS varchar(1000) ) AS "TP_ATTRIBUTE3"
                        ,CAST("TP_ATTRIBUTE4" AS varchar(1000) ) AS "TP_ATTRIBUTE4"
                        ,CAST("TP_ATTRIBUTE5" AS varchar(1000) ) AS "TP_ATTRIBUTE5"
                        ,CAST("TP_ATTRIBUTE6" AS varchar(1000) ) AS "TP_ATTRIBUTE6"
                        ,CAST("TP_ATTRIBUTE7" AS varchar(1000) ) AS "TP_ATTRIBUTE7"
                        ,CAST("TP_ATTRIBUTE8" AS varchar(1000) ) AS "TP_ATTRIBUTE8"
                        ,CAST("TP_ATTRIBUTE9" AS varchar(1000) ) AS "TP_ATTRIBUTE9"
                        ,CAST("TP_ATTRIBUTE10" AS varchar(1000) ) AS "TP_ATTRIBUTE10"
                        ,CAST("TP_ATTRIBUTE11" AS varchar(1000) ) AS "TP_ATTRIBUTE11"
                        ,CAST("TP_ATTRIBUTE12" AS varchar(1000) ) AS "TP_ATTRIBUTE12"
                        ,CAST("TP_ATTRIBUTE13" AS varchar(1000) ) AS "TP_ATTRIBUTE13"
                        ,CAST("TP_ATTRIBUTE14" AS varchar(1000) ) AS "TP_ATTRIBUTE14"
                        ,CAST("TP_ATTRIBUTE15" AS varchar(1000) ) AS "TP_ATTRIBUTE15"
                        ,TRY_CONVERT(datetime2,"CREATION_DATE",121) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,TRY_CONVERT(datetime2,"LAST_UPDATE_DATE",121) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,TRY_CONVERT(datetime2,"PROGRAM_UPDATE_DATE",121) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,TRY_CONVERT(datetime2,"CONFIRM_DATE",121) AS "CONFIRM_DATE"
                        ,CAST("SHIP_METHOD_CODE" AS varchar(100) ) AS "SHIP_METHOD_CODE"
                        ,CAST("DOCK_CODE" AS varchar(100) ) AS "DOCK_CODE"
                        ,CAST("DELIVERY_TYPE" AS varchar(100) ) AS "DELIVERY_TYPE"
                        ,CAST("CARRIER_ID" AS float) AS "CARRIER_ID"
                        ,CAST("CURRENCY_CODE" AS varchar(100) ) AS "CURRENCY_CODE"
                        ,CAST("ORGANIZATION_ID" AS float) AS "ORGANIZATION_ID"
                        ,CAST("LOADING_SEQUENCE" AS float) AS "LOADING_SEQUENCE"
                        ,CAST("LOADING_ORDER_FLAG" AS varchar(100) ) AS "LOADING_ORDER_FLAG"
                        ,CAST("NUMBER_OF_LPN" AS float) AS "NUMBER_OF_LPN"
                        ,CAST("BATCH_ID" AS float) AS "BATCH_ID"
                        ,CAST("SOURCE_HEADER_ID" AS float) AS "SOURCE_HEADER_ID"
                        ,CAST("HASH_VALUE" AS float) AS "HASH_VALUE"
                        ,CAST("FTZ_NUMBER" AS varchar(100) ) AS "FTZ_NUMBER"
                        ,CAST("ROUTED_EXPORT_TXN" AS varchar(100) ) AS "ROUTED_EXPORT_TXN"
                        ,CAST("ENTRY_NUMBER" AS varchar(100) ) AS "ENTRY_NUMBER"
                        ,CAST("ROUTING_INSTRUCTIONS" AS varchar(1000) ) AS "ROUTING_INSTRUCTIONS"
                        ,CAST("IN_BOND_CODE" AS varchar(100) ) AS "IN_BOND_CODE"
                        ,CAST("SHIPPING_MARKS" AS varchar(1000) ) AS "SHIPPING_MARKS"
                        ,CAST("SERVICE_LEVEL" AS varchar(100) ) AS "SERVICE_LEVEL"
                        ,CAST("MODE_OF_TRANSPORT" AS varchar(100) ) AS "MODE_OF_TRANSPORT"
                        ,CAST("ASSIGNED_TO_FTE_TRIPS" AS varchar(100) ) AS "ASSIGNED_TO_FTE_TRIPS"
                        ,CAST("AUTO_SC_EXCLUDE_FLAG" AS varchar(100) ) AS "AUTO_SC_EXCLUDE_FLAG"
                        ,CAST("AUTO_AP_EXCLUDE_FLAG" AS varchar(100) ) AS "AUTO_AP_EXCLUDE_FLAG"
                        ,CAST("AP_BATCH_ID" AS float) AS "AP_BATCH_ID"
                        ,CAST("TP_DELIVERY_NUMBER" AS float) AS "TP_DELIVERY_NUMBER"
                        ,CAST("TP_PLAN_NAME" AS varchar(100) ) AS "TP_PLAN_NAME"
                        ,CAST("VENDOR_ID" AS float) AS "VENDOR_ID"
                        ,TRY_CONVERT(datetime2,"EARLIEST_PICKUP_DATE",121) AS "EARLIEST_PICKUP_DATE"
                        ,TRY_CONVERT(datetime2,"LATEST_PICKUP_DATE",121) AS "LATEST_PICKUP_DATE"
                        ,TRY_CONVERT(datetime2,"EARLIEST_DROPOFF_DATE",121) AS "EARLIEST_DROPOFF_DATE"
                        ,TRY_CONVERT(datetime2,"LATEST_DROPOFF_DATE",121) AS "LATEST_DROPOFF_DATE"
                        ,CAST("IGNORE_FOR_PLANNING" AS varchar(100) ) AS "IGNORE_FOR_PLANNING"
                        ,CAST("PARTY_ID" AS float) AS "PARTY_ID"
                        ,CAST("ROUTING_RESPONSE_ID" AS float) AS "ROUTING_RESPONSE_ID"
                        ,CAST("RCV_SHIPMENT_HEADER_ID" AS float) AS "RCV_SHIPMENT_HEADER_ID"
                        ,CAST("ASN_SHIPMENT_HEADER_ID" AS float) AS "ASN_SHIPMENT_HEADER_ID"
                        ,CAST("SHIPMENT_DIRECTION" AS varchar(100) ) AS "SHIPMENT_DIRECTION"
                        ,CAST("SHIPPING_CONTROL" AS varchar(100) ) AS "SHIPPING_CONTROL"
                        ,CAST("WV_FROZEN_FLAG" AS varchar(100) ) AS "WV_FROZEN_FLAG"
                        ,CAST("HASH_STRING" AS varchar(8000) ) AS "HASH_STRING"
                        ,CAST("ITINERARY_COMPLETE" AS varchar(100) ) AS "ITINERARY_COMPLETE"
                        ,TRY_CONVERT(datetime2,"DELIVERED_DATE",121) AS "DELIVERED_DATE"
                        ,CAST("DELIVERY_WF_PROCESS" AS varchar(100) ) AS "DELIVERY_WF_PROCESS"
                        ,CAST("DEL_WF_INTRANSIT_ATTR" AS varchar(100) ) AS "DEL_WF_INTRANSIT_ATTR"
                        ,CAST("DEL_WF_INTERFACE_ATTR" AS varchar(100) ) AS "DEL_WF_INTERFACE_ATTR"
                        ,CAST("DEL_WF_CLOSE_ATTR" AS varchar(100) ) AS "DEL_WF_CLOSE_ATTR"
                        ,CAST("DELIVERY_SCPOD_WF_PROCESS" AS varchar(100) ) AS "DELIVERY_SCPOD_WF_PROCESS"
                        ,CAST("TMS_VERSION_NUMBER" AS float) AS "TMS_VERSION_NUMBER"
                        ,CAST("TMS_INTERFACE_FLAG" AS varchar(100) ) AS "TMS_INTERFACE_FLAG"
                        ,CAST("PENDING_ADVICE_FLAG" AS varchar(100) ) AS "PENDING_ADVICE_FLAG"
                        ,CAST("CLIENT_ID" AS float) AS "CLIENT_ID"
                        ,CAST("CONSIGNEE_FLAG" AS varchar(100) ) AS "CONSIGNEE_FLAG"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "DELIVERY_ID"
                            , "NAME"
                            , "PLANNED_FLAG"
                            , "STATUS_CODE"
                            , "INITIAL_PICKUP_DATE"
                            , "INITIAL_PICKUP_LOCATION_ID"
                            , "ULTIMATE_DROPOFF_LOCATION_ID"
                            , "ULTIMATE_DROPOFF_DATE"
                            , "CUSTOMER_ID"
                            , "INTMED_SHIP_TO_LOCATION_ID"
                            , "POOLED_SHIP_TO_LOCATION_ID"
                            , "FREIGHT_TERMS_CODE"
                            , "FOB_CODE"
                            , "FOB_LOCATION_ID"
                            , "WAYBILL"
                            , "ACCEPTANCE_FLAG"
                            , "ACCEPTED_BY"
                            , "ACCEPTED_DATE"
                            , "ACKNOWLEDGED_BY"
                            , "CONFIRMED_BY"
                            , "ASN_DATE_SENT"
                            , "ASN_STATUS_CODE"
                            , "ASN_SEQ_NUMBER"
                            , "REASON_OF_TRANSPORT"
                            , "DESCRIPTION"
                            , "GROSS_WEIGHT"
                            , "NET_WEIGHT"
                            , "WEIGHT_UOM_CODE"
                            , "VOLUME"
                            , "VOLUME_UOM_CODE"
                            , "ADDITIONAL_SHIPMENT_INFO"
                            , "PORT_OF_DISCHARGE"
                            , "BOOKING_NUMBER"
                            , "COD_AMOUNT"
                            , "COD_CURRENCY_CODE"
                            , "SERVICE_CONTRACT"
                            , "COD_REMIT_TO"
                            , "COD_CHARGE_PAID_BY"
                            , "PROBLEM_CONTACT_REFERENCE"
                            , "BILL_FREIGHT_TO"
                            , "CARRIED_BY"
                            , "PORT_OF_LOADING"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "TP_ATTRIBUTE_CATEGORY"
                            , "TP_ATTRIBUTE1"
                            , "TP_ATTRIBUTE2"
                            , "TP_ATTRIBUTE3"
                            , "TP_ATTRIBUTE4"
                            , "TP_ATTRIBUTE5"
                            , "TP_ATTRIBUTE6"
                            , "TP_ATTRIBUTE7"
                            , "TP_ATTRIBUTE8"
                            , "TP_ATTRIBUTE9"
                            , "TP_ATTRIBUTE10"
                            , "TP_ATTRIBUTE11"
                            , "TP_ATTRIBUTE12"
                            , "TP_ATTRIBUTE13"
                            , "TP_ATTRIBUTE14"
                            , "TP_ATTRIBUTE15"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "REQUEST_ID"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "CONFIRM_DATE"
                            , "SHIP_METHOD_CODE"
                            , "DOCK_CODE"
                            , "DELIVERY_TYPE"
                            , "CARRIER_ID"
                            , "CURRENCY_CODE"
                            , "ORGANIZATION_ID"
                            , "LOADING_SEQUENCE"
                            , "LOADING_ORDER_FLAG"
                            , "NUMBER_OF_LPN"
                            , "BATCH_ID"
                            , "SOURCE_HEADER_ID"
                            , "HASH_VALUE"
                            , "FTZ_NUMBER"
                            , "ROUTED_EXPORT_TXN"
                            , "ENTRY_NUMBER"
                            , "ROUTING_INSTRUCTIONS"
                            , "IN_BOND_CODE"
                            , "SHIPPING_MARKS"
                            , "SERVICE_LEVEL"
                            , "MODE_OF_TRANSPORT"
                            , "ASSIGNED_TO_FTE_TRIPS"
                            , "AUTO_SC_EXCLUDE_FLAG"
                            , "AUTO_AP_EXCLUDE_FLAG"
                            , "AP_BATCH_ID"
                            , "TP_DELIVERY_NUMBER"
                            , "TP_PLAN_NAME"
                            , "VENDOR_ID"
                            , "EARLIEST_PICKUP_DATE"
                            , "LATEST_PICKUP_DATE"
                            , "EARLIEST_DROPOFF_DATE"
                            , "LATEST_DROPOFF_DATE"
                            , "IGNORE_FOR_PLANNING"
                            , "PARTY_ID"
                            , "ROUTING_RESPONSE_ID"
                            , "RCV_SHIPMENT_HEADER_ID"
                            , "ASN_SHIPMENT_HEADER_ID"
                            , "SHIPMENT_DIRECTION"
                            , "SHIPPING_CONTROL"
                            , "WV_FROZEN_FLAG"
                            , "HASH_STRING"
                            , "ITINERARY_COMPLETE"
                            , "DELIVERED_DATE"
                            , "DELIVERY_WF_PROCESS"
                            , "DEL_WF_INTRANSIT_ATTR"
                            , "DEL_WF_INTERFACE_ATTR"
                            , "DEL_WF_CLOSE_ATTR"
                            , "DELIVERY_SCPOD_WF_PROCESS"
                            , "TMS_VERSION_NUMBER"
                            , "TMS_INTERFACE_FLAG"
                            , "PENDING_ADVICE_FLAG"
                            , "CLIENT_ID"
                            , "CONSIGNEE_FLAG"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_WSH_NEW_DELIVERIES"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
