

CREATE PROCEDURE [STG].[LOAD_STG_EBS_RA_CUSTOMER_TRX_ALL]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        8/03/2022 5:53:40 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_RA_CUSTOMER_TRX_ALL";
    
    
    Source                                 Destination                         
    -----------------------------------    ----------------------------------- 
    LND"."LND_EBS_RA_CUSTOMER_TRX_ALL"    "STG"."STG_EBS_RA_CUSTOMER_TRX_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-08    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_RA_CUSTOMER_TRX_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_RA_CUSTOMER_TRX_ALL"
                (
                    "CUSTOMER_TRX_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"TRX_NUMBER"
                    ,"CUST_TRX_TYPE_ID"
                    ,"TRX_DATE"
                    ,"SET_OF_BOOKS_ID"
                    ,"BILL_TO_CONTACT_ID"
                    ,"BATCH_ID"
                    ,"BATCH_SOURCE_ID"
                    ,"REASON_CODE"
                    ,"SOLD_TO_CUSTOMER_ID"
                    ,"SOLD_TO_CONTACT_ID"
                    ,"SOLD_TO_SITE_USE_ID"
                    ,"BILL_TO_CUSTOMER_ID"
                    ,"BILL_TO_SITE_USE_ID"
                    ,"SHIP_TO_CUSTOMER_ID"
                    ,"SHIP_TO_CONTACT_ID"
                    ,"SHIP_TO_SITE_USE_ID"
                    ,"SHIPMENT_ID"
                    ,"REMIT_TO_ADDRESS_ID"
                    ,"TERM_ID"
                    ,"TERM_DUE_DATE"
                    ,"PREVIOUS_CUSTOMER_TRX_ID"
                    ,"PRIMARY_SALESREP_ID"
                    ,"PRINTING_ORIGINAL_DATE"
                    ,"PRINTING_LAST_PRINTED"
                    ,"PRINTING_OPTION"
                    ,"PRINTING_COUNT"
                    ,"PRINTING_PENDING"
                    ,"PURCHASE_ORDER"
                    ,"PURCHASE_ORDER_REVISION"
                    ,"PURCHASE_ORDER_DATE"
                    ,"CUSTOMER_REFERENCE"
                    ,"CUSTOMER_REFERENCE_DATE"
                    ,"COMMENTS"
                    ,"INTERNAL_NOTES"
                    ,"EXCHANGE_RATE_TYPE"
                    ,"EXCHANGE_DATE"
                    ,"EXCHANGE_RATE"
                    ,"TERRITORY_ID"
                    ,"INVOICE_CURRENCY_CODE"
                    ,"INITIAL_CUSTOMER_TRX_ID"
                    ,"AGREEMENT_ID"
                    ,"END_DATE_COMMITMENT"
                    ,"START_DATE_COMMITMENT"
                    ,"LAST_PRINTED_SEQUENCE_NUM"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ORIG_SYSTEM_BATCH_NAME"
                    ,"POST_REQUEST_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"FINANCE_CHARGES"
                    ,"COMPLETE_FLAG"
                    ,"POSTING_CONTROL_ID"
                    ,"BILL_TO_ADDRESS_ID"
                    ,"RA_POST_LOOP_NUMBER"
                    ,"SHIP_TO_ADDRESS_ID"
                    ,"CREDIT_METHOD_FOR_RULES"
                    ,"CREDIT_METHOD_FOR_INSTALLMENTS"
                    ,"RECEIPT_METHOD_ID"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"RELATED_CUSTOMER_TRX_ID"
                    ,"INVOICING_RULE_ID"
                    ,"SHIP_VIA"
                    ,"SHIP_DATE_ACTUAL"
                    ,"WAYBILL_NUMBER"
                    ,"FOB_POINT"
                    ,"CUSTOMER_BANK_ACCOUNT_ID"
                    ,"INTERFACE_HEADER_ATTRIBUTE1"
                    ,"INTERFACE_HEADER_ATTRIBUTE2"
                    ,"INTERFACE_HEADER_ATTRIBUTE3"
                    ,"INTERFACE_HEADER_ATTRIBUTE4"
                    ,"INTERFACE_HEADER_ATTRIBUTE5"
                    ,"INTERFACE_HEADER_ATTRIBUTE6"
                    ,"INTERFACE_HEADER_ATTRIBUTE7"
                    ,"INTERFACE_HEADER_ATTRIBUTE8"
                    ,"INTERFACE_HEADER_CONTEXT"
                    ,"DEFAULT_USSGL_TRX_CODE_CONTEXT"
                    ,"INTERFACE_HEADER_ATTRIBUTE10"
                    ,"INTERFACE_HEADER_ATTRIBUTE11"
                    ,"INTERFACE_HEADER_ATTRIBUTE12"
                    ,"INTERFACE_HEADER_ATTRIBUTE13"
                    ,"INTERFACE_HEADER_ATTRIBUTE14"
                    ,"INTERFACE_HEADER_ATTRIBUTE15"
                    ,"INTERFACE_HEADER_ATTRIBUTE9"
                    ,"DEFAULT_USSGL_TRANSACTION_CODE"
                    ,"RECURRED_FROM_TRX_NUMBER"
                    ,"STATUS_TRX"
                    ,"DOC_SEQUENCE_ID"
                    ,"DOC_SEQUENCE_VALUE"
                    ,"PAYING_CUSTOMER_ID"
                    ,"PAYING_SITE_USE_ID"
                    ,"RELATED_BATCH_SOURCE_ID"
                    ,"DEFAULT_TAX_EXEMPT_FLAG"
                    ,"CREATED_FROM"
                    ,"ORG_ID"
                    ,"WH_UPDATE_DATE"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"GLOBAL_ATTRIBUTE21"
                    ,"GLOBAL_ATTRIBUTE22"
                    ,"GLOBAL_ATTRIBUTE23"
                    ,"GLOBAL_ATTRIBUTE24"
                    ,"GLOBAL_ATTRIBUTE25"
                    ,"GLOBAL_ATTRIBUTE26"
                    ,"GLOBAL_ATTRIBUTE27"
                    ,"GLOBAL_ATTRIBUTE28"
                    ,"GLOBAL_ATTRIBUTE29"
                    ,"GLOBAL_ATTRIBUTE30"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"EDI_PROCESSED_FLAG"
                    ,"EDI_PROCESSED_STATUS"
                    ,"MRC_EXCHANGE_RATE_TYPE"
                    ,"MRC_EXCHANGE_DATE"
                    ,"MRC_EXCHANGE_RATE"
                    ,"PAYMENT_SERVER_ORDER_NUM"
                    ,"APPROVAL_CODE"
                    ,"ADDRESS_VERIFICATION_CODE"
                    ,"OLD_TRX_NUMBER"
                    ,"BR_AMOUNT"
                    ,"BR_UNPAID_FLAG"
                    ,"BR_ON_HOLD_FLAG"
                    ,"DRAWEE_ID"
                    ,"DRAWEE_CONTACT_ID"
                    ,"DRAWEE_SITE_USE_ID"
                    ,"REMITTANCE_BANK_ACCOUNT_ID"
                    ,"OVERRIDE_REMIT_ACCOUNT_FLAG"
                    ,"DRAWEE_BANK_ACCOUNT_ID"
                    ,"SPECIAL_INSTRUCTIONS"
                    ,"REMITTANCE_BATCH_ID"
                    ,"PREPAYMENT_FLAG"
                    ,"CT_REFERENCE"
                    ,"CONTRACT_ID"
                    ,"BILL_TEMPLATE_ID"
                    ,"REVERSED_CASH_RECEIPT_ID"
                    ,"CC_ERROR_CODE"
                    ,"CC_ERROR_TEXT"
                    ,"CC_ERROR_FLAG"
                    ,"UPGRADE_METHOD"
                    ,"LEGAL_ENTITY_ID"
                    ,"REMIT_BANK_ACCT_USE_ID"
                    ,"PAYMENT_TRXN_EXTENSION_ID"
                    ,"AX_ACCOUNTED_FLAG"
                    ,"APPLICATION_ID"
                    ,"PAYMENT_ATTRIBUTES"
                    ,"BILLING_DATE"
                    ,"INTEREST_HEADER_ID"
                    ,"LATE_CHARGES_ASSESSED"
                    ,"TRAILER_NUMBER"
                    ,"REV_REC_APPLICATION"
                    ,"DOCUMENT_TYPE_ID"
                    ,"DOCUMENT_CREATION_DATE"
                    ,"SRC_INVOICING_RULE_ID"
                    ,"BILLING_EXT_REQUEST"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("CUSTOMER_TRX_ID" AS float) AS "CUSTOMER_TRX_ID"
                        ,TRY_CONVERT(datetime2,"LAST_UPDATE_DATE",121) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,TRY_CONVERT(datetime2,"CREATION_DATE",121) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("TRX_NUMBER" AS varchar(100) ) AS "TRX_NUMBER"
                        ,CAST("CUST_TRX_TYPE_ID" AS float) AS "CUST_TRX_TYPE_ID"
                        ,TRY_CONVERT(datetime2,"TRX_DATE",121) AS "TRX_DATE"
                        ,CAST("SET_OF_BOOKS_ID" AS float) AS "SET_OF_BOOKS_ID"
                        ,CAST("BILL_TO_CONTACT_ID" AS float) AS "BILL_TO_CONTACT_ID"
                        ,CAST("BATCH_ID" AS float) AS "BATCH_ID"
                        ,CAST("BATCH_SOURCE_ID" AS float) AS "BATCH_SOURCE_ID"
                        ,CAST("REASON_CODE" AS varchar(100) ) AS "REASON_CODE"
                        ,CAST("SOLD_TO_CUSTOMER_ID" AS float) AS "SOLD_TO_CUSTOMER_ID"
                        ,CAST("SOLD_TO_CONTACT_ID" AS float) AS "SOLD_TO_CONTACT_ID"
                        ,CAST("SOLD_TO_SITE_USE_ID" AS float) AS "SOLD_TO_SITE_USE_ID"
                        ,CAST("BILL_TO_CUSTOMER_ID" AS float) AS "BILL_TO_CUSTOMER_ID"
                        ,CAST("BILL_TO_SITE_USE_ID" AS float) AS "BILL_TO_SITE_USE_ID"
                        ,CAST("SHIP_TO_CUSTOMER_ID" AS float) AS "SHIP_TO_CUSTOMER_ID"
                        ,CAST("SHIP_TO_CONTACT_ID" AS float) AS "SHIP_TO_CONTACT_ID"
                        ,CAST("SHIP_TO_SITE_USE_ID" AS float) AS "SHIP_TO_SITE_USE_ID"
                        ,CAST("SHIPMENT_ID" AS float) AS "SHIPMENT_ID"
                        ,CAST("REMIT_TO_ADDRESS_ID" AS float) AS "REMIT_TO_ADDRESS_ID"
                        ,CAST("TERM_ID" AS float) AS "TERM_ID"
                        ,TRY_CONVERT(datetime2,"TERM_DUE_DATE",121) AS "TERM_DUE_DATE"
                        ,CAST("PREVIOUS_CUSTOMER_TRX_ID" AS float) AS "PREVIOUS_CUSTOMER_TRX_ID"
                        ,CAST("PRIMARY_SALESREP_ID" AS float) AS "PRIMARY_SALESREP_ID"
                        ,TRY_CONVERT(datetime2,"PRINTING_ORIGINAL_DATE",121) AS "PRINTING_ORIGINAL_DATE"
                        ,TRY_CONVERT(datetime2,"PRINTING_LAST_PRINTED",121) AS "PRINTING_LAST_PRINTED"
                        ,CAST("PRINTING_OPTION" AS varchar(100) ) AS "PRINTING_OPTION"
                        ,CAST("PRINTING_COUNT" AS float) AS "PRINTING_COUNT"
                        ,CAST("PRINTING_PENDING" AS varchar(100) ) AS "PRINTING_PENDING"
                        ,CAST("PURCHASE_ORDER" AS varchar(1000) ) AS "PURCHASE_ORDER"
                        ,CAST("PURCHASE_ORDER_REVISION" AS varchar(1000) ) AS "PURCHASE_ORDER_REVISION"
                        ,TRY_CONVERT(datetime2,"PURCHASE_ORDER_DATE",121) AS "PURCHASE_ORDER_DATE"
                        ,CAST("CUSTOMER_REFERENCE" AS varchar(100) ) AS "CUSTOMER_REFERENCE"
                        ,TRY_CONVERT(datetime2,"CUSTOMER_REFERENCE_DATE",121) AS "CUSTOMER_REFERENCE_DATE"
                        ,CAST("COMMENTS" AS varchar(8000) ) AS "COMMENTS"
                        ,CAST("INTERNAL_NOTES" AS varchar(1000) ) AS "INTERNAL_NOTES"
                        ,CAST("EXCHANGE_RATE_TYPE" AS varchar(100) ) AS "EXCHANGE_RATE_TYPE"
                        ,TRY_CONVERT(datetime2,"EXCHANGE_DATE",121) AS "EXCHANGE_DATE"
                        ,CAST("EXCHANGE_RATE" AS float) AS "EXCHANGE_RATE"
                        ,CAST("TERRITORY_ID" AS float) AS "TERRITORY_ID"
                        ,CAST("INVOICE_CURRENCY_CODE" AS varchar(100) ) AS "INVOICE_CURRENCY_CODE"
                        ,CAST("INITIAL_CUSTOMER_TRX_ID" AS float) AS "INITIAL_CUSTOMER_TRX_ID"
                        ,CAST("AGREEMENT_ID" AS float) AS "AGREEMENT_ID"
                        ,TRY_CONVERT(datetime2,"END_DATE_COMMITMENT",121) AS "END_DATE_COMMITMENT"
                        ,TRY_CONVERT(datetime2,"START_DATE_COMMITMENT",121) AS "START_DATE_COMMITMENT"
                        ,CAST("LAST_PRINTED_SEQUENCE_NUM" AS float) AS "LAST_PRINTED_SEQUENCE_NUM"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ORIG_SYSTEM_BATCH_NAME" AS varchar(100) ) AS "ORIG_SYSTEM_BATCH_NAME"
                        ,CAST("POST_REQUEST_ID" AS float) AS "POST_REQUEST_ID"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,TRY_CONVERT(datetime2,"PROGRAM_UPDATE_DATE",121) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("FINANCE_CHARGES" AS varchar(100) ) AS "FINANCE_CHARGES"
                        ,CAST("COMPLETE_FLAG" AS varchar(100) ) AS "COMPLETE_FLAG"
                        ,CAST("POSTING_CONTROL_ID" AS float) AS "POSTING_CONTROL_ID"
                        ,CAST("BILL_TO_ADDRESS_ID" AS float) AS "BILL_TO_ADDRESS_ID"
                        ,CAST("RA_POST_LOOP_NUMBER" AS float) AS "RA_POST_LOOP_NUMBER"
                        ,CAST("SHIP_TO_ADDRESS_ID" AS float) AS "SHIP_TO_ADDRESS_ID"
                        ,CAST("CREDIT_METHOD_FOR_RULES" AS varchar(100) ) AS "CREDIT_METHOD_FOR_RULES"
                        ,CAST("CREDIT_METHOD_FOR_INSTALLMENTS" AS varchar(100) ) AS "CREDIT_METHOD_FOR_INSTALLMENTS"
                        ,CAST("RECEIPT_METHOD_ID" AS float) AS "RECEIPT_METHOD_ID"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("RELATED_CUSTOMER_TRX_ID" AS float) AS "RELATED_CUSTOMER_TRX_ID"
                        ,CAST("INVOICING_RULE_ID" AS float) AS "INVOICING_RULE_ID"
                        ,CAST("SHIP_VIA" AS varchar(100) ) AS "SHIP_VIA"
                        ,TRY_CONVERT(datetime2,"SHIP_DATE_ACTUAL",121) AS "SHIP_DATE_ACTUAL"
                        ,CAST("WAYBILL_NUMBER" AS varchar(1000) ) AS "WAYBILL_NUMBER"
                        ,CAST("FOB_POINT" AS varchar(100) ) AS "FOB_POINT"
                        ,CAST("CUSTOMER_BANK_ACCOUNT_ID" AS float) AS "CUSTOMER_BANK_ACCOUNT_ID"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE1" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE1"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE2" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE2"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE3" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE3"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE4" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE4"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE5" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE5"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE6" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE6"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE7" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE7"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE8" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE8"
                        ,CAST("INTERFACE_HEADER_CONTEXT" AS varchar(100) ) AS "INTERFACE_HEADER_CONTEXT"
                        ,CAST("DEFAULT_USSGL_TRX_CODE_CONTEXT" AS varchar(100) ) AS "DEFAULT_USSGL_TRX_CODE_CONTEXT"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE10" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE10"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE11" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE11"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE12" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE12"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE13" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE13"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE14" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE14"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE15" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE15"
                        ,CAST("INTERFACE_HEADER_ATTRIBUTE9" AS varchar(1000) ) AS "INTERFACE_HEADER_ATTRIBUTE9"
                        ,CAST("DEFAULT_USSGL_TRANSACTION_CODE" AS varchar(100) ) AS "DEFAULT_USSGL_TRANSACTION_CODE"
                        ,CAST("RECURRED_FROM_TRX_NUMBER" AS varchar(100) ) AS "RECURRED_FROM_TRX_NUMBER"
                        ,CAST("STATUS_TRX" AS varchar(100) ) AS "STATUS_TRX"
                        ,CAST("DOC_SEQUENCE_ID" AS float) AS "DOC_SEQUENCE_ID"
                        ,CAST("DOC_SEQUENCE_VALUE" AS float) AS "DOC_SEQUENCE_VALUE"
                        ,CAST("PAYING_CUSTOMER_ID" AS float) AS "PAYING_CUSTOMER_ID"
                        ,CAST("PAYING_SITE_USE_ID" AS float) AS "PAYING_SITE_USE_ID"
                        ,CAST("RELATED_BATCH_SOURCE_ID" AS float) AS "RELATED_BATCH_SOURCE_ID"
                        ,CAST("DEFAULT_TAX_EXEMPT_FLAG" AS varchar(100) ) AS "DEFAULT_TAX_EXEMPT_FLAG"
                        ,CAST("CREATED_FROM" AS varchar(100) ) AS "CREATED_FROM"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,TRY_CONVERT(datetime2,"WH_UPDATE_DATE",121) AS "WH_UPDATE_DATE"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("GLOBAL_ATTRIBUTE21" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE21"
                        ,CAST("GLOBAL_ATTRIBUTE22" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE22"
                        ,CAST("GLOBAL_ATTRIBUTE23" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE23"
                        ,CAST("GLOBAL_ATTRIBUTE24" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE24"
                        ,CAST("GLOBAL_ATTRIBUTE25" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE25"
                        ,CAST("GLOBAL_ATTRIBUTE26" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE26"
                        ,CAST("GLOBAL_ATTRIBUTE27" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE27"
                        ,CAST("GLOBAL_ATTRIBUTE28" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE28"
                        ,CAST("GLOBAL_ATTRIBUTE29" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE29"
                        ,CAST("GLOBAL_ATTRIBUTE30" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE30"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("EDI_PROCESSED_FLAG" AS varchar(100) ) AS "EDI_PROCESSED_FLAG"
                        ,CAST("EDI_PROCESSED_STATUS" AS varchar(100) ) AS "EDI_PROCESSED_STATUS"
                        ,CAST("MRC_EXCHANGE_RATE_TYPE" AS varchar(8000) ) AS "MRC_EXCHANGE_RATE_TYPE"
                        ,CAST("MRC_EXCHANGE_DATE" AS varchar(8000) ) AS "MRC_EXCHANGE_DATE"
                        ,CAST("MRC_EXCHANGE_RATE" AS varchar(8000) ) AS "MRC_EXCHANGE_RATE"
                        ,CAST("PAYMENT_SERVER_ORDER_NUM" AS varchar(1000) ) AS "PAYMENT_SERVER_ORDER_NUM"
                        ,CAST("APPROVAL_CODE" AS varchar(1000) ) AS "APPROVAL_CODE"
                        ,CAST("ADDRESS_VERIFICATION_CODE" AS varchar(1000) ) AS "ADDRESS_VERIFICATION_CODE"
                        ,CAST("OLD_TRX_NUMBER" AS varchar(100) ) AS "OLD_TRX_NUMBER"
                        ,CAST("BR_AMOUNT" AS float) AS "BR_AMOUNT"
                        ,CAST("BR_UNPAID_FLAG" AS varchar(100) ) AS "BR_UNPAID_FLAG"
                        ,CAST("BR_ON_HOLD_FLAG" AS varchar(100) ) AS "BR_ON_HOLD_FLAG"
                        ,CAST("DRAWEE_ID" AS float) AS "DRAWEE_ID"
                        ,CAST("DRAWEE_CONTACT_ID" AS float) AS "DRAWEE_CONTACT_ID"
                        ,CAST("DRAWEE_SITE_USE_ID" AS float) AS "DRAWEE_SITE_USE_ID"
                        ,CAST("REMITTANCE_BANK_ACCOUNT_ID" AS float) AS "REMITTANCE_BANK_ACCOUNT_ID"
                        ,CAST("OVERRIDE_REMIT_ACCOUNT_FLAG" AS varchar(100) ) AS "OVERRIDE_REMIT_ACCOUNT_FLAG"
                        ,CAST("DRAWEE_BANK_ACCOUNT_ID" AS float) AS "DRAWEE_BANK_ACCOUNT_ID"
                        ,CAST("SPECIAL_INSTRUCTIONS" AS varchar(1000) ) AS "SPECIAL_INSTRUCTIONS"
                        ,CAST("REMITTANCE_BATCH_ID" AS float) AS "REMITTANCE_BATCH_ID"
                        ,CAST("PREPAYMENT_FLAG" AS varchar(100) ) AS "PREPAYMENT_FLAG"
                        ,CAST("CT_REFERENCE" AS varchar(1000) ) AS "CT_REFERENCE"
                        ,CAST("CONTRACT_ID" AS float) AS "CONTRACT_ID"
                        ,CAST("BILL_TEMPLATE_ID" AS float) AS "BILL_TEMPLATE_ID"
                        ,CAST("REVERSED_CASH_RECEIPT_ID" AS float) AS "REVERSED_CASH_RECEIPT_ID"
                        ,CAST("CC_ERROR_CODE" AS varchar(1000) ) AS "CC_ERROR_CODE"
                        ,CAST("CC_ERROR_TEXT" AS varchar(1000) ) AS "CC_ERROR_TEXT"
                        ,CAST("CC_ERROR_FLAG" AS varchar(100) ) AS "CC_ERROR_FLAG"
                        ,CAST("UPGRADE_METHOD" AS varchar(100) ) AS "UPGRADE_METHOD"
                        ,CAST("LEGAL_ENTITY_ID" AS float) AS "LEGAL_ENTITY_ID"
                        ,CAST("REMIT_BANK_ACCT_USE_ID" AS float) AS "REMIT_BANK_ACCT_USE_ID"
                        ,CAST("PAYMENT_TRXN_EXTENSION_ID" AS float) AS "PAYMENT_TRXN_EXTENSION_ID"
                        ,CAST("AX_ACCOUNTED_FLAG" AS varchar(100) ) AS "AX_ACCOUNTED_FLAG"
                        ,CAST("APPLICATION_ID" AS float) AS "APPLICATION_ID"
                        ,CAST("PAYMENT_ATTRIBUTES" AS varchar(8000) ) AS "PAYMENT_ATTRIBUTES"
                        ,TRY_CONVERT(datetime2,"BILLING_DATE",121) AS "BILLING_DATE"
                        ,CAST("INTEREST_HEADER_ID" AS float) AS "INTEREST_HEADER_ID"
                        ,CAST("LATE_CHARGES_ASSESSED" AS varchar(100) ) AS "LATE_CHARGES_ASSESSED"
                        ,CAST("TRAILER_NUMBER" AS varchar(1000) ) AS "TRAILER_NUMBER"
                        ,CAST("REV_REC_APPLICATION" AS varchar(100) ) AS "REV_REC_APPLICATION"
                        ,CAST("DOCUMENT_TYPE_ID" AS float) AS "DOCUMENT_TYPE_ID"
                        ,TRY_CONVERT(datetime2,"DOCUMENT_CREATION_DATE",121) AS "DOCUMENT_CREATION_DATE"
                        ,CAST("SRC_INVOICING_RULE_ID" AS float) AS "SRC_INVOICING_RULE_ID"
                        ,CAST("BILLING_EXT_REQUEST" AS float) AS "BILLING_EXT_REQUEST"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "CUSTOMER_TRX_ID"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "TRX_NUMBER"
                            , "CUST_TRX_TYPE_ID"
                            , "TRX_DATE"
                            , "SET_OF_BOOKS_ID"
                            , "BILL_TO_CONTACT_ID"
                            , "BATCH_ID"
                            , "BATCH_SOURCE_ID"
                            , "REASON_CODE"
                            , "SOLD_TO_CUSTOMER_ID"
                            , "SOLD_TO_CONTACT_ID"
                            , "SOLD_TO_SITE_USE_ID"
                            , "BILL_TO_CUSTOMER_ID"
                            , "BILL_TO_SITE_USE_ID"
                            , "SHIP_TO_CUSTOMER_ID"
                            , "SHIP_TO_CONTACT_ID"
                            , "SHIP_TO_SITE_USE_ID"
                            , "SHIPMENT_ID"
                            , "REMIT_TO_ADDRESS_ID"
                            , "TERM_ID"
                            , "TERM_DUE_DATE"
                            , "PREVIOUS_CUSTOMER_TRX_ID"
                            , "PRIMARY_SALESREP_ID"
                            , "PRINTING_ORIGINAL_DATE"
                            , "PRINTING_LAST_PRINTED"
                            , "PRINTING_OPTION"
                            , "PRINTING_COUNT"
                            , "PRINTING_PENDING"
                            , "PURCHASE_ORDER"
                            , "PURCHASE_ORDER_REVISION"
                            , "PURCHASE_ORDER_DATE"
                            , "CUSTOMER_REFERENCE"
                            , "CUSTOMER_REFERENCE_DATE"
                            , "COMMENTS"
                            , "INTERNAL_NOTES"
                            , "EXCHANGE_RATE_TYPE"
                            , "EXCHANGE_DATE"
                            , "EXCHANGE_RATE"
                            , "TERRITORY_ID"
                            , "INVOICE_CURRENCY_CODE"
                            , "INITIAL_CUSTOMER_TRX_ID"
                            , "AGREEMENT_ID"
                            , "END_DATE_COMMITMENT"
                            , "START_DATE_COMMITMENT"
                            , "LAST_PRINTED_SEQUENCE_NUM"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ORIG_SYSTEM_BATCH_NAME"
                            , "POST_REQUEST_ID"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "FINANCE_CHARGES"
                            , "COMPLETE_FLAG"
                            , "POSTING_CONTROL_ID"
                            , "BILL_TO_ADDRESS_ID"
                            , "RA_POST_LOOP_NUMBER"
                            , "SHIP_TO_ADDRESS_ID"
                            , "CREDIT_METHOD_FOR_RULES"
                            , "CREDIT_METHOD_FOR_INSTALLMENTS"
                            , "RECEIPT_METHOD_ID"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "RELATED_CUSTOMER_TRX_ID"
                            , "INVOICING_RULE_ID"
                            , "SHIP_VIA"
                            , "SHIP_DATE_ACTUAL"
                            , "WAYBILL_NUMBER"
                            , "FOB_POINT"
                            , "CUSTOMER_BANK_ACCOUNT_ID"
                            , "INTERFACE_HEADER_ATTRIBUTE1"
                            , "INTERFACE_HEADER_ATTRIBUTE2"
                            , "INTERFACE_HEADER_ATTRIBUTE3"
                            , "INTERFACE_HEADER_ATTRIBUTE4"
                            , "INTERFACE_HEADER_ATTRIBUTE5"
                            , "INTERFACE_HEADER_ATTRIBUTE6"
                            , "INTERFACE_HEADER_ATTRIBUTE7"
                            , "INTERFACE_HEADER_ATTRIBUTE8"
                            , "INTERFACE_HEADER_CONTEXT"
                            , "DEFAULT_USSGL_TRX_CODE_CONTEXT"
                            , "INTERFACE_HEADER_ATTRIBUTE10"
                            , "INTERFACE_HEADER_ATTRIBUTE11"
                            , "INTERFACE_HEADER_ATTRIBUTE12"
                            , "INTERFACE_HEADER_ATTRIBUTE13"
                            , "INTERFACE_HEADER_ATTRIBUTE14"
                            , "INTERFACE_HEADER_ATTRIBUTE15"
                            , "INTERFACE_HEADER_ATTRIBUTE9"
                            , "DEFAULT_USSGL_TRANSACTION_CODE"
                            , "RECURRED_FROM_TRX_NUMBER"
                            , "STATUS_TRX"
                            , "DOC_SEQUENCE_ID"
                            , "DOC_SEQUENCE_VALUE"
                            , "PAYING_CUSTOMER_ID"
                            , "PAYING_SITE_USE_ID"
                            , "RELATED_BATCH_SOURCE_ID"
                            , "DEFAULT_TAX_EXEMPT_FLAG"
                            , "CREATED_FROM"
                            , "ORG_ID"
                            , "WH_UPDATE_DATE"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "GLOBAL_ATTRIBUTE21"
                            , "GLOBAL_ATTRIBUTE22"
                            , "GLOBAL_ATTRIBUTE23"
                            , "GLOBAL_ATTRIBUTE24"
                            , "GLOBAL_ATTRIBUTE25"
                            , "GLOBAL_ATTRIBUTE26"
                            , "GLOBAL_ATTRIBUTE27"
                            , "GLOBAL_ATTRIBUTE28"
                            , "GLOBAL_ATTRIBUTE29"
                            , "GLOBAL_ATTRIBUTE30"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "EDI_PROCESSED_FLAG"
                            , "EDI_PROCESSED_STATUS"
                            , "MRC_EXCHANGE_RATE_TYPE"
                            , "MRC_EXCHANGE_DATE"
                            , "MRC_EXCHANGE_RATE"
                            , "PAYMENT_SERVER_ORDER_NUM"
                            , "APPROVAL_CODE"
                            , "ADDRESS_VERIFICATION_CODE"
                            , "OLD_TRX_NUMBER"
                            , "BR_AMOUNT"
                            , "BR_UNPAID_FLAG"
                            , "BR_ON_HOLD_FLAG"
                            , "DRAWEE_ID"
                            , "DRAWEE_CONTACT_ID"
                            , "DRAWEE_SITE_USE_ID"
                            , "REMITTANCE_BANK_ACCOUNT_ID"
                            , "OVERRIDE_REMIT_ACCOUNT_FLAG"
                            , "DRAWEE_BANK_ACCOUNT_ID"
                            , "SPECIAL_INSTRUCTIONS"
                            , "REMITTANCE_BATCH_ID"
                            , "PREPAYMENT_FLAG"
                            , "CT_REFERENCE"
                            , "CONTRACT_ID"
                            , "BILL_TEMPLATE_ID"
                            , "REVERSED_CASH_RECEIPT_ID"
                            , "CC_ERROR_CODE"
                            , "CC_ERROR_TEXT"
                            , "CC_ERROR_FLAG"
                            , "UPGRADE_METHOD"
                            , "LEGAL_ENTITY_ID"
                            , "REMIT_BANK_ACCT_USE_ID"
                            , "PAYMENT_TRXN_EXTENSION_ID"
                            , "AX_ACCOUNTED_FLAG"
                            , "APPLICATION_ID"
                            , "PAYMENT_ATTRIBUTES"
                            , "BILLING_DATE"
                            , "INTEREST_HEADER_ID"
                            , "LATE_CHARGES_ASSESSED"
                            , "TRAILER_NUMBER"
                            , "REV_REC_APPLICATION"
                            , "DOCUMENT_TYPE_ID"
                            , "DOCUMENT_CREATION_DATE"
                            , "SRC_INVOICING_RULE_ID"
                            , "BILLING_EXT_REQUEST"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_RA_CUSTOMER_TRX_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
