

CREATE PROCEDURE [STG].[LOAD_STG_EBS_RA_BATCH_SOURCES_ALL]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        8/03/2022 5:53:38 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_RA_BATCH_SOURCES_ALL";
    
    
    Source                                  Destination                          
    ------------------------------------    ------------------------------------ 
    LND"."LND_EBS_RA_BATCH_SOURCES_ALL"    "STG"."STG_EBS_RA_BATCH_SOURCES_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-08    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_RA_BATCH_SOURCES_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_RA_BATCH_SOURCES_ALL"
                (
                    "BATCH_SOURCE_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"NAME"
                    ,"ORG_ID"
                    ,"DESCRIPTION"
                    ,"STATUS"
                    ,"LAST_BATCH_NUM"
                    ,"DEFAULT_INV_TRX_TYPE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ACCOUNTING_FLEXFIELD_RULE"
                    ,"ACCOUNTING_RULE_RULE"
                    ,"AGREEMENT_RULE"
                    ,"AUTO_BATCH_NUMBERING_FLAG"
                    ,"AUTO_TRX_NUMBERING_FLAG"
                    ,"BATCH_SOURCE_TYPE"
                    ,"BILL_ADDRESS_RULE"
                    ,"BILL_CONTACT_RULE"
                    ,"BILL_CUSTOMER_RULE"
                    ,"CREATE_CLEARING_FLAG"
                    ,"CUST_TRX_TYPE_RULE"
                    ,"DERIVE_DATE_FLAG"
                    ,"END_DATE"
                    ,"FOB_POINT_RULE"
                    ,"GL_DATE_PERIOD_RULE"
                    ,"INVALID_LINES_RULE"
                    ,"INVALID_TAX_RATE_RULE"
                    ,"INVENTORY_ITEM_RULE"
                    ,"INVOICING_RULE_RULE"
                    ,"MEMO_REASON_RULE"
                    ,"REV_ACC_ALLOCATION_RULE"
                    ,"SALESPERSON_RULE"
                    ,"SALES_CREDIT_RULE"
                    ,"SALES_CREDIT_TYPE_RULE"
                    ,"SALES_TERRITORY_RULE"
                    ,"SHIP_ADDRESS_RULE"
                    ,"SHIP_CONTACT_RULE"
                    ,"SHIP_CUSTOMER_RULE"
                    ,"SHIP_VIA_RULE"
                    ,"SOLD_CUSTOMER_RULE"
                    ,"START_DATE"
                    ,"TERM_RULE"
                    ,"UNIT_OF_MEASURE_RULE"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"CUSTOMER_BANK_ACCOUNT_RULE"
                    ,"MEMO_LINE_RULE"
                    ,"RECEIPT_METHOD_RULE"
                    ,"RELATED_DOCUMENT_RULE"
                    ,"ALLOW_SALES_CREDIT_FLAG"
                    ,"GROUPING_RULE_ID"
                    ,"CREDIT_MEMO_BATCH_SOURCE_ID"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"COPY_DOC_NUMBER_FLAG"
                    ,"DEFAULT_REFERENCE"
                    ,"COPY_INV_TIDFF_TO_CM_FLAG"
                    ,"RECEIPT_HANDLING_OPTION"
                    ,"ALLOW_DUPLICATE_TRX_NUM_FLAG"
                    ,"LEGAL_ENTITY_ID"
                    ,"GEN_LINE_LEVEL_BAL_FLAG"
                    ,"PAYMENT_DET_DEF_HIERARCHY"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("BATCH_SOURCE_ID" AS float) AS "BATCH_SOURCE_ID"
                        ,TRY_CONVERT(datetime2,"LAST_UPDATE_DATE",121) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,TRY_CONVERT(datetime2,"CREATION_DATE",121) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("NAME" AS varchar(1000) ) AS "NAME"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,CAST("DESCRIPTION" AS varchar(1000) ) AS "DESCRIPTION"
                        ,CAST("STATUS" AS varchar(100) ) AS "STATUS"
                        ,CAST("LAST_BATCH_NUM" AS float) AS "LAST_BATCH_NUM"
                        ,CAST("DEFAULT_INV_TRX_TYPE" AS float) AS "DEFAULT_INV_TRX_TYPE"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ACCOUNTING_FLEXFIELD_RULE" AS varchar(100) ) AS "ACCOUNTING_FLEXFIELD_RULE"
                        ,CAST("ACCOUNTING_RULE_RULE" AS varchar(100) ) AS "ACCOUNTING_RULE_RULE"
                        ,CAST("AGREEMENT_RULE" AS varchar(100) ) AS "AGREEMENT_RULE"
                        ,CAST("AUTO_BATCH_NUMBERING_FLAG" AS varchar(100) ) AS "AUTO_BATCH_NUMBERING_FLAG"
                        ,CAST("AUTO_TRX_NUMBERING_FLAG" AS varchar(100) ) AS "AUTO_TRX_NUMBERING_FLAG"
                        ,CAST("BATCH_SOURCE_TYPE" AS varchar(100) ) AS "BATCH_SOURCE_TYPE"
                        ,CAST("BILL_ADDRESS_RULE" AS varchar(100) ) AS "BILL_ADDRESS_RULE"
                        ,CAST("BILL_CONTACT_RULE" AS varchar(100) ) AS "BILL_CONTACT_RULE"
                        ,CAST("BILL_CUSTOMER_RULE" AS varchar(100) ) AS "BILL_CUSTOMER_RULE"
                        ,CAST("CREATE_CLEARING_FLAG" AS varchar(100) ) AS "CREATE_CLEARING_FLAG"
                        ,CAST("CUST_TRX_TYPE_RULE" AS varchar(100) ) AS "CUST_TRX_TYPE_RULE"
                        ,CAST("DERIVE_DATE_FLAG" AS varchar(100) ) AS "DERIVE_DATE_FLAG"
                        ,TRY_CONVERT(datetime2,"END_DATE",121) AS "END_DATE"
                        ,CAST("FOB_POINT_RULE" AS varchar(100) ) AS "FOB_POINT_RULE"
                        ,CAST("GL_DATE_PERIOD_RULE" AS varchar(100) ) AS "GL_DATE_PERIOD_RULE"
                        ,CAST("INVALID_LINES_RULE" AS varchar(100) ) AS "INVALID_LINES_RULE"
                        ,CAST("INVALID_TAX_RATE_RULE" AS varchar(100) ) AS "INVALID_TAX_RATE_RULE"
                        ,CAST("INVENTORY_ITEM_RULE" AS varchar(100) ) AS "INVENTORY_ITEM_RULE"
                        ,CAST("INVOICING_RULE_RULE" AS varchar(100) ) AS "INVOICING_RULE_RULE"
                        ,CAST("MEMO_REASON_RULE" AS varchar(100) ) AS "MEMO_REASON_RULE"
                        ,CAST("REV_ACC_ALLOCATION_RULE" AS varchar(100) ) AS "REV_ACC_ALLOCATION_RULE"
                        ,CAST("SALESPERSON_RULE" AS varchar(100) ) AS "SALESPERSON_RULE"
                        ,CAST("SALES_CREDIT_RULE" AS varchar(100) ) AS "SALES_CREDIT_RULE"
                        ,CAST("SALES_CREDIT_TYPE_RULE" AS varchar(100) ) AS "SALES_CREDIT_TYPE_RULE"
                        ,CAST("SALES_TERRITORY_RULE" AS varchar(100) ) AS "SALES_TERRITORY_RULE"
                        ,CAST("SHIP_ADDRESS_RULE" AS varchar(100) ) AS "SHIP_ADDRESS_RULE"
                        ,CAST("SHIP_CONTACT_RULE" AS varchar(100) ) AS "SHIP_CONTACT_RULE"
                        ,CAST("SHIP_CUSTOMER_RULE" AS varchar(100) ) AS "SHIP_CUSTOMER_RULE"
                        ,CAST("SHIP_VIA_RULE" AS varchar(100) ) AS "SHIP_VIA_RULE"
                        ,CAST("SOLD_CUSTOMER_RULE" AS varchar(100) ) AS "SOLD_CUSTOMER_RULE"
                        ,TRY_CONVERT(datetime2,"START_DATE",121) AS "START_DATE"
                        ,CAST("TERM_RULE" AS varchar(100) ) AS "TERM_RULE"
                        ,CAST("UNIT_OF_MEASURE_RULE" AS varchar(100) ) AS "UNIT_OF_MEASURE_RULE"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("CUSTOMER_BANK_ACCOUNT_RULE" AS varchar(100) ) AS "CUSTOMER_BANK_ACCOUNT_RULE"
                        ,CAST("MEMO_LINE_RULE" AS varchar(100) ) AS "MEMO_LINE_RULE"
                        ,CAST("RECEIPT_METHOD_RULE" AS varchar(100) ) AS "RECEIPT_METHOD_RULE"
                        ,CAST("RELATED_DOCUMENT_RULE" AS varchar(100) ) AS "RELATED_DOCUMENT_RULE"
                        ,CAST("ALLOW_SALES_CREDIT_FLAG" AS varchar(100) ) AS "ALLOW_SALES_CREDIT_FLAG"
                        ,CAST("GROUPING_RULE_ID" AS float) AS "GROUPING_RULE_ID"
                        ,CAST("CREDIT_MEMO_BATCH_SOURCE_ID" AS float) AS "CREDIT_MEMO_BATCH_SOURCE_ID"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("COPY_DOC_NUMBER_FLAG" AS varchar(100) ) AS "COPY_DOC_NUMBER_FLAG"
                        ,CAST("DEFAULT_REFERENCE" AS varchar(1000) ) AS "DEFAULT_REFERENCE"
                        ,CAST("COPY_INV_TIDFF_TO_CM_FLAG" AS varchar(100) ) AS "COPY_INV_TIDFF_TO_CM_FLAG"
                        ,CAST("RECEIPT_HANDLING_OPTION" AS varchar(100) ) AS "RECEIPT_HANDLING_OPTION"
                        ,CAST("ALLOW_DUPLICATE_TRX_NUM_FLAG" AS varchar(100) ) AS "ALLOW_DUPLICATE_TRX_NUM_FLAG"
                        ,CAST("LEGAL_ENTITY_ID" AS float) AS "LEGAL_ENTITY_ID"
                        ,CAST("GEN_LINE_LEVEL_BAL_FLAG" AS varchar(100) ) AS "GEN_LINE_LEVEL_BAL_FLAG"
                        ,CAST("PAYMENT_DET_DEF_HIERARCHY" AS varchar(100) ) AS "PAYMENT_DET_DEF_HIERARCHY"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "BATCH_SOURCE_ID"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "NAME"
                            , "ORG_ID"
                            , "DESCRIPTION"
                            , "STATUS"
                            , "LAST_BATCH_NUM"
                            , "DEFAULT_INV_TRX_TYPE"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ACCOUNTING_FLEXFIELD_RULE"
                            , "ACCOUNTING_RULE_RULE"
                            , "AGREEMENT_RULE"
                            , "AUTO_BATCH_NUMBERING_FLAG"
                            , "AUTO_TRX_NUMBERING_FLAG"
                            , "BATCH_SOURCE_TYPE"
                            , "BILL_ADDRESS_RULE"
                            , "BILL_CONTACT_RULE"
                            , "BILL_CUSTOMER_RULE"
                            , "CREATE_CLEARING_FLAG"
                            , "CUST_TRX_TYPE_RULE"
                            , "DERIVE_DATE_FLAG"
                            , "END_DATE"
                            , "FOB_POINT_RULE"
                            , "GL_DATE_PERIOD_RULE"
                            , "INVALID_LINES_RULE"
                            , "INVALID_TAX_RATE_RULE"
                            , "INVENTORY_ITEM_RULE"
                            , "INVOICING_RULE_RULE"
                            , "MEMO_REASON_RULE"
                            , "REV_ACC_ALLOCATION_RULE"
                            , "SALESPERSON_RULE"
                            , "SALES_CREDIT_RULE"
                            , "SALES_CREDIT_TYPE_RULE"
                            , "SALES_TERRITORY_RULE"
                            , "SHIP_ADDRESS_RULE"
                            , "SHIP_CONTACT_RULE"
                            , "SHIP_CUSTOMER_RULE"
                            , "SHIP_VIA_RULE"
                            , "SOLD_CUSTOMER_RULE"
                            , "START_DATE"
                            , "TERM_RULE"
                            , "UNIT_OF_MEASURE_RULE"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "CUSTOMER_BANK_ACCOUNT_RULE"
                            , "MEMO_LINE_RULE"
                            , "RECEIPT_METHOD_RULE"
                            , "RELATED_DOCUMENT_RULE"
                            , "ALLOW_SALES_CREDIT_FLAG"
                            , "GROUPING_RULE_ID"
                            , "CREDIT_MEMO_BATCH_SOURCE_ID"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "COPY_DOC_NUMBER_FLAG"
                            , "DEFAULT_REFERENCE"
                            , "COPY_INV_TIDFF_TO_CM_FLAG"
                            , "RECEIPT_HANDLING_OPTION"
                            , "ALLOW_DUPLICATE_TRX_NUM_FLAG"
                            , "LEGAL_ENTITY_ID"
                            , "GEN_LINE_LEVEL_BAL_FLAG"
                            , "PAYMENT_DET_DEF_HIERARCHY"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_RA_BATCH_SOURCES_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
