

CREATE PROCEDURE "STG"."LOAD_STG_CA_INMAST"
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        4/03/2022 6:47:02 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_CA_INMAST";
    
    
    Source                   Destination           
    ---------------------    --------------------- 
    LND"."LND_CA_INMAST"    "STG"."STG_CA_INMAST" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-04    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_CA_INMAST";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_CA_INMAST"
                (
                    "Item Code"
                    ,"Incat"
                    ,"Item Description"
                    ,"Uom"
                    ,"Value @ Cost"
                    ,"Stock Qty"
                    ,"Nat Buy Prc"
                    ,"Commit Qty"
                    ,"Order Qty"
                    ,"Trade Prc"
                    ,"RetailPrc"
                    ,"MSup"
                    ,"Supplier Item Code"
                    ,"Last Sale"
                    ,"2ndLstSale"
                    ,"Comment"
                    ,"User1"
                    ,"Sales 1"
                    ,"Sales 2"
                    ,"Sales 3"
                    ,"Sales 4"
                    ,"Sales 5"
                    ,"Sales 6"
                    ,"Sales 7"
                    ,"Sales 8"
                    ,"Sales 9"
                    ,"Sales 10"
                    ,"Sales 11"
                    ,"Sales 12"
                    ,"Sales 13"
                    ,"Sales 14"
                    ,"Sales 15"
                    ,"Sales 16"
                    ,"Sales 17"
                    ,"Sales 18"
                    ,"Sales 19"
                    ,"Sales 20"
                    ,"Sales 21"
                    ,"Sales 22"
                    ,"Sales 23"
                    ,"Sales 24"
                    ,"Purch 1"
                    ,"Purch 2"
                    ,"Purch 3"
                    ,"Purch 4"
                    ,"Purch 5"
                    ,"Purch 6"
                    ,"Purch 7"
                    ,"Purch 8"
                    ,"Purch 9"
                    ,"Purch 10"
                    ,"Purch 11"
                    ,"Purch 12"
                    ,"Purch 13"
                    ,"Purch 14"
                    ,"Purch 15"
                    ,"Purch 16"
                    ,"Purch 17"
                    ,"Purch 18"
                    ,"Purch 19"
                    ,"Purch 20"
                    ,"Purch 21"
                    ,"Purch 22"
                    ,"Purch 23"
                    ,"Purch 24"
                    ,"Cogs 1"
                    ,"Cogs 2"
                    ,"Cogs 3"
                    ,"Cogs 4"
                    ,"Cogs 5"
                    ,"Cogs 6"
                    ,"Cogs 7"
                    ,"Cogs 8"
                    ,"Cogs 9"
                    ,"Cogs 10"
                    ,"Cogs 11"
                    ,"Cogs 12"
                    ,"Cogs 13"
                    ,"Cogs 14"
                    ,"Cogs 15"
                    ,"Cogs 16"
                    ,"Cogs 17"
                    ,"Cogs 18"
                    ,"Cogs 19"
                    ,"Cogs 20"
                    ,"Cogs 21"
                    ,"Cogs 22"
                    ,"Cogs 23"
                    ,"Cogs 24"
                    ,"Sale Qty 1"
                    ,"Sale Qty 2"
                    ,"Sale Qty 3"
                    ,"Sale Qty 4"
                    ,"Sale Qty 5"
                    ,"Sale Qty 6"
                    ,"Sale Qty 7"
                    ,"Sale Qty 8"
                    ,"Sale Qty 9"
                    ,"Sale Qty 10"
                    ,"Sale Qty 11"
                    ,"Sale Qty 12"
                    ,"Sale Qty 13"
                    ,"Sale Qty 14"
                    ,"Sale Qty 15"
                    ,"Sale Qty 16"
                    ,"Sale Qty 17"
                    ,"Sale Qty 18"
                    ,"Sale Qty 19"
                    ,"Sale Qty 20"
                    ,"Sale Qty 21"
                    ,"Sale Qty 22"
                    ,"Sale Qty 23"
                    ,"Sale Qty 24"
                    ,"QohLastStake"
                    ,"Curr Stake"
                    ,"QohCurrStake"
                    ,"Frozen Qoh"
                    ,"PO"
                    ,"VD"
                    ,"NS"
                    ,"User2"
                    ,"User3"
                    ,"VO"
                    ,"DO"
                    ,"F"
                    ,"Border Qty"
                    ,"B"
                    ,"S"
                    ,"O"
                    ,"Q"
                    ,"D"
                    ,"OQMult"
                    ,"C"
                    ,"PkgL"
                    ,"Cut Fee"
                    ,"Start Date"
                    ,"Last Purch"
                    ,"LastPrcUpd"
                    ,"DC Price"
                    ,"Qoh Eop"
                    ,"Vac Eop"
                    ,"1st Purch"
                    ,"ObsFlagUpd"
                    ,"PurchQty 1"
                    ,"PurchQty 2"
                    ,"PurchQty 3"
                    ,"PurchQty 4"
                    ,"PurchQty 5"
                    ,"PurchQty 6"
                    ,"PurchQty 7"
                    ,"PurchQty 8"
                    ,"PurchQty 9"
                    ,"PurchQty10"
                    ,"PurchQty11"
                    ,"PurchQty12"
                    ,"PurchQty13"
                    ,"PurchQty14"
                    ,"PurchQty15"
                    ,"PurchQty16"
                    ,"PurchQty17"
                    ,"PurchQty18"
                    ,"PurchQty19"
                    ,"PurchQty20"
                    ,"PurchQty21"
                    ,"PurchQty22"
                    ,"PurchQty23"
                    ,"PurchQty24"
                    ,"Comment3"
                    ,"OracleID"
                    ,"Barcode/Gtin"
                    ,"Frozen Vac"
                    ,"User4"
                    ,"Prcat"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("ITEM CODE" AS nvarchar(60) ) AS "ITEM CODE"
                        ,CAST("INCAT" AS nvarchar(20) ) AS "INCAT"
                        ,CAST("ITEM DESCRIPTION" AS nvarchar(240) ) AS "ITEM DESCRIPTION"
                        ,CAST("UOM" AS nvarchar(20) ) AS "UOM"
                        ,CAST("VALUE @ COST" AS decimal(36,4)) AS "VALUE @ COST"
                        ,CAST("STOCK QTY" AS decimal(36,4)) AS "STOCK QTY"
                        ,CAST("NAT BUY PRC" AS decimal(36,4)) AS "NAT BUY PRC"
                        ,CAST("COMMIT QTY" AS decimal(36,4)) AS "COMMIT QTY"
                        ,CAST("ORDER QTY" AS decimal(36,4)) AS "ORDER QTY"
                        ,CAST("TRADE PRC" AS decimal(36,4)) AS "TRADE PRC"
                        ,CAST("RETAILPRC" AS decimal(36,4)) AS "RETAILPRC"
                        ,CAST("MSUP" AS decimal(36,4)) AS "MSUP"
                        ,CAST("SUPPLIER ITEM CODE" AS nvarchar(80) ) AS "SUPPLIER ITEM CODE"
                        ,TRY_CONVERT(datetime2,"Last Sale",104) AS "LAST SALE"
                        ,TRY_CONVERT(datetime2,"2ndLstSale",104) AS "2NDLSTSALE"
                        ,CAST("COMMENT" AS nvarchar(240) ) AS "COMMENT"
                        ,CAST("USER1" AS nvarchar(20) ) AS "USER1"
                        ,CAST("SALES 1" AS decimal(36,4)) AS "SALES 1"
                        ,CAST("SALES 2" AS decimal(36,4)) AS "SALES 2"
                        ,CAST("SALES 3" AS decimal(36,4)) AS "SALES 3"
                        ,CAST("SALES 4" AS decimal(36,4)) AS "SALES 4"
                        ,CAST("SALES 5" AS decimal(36,4)) AS "SALES 5"
                        ,CAST("SALES 6" AS decimal(36,4)) AS "SALES 6"
                        ,CAST("SALES 7" AS decimal(36,4)) AS "SALES 7"
                        ,CAST("SALES 8" AS decimal(36,4)) AS "SALES 8"
                        ,CAST("SALES 9" AS decimal(36,4)) AS "SALES 9"
                        ,CAST("SALES 10" AS decimal(36,4)) AS "SALES 10"
                        ,CAST("SALES 11" AS decimal(36,4)) AS "SALES 11"
                        ,CAST("SALES 12" AS decimal(36,4)) AS "SALES 12"
                        ,CAST("SALES 13" AS decimal(36,4)) AS "SALES 13"
                        ,CAST("SALES 14" AS decimal(36,4)) AS "SALES 14"
                        ,CAST("SALES 15" AS decimal(36,4)) AS "SALES 15"
                        ,CAST("SALES 16" AS decimal(36,4)) AS "SALES 16"
                        ,CAST("SALES 17" AS decimal(36,4)) AS "SALES 17"
                        ,CAST("SALES 18" AS decimal(36,4)) AS "SALES 18"
                        ,CAST("SALES 19" AS decimal(36,4)) AS "SALES 19"
                        ,CAST("SALES 20" AS decimal(36,4)) AS "SALES 20"
                        ,CAST("SALES 21" AS decimal(36,4)) AS "SALES 21"
                        ,CAST("SALES 22" AS decimal(36,4)) AS "SALES 22"
                        ,CAST("SALES 23" AS decimal(36,4)) AS "SALES 23"
                        ,CAST("SALES 24" AS decimal(36,4)) AS "SALES 24"
                        ,CAST("PURCH 1" AS decimal(36,4)) AS "PURCH 1"
                        ,CAST("PURCH 2" AS decimal(36,4)) AS "PURCH 2"
                        ,CAST("PURCH 3" AS decimal(36,4)) AS "PURCH 3"
                        ,CAST("PURCH 4" AS decimal(36,4)) AS "PURCH 4"
                        ,CAST("PURCH 5" AS decimal(36,4)) AS "PURCH 5"
                        ,CAST("PURCH 6" AS decimal(36,4)) AS "PURCH 6"
                        ,CAST("PURCH 7" AS decimal(36,4)) AS "PURCH 7"
                        ,CAST("PURCH 8" AS decimal(36,4)) AS "PURCH 8"
                        ,CAST("PURCH 9" AS decimal(36,4)) AS "PURCH 9"
                        ,CAST("PURCH 10" AS decimal(36,4)) AS "PURCH 10"
                        ,CAST("PURCH 11" AS decimal(36,4)) AS "PURCH 11"
                        ,CAST("PURCH 12" AS decimal(36,4)) AS "PURCH 12"
                        ,CAST("PURCH 13" AS decimal(36,4)) AS "PURCH 13"
                        ,CAST("PURCH 14" AS decimal(36,4)) AS "PURCH 14"
                        ,CAST("PURCH 15" AS decimal(36,4)) AS "PURCH 15"
                        ,CAST("PURCH 16" AS decimal(36,4)) AS "PURCH 16"
                        ,CAST("PURCH 17" AS decimal(36,4)) AS "PURCH 17"
                        ,CAST("PURCH 18" AS decimal(36,4)) AS "PURCH 18"
                        ,CAST("PURCH 19" AS decimal(36,4)) AS "PURCH 19"
                        ,CAST("PURCH 20" AS decimal(36,4)) AS "PURCH 20"
                        ,CAST("PURCH 21" AS decimal(36,4)) AS "PURCH 21"
                        ,CAST("PURCH 22" AS decimal(36,4)) AS "PURCH 22"
                        ,CAST("PURCH 23" AS decimal(36,4)) AS "PURCH 23"
                        ,CAST("PURCH 24" AS decimal(36,4)) AS "PURCH 24"
                        ,CAST("COGS 1" AS decimal(36,4)) AS "COGS 1"
                        ,CAST("COGS 2" AS decimal(36,4)) AS "COGS 2"
                        ,CAST("COGS 3" AS decimal(36,4)) AS "COGS 3"
                        ,CAST("COGS 4" AS decimal(36,4)) AS "COGS 4"
                        ,CAST("COGS 5" AS decimal(36,4)) AS "COGS 5"
                        ,CAST("COGS 6" AS decimal(36,4)) AS "COGS 6"
                        ,CAST("COGS 7" AS decimal(36,4)) AS "COGS 7"
                        ,CAST("COGS 8" AS decimal(36,4)) AS "COGS 8"
                        ,CAST("COGS 9" AS decimal(36,4)) AS "COGS 9"
                        ,CAST("COGS 10" AS decimal(36,4)) AS "COGS 10"
                        ,CAST("COGS 11" AS decimal(36,4)) AS "COGS 11"
                        ,CAST("COGS 12" AS decimal(36,4)) AS "COGS 12"
                        ,CAST("COGS 13" AS decimal(36,4)) AS "COGS 13"
                        ,CAST("COGS 14" AS decimal(36,4)) AS "COGS 14"
                        ,CAST("COGS 15" AS decimal(36,4)) AS "COGS 15"
                        ,CAST("COGS 16" AS decimal(36,4)) AS "COGS 16"
                        ,CAST("COGS 17" AS decimal(36,4)) AS "COGS 17"
                        ,CAST("COGS 18" AS decimal(36,4)) AS "COGS 18"
                        ,CAST("COGS 19" AS decimal(36,4)) AS "COGS 19"
                        ,CAST("COGS 20" AS decimal(36,4)) AS "COGS 20"
                        ,CAST("COGS 21" AS decimal(36,4)) AS "COGS 21"
                        ,CAST("COGS 22" AS decimal(36,4)) AS "COGS 22"
                        ,CAST("COGS 23" AS decimal(36,4)) AS "COGS 23"
                        ,CAST("COGS 24" AS decimal(36,4)) AS "COGS 24"
                        ,CAST("SALE QTY 1" AS decimal(36,4)) AS "SALE QTY 1"
                        ,CAST("SALE QTY 2" AS decimal(36,4)) AS "SALE QTY 2"
                        ,CAST("SALE QTY 3" AS decimal(36,4)) AS "SALE QTY 3"
                        ,CAST("SALE QTY 4" AS decimal(36,4)) AS "SALE QTY 4"
                        ,CAST("SALE QTY 5" AS decimal(36,4)) AS "SALE QTY 5"
                        ,CAST("SALE QTY 6" AS decimal(36,4)) AS "SALE QTY 6"
                        ,CAST("SALE QTY 7" AS decimal(36,4)) AS "SALE QTY 7"
                        ,CAST("SALE QTY 8" AS decimal(36,4)) AS "SALE QTY 8"
                        ,CAST("SALE QTY 9" AS decimal(36,4)) AS "SALE QTY 9"
                        ,CAST("SALE QTY 10" AS decimal(36,4)) AS "SALE QTY 10"
                        ,CAST("SALE QTY 11" AS decimal(36,4)) AS "SALE QTY 11"
                        ,CAST("SALE QTY 12" AS decimal(36,4)) AS "SALE QTY 12"
                        ,CAST("SALE QTY 13" AS decimal(36,4)) AS "SALE QTY 13"
                        ,CAST("SALE QTY 14" AS decimal(36,4)) AS "SALE QTY 14"
                        ,CAST("SALE QTY 15" AS decimal(36,4)) AS "SALE QTY 15"
                        ,CAST("SALE QTY 16" AS decimal(36,4)) AS "SALE QTY 16"
                        ,CAST("SALE QTY 17" AS decimal(36,4)) AS "SALE QTY 17"
                        ,CAST("SALE QTY 18" AS decimal(36,4)) AS "SALE QTY 18"
                        ,CAST("SALE QTY 19" AS decimal(36,4)) AS "SALE QTY 19"
                        ,CAST("SALE QTY 20" AS decimal(36,4)) AS "SALE QTY 20"
                        ,CAST("SALE QTY 21" AS decimal(36,4)) AS "SALE QTY 21"
                        ,CAST("SALE QTY 22" AS decimal(36,4)) AS "SALE QTY 22"
                        ,CAST("SALE QTY 23" AS decimal(36,4)) AS "SALE QTY 23"
                        ,CAST("SALE QTY 24" AS decimal(36,4)) AS "SALE QTY 24"
                        ,CAST("QOHLASTSTAKE" AS decimal(36,4)) AS "QOHLASTSTAKE"
                        ,TRY_CONVERT(datetime2,"Curr Stake",104) AS "CURR STAKE"
                        ,CAST("QOHCURRSTAKE" AS decimal(36,4)) AS "QOHCURRSTAKE"
                        ,CAST("FROZEN QOH" AS decimal(36,4)) AS "FROZEN QOH"
                        ,CAST("PO" AS nvarchar(2) ) AS "PO"
                        ,CAST("VD" AS nvarchar(2) ) AS "VD"
                        ,CAST("NS" AS nvarchar(2) ) AS "NS"
                        ,CAST("USER2" AS nvarchar(20) ) AS "USER2"
                        ,CAST("USER3" AS nvarchar(20) ) AS "USER3"
                        ,CAST("VO" AS nvarchar(2) ) AS "VO"
                        ,CAST("DO" AS nvarchar(2) ) AS "DO"
                        ,CAST("F" AS nvarchar(2) ) AS "F"
                        ,CAST("BORDER QTY" AS decimal(36,4)) AS "BORDER QTY"
                        ,CAST("B" AS nvarchar(100) ) AS "B"
                        ,CAST("S" AS nvarchar(100) ) AS "S"
                        ,CAST("O" AS nvarchar(100) ) AS "O"
                        ,CAST("Q" AS nvarchar(100) ) AS "Q"
                        ,CAST("D" AS nvarchar(100) ) AS "D"
                        ,CAST("OQMULT" AS nvarchar(100) ) AS "OQMULT"
                        ,CAST("C" AS nvarchar(100) ) AS "C"
                        ,CAST("PKGL" AS nvarchar(100) ) AS "PKGL"
                        ,CAST("CUT FEE" AS nvarchar(100) ) AS "CUT FEE"
                        ,TRY_CONVERT(datetime2,"Start Date",104) AS "START DATE"
                        ,TRY_CONVERT(datetime2,"Last Purch",104) AS "LAST PURCH"
                        ,TRY_CONVERT(datetime2,"LastPrcUpd",104) AS "LASTPRCUPD"
                        ,CAST("DC PRICE" AS decimal(36,4)) AS "DC PRICE"
                        ,CAST("QOH EOP" AS decimal(36,4)) AS "QOH EOP"
                        ,CAST("VAC EOP" AS decimal(36,4)) AS "VAC EOP"
                        ,TRY_CONVERT(datetime2,"1st Purch",104) AS "1ST PURCH"
                        ,TRY_CONVERT(datetime2,"ObsFlagUpd",104) AS "OBSFLAGUPD"
                        ,CAST("PURCHQTY 1" AS decimal(36,4)) AS "PURCHQTY 1"
                        ,CAST("PURCHQTY 2" AS decimal(36,4)) AS "PURCHQTY 2"
                        ,CAST("PURCHQTY 3" AS decimal(36,4)) AS "PURCHQTY 3"
                        ,CAST("PURCHQTY 4" AS decimal(36,4)) AS "PURCHQTY 4"
                        ,CAST("PURCHQTY 5" AS decimal(36,4)) AS "PURCHQTY 5"
                        ,CAST("PURCHQTY 6" AS decimal(36,4)) AS "PURCHQTY 6"
                        ,CAST("PURCHQTY 7" AS decimal(36,4)) AS "PURCHQTY 7"
                        ,CAST("PURCHQTY 8" AS decimal(36,4)) AS "PURCHQTY 8"
                        ,CAST("PURCHQTY 9" AS decimal(36,4)) AS "PURCHQTY 9"
                        ,CAST("PURCHQTY10" AS decimal(36,4)) AS "PURCHQTY10"
                        ,CAST("PURCHQTY11" AS decimal(36,4)) AS "PURCHQTY11"
                        ,CAST("PURCHQTY12" AS decimal(36,4)) AS "PURCHQTY12"
                        ,CAST("PURCHQTY13" AS decimal(36,4)) AS "PURCHQTY13"
                        ,CAST("PURCHQTY14" AS decimal(36,4)) AS "PURCHQTY14"
                        ,CAST("PURCHQTY15" AS decimal(36,4)) AS "PURCHQTY15"
                        ,CAST("PURCHQTY16" AS decimal(36,4)) AS "PURCHQTY16"
                        ,CAST("PURCHQTY17" AS decimal(36,4)) AS "PURCHQTY17"
                        ,CAST("PURCHQTY18" AS decimal(36,4)) AS "PURCHQTY18"
                        ,CAST("PURCHQTY19" AS decimal(36,4)) AS "PURCHQTY19"
                        ,CAST("PURCHQTY20" AS decimal(36,4)) AS "PURCHQTY20"
                        ,CAST("PURCHQTY21" AS decimal(36,4)) AS "PURCHQTY21"
                        ,CAST("PURCHQTY22" AS decimal(36,4)) AS "PURCHQTY22"
                        ,CAST("PURCHQTY23" AS decimal(36,4)) AS "PURCHQTY23"
                        ,CAST("PURCHQTY24" AS decimal(36,4)) AS "PURCHQTY24"
                        ,CAST("COMMENT3" AS nvarchar(240) ) AS "COMMENT3"
                        ,CAST("ORACLEID" AS decimal(36,4)) AS "ORACLEID"
                        ,CAST("BARCODE/GTIN" AS nvarchar(40) ) AS "BARCODE/GTIN"
                        ,CAST("FROZEN VAC" AS decimal(36,4)) AS "FROZEN VAC"
                        ,CAST("USER4" AS nvarchar(40) ) AS "USER4"
                        ,CAST("PRCAT" AS nvarchar(20) ) AS "PRCAT"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "Item Code"
                            , "Incat"
                            , "Item Description"
                            , "Uom"
                            , "Value @ Cost"
                            , "Stock Qty"
                            , "Nat Buy Prc"
                            , "Commit Qty"
                            , "Order Qty"
                            , "Trade Prc"
                            , "RetailPrc"
                            , "MSup"
                            , "Supplier Item Code"
                            , "Last Sale"
                            , "2ndLstSale"
                            , "Comment"
                            , "User1"
                            , "Sales 1"
                            , "Sales 2"
                            , "Sales 3"
                            , "Sales 4"
                            , "Sales 5"
                            , "Sales 6"
                            , "Sales 7"
                            , "Sales 8"
                            , "Sales 9"
                            , "Sales 10"
                            , "Sales 11"
                            , "Sales 12"
                            , "Sales 13"
                            , "Sales 14"
                            , "Sales 15"
                            , "Sales 16"
                            , "Sales 17"
                            , "Sales 18"
                            , "Sales 19"
                            , "Sales 20"
                            , "Sales 21"
                            , "Sales 22"
                            , "Sales 23"
                            , "Sales 24"
                            , "Purch 1"
                            , "Purch 2"
                            , "Purch 3"
                            , "Purch 4"
                            , "Purch 5"
                            , "Purch 6"
                            , "Purch 7"
                            , "Purch 8"
                            , "Purch 9"
                            , "Purch 10"
                            , "Purch 11"
                            , "Purch 12"
                            , "Purch 13"
                            , "Purch 14"
                            , "Purch 15"
                            , "Purch 16"
                            , "Purch 17"
                            , "Purch 18"
                            , "Purch 19"
                            , "Purch 20"
                            , "Purch 21"
                            , "Purch 22"
                            , "Purch 23"
                            , "Purch 24"
                            , "Cogs 1"
                            , "Cogs 2"
                            , "Cogs 3"
                            , "Cogs 4"
                            , "Cogs 5"
                            , "Cogs 6"
                            , "Cogs 7"
                            , "Cogs 8"
                            , "Cogs 9"
                            , "Cogs 10"
                            , "Cogs 11"
                            , "Cogs 12"
                            , "Cogs 13"
                            , "Cogs 14"
                            , "Cogs 15"
                            , "Cogs 16"
                            , "Cogs 17"
                            , "Cogs 18"
                            , "Cogs 19"
                            , "Cogs 20"
                            , "Cogs 21"
                            , "Cogs 22"
                            , "Cogs 23"
                            , "Cogs 24"
                            , "Sale Qty 1"
                            , "Sale Qty 2"
                            , "Sale Qty 3"
                            , "Sale Qty 4"
                            , "Sale Qty 5"
                            , "Sale Qty 6"
                            , "Sale Qty 7"
                            , "Sale Qty 8"
                            , "Sale Qty 9"
                            , "Sale Qty 10"
                            , "Sale Qty 11"
                            , "Sale Qty 12"
                            , "Sale Qty 13"
                            , "Sale Qty 14"
                            , "Sale Qty 15"
                            , "Sale Qty 16"
                            , "Sale Qty 17"
                            , "Sale Qty 18"
                            , "Sale Qty 19"
                            , "Sale Qty 20"
                            , "Sale Qty 21"
                            , "Sale Qty 22"
                            , "Sale Qty 23"
                            , "Sale Qty 24"
                            , "QohLastStake"
                            , "Curr Stake"
                            , "QohCurrStake"
                            , "Frozen Qoh"
                            , "PO"
                            , "VD"
                            , "NS"
                            , "User2"
                            , "User3"
                            , "VO"
                            , "DO"
                            , "F"
                            , "Border Qty"
                            , "B"
                            , "S"
                            , "O"
                            , "Q"
                            , "D"
                            , "OQMult"
                            , "C"
                            , "PkgL"
                            , "Cut Fee"
                            , "Start Date"
                            , "Last Purch"
                            , "LastPrcUpd"
                            , "DC Price"
                            , "Qoh Eop"
                            , "Vac Eop"
                            , "1st Purch"
                            , "ObsFlagUpd"
                            , "PurchQty 1"
                            , "PurchQty 2"
                            , "PurchQty 3"
                            , "PurchQty 4"
                            , "PurchQty 5"
                            , "PurchQty 6"
                            , "PurchQty 7"
                            , "PurchQty 8"
                            , "PurchQty 9"
                            , "PurchQty10"
                            , "PurchQty11"
                            , "PurchQty12"
                            , "PurchQty13"
                            , "PurchQty14"
                            , "PurchQty15"
                            , "PurchQty16"
                            , "PurchQty17"
                            , "PurchQty18"
                            , "PurchQty19"
                            , "PurchQty20"
                            , "PurchQty21"
                            , "PurchQty22"
                            , "PurchQty23"
                            , "PurchQty24"
                            , "Comment3"
                            , "OracleID"
                            , "Barcode/Gtin"
                            , "Frozen Vac"
                            , "User4"
                            , "Prcat"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_CA_INMAST"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
