CREATE PROCEDURE "STG"."LOAD_STG_EBS_AR_ADJUSTMENTS_ALL"
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        5/05/2022 11:48:50 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_AR_ADJUSTMENTS_ALL";
    
    
    Source                                Destination                        
    ----------------------------------    ---------------------------------- 
    LND"."LND_EBS_AR_ADJUSTMENTS_ALL"    "STG"."STG_EBS_AR_ADJUSTMENTS_ALL" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-05    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_AR_ADJUSTMENTS_ALL";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_AR_ADJUSTMENTS_ALL"
                (
                    "ADJUSTMENT_ID"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATED_BY"
                    ,"CREATION_DATE"
                    ,"AMOUNT"
                    ,"APPLY_DATE"
                    ,"GL_DATE"
                    ,"SET_OF_BOOKS_ID"
                    ,"CODE_COMBINATION_ID"
                    ,"TYPE"
                    ,"ADJUSTMENT_TYPE"
                    ,"STATUS"
                    ,"LINE_ADJUSTED"
                    ,"FREIGHT_ADJUSTED"
                    ,"TAX_ADJUSTED"
                    ,"RECEIVABLES_CHARGES_ADJUSTED"
                    ,"ASSOCIATED_CASH_RECEIPT_ID"
                    ,"CHARGEBACK_CUSTOMER_TRX_ID"
                    ,"BATCH_ID"
                    ,"CUSTOMER_TRX_ID"
                    ,"CUSTOMER_TRX_LINE_ID"
                    ,"SUBSEQUENT_TRX_ID"
                    ,"PAYMENT_SCHEDULE_ID"
                    ,"RECEIVABLES_TRX_ID"
                    ,"DISTRIBUTION_SET_ID"
                    ,"GL_POSTED_DATE"
                    ,"COMMENTS"
                    ,"AUTOMATICALLY_GENERATED"
                    ,"CREATED_FROM"
                    ,"REASON_CODE"
                    ,"POSTABLE"
                    ,"APPROVED_BY"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"POSTING_CONTROL_ID"
                    ,"ACCTD_AMOUNT"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"REQUEST_ID"
                    ,"ADJUSTMENT_NUMBER"
                    ,"ORG_ID"
                    ,"USSGL_TRANSACTION_CODE"
                    ,"USSGL_TRANSACTION_CODE_CONTEXT"
                    ,"DOC_SEQUENCE_VALUE"
                    ,"DOC_SEQUENCE_ID"
                    ,"ASSOCIATED_APPLICATION_ID"
                    ,"CONS_INV_ID"
                    ,"MRC_GL_POSTED_DATE"
                    ,"MRC_POSTING_CONTROL_ID"
                    ,"MRC_ACCTD_AMOUNT"
                    ,"ADJ_TAX_ACCT_RULE"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"LINK_TO_TRX_HIST_ID"
                    ,"EVENT_ID"
                    ,"UPGRADE_METHOD"
                    ,"AX_ACCOUNTED_FLAG"
                    ,"INTEREST_HEADER_ID"
                    ,"INTEREST_LINE_ID"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("ADJUSTMENT_ID" AS float) AS "ADJUSTMENT_ID"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("LAST_UPDATE_DATE"  AS datetime2) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("CREATION_DATE"  AS datetime2) AS "CREATION_DATE"
                        ,CAST("AMOUNT" AS float) AS "AMOUNT"
                        ,CAST("APPLY_DATE"  AS datetime2) AS "APPLY_DATE"
                        ,CAST("GL_DATE"  AS datetime2) AS "GL_DATE"
                        ,CAST("SET_OF_BOOKS_ID" AS float) AS "SET_OF_BOOKS_ID"
                        ,CAST("CODE_COMBINATION_ID" AS float) AS "CODE_COMBINATION_ID"
                        ,CAST("TYPE" AS varchar(100) ) AS "TYPE"
                        ,CAST("ADJUSTMENT_TYPE" AS varchar(100) ) AS "ADJUSTMENT_TYPE"
                        ,CAST("STATUS" AS varchar(100) ) AS "STATUS"
                        ,CAST("LINE_ADJUSTED" AS float) AS "LINE_ADJUSTED"
                        ,CAST("FREIGHT_ADJUSTED" AS float) AS "FREIGHT_ADJUSTED"
                        ,CAST("TAX_ADJUSTED" AS float) AS "TAX_ADJUSTED"
                        ,CAST("RECEIVABLES_CHARGES_ADJUSTED" AS float) AS "RECEIVABLES_CHARGES_ADJUSTED"
                        ,CAST("ASSOCIATED_CASH_RECEIPT_ID" AS float) AS "ASSOCIATED_CASH_RECEIPT_ID"
                        ,CAST("CHARGEBACK_CUSTOMER_TRX_ID" AS float) AS "CHARGEBACK_CUSTOMER_TRX_ID"
                        ,CAST("BATCH_ID" AS float) AS "BATCH_ID"
                        ,CAST("CUSTOMER_TRX_ID" AS float) AS "CUSTOMER_TRX_ID"
                        ,CAST("CUSTOMER_TRX_LINE_ID" AS float) AS "CUSTOMER_TRX_LINE_ID"
                        ,CAST("SUBSEQUENT_TRX_ID" AS float) AS "SUBSEQUENT_TRX_ID"
                        ,CAST("PAYMENT_SCHEDULE_ID" AS float) AS "PAYMENT_SCHEDULE_ID"
                        ,CAST("RECEIVABLES_TRX_ID" AS float) AS "RECEIVABLES_TRX_ID"
                        ,CAST("DISTRIBUTION_SET_ID" AS float) AS "DISTRIBUTION_SET_ID"
                        ,CAST("GL_POSTED_DATE"  AS datetime2) AS "GL_POSTED_DATE"
                        ,CAST("COMMENTS" AS varchar(8000) ) AS "COMMENTS"
                        ,CAST("AUTOMATICALLY_GENERATED" AS varchar(100) ) AS "AUTOMATICALLY_GENERATED"
                        ,CAST("CREATED_FROM" AS varchar(100) ) AS "CREATED_FROM"
                        ,CAST("REASON_CODE" AS varchar(100) ) AS "REASON_CODE"
                        ,CAST("POSTABLE" AS varchar(100) ) AS "POSTABLE"
                        ,CAST("APPROVED_BY" AS float) AS "APPROVED_BY"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("POSTING_CONTROL_ID" AS float) AS "POSTING_CONTROL_ID"
                        ,CAST("ACCTD_AMOUNT" AS float) AS "ACCTD_AMOUNT"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,CAST("PROGRAM_UPDATE_DATE"  AS datetime2) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("ADJUSTMENT_NUMBER" AS varchar(100) ) AS "ADJUSTMENT_NUMBER"
                        ,CAST("ORG_ID" AS float) AS "ORG_ID"
                        ,CAST("USSGL_TRANSACTION_CODE" AS varchar(100) ) AS "USSGL_TRANSACTION_CODE"
                        ,CAST("USSGL_TRANSACTION_CODE_CONTEXT" AS varchar(100) ) AS "USSGL_TRANSACTION_CODE_CONTEXT"
                        ,CAST("DOC_SEQUENCE_VALUE" AS float) AS "DOC_SEQUENCE_VALUE"
                        ,CAST("DOC_SEQUENCE_ID" AS float) AS "DOC_SEQUENCE_ID"
                        ,CAST("ASSOCIATED_APPLICATION_ID" AS float) AS "ASSOCIATED_APPLICATION_ID"
                        ,CAST("CONS_INV_ID" AS float) AS "CONS_INV_ID"
                        ,CAST("MRC_GL_POSTED_DATE" AS varchar(8000) ) AS "MRC_GL_POSTED_DATE"
                        ,CAST("MRC_POSTING_CONTROL_ID" AS varchar(8000) ) AS "MRC_POSTING_CONTROL_ID"
                        ,CAST("MRC_ACCTD_AMOUNT" AS varchar(8000) ) AS "MRC_ACCTD_AMOUNT"
                        ,CAST("ADJ_TAX_ACCT_RULE" AS varchar(100) ) AS "ADJ_TAX_ACCT_RULE"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("LINK_TO_TRX_HIST_ID" AS float) AS "LINK_TO_TRX_HIST_ID"
                        ,CAST("EVENT_ID" AS float) AS "EVENT_ID"
                        ,CAST("UPGRADE_METHOD" AS varchar(100) ) AS "UPGRADE_METHOD"
                        ,CAST("AX_ACCOUNTED_FLAG" AS varchar(100) ) AS "AX_ACCOUNTED_FLAG"
                        ,CAST("INTEREST_HEADER_ID" AS float) AS "INTEREST_HEADER_ID"
                        ,CAST("INTEREST_LINE_ID" AS float) AS "INTEREST_LINE_ID"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "ADJUSTMENT_ID"
                            , "LAST_UPDATED_BY"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATE_LOGIN"
                            , "CREATED_BY"
                            , "CREATION_DATE"
                            , "AMOUNT"
                            , "APPLY_DATE"
                            , "GL_DATE"
                            , "SET_OF_BOOKS_ID"
                            , "CODE_COMBINATION_ID"
                            , "TYPE"
                            , "ADJUSTMENT_TYPE"
                            , "STATUS"
                            , "LINE_ADJUSTED"
                            , "FREIGHT_ADJUSTED"
                            , "TAX_ADJUSTED"
                            , "RECEIVABLES_CHARGES_ADJUSTED"
                            , "ASSOCIATED_CASH_RECEIPT_ID"
                            , "CHARGEBACK_CUSTOMER_TRX_ID"
                            , "BATCH_ID"
                            , "CUSTOMER_TRX_ID"
                            , "CUSTOMER_TRX_LINE_ID"
                            , "SUBSEQUENT_TRX_ID"
                            , "PAYMENT_SCHEDULE_ID"
                            , "RECEIVABLES_TRX_ID"
                            , "DISTRIBUTION_SET_ID"
                            , "GL_POSTED_DATE"
                            , "COMMENTS"
                            , "AUTOMATICALLY_GENERATED"
                            , "CREATED_FROM"
                            , "REASON_CODE"
                            , "POSTABLE"
                            , "APPROVED_BY"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "POSTING_CONTROL_ID"
                            , "ACCTD_AMOUNT"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "REQUEST_ID"
                            , "ADJUSTMENT_NUMBER"
                            , "ORG_ID"
                            , "USSGL_TRANSACTION_CODE"
                            , "USSGL_TRANSACTION_CODE_CONTEXT"
                            , "DOC_SEQUENCE_VALUE"
                            , "DOC_SEQUENCE_ID"
                            , "ASSOCIATED_APPLICATION_ID"
                            , "CONS_INV_ID"
                            , "MRC_GL_POSTED_DATE"
                            , "MRC_POSTING_CONTROL_ID"
                            , "MRC_ACCTD_AMOUNT"
                            , "ADJ_TAX_ACCT_RULE"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                            , "LINK_TO_TRX_HIST_ID"
                            , "EVENT_ID"
                            , "UPGRADE_METHOD"
                            , "AX_ACCOUNTED_FLAG"
                            , "INTEREST_HEADER_ID"
                            , "INTEREST_LINE_ID"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_AR_ADJUSTMENTS_ALL"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END