

CREATE PROCEDURE [STG].[LOAD_STG_EBS_MTL_SYSTEM_ITEMS_B]
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        10/03/2022 10:45:43 am
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_MTL_SYSTEM_ITEMS_B";
    
    
    Source                                Destination                        
    ----------------------------------    ---------------------------------- 
    LND"."LND_EBS_MTL_SYSTEM_ITEMS_B"    "STG"."STG_EBS_MTL_SYSTEM_ITEMS_B" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-03-10    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_MTL_SYSTEM_ITEMS_B";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_MTL_SYSTEM_ITEMS_B"
                (
                    "INVENTORY_ITEM_ID"
                    ,"ORGANIZATION_ID"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"CREATION_DATE"
                    ,"CREATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"SUMMARY_FLAG"
                    ,"ENABLED_FLAG"
                    ,"START_DATE_ACTIVE"
                    ,"END_DATE_ACTIVE"
                    ,"DESCRIPTION"
                    ,"BUYER_ID"
                    ,"ACCOUNTING_RULE_ID"
                    ,"INVOICING_RULE_ID"
                    ,"SEGMENT1"
                    ,"SEGMENT2"
                    ,"SEGMENT3"
                    ,"SEGMENT4"
                    ,"SEGMENT5"
                    ,"SEGMENT6"
                    ,"SEGMENT7"
                    ,"SEGMENT8"
                    ,"SEGMENT9"
                    ,"SEGMENT10"
                    ,"SEGMENT11"
                    ,"SEGMENT12"
                    ,"SEGMENT13"
                    ,"SEGMENT14"
                    ,"SEGMENT15"
                    ,"SEGMENT16"
                    ,"SEGMENT17"
                    ,"SEGMENT18"
                    ,"SEGMENT19"
                    ,"SEGMENT20"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"PURCHASING_ITEM_FLAG"
                    ,"SHIPPABLE_ITEM_FLAG"
                    ,"CUSTOMER_ORDER_FLAG"
                    ,"INTERNAL_ORDER_FLAG"
                    ,"SERVICE_ITEM_FLAG"
                    ,"INVENTORY_ITEM_FLAG"
                    ,"ENG_ITEM_FLAG"
                    ,"INVENTORY_ASSET_FLAG"
                    ,"PURCHASING_ENABLED_FLAG"
                    ,"CUSTOMER_ORDER_ENABLED_FLAG"
                    ,"INTERNAL_ORDER_ENABLED_FLAG"
                    ,"SO_TRANSACTIONS_FLAG"
                    ,"MTL_TRANSACTIONS_ENABLED_FLAG"
                    ,"STOCK_ENABLED_FLAG"
                    ,"BOM_ENABLED_FLAG"
                    ,"BUILD_IN_WIP_FLAG"
                    ,"REVISION_QTY_CONTROL_CODE"
                    ,"ITEM_CATALOG_GROUP_ID"
                    ,"CATALOG_STATUS_FLAG"
                    ,"RETURNABLE_FLAG"
                    ,"DEFAULT_SHIPPING_ORG"
                    ,"COLLATERAL_FLAG"
                    ,"TAXABLE_FLAG"
                    ,"QTY_RCV_EXCEPTION_CODE"
                    ,"ALLOW_ITEM_DESC_UPDATE_FLAG"
                    ,"INSPECTION_REQUIRED_FLAG"
                    ,"RECEIPT_REQUIRED_FLAG"
                    ,"MARKET_PRICE"
                    ,"HAZARD_CLASS_ID"
                    ,"RFQ_REQUIRED_FLAG"
                    ,"QTY_RCV_TOLERANCE"
                    ,"LIST_PRICE_PER_UNIT"
                    ,"UN_NUMBER_ID"
                    ,"PRICE_TOLERANCE_PERCENT"
                    ,"ASSET_CATEGORY_ID"
                    ,"ROUNDING_FACTOR"
                    ,"UNIT_OF_ISSUE"
                    ,"ENFORCE_SHIP_TO_LOCATION_CODE"
                    ,"ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                    ,"ALLOW_UNORDERED_RECEIPTS_FLAG"
                    ,"ALLOW_EXPRESS_DELIVERY_FLAG"
                    ,"DAYS_EARLY_RECEIPT_ALLOWED"
                    ,"DAYS_LATE_RECEIPT_ALLOWED"
                    ,"RECEIPT_DAYS_EXCEPTION_CODE"
                    ,"RECEIVING_ROUTING_ID"
                    ,"INVOICE_CLOSE_TOLERANCE"
                    ,"RECEIVE_CLOSE_TOLERANCE"
                    ,"AUTO_LOT_ALPHA_PREFIX"
                    ,"START_AUTO_LOT_NUMBER"
                    ,"LOT_CONTROL_CODE"
                    ,"SHELF_LIFE_CODE"
                    ,"SHELF_LIFE_DAYS"
                    ,"SERIAL_NUMBER_CONTROL_CODE"
                    ,"START_AUTO_SERIAL_NUMBER"
                    ,"AUTO_SERIAL_ALPHA_PREFIX"
                    ,"SOURCE_TYPE"
                    ,"SOURCE_ORGANIZATION_ID"
                    ,"SOURCE_SUBINVENTORY"
                    ,"EXPENSE_ACCOUNT"
                    ,"ENCUMBRANCE_ACCOUNT"
                    ,"RESTRICT_SUBINVENTORIES_CODE"
                    ,"UNIT_WEIGHT"
                    ,"WEIGHT_UOM_CODE"
                    ,"VOLUME_UOM_CODE"
                    ,"UNIT_VOLUME"
                    ,"RESTRICT_LOCATORS_CODE"
                    ,"LOCATION_CONTROL_CODE"
                    ,"SHRINKAGE_RATE"
                    ,"ACCEPTABLE_EARLY_DAYS"
                    ,"PLANNING_TIME_FENCE_CODE"
                    ,"DEMAND_TIME_FENCE_CODE"
                    ,"LEAD_TIME_LOT_SIZE"
                    ,"STD_LOT_SIZE"
                    ,"CUM_MANUFACTURING_LEAD_TIME"
                    ,"OVERRUN_PERCENTAGE"
                    ,"MRP_CALCULATE_ATP_FLAG"
                    ,"ACCEPTABLE_RATE_INCREASE"
                    ,"ACCEPTABLE_RATE_DECREASE"
                    ,"CUMULATIVE_TOTAL_LEAD_TIME"
                    ,"PLANNING_TIME_FENCE_DAYS"
                    ,"DEMAND_TIME_FENCE_DAYS"
                    ,"END_ASSEMBLY_PEGGING_FLAG"
                    ,"REPETITIVE_PLANNING_FLAG"
                    ,"PLANNING_EXCEPTION_SET"
                    ,"BOM_ITEM_TYPE"
                    ,"PICK_COMPONENTS_FLAG"
                    ,"REPLENISH_TO_ORDER_FLAG"
                    ,"BASE_ITEM_ID"
                    ,"ATP_COMPONENTS_FLAG"
                    ,"ATP_FLAG"
                    ,"FIXED_LEAD_TIME"
                    ,"VARIABLE_LEAD_TIME"
                    ,"WIP_SUPPLY_LOCATOR_ID"
                    ,"WIP_SUPPLY_TYPE"
                    ,"WIP_SUPPLY_SUBINVENTORY"
                    ,"PRIMARY_UOM_CODE"
                    ,"PRIMARY_UNIT_OF_MEASURE"
                    ,"ALLOWED_UNITS_LOOKUP_CODE"
                    ,"COST_OF_SALES_ACCOUNT"
                    ,"SALES_ACCOUNT"
                    ,"DEFAULT_INCLUDE_IN_ROLLUP_FLAG"
                    ,"INVENTORY_ITEM_STATUS_CODE"
                    ,"INVENTORY_PLANNING_CODE"
                    ,"PLANNER_CODE"
                    ,"PLANNING_MAKE_BUY_CODE"
                    ,"FIXED_LOT_MULTIPLIER"
                    ,"ROUNDING_CONTROL_TYPE"
                    ,"CARRYING_COST"
                    ,"POSTPROCESSING_LEAD_TIME"
                    ,"PREPROCESSING_LEAD_TIME"
                    ,"FULL_LEAD_TIME"
                    ,"ORDER_COST"
                    ,"MRP_SAFETY_STOCK_PERCENT"
                    ,"MRP_SAFETY_STOCK_CODE"
                    ,"MIN_MINMAX_QUANTITY"
                    ,"MAX_MINMAX_QUANTITY"
                    ,"MINIMUM_ORDER_QUANTITY"
                    ,"FIXED_ORDER_QUANTITY"
                    ,"FIXED_DAYS_SUPPLY"
                    ,"MAXIMUM_ORDER_QUANTITY"
                    ,"ATP_RULE_ID"
                    ,"PICKING_RULE_ID"
                    ,"RESERVABLE_TYPE"
                    ,"POSITIVE_MEASUREMENT_ERROR"
                    ,"NEGATIVE_MEASUREMENT_ERROR"
                    ,"ENGINEERING_ECN_CODE"
                    ,"ENGINEERING_ITEM_ID"
                    ,"ENGINEERING_DATE"
                    ,"SERVICE_STARTING_DELAY"
                    ,"VENDOR_WARRANTY_FLAG"
                    ,"SERVICEABLE_COMPONENT_FLAG"
                    ,"SERVICEABLE_PRODUCT_FLAG"
                    ,"BASE_WARRANTY_SERVICE_ID"
                    ,"PAYMENT_TERMS_ID"
                    ,"PREVENTIVE_MAINTENANCE_FLAG"
                    ,"PRIMARY_SPECIALIST_ID"
                    ,"SECONDARY_SPECIALIST_ID"
                    ,"SERVICEABLE_ITEM_CLASS_ID"
                    ,"TIME_BILLABLE_FLAG"
                    ,"MATERIAL_BILLABLE_FLAG"
                    ,"EXPENSE_BILLABLE_FLAG"
                    ,"PRORATE_SERVICE_FLAG"
                    ,"COVERAGE_SCHEDULE_ID"
                    ,"SERVICE_DURATION_PERIOD_CODE"
                    ,"SERVICE_DURATION"
                    ,"WARRANTY_VENDOR_ID"
                    ,"MAX_WARRANTY_AMOUNT"
                    ,"RESPONSE_TIME_PERIOD_CODE"
                    ,"RESPONSE_TIME_VALUE"
                    ,"NEW_REVISION_CODE"
                    ,"INVOICEABLE_ITEM_FLAG"
                    ,"TAX_CODE"
                    ,"INVOICE_ENABLED_FLAG"
                    ,"MUST_USE_APPROVED_VENDOR_FLAG"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"OUTSIDE_OPERATION_FLAG"
                    ,"OUTSIDE_OPERATION_UOM_TYPE"
                    ,"SAFETY_STOCK_BUCKET_DAYS"
                    ,"AUTO_REDUCE_MPS"
                    ,"COSTING_ENABLED_FLAG"
                    ,"AUTO_CREATED_CONFIG_FLAG"
                    ,"CYCLE_COUNT_ENABLED_FLAG"
                    ,"ITEM_TYPE"
                    ,"MODEL_CONFIG_CLAUSE_NAME"
                    ,"SHIP_MODEL_COMPLETE_FLAG"
                    ,"MRP_PLANNING_CODE"
                    ,"RETURN_INSPECTION_REQUIREMENT"
                    ,"ATO_FORECAST_CONTROL"
                    ,"RELEASE_TIME_FENCE_CODE"
                    ,"RELEASE_TIME_FENCE_DAYS"
                    ,"CONTAINER_ITEM_FLAG"
                    ,"VEHICLE_ITEM_FLAG"
                    ,"MAXIMUM_LOAD_WEIGHT"
                    ,"MINIMUM_FILL_PERCENT"
                    ,"CONTAINER_TYPE_CODE"
                    ,"INTERNAL_VOLUME"
                    ,"WH_UPDATE_DATE"
                    ,"PRODUCT_FAMILY_ITEM_ID"
                    ,"GLOBAL_ATTRIBUTE_CATEGORY"
                    ,"GLOBAL_ATTRIBUTE1"
                    ,"GLOBAL_ATTRIBUTE2"
                    ,"GLOBAL_ATTRIBUTE3"
                    ,"GLOBAL_ATTRIBUTE4"
                    ,"GLOBAL_ATTRIBUTE5"
                    ,"GLOBAL_ATTRIBUTE6"
                    ,"GLOBAL_ATTRIBUTE7"
                    ,"GLOBAL_ATTRIBUTE8"
                    ,"GLOBAL_ATTRIBUTE9"
                    ,"GLOBAL_ATTRIBUTE10"
                    ,"PURCHASING_TAX_CODE"
                    ,"OVERCOMPLETION_TOLERANCE_TYPE"
                    ,"OVERCOMPLETION_TOLERANCE_VALUE"
                    ,"EFFECTIVITY_CONTROL"
                    ,"CHECK_SHORTAGES_FLAG"
                    ,"OVER_SHIPMENT_TOLERANCE"
                    ,"UNDER_SHIPMENT_TOLERANCE"
                    ,"OVER_RETURN_TOLERANCE"
                    ,"UNDER_RETURN_TOLERANCE"
                    ,"EQUIPMENT_TYPE"
                    ,"RECOVERED_PART_DISP_CODE"
                    ,"DEFECT_TRACKING_ON_FLAG"
                    ,"USAGE_ITEM_FLAG"
                    ,"EVENT_FLAG"
                    ,"ELECTRONIC_FLAG"
                    ,"DOWNLOADABLE_FLAG"
                    ,"VOL_DISCOUNT_EXEMPT_FLAG"
                    ,"COUPON_EXEMPT_FLAG"
                    ,"COMMS_NL_TRACKABLE_FLAG"
                    ,"ASSET_CREATION_CODE"
                    ,"COMMS_ACTIVATION_REQD_FLAG"
                    ,"ORDERABLE_ON_WEB_FLAG"
                    ,"BACK_ORDERABLE_FLAG"
                    ,"WEB_STATUS"
                    ,"INDIVISIBLE_FLAG"
                    ,"DIMENSION_UOM_CODE"
                    ,"UNIT_LENGTH"
                    ,"UNIT_WIDTH"
                    ,"UNIT_HEIGHT"
                    ,"BULK_PICKED_FLAG"
                    ,"LOT_STATUS_ENABLED"
                    ,"DEFAULT_LOT_STATUS_ID"
                    ,"SERIAL_STATUS_ENABLED"
                    ,"DEFAULT_SERIAL_STATUS_ID"
                    ,"LOT_SPLIT_ENABLED"
                    ,"LOT_MERGE_ENABLED"
                    ,"INVENTORY_CARRY_PENALTY"
                    ,"OPERATION_SLACK_PENALTY"
                    ,"FINANCING_ALLOWED_FLAG"
                    ,"EAM_ITEM_TYPE"
                    ,"EAM_ACTIVITY_TYPE_CODE"
                    ,"EAM_ACTIVITY_CAUSE_CODE"
                    ,"EAM_ACT_NOTIFICATION_FLAG"
                    ,"EAM_ACT_SHUTDOWN_STATUS"
                    ,"DUAL_UOM_CONTROL"
                    ,"SECONDARY_UOM_CODE"
                    ,"DUAL_UOM_DEVIATION_HIGH"
                    ,"DUAL_UOM_DEVIATION_LOW"
                    ,"CONTRACT_ITEM_TYPE_CODE"
                    ,"SUBSCRIPTION_DEPEND_FLAG"
                    ,"SERV_REQ_ENABLED_CODE"
                    ,"SERV_BILLING_ENABLED_FLAG"
                    ,"SERV_IMPORTANCE_LEVEL"
                    ,"PLANNED_INV_POINT_FLAG"
                    ,"LOT_TRANSLATE_ENABLED"
                    ,"DEFAULT_SO_SOURCE_TYPE"
                    ,"CREATE_SUPPLY_FLAG"
                    ,"SUBSTITUTION_WINDOW_CODE"
                    ,"SUBSTITUTION_WINDOW_DAYS"
                    ,"IB_ITEM_INSTANCE_CLASS"
                    ,"CONFIG_MODEL_TYPE"
                    ,"LOT_SUBSTITUTION_ENABLED"
                    ,"MINIMUM_LICENSE_QUANTITY"
                    ,"EAM_ACTIVITY_SOURCE_CODE"
                    ,"LIFECYCLE_ID"
                    ,"CURRENT_PHASE_ID"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"TRACKING_QUANTITY_IND"
                    ,"ONT_PRICING_QTY_SOURCE"
                    ,"SECONDARY_DEFAULT_IND"
                    ,"OPTION_SPECIFIC_SOURCED"
                    ,"APPROVAL_STATUS"
                    ,"VMI_MINIMUM_UNITS"
                    ,"VMI_MINIMUM_DAYS"
                    ,"VMI_MAXIMUM_UNITS"
                    ,"VMI_MAXIMUM_DAYS"
                    ,"VMI_FIXED_ORDER_QUANTITY"
                    ,"SO_AUTHORIZATION_FLAG"
                    ,"CONSIGNED_FLAG"
                    ,"ASN_AUTOEXPIRE_FLAG"
                    ,"VMI_FORECAST_TYPE"
                    ,"FORECAST_HORIZON"
                    ,"EXCLUDE_FROM_BUDGET_FLAG"
                    ,"DAYS_TGT_INV_SUPPLY"
                    ,"DAYS_TGT_INV_WINDOW"
                    ,"DAYS_MAX_INV_SUPPLY"
                    ,"DAYS_MAX_INV_WINDOW"
                    ,"DRP_PLANNED_FLAG"
                    ,"CRITICAL_COMPONENT_FLAG"
                    ,"CONTINOUS_TRANSFER"
                    ,"CONVERGENCE"
                    ,"DIVERGENCE"
                    ,"CONFIG_ORGS"
                    ,"CONFIG_MATCH"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"ATTRIBUTE21"
                    ,"ATTRIBUTE22"
                    ,"ATTRIBUTE23"
                    ,"ATTRIBUTE24"
                    ,"ATTRIBUTE25"
                    ,"ATTRIBUTE26"
                    ,"ATTRIBUTE27"
                    ,"ATTRIBUTE28"
                    ,"ATTRIBUTE29"
                    ,"ATTRIBUTE30"
                    ,"CAS_NUMBER"
                    ,"CHILD_LOT_FLAG"
                    ,"CHILD_LOT_PREFIX"
                    ,"CHILD_LOT_STARTING_NUMBER"
                    ,"CHILD_LOT_VALIDATION_FLAG"
                    ,"COPY_LOT_ATTRIBUTE_FLAG"
                    ,"DEFAULT_GRADE"
                    ,"EXPIRATION_ACTION_CODE"
                    ,"EXPIRATION_ACTION_INTERVAL"
                    ,"GRADE_CONTROL_FLAG"
                    ,"HAZARDOUS_MATERIAL_FLAG"
                    ,"HOLD_DAYS"
                    ,"LOT_DIVISIBLE_FLAG"
                    ,"MATURITY_DAYS"
                    ,"PARENT_CHILD_GENERATION_FLAG"
                    ,"PROCESS_COSTING_ENABLED_FLAG"
                    ,"PROCESS_EXECUTION_ENABLED_FLAG"
                    ,"PROCESS_QUALITY_ENABLED_FLAG"
                    ,"PROCESS_SUPPLY_LOCATOR_ID"
                    ,"PROCESS_SUPPLY_SUBINVENTORY"
                    ,"PROCESS_YIELD_LOCATOR_ID"
                    ,"PROCESS_YIELD_SUBINVENTORY"
                    ,"RECIPE_ENABLED_FLAG"
                    ,"RETEST_INTERVAL"
                    ,"CHARGE_PERIODICITY_CODE"
                    ,"REPAIR_LEADTIME"
                    ,"REPAIR_YIELD"
                    ,"PREPOSITION_POINT"
                    ,"REPAIR_PROGRAM"
                    ,"SUBCONTRACTING_COMPONENT"
                    ,"OUTSOURCED_ASSEMBLY"
                    ,"EGO_MASTER_ITEMS_DFF_CTX"
                    ,"GDSN_OUTBOUND_ENABLED_FLAG"
                    ,"TRADE_ITEM_DESCRIPTOR"
                    ,"STYLE_ITEM_ID"
                    ,"STYLE_ITEM_FLAG"
                    ,"LAST_SUBMITTED_NIR_ID"
                    ,"DEFAULT_MATERIAL_STATUS_ID"
                    ,"GLOBAL_ATTRIBUTE11"
                    ,"GLOBAL_ATTRIBUTE12"
                    ,"GLOBAL_ATTRIBUTE13"
                    ,"GLOBAL_ATTRIBUTE14"
                    ,"GLOBAL_ATTRIBUTE15"
                    ,"GLOBAL_ATTRIBUTE16"
                    ,"GLOBAL_ATTRIBUTE17"
                    ,"GLOBAL_ATTRIBUTE18"
                    ,"GLOBAL_ATTRIBUTE19"
                    ,"GLOBAL_ATTRIBUTE20"
                    ,"SERIAL_TAGGING_FLAG"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("INVENTORY_ITEM_ID" AS float) AS "INVENTORY_ITEM_ID"
                        ,CAST("ORGANIZATION_ID" AS float) AS "ORGANIZATION_ID"
                        ,TRY_CONVERT(datetime2,"LAST_UPDATE_DATE",121) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,TRY_CONVERT(datetime2,"CREATION_DATE",121) AS "CREATION_DATE"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("SUMMARY_FLAG" AS varchar(100) ) AS "SUMMARY_FLAG"
                        ,CAST("ENABLED_FLAG" AS varchar(100) ) AS "ENABLED_FLAG"
                        ,TRY_CONVERT(datetime2,"START_DATE_ACTIVE",121) AS "START_DATE_ACTIVE"
                        ,TRY_CONVERT(datetime2,"END_DATE_ACTIVE",121) AS "END_DATE_ACTIVE"
                        ,CAST("DESCRIPTION" AS varchar(1000) ) AS "DESCRIPTION"
                        ,CAST("BUYER_ID" AS float) AS "BUYER_ID"
                        ,CAST("ACCOUNTING_RULE_ID" AS float) AS "ACCOUNTING_RULE_ID"
                        ,CAST("INVOICING_RULE_ID" AS float) AS "INVOICING_RULE_ID"
                        ,CAST("SEGMENT1" AS varchar(100) ) AS "SEGMENT1"
                        ,CAST("SEGMENT2" AS varchar(100) ) AS "SEGMENT2"
                        ,CAST("SEGMENT3" AS varchar(100) ) AS "SEGMENT3"
                        ,CAST("SEGMENT4" AS varchar(100) ) AS "SEGMENT4"
                        ,CAST("SEGMENT5" AS varchar(100) ) AS "SEGMENT5"
                        ,CAST("SEGMENT6" AS varchar(100) ) AS "SEGMENT6"
                        ,CAST("SEGMENT7" AS varchar(100) ) AS "SEGMENT7"
                        ,CAST("SEGMENT8" AS varchar(100) ) AS "SEGMENT8"
                        ,CAST("SEGMENT9" AS varchar(100) ) AS "SEGMENT9"
                        ,CAST("SEGMENT10" AS varchar(100) ) AS "SEGMENT10"
                        ,CAST("SEGMENT11" AS varchar(100) ) AS "SEGMENT11"
                        ,CAST("SEGMENT12" AS varchar(100) ) AS "SEGMENT12"
                        ,CAST("SEGMENT13" AS varchar(100) ) AS "SEGMENT13"
                        ,CAST("SEGMENT14" AS varchar(100) ) AS "SEGMENT14"
                        ,CAST("SEGMENT15" AS varchar(100) ) AS "SEGMENT15"
                        ,CAST("SEGMENT16" AS varchar(100) ) AS "SEGMENT16"
                        ,CAST("SEGMENT17" AS varchar(100) ) AS "SEGMENT17"
                        ,CAST("SEGMENT18" AS varchar(100) ) AS "SEGMENT18"
                        ,CAST("SEGMENT19" AS varchar(100) ) AS "SEGMENT19"
                        ,CAST("SEGMENT20" AS varchar(100) ) AS "SEGMENT20"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("PURCHASING_ITEM_FLAG" AS varchar(100) ) AS "PURCHASING_ITEM_FLAG"
                        ,CAST("SHIPPABLE_ITEM_FLAG" AS varchar(100) ) AS "SHIPPABLE_ITEM_FLAG"
                        ,CAST("CUSTOMER_ORDER_FLAG" AS varchar(100) ) AS "CUSTOMER_ORDER_FLAG"
                        ,CAST("INTERNAL_ORDER_FLAG" AS varchar(100) ) AS "INTERNAL_ORDER_FLAG"
                        ,CAST("SERVICE_ITEM_FLAG" AS varchar(100) ) AS "SERVICE_ITEM_FLAG"
                        ,CAST("INVENTORY_ITEM_FLAG" AS varchar(100) ) AS "INVENTORY_ITEM_FLAG"
                        ,CAST("ENG_ITEM_FLAG" AS varchar(100) ) AS "ENG_ITEM_FLAG"
                        ,CAST("INVENTORY_ASSET_FLAG" AS varchar(100) ) AS "INVENTORY_ASSET_FLAG"
                        ,CAST("PURCHASING_ENABLED_FLAG" AS varchar(100) ) AS "PURCHASING_ENABLED_FLAG"
                        ,CAST("CUSTOMER_ORDER_ENABLED_FLAG" AS varchar(100) ) AS "CUSTOMER_ORDER_ENABLED_FLAG"
                        ,CAST("INTERNAL_ORDER_ENABLED_FLAG" AS varchar(100) ) AS "INTERNAL_ORDER_ENABLED_FLAG"
                        ,CAST("SO_TRANSACTIONS_FLAG" AS varchar(100) ) AS "SO_TRANSACTIONS_FLAG"
                        ,CAST("MTL_TRANSACTIONS_ENABLED_FLAG" AS varchar(100) ) AS "MTL_TRANSACTIONS_ENABLED_FLAG"
                        ,CAST("STOCK_ENABLED_FLAG" AS varchar(100) ) AS "STOCK_ENABLED_FLAG"
                        ,CAST("BOM_ENABLED_FLAG" AS varchar(100) ) AS "BOM_ENABLED_FLAG"
                        ,CAST("BUILD_IN_WIP_FLAG" AS varchar(100) ) AS "BUILD_IN_WIP_FLAG"
                        ,CAST("REVISION_QTY_CONTROL_CODE" AS float) AS "REVISION_QTY_CONTROL_CODE"
                        ,CAST("ITEM_CATALOG_GROUP_ID" AS float) AS "ITEM_CATALOG_GROUP_ID"
                        ,CAST("CATALOG_STATUS_FLAG" AS varchar(100) ) AS "CATALOG_STATUS_FLAG"
                        ,CAST("RETURNABLE_FLAG" AS varchar(100) ) AS "RETURNABLE_FLAG"
                        ,CAST("DEFAULT_SHIPPING_ORG" AS float) AS "DEFAULT_SHIPPING_ORG"
                        ,CAST("COLLATERAL_FLAG" AS varchar(100) ) AS "COLLATERAL_FLAG"
                        ,CAST("TAXABLE_FLAG" AS varchar(100) ) AS "TAXABLE_FLAG"
                        ,CAST("QTY_RCV_EXCEPTION_CODE" AS varchar(100) ) AS "QTY_RCV_EXCEPTION_CODE"
                        ,CAST("ALLOW_ITEM_DESC_UPDATE_FLAG" AS varchar(100) ) AS "ALLOW_ITEM_DESC_UPDATE_FLAG"
                        ,CAST("INSPECTION_REQUIRED_FLAG" AS varchar(100) ) AS "INSPECTION_REQUIRED_FLAG"
                        ,CAST("RECEIPT_REQUIRED_FLAG" AS varchar(100) ) AS "RECEIPT_REQUIRED_FLAG"
                        ,CAST("MARKET_PRICE" AS float) AS "MARKET_PRICE"
                        ,CAST("HAZARD_CLASS_ID" AS float) AS "HAZARD_CLASS_ID"
                        ,CAST("RFQ_REQUIRED_FLAG" AS varchar(100) ) AS "RFQ_REQUIRED_FLAG"
                        ,CAST("QTY_RCV_TOLERANCE" AS float) AS "QTY_RCV_TOLERANCE"
                        ,CAST("LIST_PRICE_PER_UNIT" AS float) AS "LIST_PRICE_PER_UNIT"
                        ,CAST("UN_NUMBER_ID" AS float) AS "UN_NUMBER_ID"
                        ,CAST("PRICE_TOLERANCE_PERCENT" AS float) AS "PRICE_TOLERANCE_PERCENT"
                        ,CAST("ASSET_CATEGORY_ID" AS float) AS "ASSET_CATEGORY_ID"
                        ,CAST("ROUNDING_FACTOR" AS float) AS "ROUNDING_FACTOR"
                        ,CAST("UNIT_OF_ISSUE" AS varchar(100) ) AS "UNIT_OF_ISSUE"
                        ,CAST("ENFORCE_SHIP_TO_LOCATION_CODE" AS varchar(100) ) AS "ENFORCE_SHIP_TO_LOCATION_CODE"
                        ,CAST("ALLOW_SUBSTITUTE_RECEIPTS_FLAG" AS varchar(100) ) AS "ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                        ,CAST("ALLOW_UNORDERED_RECEIPTS_FLAG" AS varchar(100) ) AS "ALLOW_UNORDERED_RECEIPTS_FLAG"
                        ,CAST("ALLOW_EXPRESS_DELIVERY_FLAG" AS varchar(100) ) AS "ALLOW_EXPRESS_DELIVERY_FLAG"
                        ,CAST("DAYS_EARLY_RECEIPT_ALLOWED" AS float) AS "DAYS_EARLY_RECEIPT_ALLOWED"
                        ,CAST("DAYS_LATE_RECEIPT_ALLOWED" AS float) AS "DAYS_LATE_RECEIPT_ALLOWED"
                        ,CAST("RECEIPT_DAYS_EXCEPTION_CODE" AS varchar(100) ) AS "RECEIPT_DAYS_EXCEPTION_CODE"
                        ,CAST("RECEIVING_ROUTING_ID" AS float) AS "RECEIVING_ROUTING_ID"
                        ,CAST("INVOICE_CLOSE_TOLERANCE" AS float) AS "INVOICE_CLOSE_TOLERANCE"
                        ,CAST("RECEIVE_CLOSE_TOLERANCE" AS float) AS "RECEIVE_CLOSE_TOLERANCE"
                        ,CAST("AUTO_LOT_ALPHA_PREFIX" AS varchar(100) ) AS "AUTO_LOT_ALPHA_PREFIX"
                        ,CAST("START_AUTO_LOT_NUMBER" AS varchar(100) ) AS "START_AUTO_LOT_NUMBER"
                        ,CAST("LOT_CONTROL_CODE" AS float) AS "LOT_CONTROL_CODE"
                        ,CAST("SHELF_LIFE_CODE" AS float) AS "SHELF_LIFE_CODE"
                        ,CAST("SHELF_LIFE_DAYS" AS float) AS "SHELF_LIFE_DAYS"
                        ,CAST("SERIAL_NUMBER_CONTROL_CODE" AS float) AS "SERIAL_NUMBER_CONTROL_CODE"
                        ,CAST("START_AUTO_SERIAL_NUMBER" AS varchar(100) ) AS "START_AUTO_SERIAL_NUMBER"
                        ,CAST("AUTO_SERIAL_ALPHA_PREFIX" AS varchar(100) ) AS "AUTO_SERIAL_ALPHA_PREFIX"
                        ,CAST("SOURCE_TYPE" AS float) AS "SOURCE_TYPE"
                        ,CAST("SOURCE_ORGANIZATION_ID" AS float) AS "SOURCE_ORGANIZATION_ID"
                        ,CAST("SOURCE_SUBINVENTORY" AS varchar(100) ) AS "SOURCE_SUBINVENTORY"
                        ,CAST("EXPENSE_ACCOUNT" AS float) AS "EXPENSE_ACCOUNT"
                        ,CAST("ENCUMBRANCE_ACCOUNT" AS float) AS "ENCUMBRANCE_ACCOUNT"
                        ,CAST("RESTRICT_SUBINVENTORIES_CODE" AS float) AS "RESTRICT_SUBINVENTORIES_CODE"
                        ,CAST("UNIT_WEIGHT" AS float) AS "UNIT_WEIGHT"
                        ,CAST("WEIGHT_UOM_CODE" AS varchar(100) ) AS "WEIGHT_UOM_CODE"
                        ,CAST("VOLUME_UOM_CODE" AS varchar(100) ) AS "VOLUME_UOM_CODE"
                        ,CAST("UNIT_VOLUME" AS float) AS "UNIT_VOLUME"
                        ,CAST("RESTRICT_LOCATORS_CODE" AS float) AS "RESTRICT_LOCATORS_CODE"
                        ,CAST("LOCATION_CONTROL_CODE" AS float) AS "LOCATION_CONTROL_CODE"
                        ,CAST("SHRINKAGE_RATE" AS float) AS "SHRINKAGE_RATE"
                        ,CAST("ACCEPTABLE_EARLY_DAYS" AS float) AS "ACCEPTABLE_EARLY_DAYS"
                        ,CAST("PLANNING_TIME_FENCE_CODE" AS float) AS "PLANNING_TIME_FENCE_CODE"
                        ,CAST("DEMAND_TIME_FENCE_CODE" AS float) AS "DEMAND_TIME_FENCE_CODE"
                        ,CAST("LEAD_TIME_LOT_SIZE" AS float) AS "LEAD_TIME_LOT_SIZE"
                        ,CAST("STD_LOT_SIZE" AS float) AS "STD_LOT_SIZE"
                        ,CAST("CUM_MANUFACTURING_LEAD_TIME" AS float) AS "CUM_MANUFACTURING_LEAD_TIME"
                        ,CAST("OVERRUN_PERCENTAGE" AS float) AS "OVERRUN_PERCENTAGE"
                        ,CAST("MRP_CALCULATE_ATP_FLAG" AS varchar(100) ) AS "MRP_CALCULATE_ATP_FLAG"
                        ,CAST("ACCEPTABLE_RATE_INCREASE" AS float) AS "ACCEPTABLE_RATE_INCREASE"
                        ,CAST("ACCEPTABLE_RATE_DECREASE" AS float) AS "ACCEPTABLE_RATE_DECREASE"
                        ,CAST("CUMULATIVE_TOTAL_LEAD_TIME" AS float) AS "CUMULATIVE_TOTAL_LEAD_TIME"
                        ,CAST("PLANNING_TIME_FENCE_DAYS" AS float) AS "PLANNING_TIME_FENCE_DAYS"
                        ,CAST("DEMAND_TIME_FENCE_DAYS" AS float) AS "DEMAND_TIME_FENCE_DAYS"
                        ,CAST("END_ASSEMBLY_PEGGING_FLAG" AS varchar(100) ) AS "END_ASSEMBLY_PEGGING_FLAG"
                        ,CAST("REPETITIVE_PLANNING_FLAG" AS varchar(100) ) AS "REPETITIVE_PLANNING_FLAG"
                        ,CAST("PLANNING_EXCEPTION_SET" AS varchar(100) ) AS "PLANNING_EXCEPTION_SET"
                        ,CAST("BOM_ITEM_TYPE" AS float) AS "BOM_ITEM_TYPE"
                        ,CAST("PICK_COMPONENTS_FLAG" AS varchar(100) ) AS "PICK_COMPONENTS_FLAG"
                        ,CAST("REPLENISH_TO_ORDER_FLAG" AS varchar(100) ) AS "REPLENISH_TO_ORDER_FLAG"
                        ,CAST("BASE_ITEM_ID" AS float) AS "BASE_ITEM_ID"
                        ,CAST("ATP_COMPONENTS_FLAG" AS varchar(100) ) AS "ATP_COMPONENTS_FLAG"
                        ,CAST("ATP_FLAG" AS varchar(100) ) AS "ATP_FLAG"
                        ,CAST("FIXED_LEAD_TIME" AS float) AS "FIXED_LEAD_TIME"
                        ,CAST("VARIABLE_LEAD_TIME" AS float) AS "VARIABLE_LEAD_TIME"
                        ,CAST("WIP_SUPPLY_LOCATOR_ID" AS float) AS "WIP_SUPPLY_LOCATOR_ID"
                        ,CAST("WIP_SUPPLY_TYPE" AS float) AS "WIP_SUPPLY_TYPE"
                        ,CAST("WIP_SUPPLY_SUBINVENTORY" AS varchar(100) ) AS "WIP_SUPPLY_SUBINVENTORY"
                        ,CAST("PRIMARY_UOM_CODE" AS varchar(100) ) AS "PRIMARY_UOM_CODE"
                        ,CAST("PRIMARY_UNIT_OF_MEASURE" AS varchar(100) ) AS "PRIMARY_UNIT_OF_MEASURE"
                        ,CAST("ALLOWED_UNITS_LOOKUP_CODE" AS float) AS "ALLOWED_UNITS_LOOKUP_CODE"
                        ,CAST("COST_OF_SALES_ACCOUNT" AS float) AS "COST_OF_SALES_ACCOUNT"
                        ,CAST("SALES_ACCOUNT" AS float) AS "SALES_ACCOUNT"
                        ,CAST("DEFAULT_INCLUDE_IN_ROLLUP_FLAG" AS varchar(100) ) AS "DEFAULT_INCLUDE_IN_ROLLUP_FLAG"
                        ,CAST("INVENTORY_ITEM_STATUS_CODE" AS varchar(100) ) AS "INVENTORY_ITEM_STATUS_CODE"
                        ,CAST("INVENTORY_PLANNING_CODE" AS float) AS "INVENTORY_PLANNING_CODE"
                        ,CAST("PLANNER_CODE" AS varchar(100) ) AS "PLANNER_CODE"
                        ,CAST("PLANNING_MAKE_BUY_CODE" AS float) AS "PLANNING_MAKE_BUY_CODE"
                        ,CAST("FIXED_LOT_MULTIPLIER" AS float) AS "FIXED_LOT_MULTIPLIER"
                        ,CAST("ROUNDING_CONTROL_TYPE" AS float) AS "ROUNDING_CONTROL_TYPE"
                        ,CAST("CARRYING_COST" AS float) AS "CARRYING_COST"
                        ,CAST("POSTPROCESSING_LEAD_TIME" AS float) AS "POSTPROCESSING_LEAD_TIME"
                        ,CAST("PREPROCESSING_LEAD_TIME" AS float) AS "PREPROCESSING_LEAD_TIME"
                        ,CAST("FULL_LEAD_TIME" AS float) AS "FULL_LEAD_TIME"
                        ,CAST("ORDER_COST" AS float) AS "ORDER_COST"
                        ,CAST("MRP_SAFETY_STOCK_PERCENT" AS float) AS "MRP_SAFETY_STOCK_PERCENT"
                        ,CAST("MRP_SAFETY_STOCK_CODE" AS float) AS "MRP_SAFETY_STOCK_CODE"
                        ,CAST("MIN_MINMAX_QUANTITY" AS float) AS "MIN_MINMAX_QUANTITY"
                        ,CAST("MAX_MINMAX_QUANTITY" AS float) AS "MAX_MINMAX_QUANTITY"
                        ,CAST("MINIMUM_ORDER_QUANTITY" AS float) AS "MINIMUM_ORDER_QUANTITY"
                        ,CAST("FIXED_ORDER_QUANTITY" AS float) AS "FIXED_ORDER_QUANTITY"
                        ,CAST("FIXED_DAYS_SUPPLY" AS float) AS "FIXED_DAYS_SUPPLY"
                        ,CAST("MAXIMUM_ORDER_QUANTITY" AS float) AS "MAXIMUM_ORDER_QUANTITY"
                        ,CAST("ATP_RULE_ID" AS float) AS "ATP_RULE_ID"
                        ,CAST("PICKING_RULE_ID" AS float) AS "PICKING_RULE_ID"
                        ,CAST("RESERVABLE_TYPE" AS float) AS "RESERVABLE_TYPE"
                        ,CAST("POSITIVE_MEASUREMENT_ERROR" AS float) AS "POSITIVE_MEASUREMENT_ERROR"
                        ,CAST("NEGATIVE_MEASUREMENT_ERROR" AS float) AS "NEGATIVE_MEASUREMENT_ERROR"
                        ,CAST("ENGINEERING_ECN_CODE" AS varchar(1000) ) AS "ENGINEERING_ECN_CODE"
                        ,CAST("ENGINEERING_ITEM_ID" AS float) AS "ENGINEERING_ITEM_ID"
                        ,TRY_CONVERT(datetime2,"ENGINEERING_DATE",121) AS "ENGINEERING_DATE"
                        ,CAST("SERVICE_STARTING_DELAY" AS float) AS "SERVICE_STARTING_DELAY"
                        ,CAST("VENDOR_WARRANTY_FLAG" AS varchar(100) ) AS "VENDOR_WARRANTY_FLAG"
                        ,CAST("SERVICEABLE_COMPONENT_FLAG" AS varchar(100) ) AS "SERVICEABLE_COMPONENT_FLAG"
                        ,CAST("SERVICEABLE_PRODUCT_FLAG" AS varchar(100) ) AS "SERVICEABLE_PRODUCT_FLAG"
                        ,CAST("BASE_WARRANTY_SERVICE_ID" AS float) AS "BASE_WARRANTY_SERVICE_ID"
                        ,CAST("PAYMENT_TERMS_ID" AS float) AS "PAYMENT_TERMS_ID"
                        ,CAST("PREVENTIVE_MAINTENANCE_FLAG" AS varchar(100) ) AS "PREVENTIVE_MAINTENANCE_FLAG"
                        ,CAST("PRIMARY_SPECIALIST_ID" AS float) AS "PRIMARY_SPECIALIST_ID"
                        ,CAST("SECONDARY_SPECIALIST_ID" AS float) AS "SECONDARY_SPECIALIST_ID"
                        ,CAST("SERVICEABLE_ITEM_CLASS_ID" AS float) AS "SERVICEABLE_ITEM_CLASS_ID"
                        ,CAST("TIME_BILLABLE_FLAG" AS varchar(100) ) AS "TIME_BILLABLE_FLAG"
                        ,CAST("MATERIAL_BILLABLE_FLAG" AS varchar(100) ) AS "MATERIAL_BILLABLE_FLAG"
                        ,CAST("EXPENSE_BILLABLE_FLAG" AS varchar(100) ) AS "EXPENSE_BILLABLE_FLAG"
                        ,CAST("PRORATE_SERVICE_FLAG" AS varchar(100) ) AS "PRORATE_SERVICE_FLAG"
                        ,CAST("COVERAGE_SCHEDULE_ID" AS float) AS "COVERAGE_SCHEDULE_ID"
                        ,CAST("SERVICE_DURATION_PERIOD_CODE" AS varchar(100) ) AS "SERVICE_DURATION_PERIOD_CODE"
                        ,CAST("SERVICE_DURATION" AS float) AS "SERVICE_DURATION"
                        ,CAST("WARRANTY_VENDOR_ID" AS float) AS "WARRANTY_VENDOR_ID"
                        ,CAST("MAX_WARRANTY_AMOUNT" AS float) AS "MAX_WARRANTY_AMOUNT"
                        ,CAST("RESPONSE_TIME_PERIOD_CODE" AS varchar(100) ) AS "RESPONSE_TIME_PERIOD_CODE"
                        ,CAST("RESPONSE_TIME_VALUE" AS float) AS "RESPONSE_TIME_VALUE"
                        ,CAST("NEW_REVISION_CODE" AS varchar(100) ) AS "NEW_REVISION_CODE"
                        ,CAST("INVOICEABLE_ITEM_FLAG" AS varchar(100) ) AS "INVOICEABLE_ITEM_FLAG"
                        ,CAST("TAX_CODE" AS varchar(1000) ) AS "TAX_CODE"
                        ,CAST("INVOICE_ENABLED_FLAG" AS varchar(100) ) AS "INVOICE_ENABLED_FLAG"
                        ,CAST("MUST_USE_APPROVED_VENDOR_FLAG" AS varchar(100) ) AS "MUST_USE_APPROVED_VENDOR_FLAG"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,TRY_CONVERT(datetime2,"PROGRAM_UPDATE_DATE",121) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("OUTSIDE_OPERATION_FLAG" AS varchar(100) ) AS "OUTSIDE_OPERATION_FLAG"
                        ,CAST("OUTSIDE_OPERATION_UOM_TYPE" AS varchar(100) ) AS "OUTSIDE_OPERATION_UOM_TYPE"
                        ,CAST("SAFETY_STOCK_BUCKET_DAYS" AS float) AS "SAFETY_STOCK_BUCKET_DAYS"
                        ,CAST("AUTO_REDUCE_MPS" AS float) AS "AUTO_REDUCE_MPS"
                        ,CAST("COSTING_ENABLED_FLAG" AS varchar(100) ) AS "COSTING_ENABLED_FLAG"
                        ,CAST("AUTO_CREATED_CONFIG_FLAG" AS varchar(100) ) AS "AUTO_CREATED_CONFIG_FLAG"
                        ,CAST("CYCLE_COUNT_ENABLED_FLAG" AS varchar(100) ) AS "CYCLE_COUNT_ENABLED_FLAG"
                        ,CAST("ITEM_TYPE" AS varchar(100) ) AS "ITEM_TYPE"
                        ,CAST("MODEL_CONFIG_CLAUSE_NAME" AS varchar(100) ) AS "MODEL_CONFIG_CLAUSE_NAME"
                        ,CAST("SHIP_MODEL_COMPLETE_FLAG" AS varchar(100) ) AS "SHIP_MODEL_COMPLETE_FLAG"
                        ,CAST("MRP_PLANNING_CODE" AS float) AS "MRP_PLANNING_CODE"
                        ,CAST("RETURN_INSPECTION_REQUIREMENT" AS float) AS "RETURN_INSPECTION_REQUIREMENT"
                        ,CAST("ATO_FORECAST_CONTROL" AS float) AS "ATO_FORECAST_CONTROL"
                        ,CAST("RELEASE_TIME_FENCE_CODE" AS float) AS "RELEASE_TIME_FENCE_CODE"
                        ,CAST("RELEASE_TIME_FENCE_DAYS" AS float) AS "RELEASE_TIME_FENCE_DAYS"
                        ,CAST("CONTAINER_ITEM_FLAG" AS varchar(100) ) AS "CONTAINER_ITEM_FLAG"
                        ,CAST("VEHICLE_ITEM_FLAG" AS varchar(100) ) AS "VEHICLE_ITEM_FLAG"
                        ,CAST("MAXIMUM_LOAD_WEIGHT" AS float) AS "MAXIMUM_LOAD_WEIGHT"
                        ,CAST("MINIMUM_FILL_PERCENT" AS float) AS "MINIMUM_FILL_PERCENT"
                        ,CAST("CONTAINER_TYPE_CODE" AS varchar(100) ) AS "CONTAINER_TYPE_CODE"
                        ,CAST("INTERNAL_VOLUME" AS float) AS "INTERNAL_VOLUME"
                        ,TRY_CONVERT(datetime2,"WH_UPDATE_DATE",121) AS "WH_UPDATE_DATE"
                        ,CAST("PRODUCT_FAMILY_ITEM_ID" AS float) AS "PRODUCT_FAMILY_ITEM_ID"
                        ,CAST("GLOBAL_ATTRIBUTE_CATEGORY" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE_CATEGORY"
                        ,CAST("GLOBAL_ATTRIBUTE1" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE1"
                        ,CAST("GLOBAL_ATTRIBUTE2" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE2"
                        ,CAST("GLOBAL_ATTRIBUTE3" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE3"
                        ,CAST("GLOBAL_ATTRIBUTE4" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE4"
                        ,CAST("GLOBAL_ATTRIBUTE5" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE5"
                        ,CAST("GLOBAL_ATTRIBUTE6" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE6"
                        ,CAST("GLOBAL_ATTRIBUTE7" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE7"
                        ,CAST("GLOBAL_ATTRIBUTE8" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE8"
                        ,CAST("GLOBAL_ATTRIBUTE9" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE9"
                        ,CAST("GLOBAL_ATTRIBUTE10" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE10"
                        ,CAST("PURCHASING_TAX_CODE" AS varchar(1000) ) AS "PURCHASING_TAX_CODE"
                        ,CAST("OVERCOMPLETION_TOLERANCE_TYPE" AS float) AS "OVERCOMPLETION_TOLERANCE_TYPE"
                        ,CAST("OVERCOMPLETION_TOLERANCE_VALUE" AS float) AS "OVERCOMPLETION_TOLERANCE_VALUE"
                        ,CAST("EFFECTIVITY_CONTROL" AS float) AS "EFFECTIVITY_CONTROL"
                        ,CAST("CHECK_SHORTAGES_FLAG" AS varchar(100) ) AS "CHECK_SHORTAGES_FLAG"
                        ,CAST("OVER_SHIPMENT_TOLERANCE" AS float) AS "OVER_SHIPMENT_TOLERANCE"
                        ,CAST("UNDER_SHIPMENT_TOLERANCE" AS float) AS "UNDER_SHIPMENT_TOLERANCE"
                        ,CAST("OVER_RETURN_TOLERANCE" AS float) AS "OVER_RETURN_TOLERANCE"
                        ,CAST("UNDER_RETURN_TOLERANCE" AS float) AS "UNDER_RETURN_TOLERANCE"
                        ,CAST("EQUIPMENT_TYPE" AS float) AS "EQUIPMENT_TYPE"
                        ,CAST("RECOVERED_PART_DISP_CODE" AS varchar(100) ) AS "RECOVERED_PART_DISP_CODE"
                        ,CAST("DEFECT_TRACKING_ON_FLAG" AS varchar(100) ) AS "DEFECT_TRACKING_ON_FLAG"
                        ,CAST("USAGE_ITEM_FLAG" AS varchar(100) ) AS "USAGE_ITEM_FLAG"
                        ,CAST("EVENT_FLAG" AS varchar(100) ) AS "EVENT_FLAG"
                        ,CAST("ELECTRONIC_FLAG" AS varchar(100) ) AS "ELECTRONIC_FLAG"
                        ,CAST("DOWNLOADABLE_FLAG" AS varchar(100) ) AS "DOWNLOADABLE_FLAG"
                        ,CAST("VOL_DISCOUNT_EXEMPT_FLAG" AS varchar(100) ) AS "VOL_DISCOUNT_EXEMPT_FLAG"
                        ,CAST("COUPON_EXEMPT_FLAG" AS varchar(100) ) AS "COUPON_EXEMPT_FLAG"
                        ,CAST("COMMS_NL_TRACKABLE_FLAG" AS varchar(100) ) AS "COMMS_NL_TRACKABLE_FLAG"
                        ,CAST("ASSET_CREATION_CODE" AS varchar(100) ) AS "ASSET_CREATION_CODE"
                        ,CAST("COMMS_ACTIVATION_REQD_FLAG" AS varchar(100) ) AS "COMMS_ACTIVATION_REQD_FLAG"
                        ,CAST("ORDERABLE_ON_WEB_FLAG" AS varchar(100) ) AS "ORDERABLE_ON_WEB_FLAG"
                        ,CAST("BACK_ORDERABLE_FLAG" AS varchar(100) ) AS "BACK_ORDERABLE_FLAG"
                        ,CAST("WEB_STATUS" AS varchar(100) ) AS "WEB_STATUS"
                        ,CAST("INDIVISIBLE_FLAG" AS varchar(100) ) AS "INDIVISIBLE_FLAG"
                        ,CAST("DIMENSION_UOM_CODE" AS varchar(100) ) AS "DIMENSION_UOM_CODE"
                        ,CAST("UNIT_LENGTH" AS float) AS "UNIT_LENGTH"
                        ,CAST("UNIT_WIDTH" AS float) AS "UNIT_WIDTH"
                        ,CAST("UNIT_HEIGHT" AS float) AS "UNIT_HEIGHT"
                        ,CAST("BULK_PICKED_FLAG" AS varchar(100) ) AS "BULK_PICKED_FLAG"
                        ,CAST("LOT_STATUS_ENABLED" AS varchar(100) ) AS "LOT_STATUS_ENABLED"
                        ,CAST("DEFAULT_LOT_STATUS_ID" AS float) AS "DEFAULT_LOT_STATUS_ID"
                        ,CAST("SERIAL_STATUS_ENABLED" AS varchar(100) ) AS "SERIAL_STATUS_ENABLED"
                        ,CAST("DEFAULT_SERIAL_STATUS_ID" AS float) AS "DEFAULT_SERIAL_STATUS_ID"
                        ,CAST("LOT_SPLIT_ENABLED" AS varchar(100) ) AS "LOT_SPLIT_ENABLED"
                        ,CAST("LOT_MERGE_ENABLED" AS varchar(100) ) AS "LOT_MERGE_ENABLED"
                        ,CAST("INVENTORY_CARRY_PENALTY" AS float) AS "INVENTORY_CARRY_PENALTY"
                        ,CAST("OPERATION_SLACK_PENALTY" AS float) AS "OPERATION_SLACK_PENALTY"
                        ,CAST("FINANCING_ALLOWED_FLAG" AS varchar(100) ) AS "FINANCING_ALLOWED_FLAG"
                        ,CAST("EAM_ITEM_TYPE" AS float) AS "EAM_ITEM_TYPE"
                        ,CAST("EAM_ACTIVITY_TYPE_CODE" AS varchar(100) ) AS "EAM_ACTIVITY_TYPE_CODE"
                        ,CAST("EAM_ACTIVITY_CAUSE_CODE" AS varchar(100) ) AS "EAM_ACTIVITY_CAUSE_CODE"
                        ,CAST("EAM_ACT_NOTIFICATION_FLAG" AS varchar(100) ) AS "EAM_ACT_NOTIFICATION_FLAG"
                        ,CAST("EAM_ACT_SHUTDOWN_STATUS" AS varchar(100) ) AS "EAM_ACT_SHUTDOWN_STATUS"
                        ,CAST("DUAL_UOM_CONTROL" AS float) AS "DUAL_UOM_CONTROL"
                        ,CAST("SECONDARY_UOM_CODE" AS varchar(100) ) AS "SECONDARY_UOM_CODE"
                        ,CAST("DUAL_UOM_DEVIATION_HIGH" AS float) AS "DUAL_UOM_DEVIATION_HIGH"
                        ,CAST("DUAL_UOM_DEVIATION_LOW" AS float) AS "DUAL_UOM_DEVIATION_LOW"
                        ,CAST("CONTRACT_ITEM_TYPE_CODE" AS varchar(100) ) AS "CONTRACT_ITEM_TYPE_CODE"
                        ,CAST("SUBSCRIPTION_DEPEND_FLAG" AS varchar(100) ) AS "SUBSCRIPTION_DEPEND_FLAG"
                        ,CAST("SERV_REQ_ENABLED_CODE" AS varchar(100) ) AS "SERV_REQ_ENABLED_CODE"
                        ,CAST("SERV_BILLING_ENABLED_FLAG" AS varchar(100) ) AS "SERV_BILLING_ENABLED_FLAG"
                        ,CAST("SERV_IMPORTANCE_LEVEL" AS float) AS "SERV_IMPORTANCE_LEVEL"
                        ,CAST("PLANNED_INV_POINT_FLAG" AS varchar(100) ) AS "PLANNED_INV_POINT_FLAG"
                        ,CAST("LOT_TRANSLATE_ENABLED" AS varchar(100) ) AS "LOT_TRANSLATE_ENABLED"
                        ,CAST("DEFAULT_SO_SOURCE_TYPE" AS varchar(100) ) AS "DEFAULT_SO_SOURCE_TYPE"
                        ,CAST("CREATE_SUPPLY_FLAG" AS varchar(100) ) AS "CREATE_SUPPLY_FLAG"
                        ,CAST("SUBSTITUTION_WINDOW_CODE" AS float) AS "SUBSTITUTION_WINDOW_CODE"
                        ,CAST("SUBSTITUTION_WINDOW_DAYS" AS float) AS "SUBSTITUTION_WINDOW_DAYS"
                        ,CAST("IB_ITEM_INSTANCE_CLASS" AS varchar(100) ) AS "IB_ITEM_INSTANCE_CLASS"
                        ,CAST("CONFIG_MODEL_TYPE" AS varchar(100) ) AS "CONFIG_MODEL_TYPE"
                        ,CAST("LOT_SUBSTITUTION_ENABLED" AS varchar(100) ) AS "LOT_SUBSTITUTION_ENABLED"
                        ,CAST("MINIMUM_LICENSE_QUANTITY" AS float) AS "MINIMUM_LICENSE_QUANTITY"
                        ,CAST("EAM_ACTIVITY_SOURCE_CODE" AS varchar(100) ) AS "EAM_ACTIVITY_SOURCE_CODE"
                        ,CAST("LIFECYCLE_ID" AS float) AS "LIFECYCLE_ID"
                        ,CAST("CURRENT_PHASE_ID" AS float) AS "CURRENT_PHASE_ID"
                        ,CAST("OBJECT_VERSION_NUMBER" AS float) AS "OBJECT_VERSION_NUMBER"
                        ,CAST("TRACKING_QUANTITY_IND" AS varchar(100) ) AS "TRACKING_QUANTITY_IND"
                        ,CAST("ONT_PRICING_QTY_SOURCE" AS varchar(100) ) AS "ONT_PRICING_QTY_SOURCE"
                        ,CAST("SECONDARY_DEFAULT_IND" AS varchar(100) ) AS "SECONDARY_DEFAULT_IND"
                        ,CAST("OPTION_SPECIFIC_SOURCED" AS float) AS "OPTION_SPECIFIC_SOURCED"
                        ,CAST("APPROVAL_STATUS" AS varchar(100) ) AS "APPROVAL_STATUS"
                        ,CAST("VMI_MINIMUM_UNITS" AS float) AS "VMI_MINIMUM_UNITS"
                        ,CAST("VMI_MINIMUM_DAYS" AS float) AS "VMI_MINIMUM_DAYS"
                        ,CAST("VMI_MAXIMUM_UNITS" AS float) AS "VMI_MAXIMUM_UNITS"
                        ,CAST("VMI_MAXIMUM_DAYS" AS float) AS "VMI_MAXIMUM_DAYS"
                        ,CAST("VMI_FIXED_ORDER_QUANTITY" AS float) AS "VMI_FIXED_ORDER_QUANTITY"
                        ,CAST("SO_AUTHORIZATION_FLAG" AS float) AS "SO_AUTHORIZATION_FLAG"
                        ,CAST("CONSIGNED_FLAG" AS float) AS "CONSIGNED_FLAG"
                        ,CAST("ASN_AUTOEXPIRE_FLAG" AS float) AS "ASN_AUTOEXPIRE_FLAG"
                        ,CAST("VMI_FORECAST_TYPE" AS float) AS "VMI_FORECAST_TYPE"
                        ,CAST("FORECAST_HORIZON" AS float) AS "FORECAST_HORIZON"
                        ,CAST("EXCLUDE_FROM_BUDGET_FLAG" AS float) AS "EXCLUDE_FROM_BUDGET_FLAG"
                        ,CAST("DAYS_TGT_INV_SUPPLY" AS float) AS "DAYS_TGT_INV_SUPPLY"
                        ,CAST("DAYS_TGT_INV_WINDOW" AS float) AS "DAYS_TGT_INV_WINDOW"
                        ,CAST("DAYS_MAX_INV_SUPPLY" AS float) AS "DAYS_MAX_INV_SUPPLY"
                        ,CAST("DAYS_MAX_INV_WINDOW" AS float) AS "DAYS_MAX_INV_WINDOW"
                        ,CAST("DRP_PLANNED_FLAG" AS float) AS "DRP_PLANNED_FLAG"
                        ,CAST("CRITICAL_COMPONENT_FLAG" AS float) AS "CRITICAL_COMPONENT_FLAG"
                        ,CAST("CONTINOUS_TRANSFER" AS float) AS "CONTINOUS_TRANSFER"
                        ,CAST("CONVERGENCE" AS float) AS "CONVERGENCE"
                        ,CAST("DIVERGENCE" AS float) AS "DIVERGENCE"
                        ,CAST("CONFIG_ORGS" AS varchar(100) ) AS "CONFIG_ORGS"
                        ,CAST("CONFIG_MATCH" AS varchar(100) ) AS "CONFIG_MATCH"
                        ,CAST("ATTRIBUTE16" AS varchar(1000) ) AS "ATTRIBUTE16"
                        ,CAST("ATTRIBUTE17" AS varchar(1000) ) AS "ATTRIBUTE17"
                        ,CAST("ATTRIBUTE18" AS varchar(1000) ) AS "ATTRIBUTE18"
                        ,CAST("ATTRIBUTE19" AS varchar(1000) ) AS "ATTRIBUTE19"
                        ,CAST("ATTRIBUTE20" AS varchar(1000) ) AS "ATTRIBUTE20"
                        ,CAST("ATTRIBUTE21" AS varchar(1000) ) AS "ATTRIBUTE21"
                        ,CAST("ATTRIBUTE22" AS varchar(1000) ) AS "ATTRIBUTE22"
                        ,CAST("ATTRIBUTE23" AS varchar(1000) ) AS "ATTRIBUTE23"
                        ,CAST("ATTRIBUTE24" AS varchar(1000) ) AS "ATTRIBUTE24"
                        ,CAST("ATTRIBUTE25" AS varchar(1000) ) AS "ATTRIBUTE25"
                        ,CAST("ATTRIBUTE26" AS varchar(1000) ) AS "ATTRIBUTE26"
                        ,CAST("ATTRIBUTE27" AS varchar(1000) ) AS "ATTRIBUTE27"
                        ,CAST("ATTRIBUTE28" AS varchar(1000) ) AS "ATTRIBUTE28"
                        ,CAST("ATTRIBUTE29" AS varchar(1000) ) AS "ATTRIBUTE29"
                        ,CAST("ATTRIBUTE30" AS varchar(1000) ) AS "ATTRIBUTE30"
                        ,CAST("CAS_NUMBER" AS varchar(100) ) AS "CAS_NUMBER"
                        ,CAST("CHILD_LOT_FLAG" AS varchar(100) ) AS "CHILD_LOT_FLAG"
                        ,CAST("CHILD_LOT_PREFIX" AS varchar(100) ) AS "CHILD_LOT_PREFIX"
                        ,CAST("CHILD_LOT_STARTING_NUMBER" AS float) AS "CHILD_LOT_STARTING_NUMBER"
                        ,CAST("CHILD_LOT_VALIDATION_FLAG" AS varchar(100) ) AS "CHILD_LOT_VALIDATION_FLAG"
                        ,CAST("COPY_LOT_ATTRIBUTE_FLAG" AS varchar(100) ) AS "COPY_LOT_ATTRIBUTE_FLAG"
                        ,CAST("DEFAULT_GRADE" AS varchar(1000) ) AS "DEFAULT_GRADE"
                        ,CAST("EXPIRATION_ACTION_CODE" AS varchar(100) ) AS "EXPIRATION_ACTION_CODE"
                        ,CAST("EXPIRATION_ACTION_INTERVAL" AS float) AS "EXPIRATION_ACTION_INTERVAL"
                        ,CAST("GRADE_CONTROL_FLAG" AS varchar(100) ) AS "GRADE_CONTROL_FLAG"
                        ,CAST("HAZARDOUS_MATERIAL_FLAG" AS varchar(100) ) AS "HAZARDOUS_MATERIAL_FLAG"
                        ,CAST("HOLD_DAYS" AS float) AS "HOLD_DAYS"
                        ,CAST("LOT_DIVISIBLE_FLAG" AS varchar(100) ) AS "LOT_DIVISIBLE_FLAG"
                        ,CAST("MATURITY_DAYS" AS float) AS "MATURITY_DAYS"
                        ,CAST("PARENT_CHILD_GENERATION_FLAG" AS varchar(100) ) AS "PARENT_CHILD_GENERATION_FLAG"
                        ,CAST("PROCESS_COSTING_ENABLED_FLAG" AS varchar(100) ) AS "PROCESS_COSTING_ENABLED_FLAG"
                        ,CAST("PROCESS_EXECUTION_ENABLED_FLAG" AS varchar(100) ) AS "PROCESS_EXECUTION_ENABLED_FLAG"
                        ,CAST("PROCESS_QUALITY_ENABLED_FLAG" AS varchar(100) ) AS "PROCESS_QUALITY_ENABLED_FLAG"
                        ,CAST("PROCESS_SUPPLY_LOCATOR_ID" AS float) AS "PROCESS_SUPPLY_LOCATOR_ID"
                        ,CAST("PROCESS_SUPPLY_SUBINVENTORY" AS varchar(100) ) AS "PROCESS_SUPPLY_SUBINVENTORY"
                        ,CAST("PROCESS_YIELD_LOCATOR_ID" AS float) AS "PROCESS_YIELD_LOCATOR_ID"
                        ,CAST("PROCESS_YIELD_SUBINVENTORY" AS varchar(100) ) AS "PROCESS_YIELD_SUBINVENTORY"
                        ,CAST("RECIPE_ENABLED_FLAG" AS varchar(100) ) AS "RECIPE_ENABLED_FLAG"
                        ,CAST("RETEST_INTERVAL" AS float) AS "RETEST_INTERVAL"
                        ,CAST("CHARGE_PERIODICITY_CODE" AS varchar(100) ) AS "CHARGE_PERIODICITY_CODE"
                        ,CAST("REPAIR_LEADTIME" AS float) AS "REPAIR_LEADTIME"
                        ,CAST("REPAIR_YIELD" AS float) AS "REPAIR_YIELD"
                        ,CAST("PREPOSITION_POINT" AS varchar(100) ) AS "PREPOSITION_POINT"
                        ,CAST("REPAIR_PROGRAM" AS float) AS "REPAIR_PROGRAM"
                        ,CAST("SUBCONTRACTING_COMPONENT" AS float) AS "SUBCONTRACTING_COMPONENT"
                        ,CAST("OUTSOURCED_ASSEMBLY" AS float) AS "OUTSOURCED_ASSEMBLY"
                        ,CAST("EGO_MASTER_ITEMS_DFF_CTX" AS varchar(100) ) AS "EGO_MASTER_ITEMS_DFF_CTX"
                        ,CAST("GDSN_OUTBOUND_ENABLED_FLAG" AS varchar(100) ) AS "GDSN_OUTBOUND_ENABLED_FLAG"
                        ,CAST("TRADE_ITEM_DESCRIPTOR" AS varchar(100) ) AS "TRADE_ITEM_DESCRIPTOR"
                        ,CAST("STYLE_ITEM_ID" AS float) AS "STYLE_ITEM_ID"
                        ,CAST("STYLE_ITEM_FLAG" AS varchar(100) ) AS "STYLE_ITEM_FLAG"
                        ,CAST("LAST_SUBMITTED_NIR_ID" AS float) AS "LAST_SUBMITTED_NIR_ID"
                        ,CAST("DEFAULT_MATERIAL_STATUS_ID" AS float) AS "DEFAULT_MATERIAL_STATUS_ID"
                        ,CAST("GLOBAL_ATTRIBUTE11" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE11"
                        ,CAST("GLOBAL_ATTRIBUTE12" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE12"
                        ,CAST("GLOBAL_ATTRIBUTE13" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE13"
                        ,CAST("GLOBAL_ATTRIBUTE14" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE14"
                        ,CAST("GLOBAL_ATTRIBUTE15" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE15"
                        ,CAST("GLOBAL_ATTRIBUTE16" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE16"
                        ,CAST("GLOBAL_ATTRIBUTE17" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE17"
                        ,CAST("GLOBAL_ATTRIBUTE18" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE18"
                        ,CAST("GLOBAL_ATTRIBUTE19" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE19"
                        ,CAST("GLOBAL_ATTRIBUTE20" AS varchar(1000) ) AS "GLOBAL_ATTRIBUTE20"
                        ,CAST("SERIAL_TAGGING_FLAG" AS varchar(100) ) AS "SERIAL_TAGGING_FLAG"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "INVENTORY_ITEM_ID"
                            , "ORGANIZATION_ID"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "CREATION_DATE"
                            , "CREATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "SUMMARY_FLAG"
                            , "ENABLED_FLAG"
                            , "START_DATE_ACTIVE"
                            , "END_DATE_ACTIVE"
                            , "DESCRIPTION"
                            , "BUYER_ID"
                            , "ACCOUNTING_RULE_ID"
                            , "INVOICING_RULE_ID"
                            , "SEGMENT1"
                            , "SEGMENT2"
                            , "SEGMENT3"
                            , "SEGMENT4"
                            , "SEGMENT5"
                            , "SEGMENT6"
                            , "SEGMENT7"
                            , "SEGMENT8"
                            , "SEGMENT9"
                            , "SEGMENT10"
                            , "SEGMENT11"
                            , "SEGMENT12"
                            , "SEGMENT13"
                            , "SEGMENT14"
                            , "SEGMENT15"
                            , "SEGMENT16"
                            , "SEGMENT17"
                            , "SEGMENT18"
                            , "SEGMENT19"
                            , "SEGMENT20"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "PURCHASING_ITEM_FLAG"
                            , "SHIPPABLE_ITEM_FLAG"
                            , "CUSTOMER_ORDER_FLAG"
                            , "INTERNAL_ORDER_FLAG"
                            , "SERVICE_ITEM_FLAG"
                            , "INVENTORY_ITEM_FLAG"
                            , "ENG_ITEM_FLAG"
                            , "INVENTORY_ASSET_FLAG"
                            , "PURCHASING_ENABLED_FLAG"
                            , "CUSTOMER_ORDER_ENABLED_FLAG"
                            , "INTERNAL_ORDER_ENABLED_FLAG"
                            , "SO_TRANSACTIONS_FLAG"
                            , "MTL_TRANSACTIONS_ENABLED_FLAG"
                            , "STOCK_ENABLED_FLAG"
                            , "BOM_ENABLED_FLAG"
                            , "BUILD_IN_WIP_FLAG"
                            , "REVISION_QTY_CONTROL_CODE"
                            , "ITEM_CATALOG_GROUP_ID"
                            , "CATALOG_STATUS_FLAG"
                            , "RETURNABLE_FLAG"
                            , "DEFAULT_SHIPPING_ORG"
                            , "COLLATERAL_FLAG"
                            , "TAXABLE_FLAG"
                            , "QTY_RCV_EXCEPTION_CODE"
                            , "ALLOW_ITEM_DESC_UPDATE_FLAG"
                            , "INSPECTION_REQUIRED_FLAG"
                            , "RECEIPT_REQUIRED_FLAG"
                            , "MARKET_PRICE"
                            , "HAZARD_CLASS_ID"
                            , "RFQ_REQUIRED_FLAG"
                            , "QTY_RCV_TOLERANCE"
                            , "LIST_PRICE_PER_UNIT"
                            , "UN_NUMBER_ID"
                            , "PRICE_TOLERANCE_PERCENT"
                            , "ASSET_CATEGORY_ID"
                            , "ROUNDING_FACTOR"
                            , "UNIT_OF_ISSUE"
                            , "ENFORCE_SHIP_TO_LOCATION_CODE"
                            , "ALLOW_SUBSTITUTE_RECEIPTS_FLAG"
                            , "ALLOW_UNORDERED_RECEIPTS_FLAG"
                            , "ALLOW_EXPRESS_DELIVERY_FLAG"
                            , "DAYS_EARLY_RECEIPT_ALLOWED"
                            , "DAYS_LATE_RECEIPT_ALLOWED"
                            , "RECEIPT_DAYS_EXCEPTION_CODE"
                            , "RECEIVING_ROUTING_ID"
                            , "INVOICE_CLOSE_TOLERANCE"
                            , "RECEIVE_CLOSE_TOLERANCE"
                            , "AUTO_LOT_ALPHA_PREFIX"
                            , "START_AUTO_LOT_NUMBER"
                            , "LOT_CONTROL_CODE"
                            , "SHELF_LIFE_CODE"
                            , "SHELF_LIFE_DAYS"
                            , "SERIAL_NUMBER_CONTROL_CODE"
                            , "START_AUTO_SERIAL_NUMBER"
                            , "AUTO_SERIAL_ALPHA_PREFIX"
                            , "SOURCE_TYPE"
                            , "SOURCE_ORGANIZATION_ID"
                            , "SOURCE_SUBINVENTORY"
                            , "EXPENSE_ACCOUNT"
                            , "ENCUMBRANCE_ACCOUNT"
                            , "RESTRICT_SUBINVENTORIES_CODE"
                            , "UNIT_WEIGHT"
                            , "WEIGHT_UOM_CODE"
                            , "VOLUME_UOM_CODE"
                            , "UNIT_VOLUME"
                            , "RESTRICT_LOCATORS_CODE"
                            , "LOCATION_CONTROL_CODE"
                            , "SHRINKAGE_RATE"
                            , "ACCEPTABLE_EARLY_DAYS"
                            , "PLANNING_TIME_FENCE_CODE"
                            , "DEMAND_TIME_FENCE_CODE"
                            , "LEAD_TIME_LOT_SIZE"
                            , "STD_LOT_SIZE"
                            , "CUM_MANUFACTURING_LEAD_TIME"
                            , "OVERRUN_PERCENTAGE"
                            , "MRP_CALCULATE_ATP_FLAG"
                            , "ACCEPTABLE_RATE_INCREASE"
                            , "ACCEPTABLE_RATE_DECREASE"
                            , "CUMULATIVE_TOTAL_LEAD_TIME"
                            , "PLANNING_TIME_FENCE_DAYS"
                            , "DEMAND_TIME_FENCE_DAYS"
                            , "END_ASSEMBLY_PEGGING_FLAG"
                            , "REPETITIVE_PLANNING_FLAG"
                            , "PLANNING_EXCEPTION_SET"
                            , "BOM_ITEM_TYPE"
                            , "PICK_COMPONENTS_FLAG"
                            , "REPLENISH_TO_ORDER_FLAG"
                            , "BASE_ITEM_ID"
                            , "ATP_COMPONENTS_FLAG"
                            , "ATP_FLAG"
                            , "FIXED_LEAD_TIME"
                            , "VARIABLE_LEAD_TIME"
                            , "WIP_SUPPLY_LOCATOR_ID"
                            , "WIP_SUPPLY_TYPE"
                            , "WIP_SUPPLY_SUBINVENTORY"
                            , "PRIMARY_UOM_CODE"
                            , "PRIMARY_UNIT_OF_MEASURE"
                            , "ALLOWED_UNITS_LOOKUP_CODE"
                            , "COST_OF_SALES_ACCOUNT"
                            , "SALES_ACCOUNT"
                            , "DEFAULT_INCLUDE_IN_ROLLUP_FLAG"
                            , "INVENTORY_ITEM_STATUS_CODE"
                            , "INVENTORY_PLANNING_CODE"
                            , "PLANNER_CODE"
                            , "PLANNING_MAKE_BUY_CODE"
                            , "FIXED_LOT_MULTIPLIER"
                            , "ROUNDING_CONTROL_TYPE"
                            , "CARRYING_COST"
                            , "POSTPROCESSING_LEAD_TIME"
                            , "PREPROCESSING_LEAD_TIME"
                            , "FULL_LEAD_TIME"
                            , "ORDER_COST"
                            , "MRP_SAFETY_STOCK_PERCENT"
                            , "MRP_SAFETY_STOCK_CODE"
                            , "MIN_MINMAX_QUANTITY"
                            , "MAX_MINMAX_QUANTITY"
                            , "MINIMUM_ORDER_QUANTITY"
                            , "FIXED_ORDER_QUANTITY"
                            , "FIXED_DAYS_SUPPLY"
                            , "MAXIMUM_ORDER_QUANTITY"
                            , "ATP_RULE_ID"
                            , "PICKING_RULE_ID"
                            , "RESERVABLE_TYPE"
                            , "POSITIVE_MEASUREMENT_ERROR"
                            , "NEGATIVE_MEASUREMENT_ERROR"
                            , "ENGINEERING_ECN_CODE"
                            , "ENGINEERING_ITEM_ID"
                            , "ENGINEERING_DATE"
                            , "SERVICE_STARTING_DELAY"
                            , "VENDOR_WARRANTY_FLAG"
                            , "SERVICEABLE_COMPONENT_FLAG"
                            , "SERVICEABLE_PRODUCT_FLAG"
                            , "BASE_WARRANTY_SERVICE_ID"
                            , "PAYMENT_TERMS_ID"
                            , "PREVENTIVE_MAINTENANCE_FLAG"
                            , "PRIMARY_SPECIALIST_ID"
                            , "SECONDARY_SPECIALIST_ID"
                            , "SERVICEABLE_ITEM_CLASS_ID"
                            , "TIME_BILLABLE_FLAG"
                            , "MATERIAL_BILLABLE_FLAG"
                            , "EXPENSE_BILLABLE_FLAG"
                            , "PRORATE_SERVICE_FLAG"
                            , "COVERAGE_SCHEDULE_ID"
                            , "SERVICE_DURATION_PERIOD_CODE"
                            , "SERVICE_DURATION"
                            , "WARRANTY_VENDOR_ID"
                            , "MAX_WARRANTY_AMOUNT"
                            , "RESPONSE_TIME_PERIOD_CODE"
                            , "RESPONSE_TIME_VALUE"
                        ,'||')+CONCAT_WS( '||','||'
                            , "NEW_REVISION_CODE"
                            , "INVOICEABLE_ITEM_FLAG"
                            , "TAX_CODE"
                            , "INVOICE_ENABLED_FLAG"
                            , "MUST_USE_APPROVED_VENDOR_FLAG"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "OUTSIDE_OPERATION_FLAG"
                            , "OUTSIDE_OPERATION_UOM_TYPE"
                            , "SAFETY_STOCK_BUCKET_DAYS"
                            , "AUTO_REDUCE_MPS"
                            , "COSTING_ENABLED_FLAG"
                            , "AUTO_CREATED_CONFIG_FLAG"
                            , "CYCLE_COUNT_ENABLED_FLAG"
                            , "ITEM_TYPE"
                            , "MODEL_CONFIG_CLAUSE_NAME"
                            , "SHIP_MODEL_COMPLETE_FLAG"
                            , "MRP_PLANNING_CODE"
                            , "RETURN_INSPECTION_REQUIREMENT"
                            , "ATO_FORECAST_CONTROL"
                            , "RELEASE_TIME_FENCE_CODE"
                            , "RELEASE_TIME_FENCE_DAYS"
                            , "CONTAINER_ITEM_FLAG"
                            , "VEHICLE_ITEM_FLAG"
                            , "MAXIMUM_LOAD_WEIGHT"
                            , "MINIMUM_FILL_PERCENT"
                            , "CONTAINER_TYPE_CODE"
                            , "INTERNAL_VOLUME"
                            , "WH_UPDATE_DATE"
                            , "PRODUCT_FAMILY_ITEM_ID"
                            , "GLOBAL_ATTRIBUTE_CATEGORY"
                            , "GLOBAL_ATTRIBUTE1"
                            , "GLOBAL_ATTRIBUTE2"
                            , "GLOBAL_ATTRIBUTE3"
                            , "GLOBAL_ATTRIBUTE4"
                            , "GLOBAL_ATTRIBUTE5"
                            , "GLOBAL_ATTRIBUTE6"
                            , "GLOBAL_ATTRIBUTE7"
                            , "GLOBAL_ATTRIBUTE8"
                            , "GLOBAL_ATTRIBUTE9"
                            , "GLOBAL_ATTRIBUTE10"
                            , "PURCHASING_TAX_CODE"
                            , "OVERCOMPLETION_TOLERANCE_TYPE"
                            , "OVERCOMPLETION_TOLERANCE_VALUE"
                            , "EFFECTIVITY_CONTROL"
                            , "CHECK_SHORTAGES_FLAG"
                            , "OVER_SHIPMENT_TOLERANCE"
                            , "UNDER_SHIPMENT_TOLERANCE"
                            , "OVER_RETURN_TOLERANCE"
                            , "UNDER_RETURN_TOLERANCE"
                            , "EQUIPMENT_TYPE"
                            , "RECOVERED_PART_DISP_CODE"
                            , "DEFECT_TRACKING_ON_FLAG"
                            , "USAGE_ITEM_FLAG"
                            , "EVENT_FLAG"
                            , "ELECTRONIC_FLAG"
                            , "DOWNLOADABLE_FLAG"
                            , "VOL_DISCOUNT_EXEMPT_FLAG"
                            , "COUPON_EXEMPT_FLAG"
                            , "COMMS_NL_TRACKABLE_FLAG"
                            , "ASSET_CREATION_CODE"
                            , "COMMS_ACTIVATION_REQD_FLAG"
                            , "ORDERABLE_ON_WEB_FLAG"
                            , "BACK_ORDERABLE_FLAG"
                            , "WEB_STATUS"
                            , "INDIVISIBLE_FLAG"
                            , "DIMENSION_UOM_CODE"
                            , "UNIT_LENGTH"
                            , "UNIT_WIDTH"
                            , "UNIT_HEIGHT"
                            , "BULK_PICKED_FLAG"
                            , "LOT_STATUS_ENABLED"
                            , "DEFAULT_LOT_STATUS_ID"
                            , "SERIAL_STATUS_ENABLED"
                            , "DEFAULT_SERIAL_STATUS_ID"
                            , "LOT_SPLIT_ENABLED"
                            , "LOT_MERGE_ENABLED"
                            , "INVENTORY_CARRY_PENALTY"
                            , "OPERATION_SLACK_PENALTY"
                            , "FINANCING_ALLOWED_FLAG"
                            , "EAM_ITEM_TYPE"
                            , "EAM_ACTIVITY_TYPE_CODE"
                            , "EAM_ACTIVITY_CAUSE_CODE"
                            , "EAM_ACT_NOTIFICATION_FLAG"
                            , "EAM_ACT_SHUTDOWN_STATUS"
                            , "DUAL_UOM_CONTROL"
                            , "SECONDARY_UOM_CODE"
                            , "DUAL_UOM_DEVIATION_HIGH"
                            , "DUAL_UOM_DEVIATION_LOW"
                            , "CONTRACT_ITEM_TYPE_CODE"
                            , "SUBSCRIPTION_DEPEND_FLAG"
                            , "SERV_REQ_ENABLED_CODE"
                            , "SERV_BILLING_ENABLED_FLAG"
                            , "SERV_IMPORTANCE_LEVEL"
                            , "PLANNED_INV_POINT_FLAG"
                            , "LOT_TRANSLATE_ENABLED"
                            , "DEFAULT_SO_SOURCE_TYPE"
                            , "CREATE_SUPPLY_FLAG"
                            , "SUBSTITUTION_WINDOW_CODE"
                            , "SUBSTITUTION_WINDOW_DAYS"
                            , "IB_ITEM_INSTANCE_CLASS"
                            , "CONFIG_MODEL_TYPE"
                            , "LOT_SUBSTITUTION_ENABLED"
                            , "MINIMUM_LICENSE_QUANTITY"
                            , "EAM_ACTIVITY_SOURCE_CODE"
                            , "LIFECYCLE_ID"
                            , "CURRENT_PHASE_ID"
                            , "OBJECT_VERSION_NUMBER"
                            , "TRACKING_QUANTITY_IND"
                            , "ONT_PRICING_QTY_SOURCE"
                            , "SECONDARY_DEFAULT_IND"
                            , "OPTION_SPECIFIC_SOURCED"
                            , "APPROVAL_STATUS"
                            , "VMI_MINIMUM_UNITS"
                            , "VMI_MINIMUM_DAYS"
                            , "VMI_MAXIMUM_UNITS"
                            , "VMI_MAXIMUM_DAYS"
                            , "VMI_FIXED_ORDER_QUANTITY"
                            , "SO_AUTHORIZATION_FLAG"
                            , "CONSIGNED_FLAG"
                            , "ASN_AUTOEXPIRE_FLAG"
                            , "VMI_FORECAST_TYPE"
                            , "FORECAST_HORIZON"
                            , "EXCLUDE_FROM_BUDGET_FLAG"
                            , "DAYS_TGT_INV_SUPPLY"
                            , "DAYS_TGT_INV_WINDOW"
                            , "DAYS_MAX_INV_SUPPLY"
                            , "DAYS_MAX_INV_WINDOW"
                            , "DRP_PLANNED_FLAG"
                            , "CRITICAL_COMPONENT_FLAG"
                            , "CONTINOUS_TRANSFER"
                            , "CONVERGENCE"
                            , "DIVERGENCE"
                            , "CONFIG_ORGS"
                            , "CONFIG_MATCH"
                            , "ATTRIBUTE16"
                            , "ATTRIBUTE17"
                            , "ATTRIBUTE18"
                            , "ATTRIBUTE19"
                            , "ATTRIBUTE20"
                            , "ATTRIBUTE21"
                            , "ATTRIBUTE22"
                            , "ATTRIBUTE23"
                            , "ATTRIBUTE24"
                            , "ATTRIBUTE25"
                            , "ATTRIBUTE26"
                            , "ATTRIBUTE27"
                            , "ATTRIBUTE28"
                            , "ATTRIBUTE29"
                            , "ATTRIBUTE30"
                            , "CAS_NUMBER"
                            , "CHILD_LOT_FLAG"
                            , "CHILD_LOT_PREFIX"
                            , "CHILD_LOT_STARTING_NUMBER"
                            , "CHILD_LOT_VALIDATION_FLAG"
                            , "COPY_LOT_ATTRIBUTE_FLAG"
                            , "DEFAULT_GRADE"
                            , "EXPIRATION_ACTION_CODE"
                            , "EXPIRATION_ACTION_INTERVAL"
                            , "GRADE_CONTROL_FLAG"
                            , "HAZARDOUS_MATERIAL_FLAG"
                            , "HOLD_DAYS"
                            , "LOT_DIVISIBLE_FLAG"
                            , "MATURITY_DAYS"
                            , "PARENT_CHILD_GENERATION_FLAG"
                            , "PROCESS_COSTING_ENABLED_FLAG"
                            , "PROCESS_EXECUTION_ENABLED_FLAG"
                            , "PROCESS_QUALITY_ENABLED_FLAG"
                            , "PROCESS_SUPPLY_LOCATOR_ID"
                            , "PROCESS_SUPPLY_SUBINVENTORY"
                            , "PROCESS_YIELD_LOCATOR_ID"
                            , "PROCESS_YIELD_SUBINVENTORY"
                            , "RECIPE_ENABLED_FLAG"
                            , "RETEST_INTERVAL"
                            , "CHARGE_PERIODICITY_CODE"
                            , "REPAIR_LEADTIME"
                            , "REPAIR_YIELD"
                            , "PREPOSITION_POINT"
                            , "REPAIR_PROGRAM"
                            , "SUBCONTRACTING_COMPONENT"
                            , "OUTSOURCED_ASSEMBLY"
                            , "EGO_MASTER_ITEMS_DFF_CTX"
                            , "GDSN_OUTBOUND_ENABLED_FLAG"
                            , "TRADE_ITEM_DESCRIPTOR"
                            , "STYLE_ITEM_ID"
                            , "STYLE_ITEM_FLAG"
                            , "LAST_SUBMITTED_NIR_ID"
                            , "DEFAULT_MATERIAL_STATUS_ID"
                            , "GLOBAL_ATTRIBUTE11"
                            , "GLOBAL_ATTRIBUTE12"
                            , "GLOBAL_ATTRIBUTE13"
                            , "GLOBAL_ATTRIBUTE14"
                            , "GLOBAL_ATTRIBUTE15"
                            , "GLOBAL_ATTRIBUTE16"
                            , "GLOBAL_ATTRIBUTE17"
                            , "GLOBAL_ATTRIBUTE18"
                            , "GLOBAL_ATTRIBUTE19"
                            , "GLOBAL_ATTRIBUTE20"
                        ,'||')+CONCAT_WS( '||','||'
                            , "SERIAL_TAGGING_FLAG"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_MTL_SYSTEM_ITEMS_B"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END
