CREATE PROCEDURE "STG"."LOAD_STG_EBS_PER_ALL_PEOPLE_F"
AS 
BEGIN 


SET NOCOUNT ON;
    /* ---------------------------------------------------------------------------------
    Overview:
    ---------
    
    Author:      ONE51 CONSULTING
    Email:       composer@one51.com.au
    Date:        5/05/2022 11:48:52 pm
    Jira Task:   NA
    Confluence:  NA
    
    Notes:				
    -----------
    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    
    EXEC "STG"."LOAD_STG_EBS_PER_ALL_PEOPLE_F";
    
    
    Source                              Destination                      
    --------------------------------    -------------------------------- 
    LND"."LND_EBS_PER_ALL_PEOPLE_F"    "STG"."STG_EBS_PER_ALL_PEOPLE_F" 
    
    Change History:
    ---------------	
    Date          Who               Details       
    ----------    --------------    ----------------------------------------------------
    2022-05-05    ONE51 COMPOSER    THIS IS AN AUTO GENERATED SCRIPT FROM ONE51 COMPOSER
    ----------    --------------    ----------------------------------------------------
    ------------------------------------------------------------------------------------
    */


    
    
    BEGIN TRY
    
        /* ETL - Starting ETL Code */
        /* Step 1:  TRUNCATE STAGING TABLE*/
                TRUNCATE TABLE "STG"."STG_EBS_PER_ALL_PEOPLE_F";
        
        
        /* Step 2:  IMPORT FROM LANDING TO STAGING*/
                INSERT INTO "STG"."STG_EBS_PER_ALL_PEOPLE_F"
                (
                    "PERSON_ID"
                    ,"EFFECTIVE_START_DATE"
                    ,"EFFECTIVE_END_DATE"
                    ,"BUSINESS_GROUP_ID"
                    ,"PERSON_TYPE_ID"
                    ,"LAST_NAME"
                    ,"START_DATE"
                    ,"APPLICANT_NUMBER"
                    ,"BACKGROUND_CHECK_STATUS"
                    ,"BACKGROUND_DATE_CHECK"
                    ,"BLOOD_TYPE"
                    ,"COMMENT_ID"
                    ,"CORRESPONDENCE_LANGUAGE"
                    ,"CURRENT_APPLICANT_FLAG"
                    ,"CURRENT_EMP_OR_APL_FLAG"
                    ,"CURRENT_EMPLOYEE_FLAG"
                    ,"DATE_EMPLOYEE_DATA_VERIFIED"
                    ,"DATE_OF_BIRTH"
                    ,"EMAIL_ADDRESS"
                    ,"EMPLOYEE_NUMBER"
                    ,"EXPENSE_CHECK_SEND_TO_ADDRESS"
                    ,"FAST_PATH_EMPLOYEE"
                    ,"FIRST_NAME"
                    ,"FTE_CAPACITY"
                    ,"FULL_NAME"
                    ,"HOLD_APPLICANT_DATE_UNTIL"
                    ,"HONORS"
                    ,"INTERNAL_LOCATION"
                    ,"KNOWN_AS"
                    ,"LAST_MEDICAL_TEST_BY"
                    ,"LAST_MEDICAL_TEST_DATE"
                    ,"MAILSTOP"
                    ,"MARITAL_STATUS"
                    ,"MIDDLE_NAMES"
                    ,"NATIONALITY"
                    ,"NATIONAL_IDENTIFIER"
                    ,"OFFICE_NUMBER"
                    ,"ON_MILITARY_SERVICE"
                    ,"ORDER_NAME"
                    ,"PRE_NAME_ADJUNCT"
                    ,"PREVIOUS_LAST_NAME"
                    ,"PROJECTED_START_DATE"
                    ,"REHIRE_AUTHORIZOR"
                    ,"REHIRE_REASON"
                    ,"REHIRE_RECOMMENDATION"
                    ,"RESUME_EXISTS"
                    ,"RESUME_LAST_UPDATED"
                    ,"REGISTERED_DISABLED_FLAG"
                    ,"SECOND_PASSPORT_EXISTS"
                    ,"SEX"
                    ,"STUDENT_STATUS"
                    ,"SUFFIX"
                    ,"TITLE"
                    ,"VENDOR_ID"
                    ,"WORK_SCHEDULE"
                    ,"WORK_TELEPHONE"
                    ,"COORD_BEN_MED_PLN_NO"
                    ,"COORD_BEN_NO_CVG_FLAG"
                    ,"DPDNT_ADOPTION_DATE"
                    ,"DPDNT_VLNTRY_SVCE_FLAG"
                    ,"RECEIPT_OF_DEATH_CERT_DATE"
                    ,"USES_TOBACCO_FLAG"
                    ,"BENEFIT_GROUP_ID"
                    ,"REQUEST_ID"
                    ,"PROGRAM_APPLICATION_ID"
                    ,"PROGRAM_ID"
                    ,"PROGRAM_UPDATE_DATE"
                    ,"ATTRIBUTE_CATEGORY"
                    ,"ATTRIBUTE1"
                    ,"ATTRIBUTE2"
                    ,"ATTRIBUTE3"
                    ,"ATTRIBUTE4"
                    ,"ATTRIBUTE5"
                    ,"ATTRIBUTE6"
                    ,"ATTRIBUTE7"
                    ,"ATTRIBUTE8"
                    ,"ATTRIBUTE9"
                    ,"ATTRIBUTE10"
                    ,"ATTRIBUTE11"
                    ,"ATTRIBUTE12"
                    ,"ATTRIBUTE13"
                    ,"ATTRIBUTE14"
                    ,"ATTRIBUTE15"
                    ,"ATTRIBUTE16"
                    ,"ATTRIBUTE17"
                    ,"ATTRIBUTE18"
                    ,"ATTRIBUTE19"
                    ,"ATTRIBUTE20"
                    ,"ATTRIBUTE21"
                    ,"ATTRIBUTE22"
                    ,"ATTRIBUTE23"
                    ,"ATTRIBUTE24"
                    ,"ATTRIBUTE25"
                    ,"ATTRIBUTE26"
                    ,"ATTRIBUTE27"
                    ,"ATTRIBUTE28"
                    ,"ATTRIBUTE29"
                    ,"ATTRIBUTE30"
                    ,"LAST_UPDATE_DATE"
                    ,"LAST_UPDATED_BY"
                    ,"LAST_UPDATE_LOGIN"
                    ,"CREATED_BY"
                    ,"CREATION_DATE"
                    ,"PER_INFORMATION_CATEGORY"
                    ,"PER_INFORMATION1"
                    ,"PER_INFORMATION2"
                    ,"PER_INFORMATION3"
                    ,"PER_INFORMATION4"
                    ,"PER_INFORMATION5"
                    ,"PER_INFORMATION6"
                    ,"PER_INFORMATION7"
                    ,"PER_INFORMATION8"
                    ,"PER_INFORMATION9"
                    ,"PER_INFORMATION10"
                    ,"PER_INFORMATION11"
                    ,"PER_INFORMATION12"
                    ,"PER_INFORMATION13"
                    ,"PER_INFORMATION14"
                    ,"PER_INFORMATION15"
                    ,"PER_INFORMATION16"
                    ,"PER_INFORMATION17"
                    ,"PER_INFORMATION18"
                    ,"PER_INFORMATION19"
                    ,"PER_INFORMATION20"
                    ,"PER_INFORMATION21"
                    ,"PER_INFORMATION22"
                    ,"PER_INFORMATION23"
                    ,"PER_INFORMATION24"
                    ,"PER_INFORMATION25"
                    ,"PER_INFORMATION26"
                    ,"PER_INFORMATION27"
                    ,"PER_INFORMATION28"
                    ,"PER_INFORMATION29"
                    ,"PER_INFORMATION30"
                    ,"OBJECT_VERSION_NUMBER"
                    ,"DATE_OF_DEATH"
                    ,"ORIGINAL_DATE_OF_HIRE"
                    ,"TOWN_OF_BIRTH"
                    ,"REGION_OF_BIRTH"
                    ,"COUNTRY_OF_BIRTH"
                    ,"GLOBAL_PERSON_ID"
                    ,"COORD_BEN_MED_PL_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_NAME"
                    ,"COORD_BEN_MED_INSR_CRR_IDENT"
                    ,"COORD_BEN_MED_EXT_ER"
                    ,"COORD_BEN_MED_CVG_STRT_DT"
                    ,"COORD_BEN_MED_CVG_END_DT"
                    ,"PARTY_ID"
                    ,"NPW_NUMBER"
                    ,"CURRENT_NPW_FLAG"
                    ,"GLOBAL_NAME"
                    ,"LOCAL_NAME"
                    ,"OMD_INSERT_DATETIME"
                    ,"OMD_FILE_NAME"
                    ,"OMD_HASH_FULL_RECORD"
                )
                SELECT * FROM (
                    SELECT 
                        CAST("PERSON_ID" AS float) AS "PERSON_ID"
                        ,CAST("EFFECTIVE_START_DATE"  AS datetime2) AS "EFFECTIVE_START_DATE"
                        ,CAST("EFFECTIVE_END_DATE"  AS datetime2) AS "EFFECTIVE_END_DATE"
                        ,CAST("BUSINESS_GROUP_ID" AS float) AS "BUSINESS_GROUP_ID"
                        ,CAST("PERSON_TYPE_ID" AS float) AS "PERSON_TYPE_ID"
                        ,CAST("LAST_NAME" AS varchar(1000) ) AS "LAST_NAME"
                        ,CAST("START_DATE"  AS datetime2) AS "START_DATE"
                        ,CAST("APPLICANT_NUMBER" AS varchar(100) ) AS "APPLICANT_NUMBER"
                        ,CAST("BACKGROUND_CHECK_STATUS" AS varchar(100) ) AS "BACKGROUND_CHECK_STATUS"
                        ,CAST("BACKGROUND_DATE_CHECK"  AS datetime2) AS "BACKGROUND_DATE_CHECK"
                        ,CAST("BLOOD_TYPE" AS varchar(100) ) AS "BLOOD_TYPE"
                        ,CAST("COMMENT_ID" AS float) AS "COMMENT_ID"
                        ,CAST("CORRESPONDENCE_LANGUAGE" AS varchar(100) ) AS "CORRESPONDENCE_LANGUAGE"
                        ,CAST("CURRENT_APPLICANT_FLAG" AS varchar(100) ) AS "CURRENT_APPLICANT_FLAG"
                        ,CAST("CURRENT_EMP_OR_APL_FLAG" AS varchar(100) ) AS "CURRENT_EMP_OR_APL_FLAG"
                        ,CAST("CURRENT_EMPLOYEE_FLAG" AS varchar(100) ) AS "CURRENT_EMPLOYEE_FLAG"
                        ,CAST("DATE_EMPLOYEE_DATA_VERIFIED"  AS datetime2) AS "DATE_EMPLOYEE_DATA_VERIFIED"
                        ,CAST("DATE_OF_BIRTH"  AS datetime2) AS "DATE_OF_BIRTH"
                        ,CAST("EMAIL_ADDRESS" AS varchar(1000) ) AS "EMAIL_ADDRESS"
                        ,CAST("EMPLOYEE_NUMBER" AS varchar(100) ) AS "EMPLOYEE_NUMBER"
                        ,CAST("EXPENSE_CHECK_SEND_TO_ADDRESS" AS varchar(100) ) AS "EXPENSE_CHECK_SEND_TO_ADDRESS"
                        ,CAST("FAST_PATH_EMPLOYEE" AS varchar(100) ) AS "FAST_PATH_EMPLOYEE"
                        ,CAST("FIRST_NAME" AS varchar(1000) ) AS "FIRST_NAME"
                        ,CAST("FTE_CAPACITY" AS float) AS "FTE_CAPACITY"
                        ,CAST("FULL_NAME" AS varchar(1000) ) AS "FULL_NAME"
                        ,CAST("HOLD_APPLICANT_DATE_UNTIL"  AS datetime2) AS "HOLD_APPLICANT_DATE_UNTIL"
                        ,CAST("HONORS" AS varchar(100) ) AS "HONORS"
                        ,CAST("INTERNAL_LOCATION" AS varchar(100) ) AS "INTERNAL_LOCATION"
                        ,CAST("KNOWN_AS" AS varchar(1000) ) AS "KNOWN_AS"
                        ,CAST("LAST_MEDICAL_TEST_BY" AS varchar(1000) ) AS "LAST_MEDICAL_TEST_BY"
                        ,CAST("LAST_MEDICAL_TEST_DATE"  AS datetime2) AS "LAST_MEDICAL_TEST_DATE"
                        ,CAST("MAILSTOP" AS varchar(100) ) AS "MAILSTOP"
                        ,CAST("MARITAL_STATUS" AS varchar(100) ) AS "MARITAL_STATUS"
                        ,CAST("MIDDLE_NAMES" AS varchar(1000) ) AS "MIDDLE_NAMES"
                        ,CAST("NATIONALITY" AS varchar(100) ) AS "NATIONALITY"
                        ,CAST("NATIONAL_IDENTIFIER" AS varchar(100) ) AS "NATIONAL_IDENTIFIER"
                        ,CAST("OFFICE_NUMBER" AS varchar(100) ) AS "OFFICE_NUMBER"
                        ,CAST("ON_MILITARY_SERVICE" AS varchar(100) ) AS "ON_MILITARY_SERVICE"
                        ,CAST("ORDER_NAME" AS varchar(1000) ) AS "ORDER_NAME"
                        ,CAST("PRE_NAME_ADJUNCT" AS varchar(100) ) AS "PRE_NAME_ADJUNCT"
                        ,CAST("PREVIOUS_LAST_NAME" AS varchar(1000) ) AS "PREVIOUS_LAST_NAME"
                        ,CAST("PROJECTED_START_DATE"  AS datetime2) AS "PROJECTED_START_DATE"
                        ,CAST("REHIRE_AUTHORIZOR" AS varchar(1000) ) AS "REHIRE_AUTHORIZOR"
                        ,CAST("REHIRE_REASON" AS varchar(1000) ) AS "REHIRE_REASON"
                        ,CAST("REHIRE_RECOMMENDATION" AS varchar(100) ) AS "REHIRE_RECOMMENDATION"
                        ,CAST("RESUME_EXISTS" AS varchar(100) ) AS "RESUME_EXISTS"
                        ,CAST("RESUME_LAST_UPDATED"  AS datetime2) AS "RESUME_LAST_UPDATED"
                        ,CAST("REGISTERED_DISABLED_FLAG" AS varchar(100) ) AS "REGISTERED_DISABLED_FLAG"
                        ,CAST("SECOND_PASSPORT_EXISTS" AS varchar(100) ) AS "SECOND_PASSPORT_EXISTS"
                        ,CAST("SEX" AS varchar(100) ) AS "SEX"
                        ,CAST("STUDENT_STATUS" AS varchar(100) ) AS "STUDENT_STATUS"
                        ,CAST("SUFFIX" AS varchar(100) ) AS "SUFFIX"
                        ,CAST("TITLE" AS varchar(100) ) AS "TITLE"
                        ,CAST("VENDOR_ID" AS float) AS "VENDOR_ID"
                        ,CAST("WORK_SCHEDULE" AS varchar(100) ) AS "WORK_SCHEDULE"
                        ,CAST("WORK_TELEPHONE" AS varchar(1000) ) AS "WORK_TELEPHONE"
                        ,CAST("COORD_BEN_MED_PLN_NO" AS varchar(100) ) AS "COORD_BEN_MED_PLN_NO"
                        ,CAST("COORD_BEN_NO_CVG_FLAG" AS varchar(100) ) AS "COORD_BEN_NO_CVG_FLAG"
                        ,CAST("DPDNT_ADOPTION_DATE"  AS datetime2) AS "DPDNT_ADOPTION_DATE"
                        ,CAST("DPDNT_VLNTRY_SVCE_FLAG" AS varchar(100) ) AS "DPDNT_VLNTRY_SVCE_FLAG"
                        ,CAST("RECEIPT_OF_DEATH_CERT_DATE"  AS datetime2) AS "RECEIPT_OF_DEATH_CERT_DATE"
                        ,CAST("USES_TOBACCO_FLAG" AS varchar(100) ) AS "USES_TOBACCO_FLAG"
                        ,CAST("BENEFIT_GROUP_ID" AS float) AS "BENEFIT_GROUP_ID"
                        ,CAST("REQUEST_ID" AS float) AS "REQUEST_ID"
                        ,CAST("PROGRAM_APPLICATION_ID" AS float) AS "PROGRAM_APPLICATION_ID"
                        ,CAST("PROGRAM_ID" AS float) AS "PROGRAM_ID"
                        ,CAST("PROGRAM_UPDATE_DATE"  AS datetime2) AS "PROGRAM_UPDATE_DATE"
                        ,CAST("ATTRIBUTE_CATEGORY" AS varchar(100) ) AS "ATTRIBUTE_CATEGORY"
                        ,CAST("ATTRIBUTE1" AS varchar(1000) ) AS "ATTRIBUTE1"
                        ,CAST("ATTRIBUTE2" AS varchar(1000) ) AS "ATTRIBUTE2"
                        ,CAST("ATTRIBUTE3" AS varchar(1000) ) AS "ATTRIBUTE3"
                        ,CAST("ATTRIBUTE4" AS varchar(1000) ) AS "ATTRIBUTE4"
                        ,CAST("ATTRIBUTE5" AS varchar(1000) ) AS "ATTRIBUTE5"
                        ,CAST("ATTRIBUTE6" AS varchar(1000) ) AS "ATTRIBUTE6"
                        ,CAST("ATTRIBUTE7" AS varchar(1000) ) AS "ATTRIBUTE7"
                        ,CAST("ATTRIBUTE8" AS varchar(1000) ) AS "ATTRIBUTE8"
                        ,CAST("ATTRIBUTE9" AS varchar(1000) ) AS "ATTRIBUTE9"
                        ,CAST("ATTRIBUTE10" AS varchar(1000) ) AS "ATTRIBUTE10"
                        ,CAST("ATTRIBUTE11" AS varchar(1000) ) AS "ATTRIBUTE11"
                        ,CAST("ATTRIBUTE12" AS varchar(1000) ) AS "ATTRIBUTE12"
                        ,CAST("ATTRIBUTE13" AS varchar(1000) ) AS "ATTRIBUTE13"
                        ,CAST("ATTRIBUTE14" AS varchar(1000) ) AS "ATTRIBUTE14"
                        ,CAST("ATTRIBUTE15" AS varchar(1000) ) AS "ATTRIBUTE15"
                        ,CAST("ATTRIBUTE16" AS varchar(1000) ) AS "ATTRIBUTE16"
                        ,CAST("ATTRIBUTE17" AS varchar(1000) ) AS "ATTRIBUTE17"
                        ,CAST("ATTRIBUTE18" AS varchar(1000) ) AS "ATTRIBUTE18"
                        ,CAST("ATTRIBUTE19" AS varchar(1000) ) AS "ATTRIBUTE19"
                        ,CAST("ATTRIBUTE20" AS varchar(1000) ) AS "ATTRIBUTE20"
                        ,CAST("ATTRIBUTE21" AS varchar(1000) ) AS "ATTRIBUTE21"
                        ,CAST("ATTRIBUTE22" AS varchar(1000) ) AS "ATTRIBUTE22"
                        ,CAST("ATTRIBUTE23" AS varchar(1000) ) AS "ATTRIBUTE23"
                        ,CAST("ATTRIBUTE24" AS varchar(1000) ) AS "ATTRIBUTE24"
                        ,CAST("ATTRIBUTE25" AS varchar(1000) ) AS "ATTRIBUTE25"
                        ,CAST("ATTRIBUTE26" AS varchar(1000) ) AS "ATTRIBUTE26"
                        ,CAST("ATTRIBUTE27" AS varchar(1000) ) AS "ATTRIBUTE27"
                        ,CAST("ATTRIBUTE28" AS varchar(1000) ) AS "ATTRIBUTE28"
                        ,CAST("ATTRIBUTE29" AS varchar(1000) ) AS "ATTRIBUTE29"
                        ,CAST("ATTRIBUTE30" AS varchar(1000) ) AS "ATTRIBUTE30"
                        ,CAST("LAST_UPDATE_DATE"  AS datetime2) AS "LAST_UPDATE_DATE"
                        ,CAST("LAST_UPDATED_BY" AS float) AS "LAST_UPDATED_BY"
                        ,CAST("LAST_UPDATE_LOGIN" AS float) AS "LAST_UPDATE_LOGIN"
                        ,CAST("CREATED_BY" AS float) AS "CREATED_BY"
                        ,CAST("CREATION_DATE"  AS datetime2) AS "CREATION_DATE"
                        ,CAST("PER_INFORMATION_CATEGORY" AS varchar(100) ) AS "PER_INFORMATION_CATEGORY"
                        ,CAST("PER_INFORMATION1" AS varchar(1000) ) AS "PER_INFORMATION1"
                        ,CAST("PER_INFORMATION2" AS varchar(1000) ) AS "PER_INFORMATION2"
                        ,CAST("PER_INFORMATION3" AS varchar(1000) ) AS "PER_INFORMATION3"
                        ,CAST("PER_INFORMATION4" AS varchar(1000) ) AS "PER_INFORMATION4"
                        ,CAST("PER_INFORMATION5" AS varchar(1000) ) AS "PER_INFORMATION5"
                        ,CAST("PER_INFORMATION6" AS varchar(1000) ) AS "PER_INFORMATION6"
                        ,CAST("PER_INFORMATION7" AS varchar(1000) ) AS "PER_INFORMATION7"
                        ,CAST("PER_INFORMATION8" AS varchar(1000) ) AS "PER_INFORMATION8"
                        ,CAST("PER_INFORMATION9" AS varchar(1000) ) AS "PER_INFORMATION9"
                        ,CAST("PER_INFORMATION10" AS varchar(1000) ) AS "PER_INFORMATION10"
                        ,CAST("PER_INFORMATION11" AS varchar(1000) ) AS "PER_INFORMATION11"
                        ,CAST("PER_INFORMATION12" AS varchar(1000) ) AS "PER_INFORMATION12"
                        ,CAST("PER_INFORMATION13" AS varchar(1000) ) AS "PER_INFORMATION13"
                        ,CAST("PER_INFORMATION14" AS varchar(1000) ) AS "PER_INFORMATION14"
                        ,CAST("PER_INFORMATION15" AS varchar(1000) ) AS "PER_INFORMATION15"
                        ,CAST("PER_INFORMATION16" AS varchar(1000) ) AS "PER_INFORMATION16"
                        ,CAST("PER_INFORMATION17" AS varchar(1000) ) AS "PER_INFORMATION17"
                        ,CAST("PER_INFORMATION18" AS varchar(1000) ) AS "PER_INFORMATION18"
                        ,CAST("PER_INFORMATION19" AS varchar(1000) ) AS "PER_INFORMATION19"
                        ,CAST("PER_INFORMATION20" AS varchar(1000) ) AS "PER_INFORMATION20"
                        ,CAST("PER_INFORMATION21" AS varchar(1000) ) AS "PER_INFORMATION21"
                        ,CAST("PER_INFORMATION22" AS varchar(1000) ) AS "PER_INFORMATION22"
                        ,CAST("PER_INFORMATION23" AS varchar(1000) ) AS "PER_INFORMATION23"
                        ,CAST("PER_INFORMATION24" AS varchar(1000) ) AS "PER_INFORMATION24"
                        ,CAST("PER_INFORMATION25" AS varchar(1000) ) AS "PER_INFORMATION25"
                        ,CAST("PER_INFORMATION26" AS varchar(1000) ) AS "PER_INFORMATION26"
                        ,CAST("PER_INFORMATION27" AS varchar(1000) ) AS "PER_INFORMATION27"
                        ,CAST("PER_INFORMATION28" AS varchar(1000) ) AS "PER_INFORMATION28"
                        ,CAST("PER_INFORMATION29" AS varchar(1000) ) AS "PER_INFORMATION29"
                        ,CAST("PER_INFORMATION30" AS varchar(1000) ) AS "PER_INFORMATION30"
                        ,CAST("OBJECT_VERSION_NUMBER" AS float) AS "OBJECT_VERSION_NUMBER"
                        ,CAST("DATE_OF_DEATH"  AS datetime2) AS "DATE_OF_DEATH"
                        ,CAST("ORIGINAL_DATE_OF_HIRE"  AS datetime2) AS "ORIGINAL_DATE_OF_HIRE"
                        ,CAST("TOWN_OF_BIRTH" AS varchar(1000) ) AS "TOWN_OF_BIRTH"
                        ,CAST("REGION_OF_BIRTH" AS varchar(1000) ) AS "REGION_OF_BIRTH"
                        ,CAST("COUNTRY_OF_BIRTH" AS varchar(1000) ) AS "COUNTRY_OF_BIRTH"
                        ,CAST("GLOBAL_PERSON_ID" AS varchar(100) ) AS "GLOBAL_PERSON_ID"
                        ,CAST("COORD_BEN_MED_PL_NAME" AS varchar(1000) ) AS "COORD_BEN_MED_PL_NAME"
                        ,CAST("COORD_BEN_MED_INSR_CRR_NAME" AS varchar(1000) ) AS "COORD_BEN_MED_INSR_CRR_NAME"
                        ,CAST("COORD_BEN_MED_INSR_CRR_IDENT" AS varchar(1000) ) AS "COORD_BEN_MED_INSR_CRR_IDENT"
                        ,CAST("COORD_BEN_MED_EXT_ER" AS varchar(1000) ) AS "COORD_BEN_MED_EXT_ER"
                        ,CAST("COORD_BEN_MED_CVG_STRT_DT"  AS datetime2) AS "COORD_BEN_MED_CVG_STRT_DT"
                        ,CAST("COORD_BEN_MED_CVG_END_DT"  AS datetime2) AS "COORD_BEN_MED_CVG_END_DT"
                        ,CAST("PARTY_ID" AS float) AS "PARTY_ID"
                        ,CAST("NPW_NUMBER" AS varchar(100) ) AS "NPW_NUMBER"
                        ,CAST("CURRENT_NPW_FLAG" AS varchar(100) ) AS "CURRENT_NPW_FLAG"
                        ,CAST("GLOBAL_NAME" AS varchar(1000) ) AS "GLOBAL_NAME"
                        ,CAST("LOCAL_NAME" AS varchar(1000) ) AS "LOCAL_NAME"
                        ,CAST(SYSDATETIMEOFFSET() AT TIME ZONE 'AUS Eastern Standard Time' AS datetime2) AS "OMD_INSERT_DATETIME"
                        ,"OMD_FILE_NAME"
                        ,CONVERT(NVARCHAR(32),HASHBYTES('MD5',CONCAT_WS( '||','||',
                            "PERSON_ID"
                            , "EFFECTIVE_START_DATE"
                            , "EFFECTIVE_END_DATE"
                            , "BUSINESS_GROUP_ID"
                            , "PERSON_TYPE_ID"
                            , "LAST_NAME"
                            , "START_DATE"
                            , "APPLICANT_NUMBER"
                            , "BACKGROUND_CHECK_STATUS"
                            , "BACKGROUND_DATE_CHECK"
                            , "BLOOD_TYPE"
                            , "COMMENT_ID"
                            , "CORRESPONDENCE_LANGUAGE"
                            , "CURRENT_APPLICANT_FLAG"
                            , "CURRENT_EMP_OR_APL_FLAG"
                            , "CURRENT_EMPLOYEE_FLAG"
                            , "DATE_EMPLOYEE_DATA_VERIFIED"
                            , "DATE_OF_BIRTH"
                            , "EMAIL_ADDRESS"
                            , "EMPLOYEE_NUMBER"
                            , "EXPENSE_CHECK_SEND_TO_ADDRESS"
                            , "FAST_PATH_EMPLOYEE"
                            , "FIRST_NAME"
                            , "FTE_CAPACITY"
                            , "FULL_NAME"
                            , "HOLD_APPLICANT_DATE_UNTIL"
                            , "HONORS"
                            , "INTERNAL_LOCATION"
                            , "KNOWN_AS"
                            , "LAST_MEDICAL_TEST_BY"
                            , "LAST_MEDICAL_TEST_DATE"
                            , "MAILSTOP"
                            , "MARITAL_STATUS"
                            , "MIDDLE_NAMES"
                            , "NATIONALITY"
                            , "NATIONAL_IDENTIFIER"
                            , "OFFICE_NUMBER"
                            , "ON_MILITARY_SERVICE"
                            , "ORDER_NAME"
                            , "PRE_NAME_ADJUNCT"
                            , "PREVIOUS_LAST_NAME"
                            , "PROJECTED_START_DATE"
                            , "REHIRE_AUTHORIZOR"
                            , "REHIRE_REASON"
                            , "REHIRE_RECOMMENDATION"
                            , "RESUME_EXISTS"
                            , "RESUME_LAST_UPDATED"
                            , "REGISTERED_DISABLED_FLAG"
                            , "SECOND_PASSPORT_EXISTS"
                            , "SEX"
                            , "STUDENT_STATUS"
                            , "SUFFIX"
                            , "TITLE"
                            , "VENDOR_ID"
                            , "WORK_SCHEDULE"
                            , "WORK_TELEPHONE"
                            , "COORD_BEN_MED_PLN_NO"
                            , "COORD_BEN_NO_CVG_FLAG"
                            , "DPDNT_ADOPTION_DATE"
                            , "DPDNT_VLNTRY_SVCE_FLAG"
                            , "RECEIPT_OF_DEATH_CERT_DATE"
                            , "USES_TOBACCO_FLAG"
                            , "BENEFIT_GROUP_ID"
                            , "REQUEST_ID"
                            , "PROGRAM_APPLICATION_ID"
                            , "PROGRAM_ID"
                            , "PROGRAM_UPDATE_DATE"
                            , "ATTRIBUTE_CATEGORY"
                            , "ATTRIBUTE1"
                            , "ATTRIBUTE2"
                            , "ATTRIBUTE3"
                            , "ATTRIBUTE4"
                            , "ATTRIBUTE5"
                            , "ATTRIBUTE6"
                            , "ATTRIBUTE7"
                            , "ATTRIBUTE8"
                            , "ATTRIBUTE9"
                            , "ATTRIBUTE10"
                            , "ATTRIBUTE11"
                            , "ATTRIBUTE12"
                            , "ATTRIBUTE13"
                            , "ATTRIBUTE14"
                            , "ATTRIBUTE15"
                            , "ATTRIBUTE16"
                            , "ATTRIBUTE17"
                            , "ATTRIBUTE18"
                            , "ATTRIBUTE19"
                            , "ATTRIBUTE20"
                            , "ATTRIBUTE21"
                            , "ATTRIBUTE22"
                            , "ATTRIBUTE23"
                            , "ATTRIBUTE24"
                            , "ATTRIBUTE25"
                            , "ATTRIBUTE26"
                            , "ATTRIBUTE27"
                            , "ATTRIBUTE28"
                            , "ATTRIBUTE29"
                            , "ATTRIBUTE30"
                            , "LAST_UPDATE_DATE"
                            , "LAST_UPDATED_BY"
                            , "LAST_UPDATE_LOGIN"
                            , "CREATED_BY"
                            , "CREATION_DATE"
                            , "PER_INFORMATION_CATEGORY"
                            , "PER_INFORMATION1"
                            , "PER_INFORMATION2"
                            , "PER_INFORMATION3"
                            , "PER_INFORMATION4"
                            , "PER_INFORMATION5"
                            , "PER_INFORMATION6"
                            , "PER_INFORMATION7"
                            , "PER_INFORMATION8"
                            , "PER_INFORMATION9"
                            , "PER_INFORMATION10"
                            , "PER_INFORMATION11"
                            , "PER_INFORMATION12"
                            , "PER_INFORMATION13"
                            , "PER_INFORMATION14"
                            , "PER_INFORMATION15"
                            , "PER_INFORMATION16"
                            , "PER_INFORMATION17"
                            , "PER_INFORMATION18"
                            , "PER_INFORMATION19"
                            , "PER_INFORMATION20"
                            , "PER_INFORMATION21"
                            , "PER_INFORMATION22"
                            , "PER_INFORMATION23"
                            , "PER_INFORMATION24"
                            , "PER_INFORMATION25"
                            , "PER_INFORMATION26"
                            , "PER_INFORMATION27"
                            , "PER_INFORMATION28"
                            , "PER_INFORMATION29"
                            , "PER_INFORMATION30"
                            , "OBJECT_VERSION_NUMBER"
                            , "DATE_OF_DEATH"
                            , "ORIGINAL_DATE_OF_HIRE"
                            , "TOWN_OF_BIRTH"
                            , "REGION_OF_BIRTH"
                            , "COUNTRY_OF_BIRTH"
                            , "GLOBAL_PERSON_ID"
                            , "COORD_BEN_MED_PL_NAME"
                            , "COORD_BEN_MED_INSR_CRR_NAME"
                            , "COORD_BEN_MED_INSR_CRR_IDENT"
                            , "COORD_BEN_MED_EXT_ER"
                            , "COORD_BEN_MED_CVG_STRT_DT"
                            , "COORD_BEN_MED_CVG_END_DT"
                            , "PARTY_ID"
                            , "NPW_NUMBER"
                            , "CURRENT_NPW_FLAG"
                            , "GLOBAL_NAME"
                            , "LOCAL_NAME"
                        ,'||')),2) AS OMD_HASH_FULL_RECORD
                    FROM "LND"."LND_EBS_PER_ALL_PEOPLE_F"
                    ) T 

        END TRY
        BEGIN CATCH
            /*SELECT   
            ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage;*/
            THROW;
    END CATCH 
END